.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.25.1 */

glabel D_8018E020_ovl5
/* 135490 8018E020 */ .space 0x04

glabel D_8018E024_ovl5
/* 135494 8018E024 */ .space 0x01

glabel D_8018E025_ovl5
/* 135495 8018E025 */ .space 0x0B

glabel D_8018E030_ovl5
/* 1354A0 8018E030 */ .space 0x04

glabel D_8018E034_ovl5
/* 1354A4 8018E034 */ .space 0x04

glabel D_8018E038_ovl5
/* 1354A8 8018E038 */ .space 0x04

glabel D_8018E03C_ovl5
/* 1354AC 8018E03C */ .space 0x04

glabel D_8018E040_ovl5
/* 1354B0 8018E040 */ .space 0x08

glabel .L8018E048_ovl5
/* 1354B8 8018E048 */ .space 0x08

glabel D_8018E050_ovl5
/* 1354C0 8018E050 */ .space 0x1C

glabel .L8018E06C_ovl5
/* 1354DC 8018E06C */ .space 0x84

glabel .L8018E0F0_ovl5
/* 135560 8018E0F0 */ .space 0x24

glabel .L8018E114_ovl5
/* 135584 8018E114 */ .space 0x44

glabel .L8018E158_ovl5
/* 1355C8 8018E158 */ .space 0x0C

glabel func_8018E164_ovl5
/* 1355D4 8018E164 */ .space 0x158

glabel .L8018E2BC_ovl5
/* 13572C 8018E2BC */ .space 0xB0

glabel func_8018E36C_ovl5
/* 1357DC 8018E36C */ .space 0x34

glabel .L8018E3A0_ovl5
/* 135810 8018E3A0 */ .space 0x04

glabel .L8018E3A4_ovl5
/* 135814 8018E3A4 */ .space 0x0C

glabel func_8018E3B0_ovl5
/* 135820 8018E3B0 */ .space 0xD4

glabel .L8018E484_ovl5
/* 1358F4 8018E484 */ .space 0x30

glabel .L8018E4B4_ovl5
/* 135924 8018E4B4 */ .space 0x2C

glabel .L8018E4E0_ovl5
/* 135950 8018E4E0 */ .space 0x10

glabel .L8018E4F0_ovl5
/* 135960 8018E4F0 */ .space 0xA4

glabel .L8018E594_ovl5
/* 135A04 8018E594 */ .space 0x28

glabel D_8018E5BC_ovl5
/* 135A2C 8018E5BC */ .space 0x34

glabel .L8018E5F0_ovl5
/* 135A60 8018E5F0 */ .space 0x0C

glabel .L8018E5FC_ovl5
/* 135A6C 8018E5FC */ .space 0x0C

glabel func_8018E608_ovl5
/* 135A78 8018E608 */ .space 0x130

glabel .L8018E738_ovl5
/* 135BA8 8018E738 */ .space 0x04

glabel .L8018E73C_ovl5
/* 135BAC 8018E73C */ .space 0xC4

glabel .L8018E800_ovl5
/* 135C70 8018E800 */ .space 0x48

glabel .L8018E848_ovl5
/* 135CB8 8018E848 */ .space 0x40

glabel .L8018E888_ovl5
/* 135CF8 8018E888 */ .space 0x20

glabel .L8018E8A8_ovl5
/* 135D18 8018E8A8 */ .space 0x14

glabel .L8018E8BC_ovl5
/* 135D2C 8018E8BC */ .space 0x54

glabel .L8018E910_ovl5
/* 135D80 8018E910 */ .space 0x0C

glabel .L8018E91C_ovl5
/* 135D8C 8018E91C */ .space 0x0C

glabel .L8018E928_ovl5
/* 135D98 8018E928 */ .space 0x24

glabel .L8018E94C_ovl5
/* 135DBC 8018E94C */ .space 0x18

glabel .L8018E964_ovl5
/* 135DD4 8018E964 */ .space 0x0C

glabel .L8018E970_ovl5
/* 135DE0 8018E970 */ .space 0x18

glabel .L8018E988_ovl5
/* 135DF8 8018E988 */ .space 0x10

glabel D_8018E998_ovl5
/* 135E08 8018E998 */ .space 0x04

glabel .L8018E99C_ovl5
/* 135E0C 8018E99C */ .space 0x04

glabel D_8018E9A0_ovl5
/* 135E10 8018E9A0 */ .space 0x04

glabel D_8018E9A4_ovl5
/* 135E14 8018E9A4 */ .space 0x04

glabel D_8018E9A8_ovl5
/* 135E18 8018E9A8 */ .space 0x01

glabel D_8018E9A9_ovl5
/* 135E19 8018E9A9 */ .space 0x01

glabel D_8018E9AA_ovl5
/* 135E1A 8018E9AA */ .space 0x26

glabel D_8018E9D0_ovl5
/* 135E40 8018E9D0 */ .space 0x0C

glabel .L8018E9DC_ovl5
/* 135E4C 8018E9DC */ .space 0x1E

glabel D_8018E9FA_ovl5
/* 135E6A 8018E9FA */ .space 0x06

glabel D_8018EA00_ovl5
/* 135E70 8018EA00 */ .space 0x34

glabel .L8018EA34_ovl5
/* 135EA4 8018EA34 */ .space 0x40

glabel .L8018EA74_ovl5
/* 135EE4 8018EA74 */ .space 0xB4

glabel .L8018EB28_ovl5
/* 135F98 8018EB28 */ .space 0x20

glabel D_8018EB48_ovl5
/* 135FB8 8018EB48 */ .space 0x10

glabel D_8018EB58_ovl5
/* 135FC8 8018EB58 */ .space 0x01

glabel D_8018EB59_ovl5
/* 135FC9 8018EB59 */ .space 0x4B

glabel .L8018EBA4_ovl5
/* 136014 8018EBA4 */ .space 0x7C

glabel .L8018EC20_ovl5
/* 136090 8018EC20 */ .space 0x40

glabel .L8018EC60_ovl5
/* 1360D0 8018EC60 */ .space 0x34

glabel .L8018EC94_ovl5
/* 136104 8018EC94 */ .space 0x0C

glabel D_8018ECA0_ovl5
/* 136110 8018ECA0 */ .space 0x08

glabel D_8018ECA8_ovl5
/* 136118 8018ECA8 */ .space 0x10

glabel D_8018ECB8_ovl5
/* 136128 8018ECB8 */ .space 0x20

glabel D_8018ECD8_ovl5
/* 136148 8018ECD8 */ .space 0x01

glabel D_8018ECD9_ovl5
/* 136149 8018ECD9 */ .space 0x07

glabel D_8018ECE0_ovl5
/* 136150 8018ECE0 */ .space 0x04

glabel D_8018ECE4_ovl5
/* 136154 8018ECE4 */ .space 0x04

glabel D_8018ECE8_ovl5
/* 136158 8018ECE8 */ .space 0x10

glabel D_8018ECF8_ovl5
/* 136168 8018ECF8 */ .space 0x01

glabel D_8018ECF9_ovl5
/* 136169 8018ECF9 */ .space 0x07

glabel D_8018ED00_ovl5
/* 136170 8018ED00 */ .space 0x04

glabel D_8018ED04_ovl5
/* 136174 8018ED04 */ .space 0x04

glabel D_8018ED08_ovl5
/* 136178 8018ED08 */ .space 0x04

glabel D_8018ED0C_ovl5
/* 13617C 8018ED0C */ .space 0x04

glabel D_8018ED10_ovl5
/* 136180 8018ED10 */ .space 0x08

glabel D_8018ED18_ovl5
/* 136188 8018ED18 */ .space 0x04

glabel D_8018ED1C_ovl5
/* 13618C 8018ED1C */ .space 0x04

glabel D_8018ED20_ovl5
/* 136190 8018ED20 */ .space 0x04

glabel D_8018ED24_ovl5
/* 136194 8018ED24 */ .space 0x04

glabel D_8018ED28_ovl5
/* 136198 8018ED28 */ .space 0x10

glabel D_8018ED38_ovl5
/* 1361A8 8018ED38 */ .space 0x01

glabel D_8018ED39_ovl5
/* 1361A9 8018ED39 */ .space 0x01

glabel D_8018ED3A_ovl5
/* 1361AA 8018ED3A */ .space 0x01

glabel D_8018ED3B_ovl5
/* 1361AB 8018ED3B */ .space 0x01

glabel D_8018ED3C_ovl5
/* 1361AC 8018ED3C */ .space 0x04

glabel D_8018ED40_ovl5
/* 1361B0 8018ED40 */ .space 0x04

glabel .L8018ED44_ovl5
/* 1361B4 8018ED44 */ .space 0x04

glabel D_8018ED48_ovl5
/* 1361B8 8018ED48 */ .space 0x04

glabel D_8018ED4C_ovl5
/* 1361BC 8018ED4C */ .space 0x04

glabel D_8018ED50_ovl5
/* 1361C0 8018ED50 */ .space 0x1C

glabel .L8018ED6C_ovl5
/* 1361DC 8018ED6C */ .space 0x24

glabel D_8018ED90_ovl5
/* 136200 8018ED90 */ .space 0x04

glabel D_8018ED94_ovl5
/* 136204 8018ED94 */ .space 0x04

glabel D_8018ED98_ovl5
/* 136208 8018ED98 */ .space 0x04

glabel D_8018ED9C_ovl5
/* 13620C 8018ED9C */ .space 0x04

glabel D_8018EDA0_ovl5
/* 136210 8018EDA0 */ .space 0x10

glabel D_8018EDB0_ovl5
/* 136220 8018EDB0 */ .space 0x04

glabel D_8018EDB4_ovl5
/* 136224 8018EDB4 */ .space 0x04

glabel D_8018EDB8_ovl5
/* 136228 8018EDB8 */ .space 0x01

glabel D_8018EDB9_ovl5
/* 136229 8018EDB9 */ .space 0x01

glabel D_8018EDBA_ovl5
/* 13622A 8018EDBA */ .space 0x06

glabel D_8018EDC0_ovl5
/* 136230 8018EDC0 */ .space 0x04

glabel D_8018EDC4_ovl5
/* 136234 8018EDC4 */ .space 0x0C

glabel D_8018EDD0_ovl5
/* 136240 8018EDD0 */ .space 0x04

glabel D_8018EDD4_ovl5
/* 136244 8018EDD4 */ .space 0x04

glabel D_8018EDD8_ovl5
/* 136248 8018EDD8 */ .space 0x04

glabel D_8018EDDC_ovl5
/* 13624C 8018EDDC */ .space 0x04

glabel D_8018EDE0_ovl5
/* 136250 8018EDE0 */ .space 0x01

glabel D_8018EDE1_ovl5
/* 136251 8018EDE1 */ .space 0x03

glabel D_8018EDE4_ovl5
/* 136254 8018EDE4 */ .space 0x04

glabel D_8018EDE8_ovl5
/* 136258 8018EDE8 */ .space 0x04

glabel D_8018EDEC_ovl5
/* 13625C 8018EDEC */ .space 0x08

glabel D_8018EDF4_ovl5
/* 136264 8018EDF4 */ .space 0x04

glabel D_8018EDF8_ovl5
/* 136268 8018EDF8 */ .space 0x04

glabel D_8018EDFC_ovl5
/* 13626C 8018EDFC */ .space 0x04

glabel D_8018EE00_ovl5
/* 136270 8018EE00 */ .space 0x04

glabel D_8018EE04_ovl5
/* 136274 8018EE04 */ .space 0x0C

glabel D_8018EE10_ovl5
/* 136280 8018EE10 */ .space 0x04

glabel D_8018EE14_ovl5
/* 136284 8018EE14 */ .space 0x04

glabel D_8018EE18_ovl5
/* 136288 8018EE18 */ .space 0x08

glabel D_8018EE20_ovl5
/* 136290 8018EE20 */ .space 0x24

glabel D_8018EE44_ovl5
/* 1362B4 8018EE44 */ .space 0x04

glabel D_8018EE48_ovl5
/* 1362B8 8018EE48 */ .space 0x02

glabel D_8018EE4A_ovl5
/* 1362BA 8018EE4A */ .space 0x02

glabel D_8018EE4C_ovl5
/* 1362BC 8018EE4C */ .space 0x04

glabel D_8018EE50_ovl5
/* 1362C0 8018EE50 */ .space 0x04

glabel D_8018EE54_ovl5
/* 1362C4 8018EE54 */ .space 0x04

glabel D_8018EE58_ovl5
/* 1362C8 8018EE58 */ .space 0x08
