.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.25.1 */

glabel D_80197BF0_ovl3
/* F8630 80197BF0 */ .space 0x1EC

glabel D_80197DDC_ovl3
/* F881C 80197DDC */ .space 0x184

glabel D_80197F60_ovl3
/* F89A0 80197F60 */ .space 0x398

glabel D_801982F8_ovl3
/* F8D38 801982F8 */ .space 0x140

glabel D_80198438_ovl3
/* F8E78 80198438 */ .space 0x100

glabel D_80198538_ovl3
/* F8F78 80198538 */ .space 0x04

glabel D_8019853C_ovl3
/* F8F7C 8019853C */ .space 0x04

glabel D_80198540_ovl3
/* F8F80 80198540 */ .space 0x1C0

glabel D_80198700_ovl3
/* F9140 80198700 */ .space 0x100

glabel D_80198800_ovl3
/* F9240 80198800 */ .space 0x20

glabel D_80198820_ovl3
/* F9260 80198820 */ .space 0x04

glabel D_80198824_ovl3
/* F9264 80198824 */ .space 0x01

glabel D_80198825_ovl3
/* F9265 80198825 */ .space 0x0B

glabel D_80198830_ovl3
/* F9270 80198830 */ .space 0x02

glabel D_80198832_ovl3
/* F9272 80198832 */ .space 0x02

glabel D_80198834_ovl3
/* F9274 80198834 */ .space 0x04

glabel D_80198838_ovl3
/* F9278 80198838 */ .space 0x04

glabel D_8019883C_ovl3
/* F927C 8019883C */ .space 0x04

glabel D_80198840_ovl3
/* F9280 80198840 */ .space 0x08

glabel D_80198848_ovl3
/* F9288 80198848 */ .space 0x10

glabel D_80198858_ovl3
/* F9298 80198858 */ .space 0x18
