#include <ultra64.h>
#include <macros.h>

#include "ovl0_2_5.h"
#include "ovl0_3.h"
#include "main.h"
#include "D_8004A7C4.h"

extern void func_80000A44(void);
extern void fatal_printf(const char *fmt, ...);

extern struct ObjThread *gObjectThreadMaybe;
extern u8 D_80040230[];
extern u32 D_8004A544;

// Unused?
struct ObjThread *func_80007F58(void) {
    struct ObjThread *ret;
    if (gObjectThreadMaybe == NULL) {
        fatal_printf(D_80040230); // om : couldn't get GObjThread
        while (TRUE);
    }
    ret = gObjectThreadMaybe;
    gObjectThreadMaybe = gObjectThreadMaybe->unk0;
    D_8004A544++;
    return ret;
}

void func_80007FB8(struct ObjThread *arg0) {
    arg0->unk0 = gObjectThreadMaybe;
    gObjectThreadMaybe = arg0;
    D_8004A544--;
}

extern struct ObjThreadStack* gObjectThreadStackMaybe;
extern u32 D_8004A548;
extern u8 D_80040250[];

struct ObjThreadStack *func_80007FE4(void) {
    struct ObjThreadStack *temp_v0;

    if (gObjectThreadStackMaybe == NULL) {
        fatal_printf(&D_80040250); // om : couldn't get GObjThreadStack
        while (TRUE);
    }
    temp_v0 = gObjectThreadStackMaybe;
    gObjectThreadStackMaybe = gObjectThreadStackMaybe->unk0;
    D_8004A548++;
    return temp_v0;
}

void func_8000803C(struct ObjThreadStack *arg0) {
    arg0->unk0 = gObjectThreadStackMaybe;
    gObjectThreadStackMaybe = arg0;
    D_8004A548--;
}

extern struct ObjProcess* gObjectProcessMaybe;
extern u32 D_8004A570;
extern u8 D_80040274[];

struct ObjProcess *func_80008068(void) {
    struct ObjProcess *temp_v0;

    if (gObjectProcessMaybe == NULL) {
        fatal_printf(&D_80040274); // om : couldn't get GObjProcess
        while (TRUE);
    }
    temp_v0 = gObjectProcessMaybe;
    gObjectProcessMaybe = gObjectProcessMaybe->unk0;
    D_8004A570++;
    return temp_v0;
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800080C0(void *arg0) {
    u8 temp_t0;
    void *temp_a2;
    void *temp_v1;
    void *temp_v1_2;
    void *temp_v1_3;
    void *phi_a2;
    void *phi_a2_2;
    void *phi_v1;
    u8 phi_a1;

    phi_a2 = arg0->unk18;
    phi_a1 = arg0->unk18->unkC;
loop_1:
    temp_t0 = phi_a1 - 1;
    phi_a2_2 = phi_a2;
    if (phi_a2 != 0) {
loop_2:
        temp_v1 = phi_a2_2->unk1C;
        phi_v1 = temp_v1;
        if (temp_v1 != 0) {
loop_3:
            if (arg0->unk10 == phi_v1->unk10) {
                arg0->unk8 = (void *) phi_v1->unk8;
                phi_v1->unk8 = arg0;
                arg0->unkC = phi_v1;
            } else {
                temp_v1_2 = phi_v1->unk4;
                phi_v1 = temp_v1_2;
                if (temp_v1_2 != 0) {
                    goto loop_3;
                }
block_6:
                temp_a2 = phi_a2_2->unk8;
                phi_a2_2 = temp_a2;
                if (temp_a2 != 0) {
                    goto loop_2;
                }
block_7:
                if (phi_a1 != 0) {
                    phi_a2 = *(&D_8004A5F8 + (temp_t0 * 4));
                    phi_a1 = temp_t0;
                    goto loop_1;
                } else {
                    temp_v1_3 = (arg0->unk10 * 4) + &D_8004A560;
                    arg0->unk8 = (void *) *temp_v1_3;
                    *temp_v1_3 = arg0;
                    arg0->unkC = NULL;
                }
            }
        } else {
            goto block_6;
        }
    } else {
        goto block_7;
    }
    if (arg0->unk8 != 0) {
        arg0->unk8->unkC = arg0;
    }
    if (arg0->unk18->unk1C != 0) {
        *arg0->unk18->unk1C = arg0;
    } else {
        arg0->unk18->unk18 = arg0;
    }
    arg0->unk0 = 0;
    arg0->unk4 = (void *) arg0->unk18->unk1C;
    arg0->unk18->unk1C = arg0;
    return arg0->unk18;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_800080C0.s")
#endif

void func_80008198(struct ObjProcess *arg0) {
    arg0->unk0 = gObjectProcessMaybe;
    gObjectProcessMaybe = arg0;
    D_8004A570--;
}

// TODO: See if this struct should merged with another
struct unk80008210Func {
    struct unk80008210Func* unk0;
    struct unk80008210Func* unk4;
    struct unk80008210Func* unk8;
    struct unk80008210Func* unkC;
    u32 unk10;
    u8 padding[0x18 - 0x04 - 0x10];
    struct unk80008210Func* unk18;
    struct unk80008210Func* unk1C;
};

extern struct unk80008210Func* D_8004A560[];

void func_800081C4(struct unk80008210Func *arg0) {
    if (arg0->unkC != 0) {
        arg0->unkC->unk8 = arg0->unk8;
    } else {
        D_8004A560[arg0->unk10] = arg0->unk8;
    }
    if (arg0->unk8 != 0) {
        arg0->unk8->unkC = arg0->unkC;
    }
}

void *func_80008210(struct unk80008210Func *arg0) {
    struct unk80008210Func *sp1C;

    sp1C = arg0->unk18;
    func_800081C4(arg0);
    if (arg0->unk4 != 0) {
        arg0->unk4->unk0 = arg0->unk0;
    } else {
        sp1C->unk18 = arg0->unk0;
    }
    if (arg0->unk0 != 0) {
        arg0->unk0->unk4 = arg0->unk4;
    } else {
        sp1C->unk1C = arg0->unk4;
    }
}

extern s32 D_8004A7D0;

s32 func_80008280(void) {
    return D_8004A7D0;
}

// Unused?
#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000828C(void *arg0) {
    u8 temp_v0;
    void *phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7D0;
    }
    if (phi_a0 != 0) {
        temp_v0 = phi_a0->unk14;
        if (temp_v0 == 0) {
            return phi_a0->unk1C->unk1B8;
        }
        if (temp_v0 == 2) {
            return phi_a0->unk1C->unk1B8;
        }
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000828C.s")
#endif

// Unused?
#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800082D4(void *arg0) {
    u8 temp_v0;
    void *phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7D0;
    }
    if (phi_a0 != 0) {
        temp_v0 = phi_a0->unk14;
        if (temp_v0 == 0) {
            return phi_a0->unk1C->unk1BC;
        }
        if (temp_v0 == 2) {
            return phi_a0->unk1C->unk1BC;
        }
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_800082D4.s")
#endif

extern s32 D_8004A558;

// Unused?
void func_8000831C(s32 arg0) {
    D_8004A558 = arg0;
}

extern struct unk8004A678Addr *D_8004A678;
extern u32 D_8004A78C;

// Unused?
s32 func_80008328(void) {
    struct unk8004A678Addr *phi_v0;
    s32 phi_v1;

    phi_v0 = D_8004A678;
    phi_v1 = 0;
    while (phi_v0 != 0) {
        phi_v0 = phi_v0->unk4;
        phi_v1 = phi_v1 + 1;
    }
    return phi_v1 + D_8004A78C;
}

// Another potential pop
struct unk8004A678Addr *func_8000835C(void) {
    struct unk8004A678Addr *temp_v0;

    if (D_8004A678 == 0) {
        return NULL;
    }
    temp_v0 = D_8004A678;
    D_8004A678 = D_8004A678->unk4;
    D_8004A78C++;
    return temp_v0;
}

// Another potential push
void func_800083A0(struct unk8004A678Addr *arg0) {
    arg0->unk4 = D_8004A678;
    D_8004A678 = arg0;
    D_8004A78C--;
}

extern void* D_8004A578[];
extern void* D_8004A5F8[];



void func_800083CC(struct unk800083CCFunc *arg0, struct unk800083CCFunc *arg1) {
    void *temp_v0;

    arg0->unk8 = arg1;
    if (arg1 != 0) {
        arg0->unk4 = arg1->unk4;
        arg1->unk4 = arg0;
    } else {
        arg0->unk4 = D_8004A578[arg0->unkC];
        D_8004A578[arg0->unkC] = arg0;
    }
    if (arg0->unk4 != 0) {
        arg0->unk4->unk8 = arg0;
    } else {
        D_8004A5F8[arg0->unkC] = arg0;
    }
}

void func_80008434(struct unk800083CCFunc *arg0) {
    struct unk800083CCFunc *phi_a1;

    phi_a1 = D_8004A5F8[arg0->unkC];
    while (phi_a1 != 0 && phi_a1->unk10 < arg0->unk10) {
        phi_a1 = phi_a1->unk8;
    }
    func_800083CC(arg0, phi_a1);
}

void func_800084A0(struct unk800083CCFunc *arg0) {
    struct unk800083CCFunc *phi_v0;
    struct unk800083CCFunc *phi_a1;

    phi_v0 = D_8004A578[arg0->unkC];
    while (phi_v0 != 0 && arg0->unk10 < phi_v0->unk10) {
            phi_v0 = phi_v0->unk4;
    }
    if (phi_v0 != 0) {
        phi_a1 = phi_v0->unk8;
    } else {
        phi_a1 =  D_8004A5F8[arg0->unkC];
    }
    func_800083CC(arg0, phi_a1);
}

void func_80008528(struct unk800083CCFunc *arg0) {
    if (arg0->unk8 != 0) {
        arg0->unk8->unk4 = arg0->unk4;
    } else {
        D_8004A578[arg0->unkC] = arg0->unk4;
    }
    if (arg0->unk4 != 0) {
        arg0->unk4->unk8 = arg0->unk8;
        return;
    }
    D_8004A5F8[arg0->unkC] = arg0->unk8;
}

// Following code paths shows that this struct is likely the same one as used in func_801DB1E0
// Seems to be some sort of doubly-linked list element
struct unk800086ECFunc {
    u8 filler[0x0D];
    u8 unkD;
    u8 filler2[0x20 - 0x0D - 0x01];
    struct unk800086ECFunc* unk20;
    struct unk800086ECFunc* unk24;
    u32 unk28;
};

extern struct unk800086ECFunc* D_8004A680[];
extern struct unk800086ECFunc* D_8004A708[];

void func_80008590(struct unk800086ECFunc *arg0, struct unk800086ECFunc *arg1) {
    struct unk800086ECFunc *temp_v0;

    arg0->unk24 = arg1;
    if (arg1 != 0) {
        arg0->unk20 = arg1->unk20;
        arg1->unk20 = arg0;
    } else {
        arg0->unk20 = D_8004A680[arg0->unkD];
        D_8004A680[arg0->unkD] = arg0;
    }
    if (arg0->unk20 != 0) {
        arg0->unk20->unk24 = arg0;
        return;
    }
    D_8004A708[arg0->unkD] = arg0;
}

void func_800085F8(struct unk800086ECFunc *arg0) {
    struct unk800086ECFunc *phi_a1;
    
    phi_a1 = D_8004A708[arg0->unkD];
    while (phi_a1 != 0 && phi_a1->unk28 < arg0->unk28) {
        phi_a1 = phi_a1->unk24;
    }
    func_80008590(arg0, phi_a1);
}

void func_80008664(struct unk800086ECFunc *arg0) {
    struct unk800086ECFunc *phi_v0;
    struct unk800086ECFunc *phi_a1;

    phi_v0 = D_8004A680[arg0->unkD];
    while (phi_v0 != 0 && arg0->unk28 < phi_v0->unk28) {
        phi_v0 = phi_v0->unk20;
    }
    if (phi_v0 != 0) {
        phi_a1 = phi_v0->unk24;
    } else {
        phi_a1 = D_8004A708[arg0->unkD];
    }
    func_80008590(arg0, phi_a1);
}

void func_800086EC(struct unk800086ECFunc *arg0) {
    if (arg0->unk24 != 0) {
        arg0->unk24->unk20 = arg0->unk20;
    } else {
        D_8004A680[arg0->unkD] = arg0->unk20;
    }
    if (arg0->unk20 != 0) {
        arg0->unk20->unk24 = arg0->unk24;
    } else {
        D_8004A708[arg0->unkD] = arg0->unk24;
    }
}

// TODO: Determine types
extern void** D_8004A790;
extern u32 D_8004A794;
extern u8 D_80040294[];

// Another potential pop
void *func_80008754(void) {
    void *temp_v0;

    if (D_8004A790 == 0) {
        fatal_printf(&D_80040294); // om : couldn't get OMMtx
        while (TRUE);
    }
    temp_v0 = D_8004A790;
    D_8004A790 = *D_8004A790; // TODO: This is probably the first member of a struct
    D_8004A794++;
    return temp_v0;
}

// Another potential push
void *func_800087AC(void **arg0) {
    *arg0 = D_8004A790;
    D_8004A790 = arg0;
    D_8004A794--;
}

extern struct AnimStack *D_8004A79C;
extern const char *D_800402B0;
extern u32 D_8004A7A0;

// pops the top of D_8004A79C?
struct AnimStack *func_800087D8(void) {
    struct AnimStack *toReturn;

    if (D_8004A79C == 0) {
        fatal_printf(&D_800402B0); // om : couldn't get AObj
        while (TRUE);
    }
    toReturn = D_8004A79C;
    D_8004A79C = D_8004A79C->next;
    D_8004A7A0++;
    return toReturn;
}

// Sets a new head of the unk6C list in anim
void func_80008830(struct Animation *anim, struct AnimStack *element) {
    element->next = anim->unk6C;
    anim->unk6C = element;
}

void func_80008840(struct unk80008840 *arg0, struct AnimStack *element) {
    element->next = arg0->unk90;
    arg0->unk90 = element;
}

// TODO: is this _really_ for Animations?
void func_80008850(struct Animation *anim, struct AnimStack *element) {
    element->next = anim->unk6C;
    anim->unk6C = element;
}

void func_80008860(struct AnimStack *arg0) {
    arg0->next = D_8004A79C;
    D_8004A7A0--;
    D_8004A79C = arg0;
}

extern struct MObj* D_8004A7A4;
extern u32 D_8004A7A8;
extern u8 D_800402C8[];

// Another potential pop
struct MObj* func_8000888C(void) {
    struct MObj *temp_v0;

    if (D_8004A7A4 == 0) {
        fatal_printf(D_800402C8); // om : couldn't get MObj
        while (TRUE);
    }
    temp_v0 = D_8004A7A4;
    D_8004A7A4 = D_8004A7A4->unk0; // TODO: This is probably the first member of a struct
    D_8004A7A8++;
    return temp_v0;
}

// Another potential push
void func_800088E4(struct MObj *arg0) {
    arg0->unk0 = D_8004A7A4;
    D_8004A7A4 = arg0;
    D_8004A7A8--;
}

extern struct DObj* D_8004A7AC;
extern u32 D_8004A7B0;
extern u8 D_800402E0[];

// Another potential pop
struct DObj *func_80008910(void) {
    struct DObj *temp_v0;

    if (D_8004A7AC == 0) {
        fatal_printf(&D_800402E0); // om : couldn't get DObj
        while (TRUE);
    }
    temp_v0 = D_8004A7AC;
    D_8004A7AC = D_8004A7AC->unk0;
    D_8004A7B0++;
    return temp_v0;
}

// Another potential push
void func_80008968(struct DObj *arg0) {
    arg0->unk0 = D_8004A7AC;
    D_8004A7AC = arg0;
    D_8004A7B0--;
}

// TODO: Determine types
extern struct Camera* D_8004A7BC;
extern u32 D_8004A7C0;
extern u8 D_800402F8[];

// Another potential pop
struct Camera *func_80008994(void) {
    struct Camera *temp_v0;

    if (D_8004A7BC == 0) {
        fatal_printf(&D_800402F8); // om : couldn't get Camera
        while (TRUE);
    }
    temp_v0 = D_8004A7BC;
    D_8004A7BC = D_8004A7BC->unk0; // TODO: This is probably the first member of a struct
    D_8004A7C0++;
    return temp_v0;
}

// Another potential push
void func_800089EC(struct Camera *arg0) {
    arg0->unk0 = D_8004A7BC;
    D_8004A7BC = arg0;
    D_8004A7C0--;
}

extern u8 D_80040314[];
extern u8 D_80040340[];
extern s32 D_8003DE50;
extern u32 D_8004A54C;

struct ObjThread *func_80007F60();
void func_800080C0(struct ObjProcess *);

#ifdef MIPS_TO_C
// Decently close to matching, types should be mostly correct based on code paths
struct ObjProcess *func_80008A18(s32 arg0, s32 arg1, u8 arg2, u32 arg3) {
    struct ObjThread *sp28;
    struct ObjProcess *sp24;
    u32 temp_a1;
    struct ObjThreadStack *temp_v1;
    struct ObjThread *temp_v0_2;
    s32 phi_a0;

    if (arg0 == 0) {
        arg0 = D_8004A7C4;
    }
    sp24 = func_80008068();
    if (arg3 >= 4U) {
        fatal_printf(D_80040314); // om : GObjProcess's priority is bad value
        while (1);
    }
    sp24->unk10 = arg3;
    sp24->unk14 = arg2;
    sp24->unk15 = 0;
    sp24->unk18 = arg0;
    sp24->unk20 = arg1;
    if (arg2 != 0) {
        if (arg2 != 1) {
            fatal_printf(D_80040340); // om : GObjProcess's kind is bad value
            while (1);
        }
        sp24->unk1C = arg1;
    } else {
        sp28 = func_80007F60();
        sp24->unk1C = sp28;
        temp_v1 = func_80007FE4();
        sp28->unk1B8 = temp_v1->unk8;
        sp28->unk1BC = (u32) D_8004A54C;
        temp_a1 = D_8003DE50;
        D_8003DE50++;
        osCreateThread(&sp28->unk8, temp_a1, arg1, arg0, (u8*)(temp_v1->unk8) + (((u32) D_8004A54C >> 3) << 3), 0x33);
        sp28->unk1B8->stack[14] = STACK_TOP_MAGIC;
        if (D_8003DE50 >= 20000000) {
            D_8003DE50 = 10000000;
        }
    }
    func_800080C0(sp24);
    return sp24;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80008A18.s")
#endif

extern u8 D_80040368[];

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80008B94(s32 arg0, s32 arg1, u32 arg2, s32 arg3, void *arg4, u32 arg5) {
    void *sp28;
    s32 temp_a3;
    s32 temp_a3_2;
    void *temp_s0;
    void *temp_v0;
    s32 phi_a0;
    s32 phi_a1;
    s32 phi_a1_2;

    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    temp_a3 = arg3;
    temp_s0 = func_80008068(phi_a0);
    if (arg2 >= 4U) {
        fatal_printf(&D_80040368, arg2, temp_a3);
loop_4:
        goto loop_4;
    }
    temp_s0->unk10 = arg2;
    temp_s0->unk15 = (u8)0;
    temp_s0->unk18 = arg0;
    temp_s0->unk20 = arg1;
    arg3 = temp_a3;
    temp_v0 = func_80007F60(&D_80040368, arg2, temp_a3);
    temp_a3_2 = arg3;
    temp_s0->unk1C = temp_v0;
    if (arg5 == 0) {
        temp_s0->unk14 = (u8)0;
        arg3 = temp_a3_2;
        sp28 = temp_v0;
        temp_v0->unk1B8 = (s32) (func_80007FE4(temp_a3_2) + 8);
        temp_v0->unk1BC = (u32) D_8004A54C;
        if (arg3 != -1) {
            phi_a1 = arg3;
        } else {
            D_8003DE50 = (s32) (D_8003DE50 + 1);
            phi_a1 = D_8003DE50;
        }
        sp28 = temp_v0;
        osCreateThread(temp_v0 + 8, phi_a1, arg1, arg0, temp_v0->unk1B8 + (((u32) D_8004A54C >> 3) * 8), 0x33);
        temp_v0->unk1B8->unk38 = 0;
        temp_v0->unk1B8->unk3C = 0xFEDCBA98;
        if (D_8003DE50 >= 0x1312D00) {
            D_8003DE50 = 0x989680;
        }
    } else {
        temp_s0->unk14 = (u8)2;
        temp_v0->unk1BC = arg5;
        temp_v0->unk1B8 = arg4;
        if (temp_a3_2 != -1) {
            phi_a1_2 = temp_a3_2;
        } else {
            D_8003DE50 = (s32) (D_8003DE50 + 1);
            phi_a1_2 = D_8003DE50;
        }
        osCreateThread(temp_v0 + 8, phi_a1_2, arg1, arg0, ((arg5 >> 3) * 8) + arg4, 0x33);
        arg4->unk38 = 0;
        arg4->unk3C = 0xFEDCBA98;
        if (D_8003DE50 >= 0x1312D00) {
            D_8003DE50 = 0x989680;
        }
    }
    func_800080C0(temp_s0);
    return temp_s0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80008B94.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u8 func_80008DA8(void *arg0) {
    u8 phi_return;

    if ((arg0 == 0) || (arg0 == D_8004A7D0)) {
        D_8004A7D4 = 1;
        if (D_8004A7D0->unk14 == 0) {
block_4:
            return func_8000B6BC(1);
        }
        phi_return = D_8004A7D0->unk14;
        if (D_8004A7D0->unk14 == 2) {
            goto block_4;
        }
    } else {
        if (D_8004A558 != 0) {
            D_8004A558(arg0);
        }
        if (arg0->unk14 != 0) {
            if (arg0->unk14 != 1) {
                if (arg0->unk14 != 2) {

                } else {
                    osDestroyThread(arg0->unk1C + 8);
                    if (D_8004A550 != 0) {
                        D_8004A550(arg0->unk1C->unk1B8);
                    }
                    func_80007FB8(arg0->unk1C);
                }
            }
        } else {
            osDestroyThread(arg0->unk1C + 8);
            func_8000803C(arg0->unk1C->unk1B8 - 8);
            func_80007FB8(arg0->unk1C);
        }
        func_80008210(arg0);
        phi_return = func_80008198(arg0);
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80008DA8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_80008EC4:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80008EC4.s")
#endif

struct unk80009628Func {
    u8 filler[0x56];
    u8 unk56;
};

void func_80008EC4(u32, u8, u8, u32);

void func_80009628(struct unk80009628Func *arg0, u8 arg1, u8 arg2) {
    func_80008EC4(arg0, arg1, arg2, arg0->unk56);
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_80009658:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009658.s")
#endif

extern void func_80008830(struct Animation *anim, struct AnimStack *stack);

// Initializes a new AnimStack with an index
struct AnimStack *func_800097E0(struct Animation *anim, u8 index) {
    struct AnimStack *toReturn;

    toReturn = func_800087D8();
    toReturn->unk4 = index;
    toReturn->unk5 = 0;
    toReturn->unk20 = 0;
    toReturn->unk1C = 0.0f;
    toReturn->unk18 = 0.0f;
    toReturn->unk14 = 0.0f;
    toReturn->unk10 = 0.0f;
    toReturn->unkC = 0.0f;
    toReturn->unk8 = 1.0f;
    func_80008830(anim, toReturn);
    return toReturn;
}

extern f32 D_8004064C;

void func_8000984C(struct unk8000BE90Func *arg0) {
    struct AnimStack *temp_s1;
    struct AnimStack *phi_s0;

    phi_s0 = arg0->unk6C;
    while (phi_s0 != 0) {
        temp_s1 = phi_s0->next;
        func_80008860(phi_s0);
        phi_s0 = temp_s1;
    }
    arg0->unk6C = 0;
    arg0->unk74 = D_8004064C;
}

void *func_800098AC(s32 arg0, u8 index) {
    struct AnimStack *toReturn;

    toReturn = func_800087D8();
    toReturn->unk4 = index;
    toReturn->unk5 = 0;
    toReturn->unk20 = 0;
    toReturn->unk1C = 0.0f;
    toReturn->unk18 = 0.0f;
    toReturn->unk14 = 0.0f;
    toReturn->unk10 = 0.0f;
    toReturn->unkC = 0.0f;
    toReturn->unk8 = 1.0f;
    func_80008840(arg0, toReturn);
    return toReturn;
}

extern f32 D_80040650;

void func_80009918(struct unk80008840 *arg0) {
    struct AnimStack *temp_s1;
    struct AnimStack *phi_s0;

    phi_s0 = arg0->unk90;
    while (phi_s0 != 0) {
        temp_s1 = phi_s0->next;
        func_80008860(phi_s0);
        phi_s0 = temp_s1;
    }
    arg0->unk90 = 0;
    arg0->unk98 = D_80040650;
}

void *func_80009978(struct Animation* arg0, u8 arg1) {
    struct AnimStack *temp_v0;

    temp_v0 = func_800087D8();
    temp_v0->unk4 = arg1;
    temp_v0->unk5 = (u8)0;
    temp_v0->unk20 = 0;
    temp_v0->unk1C = 0.0f;
    temp_v0->unk18 = 0.0f;
    temp_v0->unk14 = 0.0f;
    temp_v0->unk10 = 0.0f;
    temp_v0->unkC = 0.0f;
    temp_v0->unk8 = 1.0f;
    func_80008850(arg0, temp_v0);
    return temp_v0;
}

extern f32 D_80040654;

// Unused?
void func_800099E4(struct Animation *arg0) {
    struct AnimStack *temp_s1;
    struct AnimStack *phi_s0;

    phi_s0 = arg0->unk6C;
    while (phi_s0 != 0) {
        temp_s1 = phi_s0->next;
        func_80008860(phi_s0);
        phi_s0 = temp_s1;
    }
    arg0->unk6C = 0;
    arg0->scale = D_80040654;
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80009A44(void *arg0, void *arg1) {
    f32 temp_f6;
    void *temp_t0;
    void *temp_t9;
    void *temp_v0;
    void *temp_v1;
    void *phi_v1;
    void *phi_a0;
    f32 phi_f6;
    void *phi_t9;
    void *phi_t0;

    temp_v0 = func_8000888C();
    if (arg0->unk80 != 0) {
        phi_v1 = *arg0->unk80;
        phi_a0 = arg0->unk80;
        if (*arg0->unk80 != 0) {
loop_2:
            temp_v1 = *phi_v1;
            phi_v1 = temp_v1;
            phi_a0 = phi_v1;
            if (temp_v1 != 0) {
                goto loop_2;
            }
        }
        *phi_a0 = temp_v0;
    } else {
        arg0->unk80 = temp_v0;
    }
    temp_v0->unk0 = 0;
    temp_f6 = (f32) arg1->unk54;
    phi_f6 = temp_f6;
    if ((s32) arg1->unk54 < 0) {
        phi_f6 = temp_f6 + 4294967296.0f;
    }
    temp_v0->unk84 = (f32) (phi_f6 / 255.0f);
    phi_t9 = arg1;
    phi_t0 = temp_v0;
loop_8:
    temp_t9 = phi_t9 + 0xC;
    temp_t0 = phi_t0 + 0xC;
    temp_t0->unk-4 = (s32) *phi_t9;
    temp_t0->unk0 = (s32) temp_t9->unk-8;
    temp_t0->unk4 = (s32) temp_t9->unk-4;
    phi_t9 = temp_t9;
    phi_t0 = temp_t0;
    if (temp_t9 != (arg1 + 0x78)) {
        goto loop_8;
    }
    temp_v0->unk2C = (f32) arg1->unk14;
    temp_v0->unk80 = (u16)0;
    temp_v0->unk82 = (u16)0;
    temp_v0->unk88 = 0.0f;
    temp_v0->unk90 = 0;
    temp_v0->unk94 = 0;
    temp_v0->unk30 = (f32) arg1->unk1C;
    temp_v0->unkA0 = 0.0f;
    temp_v0->unk98 = (f32) D_80040658;
    temp_v0->unk9C = 1.0f;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009A44.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80009B5C(void *arg0) {
    void *temp_s0;
    void *temp_s0_2;
    void *temp_s1;
    void *phi_s2;
    void *phi_s0;

    phi_s2 = arg0->unk80;
    if (arg0->unk80 != 0) {
loop_1:
        temp_s0 = phi_s2->unk90;
        phi_s0 = temp_s0;
        if (temp_s0 != 0) {
loop_2:
            temp_s1 = *phi_s0;
            func_80008860(phi_s0);
            phi_s0 = temp_s1;
            if (temp_s1 != 0) {
                goto loop_2;
            }
        }
        temp_s0_2 = phi_s2->unk0;
        func_800088E4(phi_s2);
        phi_s2 = temp_s0_2;
        if (temp_s0_2 != 0) {
            goto loop_1;
        }
    }
    arg0->unk80 = 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009B5C.s")
#endif

extern f32 D_8004065C;

// Not really sure what's going on here
#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80009BD4(struct DObj *arg0) {
    arg0->unk4C = 0;
    arg0->unk54 = 0;
    arg0->unk55 = 0;
    arg0->unk56 = 0;
    arg0->unk58 = 0;
    (&arg0[1])->unk5C = 0;
    (&arg0[1])->unk60 = 0;
    (&arg0[1])->unk64 = 0;
    (&arg0[1])->unk58 = 0;
    arg0->unk6C = 0;
    arg0->unk70 = 0;
    arg0->unk74 = D_8004065C;
    arg0->unk78 = 1.0f;
    arg0->unk7C = 0.0f;
    arg0->unk80 = 0;
    arg0->unk84 = 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009BD4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80009C38(void *arg0, s32 arg1) {
    void *sp1C;
    void *temp_v0;
    void *temp_v1;
    void *phi_v1;
    void *phi_a0;

    if (arg0 == 0) {
        phi_a2 = D_8004A7C4;
    }
    arg0 = phi_a2;
    temp_v0 = func_80008910(phi_a2);
    if (arg0->unk3C != 0) {
        phi_v1 = arg0->unk3C->unk8;
        phi_a0 = arg0->unk3C;
        if (arg0->unk3C->unk8 != 0) {
loop_4:
            temp_v1 = phi_v1->unk8;
            phi_v1 = temp_v1;
            phi_a0 = phi_v1;
            if (temp_v1 != 0) {
                goto loop_4;
            }
        }
        phi_a0->unk8 = temp_v0;
        temp_v0->unkC = phi_a0;
    } else {
        arg0->unkF = (u8)1;
        arg0->unk3C = temp_v0;
        temp_v0->unkC = NULL;
    }
    temp_v0->unk4 = arg0;
    temp_v0->unk14 = 1;
    temp_v0->unk8 = 0;
    temp_v0->unk10 = 0;
    temp_v0->unk50 = arg1;
    sp1C = temp_v0;
    func_80009BD4(temp_v0, temp_v0, arg0, arg0->unk3C);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009C38.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80009CE8(void *arg0, s32 arg1) {
    void *sp1C;
    void *temp_v0;

    temp_v0 = func_80008910();
    if (arg0->unk8 != 0) {
        arg0->unk8->unkC = temp_v0;
    }
    temp_v0->unkC = arg0;
    temp_v0->unk8 = (void *) arg0->unk8;
    arg0->unk8 = temp_v0;
    temp_v0->unk4 = (s32) arg0->unk4;
    temp_v0->unk10 = 0;
    temp_v0->unk14 = (s32) arg0->unk14;
    temp_v0->unk50 = arg1;
    sp1C = temp_v0;
    func_80009BD4(temp_v0, arg0);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009CE8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80009D5C(void *arg0, s32 arg1) {
    void *sp1C;
    void *temp_v0;
    void *temp_v1;
    void *phi_v1;
    void *phi_a0;

    temp_v0 = func_80008910();
    if (arg0->unk10 != 0) {
        phi_v1 = arg0->unk10->unk8;
        phi_a0 = arg0->unk10;
        if (arg0->unk10->unk8 != 0) {
loop_2:
            temp_v1 = phi_v1->unk8;
            phi_v1 = temp_v1;
            phi_a0 = phi_v1;
            if (temp_v1 != 0) {
                goto loop_2;
            }
        }
        phi_a0->unk8 = temp_v0;
        temp_v0->unkC = phi_a0;
    } else {
        arg0->unk10 = temp_v0;
        temp_v0->unkC = NULL;
    }
    temp_v0->unk14 = arg0;
    temp_v0->unk10 = 0;
    temp_v0->unk8 = 0;
    temp_v0->unk4 = (s32) arg0->unk4;
    temp_v0->unk50 = arg1;
    sp1C = temp_v0;
    func_80009BD4(temp_v0, temp_v0, arg0->unk10, arg0);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009D5C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80009DF4(void *arg0) {
    s32 temp_a0;
    s32 temp_s0;
    void *temp_s0_2;
    void *temp_s0_3;
    void *temp_s0_4;
    void *temp_s1;
    s32 phi_s0;
    void *phi_s1;
    s32 phi_s0_2;
    void *phi_s1_2;
    void *phi_s2;
    void *phi_s1_3;

    phi_s0 = arg0->unk10;
    if (arg0->unk10 != 0) {
loop_1:
        func_80009DF4(phi_s0);
        phi_s0 = arg0->unk10;
        if (arg0->unk10 != 0) {
            goto loop_1;
        }
    }
    if (arg0->unk14 == 1) {
        if (arg0 == arg0->unk4->unk3C) {
            arg0->unk4->unk3C = (void *) arg0->unk8;
            if (arg0->unk4->unk3C == 0) {
                arg0->unk4->unkF = (u8)0;
            }
        }
    } else {
        if (arg0 == arg0->unk14->unk10) {
            arg0->unk14->unk10 = (void *) arg0->unk8;
        }
    }
    if (arg0->unkC != 0) {
        arg0->unkC->unk8 = (void *) arg0->unk8;
    }
    phi_s1 = arg0;
    phi_s0_2 = 0;
    if (arg0->unk8 != 0) {
        arg0->unk8->unkC = (void *) arg0->unkC;
        phi_s1 = arg0;
        phi_s0_2 = 0;
    }
loop_12:
    temp_a0 = phi_s1->unk58;
    if (temp_a0 != 0) {
        func_800087AC(temp_a0);
    }
    temp_s0 = phi_s0_2 + 4;
    phi_s1 = phi_s1 + 4;
    phi_s0_2 = temp_s0;
    if (temp_s0 != 0x14) {
        goto loop_12;
    }
    if (arg0->unk4C != 0) {
        if (D_8004A798 != 0) {
            D_8004A798(arg0->unk4C);
        }
    }
    phi_s1_2 = arg0->unk6C;
    if (arg0->unk6C != 0) {
loop_19:
        temp_s0_2 = *phi_s1_2;
        func_80008860(phi_s1_2);
        phi_s1_2 = temp_s0_2;
        if (temp_s0_2 != 0) {
            goto loop_19;
        }
    }
    phi_s2 = arg0->unk80;
    if (arg0->unk80 != 0) {
loop_21:
        temp_s1 = phi_s2->unk90;
        phi_s1_3 = temp_s1;
        if (temp_s1 != 0) {
loop_22:
            temp_s0_3 = *phi_s1_3;
            func_80008860(phi_s1_3);
            phi_s1_3 = temp_s0_3;
            if (temp_s0_3 != 0) {
                goto loop_22;
            }
        }
        temp_s0_4 = phi_s2->unk0;
        func_800088E4(phi_s2);
        phi_s2 = temp_s0_4;
        if (temp_s0_4 != 0) {
            goto loop_21;
        }
    }
    func_80008968(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009DF4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80009F7C(void *arg0) {
    void *sp18;
    s32 temp_a0;
    s32 temp_v0_2;
    void *temp_v0;
    void *temp_v1;
    void *phi_a2;
    void *phi_v1;
    s32 phi_v0;

    phi_a2 = arg0;
    if (arg0 == 0) {
        phi_a2 = D_8004A7C4;
    }
    phi_a2->unkF = (u8)3;
    arg0 = phi_a2;
    temp_v0 = func_80008994(phi_a2);
    temp_a0 = temp_v0 + 8;
    arg0->unk3C = temp_v0;
    temp_v0->unk4 = arg0;
    sp18 = temp_v0;
    func_80007C9C(temp_a0, arg0);
    sp18->unk60 = 0;
    phi_v1 = sp18;
    phi_v0 = 0;
loop_3:
    temp_v0_2 = phi_v0 + 1;
    temp_v1 = phi_v1 + 4;
    temp_v1->unk60 = 0;
    phi_v1 = temp_v1;
    phi_v0 = temp_v0_2;
    if (temp_v0_2 != 2) {
        goto loop_3;
    }
    sp18->unk80 = 0;
    sp18->unk84 = 0;
    sp18->unk88 = 0;
    sp18->unk8C = 0;
    sp18->unk6C = 0;
    sp18->unk70 = 0;
    sp18->unk74 = (f32) D_80040660;
    sp18->unk78 = 1.0f;
    sp18->unk7C = 0.0f;
    return sp18;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_80009F7C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A02C(void *arg0) {
    s32 temp_a0;
    s32 temp_s0;
    void *temp_s1;
    void *phi_s1;
    s32 phi_s0;
    void *phi_s0_2;

    arg0->unk4->unkF = (u8)0;
    arg0->unk4->unk3C = 0;
    phi_s1 = arg0;
    phi_s0 = 0;
loop_1:
    temp_a0 = phi_s1->unk64;
    if (temp_a0 != 0) {
        func_800087AC(temp_a0);
    }
    temp_s0 = phi_s0 + 4;
    phi_s1 = phi_s1 + 4;
    phi_s0 = temp_s0;
    if (temp_s0 != 8) {
        goto loop_1;
    }
    phi_s0_2 = arg0->unk6C;
    if (arg0->unk6C != 0) {
loop_5:
        temp_s1 = *phi_s0_2;
        func_80008860(phi_s0_2);
        phi_s0_2 = temp_s1;
        if (temp_s1 != 0) {
            goto loop_5;
        }
    }
    func_800089EC(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A02C.s")
#endif

// omGAddCommon
#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000A0C0(s32 arg0, s32 arg1, u8 arg2, s32 arg3) {
    s32 sp18;
    s32 temp_a2;
    void *temp_v0;

    temp_a2 = arg2 & 0xFF;
    sp18 = temp_a2;
    if (temp_a2 >= 0x20) {
        fatal_printf(&D_800403DC, temp_a2, arg0);
        while (TRUE);
    }
    arg2 = (u8) temp_a2;
    temp_v0 = func_8000835C(temp_a2);
    if (temp_v0 == 0) {
        return NULL;
    }
    temp_v0->unkC = arg2;
    temp_v0->unk0 = arg0;
    temp_v0->unk10 = arg3;
    temp_v0->unk18 = 0;
    temp_v0->unk1C = 0;
    temp_v0->unk44 = 0;
    temp_v0->unkF = (u8)0;
    temp_v0->unk3C = 0;
    temp_v0->unkD = (u8)0x21;
    temp_v0->unk48 = 0;
    temp_v0->unk4C = 0;
    temp_v0->unk40 = 0.0f;
    temp_v0->unk14 = arg1;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A0C0.s")
#endif

struct unk800083CCFunc *func_8000A180(s32 arg0, s32 arg1, u32 arg2, u32 arg3) {
    struct unk800083CCFunc *temp_v0;

    temp_v0 = func_8000A0C0(arg0, arg1, arg2 & 0xFF, arg3);
    if (temp_v0 == NULL) {
        return NULL;
    } else {
        func_80008434(temp_v0);
        return temp_v0;
    }
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000A1C0(s32 arg2) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_8000A0C0(arg2 & 0xFF);
    if (temp_v0 == 0) {
        return 0;
    }
    sp1C = temp_v0;
    func_800084A0(temp_v0);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A1C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000A200(void *arg2) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_8000A0C0(arg2->unkC, arg2->unk10);
    if (temp_v0 == 0) {
        return 0;
    }
    sp1C = temp_v0;
    func_800083CC(temp_v0, arg2);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A200.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000A24C(void *arg2) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_8000A0C0(arg2->unkC, arg2->unk10);
    if (temp_v0 == 0) {
        return 0;
    }
    sp1C = temp_v0;
    func_800083CC(temp_v0, arg2->unk8);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A24C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A29C(void *arg0) {
    if (arg0 == 0 || arg0 == D_8004A7C4) {
        D_8004A7D4 = 2;
        return;
    }
    func_8000B870(arg0);
    if (arg0->unkF != 1) {
        if (arg0->unkF != 2) {
            if (arg0->unkF != 3) {

            } else {
                func_8000A02C(arg0->unk3C);
            }
        }
    } else {
        func_8000BBE0(arg0);
    }
    if (arg0->unkD != 0x21) {
        func_800086EC(arg0);
    }
    func_80008528(arg0);
    func_800083A0(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A29C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A350(s32 arg0, void *arg1, u8 arg2, s32 arg3, void *arg4) {
    void *sp20;
    void *temp_s0;
    void *temp_s1;
    void *phi_s0;
    void *phi_s1;
    void *phi_s1_2;

    if ((s32) arg2 >= 0x20) {
        fatal_printf(&D_80040414, arg2, *arg1);
loop_2:
        goto loop_2;
    }
    phi_s0 = arg1;
    if (arg1 == 0) {
        phi_s0 = D_8004A7C4;
    }
    sp20 = phi_s0->unk18;
    phi_s0->unk18 = NULL;
    phi_s0->unk1C = 0;
    phi_s1 = sp20;
    if (sp20 != 0) {
loop_6:
        func_800081C4(phi_s1);
        temp_s1 = *phi_s1;
        phi_s1 = temp_s1;
        if (temp_s1 != 0) {
            goto loop_6;
        }
    }
    func_80008528(phi_s0);
    phi_s0->unkC = arg2;
    phi_s0->unk10 = arg3;
    if (arg0 != 0) {
        if (arg0 != 1) {
            if (arg0 != 2) {
                if (arg0 != 3) {

                } else {
                    func_800083CC(phi_s0, arg4->unk8);
                }
            } else {
                func_800083CC(phi_s0, arg4);
            }
        } else {
            func_800084A0(phi_s0);
        }
    } else {
        func_80008434(phi_s0);
    }
    if (sp20 != 0) {
loop_18:
        temp_s0 = *phi_s1_2;
        func_800080C0(phi_s1_2);
        phi_s1_2 = temp_s0;
        if (temp_s0 != 0) {
            goto loop_18;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A350.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A498(s32 arg0, u8 arg1, ? arg2) {
    func_8000A350(0, arg0, arg1, arg2, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A498.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A4D0(s32 arg0, u8 arg1, ? arg2) {
    func_8000A350(1, arg0, arg1, arg2, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A4D0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A508(s32 arg0, void *arg1) {
    func_8000A350(2, arg0, arg1->unkC, arg1->unk10, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A508.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A544(s32 arg0, void *arg1) {
    func_8000A350(3, arg0, arg1->unkC, arg1->unk10, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A544.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A580(void *arg0, ?32 arg1, s32 arg2, ?32 arg3, s32 arg4) {
    s32 sp24;
    s32 temp_a2;

    temp_a2 = arg2 & 0xFF;
    sp24 = temp_a2;
    if (temp_a2 >= 0x20) {
        fatal_printf(&D_8004044C, temp_a2, arg0->unk0);
loop_2:
        goto loop_2;
    }
    arg0->unkD = (s8) temp_a2;
    arg0->unk28 = arg3;
    arg0->unk2C = arg1;
    arg0->unk34 = arg4;
    arg0->unkE = (s8) (D_8003DCA8 - 1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A580.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A5FC(s32 arg0, s32 arg2, s32 arg4) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A580(phi_a0, arg2 & 0xFF, arg4);
    func_800085F8(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A5FC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A640(s32 arg0, s32 arg2, s32 arg4) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A580(phi_a0, arg2 & 0xFF, arg4);
    func_80008664(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A640.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A684(s32 arg0, s32 arg2, void *arg3) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A580(phi_a0, arg3->unkD, arg3->unk28, arg2);
    func_80008590(arg0, arg3);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A684.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A6D8(s32 arg0, s32 arg2, void *arg3) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A580(phi_a0, arg3->unkD, arg3->unk28, arg2);
    func_80008590(arg0, arg3->unk8);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A6D8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A730(void *arg0, ?32 arg1, ?32 arg2, ?32 arg3, s32 arg4) {
    arg0->unkD = (u8)0x20;
    arg0->unk28 = arg2;
    arg0->unk2C = arg1;
    arg0->unk30 = arg3;
    arg0->unk38 = 0;
    arg0->unk34 = arg4;
    arg0->unkE = (s8) (D_8003DCA8 - 1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A730.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A764(s32 arg0, s32 arg4) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A730(phi_a0, arg4);
    func_800085F8(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A764.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A7A0(s32 arg0, s32 arg4) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A730(phi_a0, arg4);
    func_80008664(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A7A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A7DC(s32 arg0, s32 arg2, s32 arg3, void *arg4) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A730(phi_a0, arg4->unk28, arg2, arg3);
    func_80008590(arg0, arg4);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A7DC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A830(s32 arg0, s32 arg2, s32 arg3, void *arg4) {
    s32 phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    arg0 = phi_a0;
    func_8000A730(phi_a0, arg4->unk28, arg2, arg3);
    func_80008590(arg0, arg4->unk8);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A830.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A888(void *arg0, u8 arg1, s32 arg2) {
    s32 sp1C;
    s32 temp_a1;
    void *temp_a0;
    void *temp_a3;

    temp_a1 = arg1 & 0xFF;
    temp_a3 = arg0;
    sp1C = temp_a1;
    if (temp_a1 >= 0x20) {
        fatal_printf(&D_80040490, temp_a1, temp_a3->unk0, temp_a3);
loop_2:
        goto loop_2;
    }
    temp_a0 = temp_a3;
    arg1 = (u8) temp_a1;
    arg0 = temp_a3;
    func_800086EC(temp_a0, temp_a1, temp_a3);
    arg0->unkD = arg1;
    arg0->unk28 = arg2;
    func_800085F8(arg0, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A888.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A904(void *arg0, u8 arg1, s32 arg2) {
    s32 sp1C;
    u8 temp_a1;
    void *temp_a0;
    void *temp_a3;

    temp_a1 = arg1;
    temp_a3 = arg0;
    sp1C = temp_a1;
    if (temp_a1 >= 0x20) {
        fatal_printf(&D_800404CC, temp_a1, temp_a3->unk0, temp_a3);
        while (TRUE);
    }
    temp_a0 = temp_a3;
    arg1 = (u8) temp_a1;
    arg0 = temp_a3;
    func_800086EC(temp_a0, temp_a1, temp_a3);
    arg0->unkD = arg1;
    arg0->unk28 = arg2;
    func_80008664(arg0, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A904.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A980(void *arg0, void *arg1) {
    func_800086EC();
    arg0->unkD = (u8) arg1->unkD;
    arg0->unk28 = (s32) arg1->unk28;
    func_80008590(arg0, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A980.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000A9C0(void *arg0, void *arg1) {
    func_800086EC();
    arg0->unkD = (u8) arg1->unkD;
    arg0->unk28 = (s32) arg1->unk28;
    func_80008590(arg0, arg1->unk24, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000A9C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000AA04(void *arg0, s32 arg1) {
    func_800086EC();
    arg0->unk28 = arg1;
    func_800085F8(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AA04.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000AA38(void *arg0, s32 arg1) {
    func_800086EC();
    arg0->unk28 = arg1;
    func_80008664(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AA38.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000AA6C(void *arg0, void *arg1) {
    func_800086EC();
    arg0->unk28 = (s32) arg1->unk28;
    func_80008590(arg0, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AA6C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000AAA4(void *arg0, void *arg1) {
    func_800086EC();
    arg0->unk28 = (s32) arg1->unk28;
    func_80008590(arg0, arg1->unk8);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AAA4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000AAE0(void) {
    s32 temp_v1;
    void *temp_ret;
    void *temp_v0;
    void *phi_v0;
    void *phi_s0;
    void *phi_return;
    void *phi_return_2;

    D_8004A7C8 = NULL;
    D_8004A7CC = 0;
    temp_v1 = D_8003DCA8 - 1;
    phi_v0 = &D_8004A7F8;
loop_1:
    temp_v0 = phi_v0 + 0x50;
    temp_v0->unk-3C = (s8) temp_v1;
    temp_v0->unk-28 = (s8) temp_v1;
    temp_v0->unk-14 = (s8) temp_v1;
    temp_v0->unk-50 = (s8) temp_v1;
    phi_v0 = temp_v0;
    if (temp_v0 != &D_8004AA78) {
        goto loop_1;
    }
    phi_s0 = D_8004A700;
    phi_return = temp_v0;
    phi_return_2 = temp_v0;
    if (D_8004A700 != 0) {
loop_3:
        if ((phi_s0->unk44 & 1) == 0) {
            D_8003DE54 = 3;
            D_8004A7C8 = phi_s0;
            temp_ret = phi_s0->unk2C(phi_s0);
            D_8003DE54 = 0;
            phi_return_2 = temp_ret;
        }
        phi_s0 = phi_s0->unk20;;
        phi_return = phi_return_2;
        if (phi_s0 != 0) {
            goto loop_3;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AAE0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000ABAC(void *arg0) {
    s32 sp1C;

    D_8003DE54 = 1;
    D_8004A7C4 = arg0;
    arg0->unk14();
    D_8004A7C4 = 0;
    D_8003DE54 = 0;
    if (D_8004A7D4 != 0) {
        if (D_8004A7D4 != 2) {
            D_8004A7D4 = 0;
        } else {
            D_8004A7D4 = 0;
            sp1C = arg0->unk4;
            func_8000A29C(arg0, arg0->unk4);
        }
    }
    return arg0->unk4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000ABAC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000AC3C(void *arg0) {
    void *sp1C;
    s32 temp_a0;
    s32 temp_v0;
    void *temp_a3;
    void *temp_v1;
    void *temp_v1_2;
    void *phi_a3;
    void *phi_v1;
    void *phi_v1_2;
    void *phi_v1_3;

    D_8003DE54 = 2;
    temp_a3 = arg0;
    D_8004A7C4 = (s32) arg0->unk18;
    D_8004A7D0 = arg0;
    if ((arg0->unk14 != 0) && (arg0->unk14 != 1)) {
        phi_a3 = temp_a3;
        if (arg0->unk14 == 2) {
block_3:
            arg0 = temp_a3;
            osStartThread(temp_a3->unk1C + 8, 2, temp_a3);
            osRecvMesg(&D_8004A7E0, 0, 1);
        }
    } else {
        goto block_3;
    }
    temp_v1 = phi_a3->unk8;
    D_8004A7C4 = 0;
    D_8004A7D0 = 0;
    D_8003DE54 = 0;
    phi_v1_3 = temp_v1;
    if (D_8004A7D4 != 0) {
        if (D_8004A7D4 != 1) {
            if (D_8004A7D4 != 2) {
                D_8004A7D4 = 0;
                phi_v1_3 = temp_v1;
            } else {
                D_8004A7D4 = 0;
                phi_v1_2 = temp_v1;
                if (temp_v1 != 0) {
                    temp_v0 = phi_a3->unk18;
                    phi_v1 = temp_v1;
                    phi_v1_2 = temp_v1;
                    if (temp_v0 == temp_v1->unk18) {
loop_12:
                        temp_v1_2 = phi_v1->unk8;
                        phi_v1_2 = temp_v1_2;
                        if (temp_v1_2 != 0) {
                            phi_v1 = temp_v1_2;
                            phi_v1_2 = temp_v1_2;
                            if (temp_v0 == temp_v1_2->unk18) {
                                goto loop_12;
                            }
                        }
                    }
                }
                sp1C = phi_v1_2;
                func_8000A29C(phi_a3->unk18, &D_8004A7D4, 2, phi_a3);
block_16:
                phi_v1_3 = sp1C;
            }
        } else {
            D_8004A7D4 = 0;
            sp1C = temp_v1;
            func_80008DA8(phi_a3, &D_8004A7D4, 2, phi_a3);
            goto block_16;
        }
    }
    return phi_v1_3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AC3C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000AD88(void) {
    void *temp_s0;
    void *temp_s0_2;
    void *temp_s1;
    void *temp_s1_2;
    void *phi_s1;
    void *phi_s0;
    void *phi_s0_2;
    void *phi_s1_2;
    void *phi_s0_3;
    void *phi_s0_4;

    D_8004A7D4 = 0;
    D_8004A7C4 = 0;
    D_8004A7D0 = 0;
    phi_s1 = &D_8004A578;
loop_1:
    temp_s0 = *phi_s1;
    phi_s0 = temp_s0;
    if (temp_s0 != 0) {
loop_2:
        if (((phi_s0->unk44 & 0x40) == 0) && (phi_s0->unk14 != 0)) {
            phi_s0_2 = func_8000ABAC(phi_s0);
        } else {
            phi_s0_2 = phi_s0->unk4;
        }
        phi_s0 = phi_s0_2;
        if (phi_s0_2 != 0) {
            goto loop_2;
        }
    }
    temp_s1 = phi_s1 + 4;
    phi_s1 = temp_s1;
    if ((u32) temp_s1 < (u32) &D_8004A5F8) {
        goto loop_1;
    }
    phi_s1_2 = &D_8004A56C;
loop_9:
    temp_s0_2 = *phi_s1_2;
    phi_s0_3 = temp_s0_2;
    if (temp_s0_2 != 0) {
loop_10:
        if (phi_s0_3->unk15 == 0) {
            phi_s0_4 = func_8000AC3C(phi_s0_3);
        } else {
            phi_s0_4 = phi_s0_3->unk8;
        }
        phi_s0_3 = phi_s0_4;
        if (phi_s0_4 != 0) {
            goto loop_10;
        }
    }
    temp_s1_2 = phi_s1_2 - 4;
    phi_s1_2 = temp_s1_2;
    if ((u32) temp_s1_2 >= (u32) &D_8004A560) {
        goto loop_9;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AD88.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000AE84(void *arg0) {
    s32 temp_a0;
    s32 temp_a0_10;
    s32 temp_a0_3;
    s32 temp_a0_4;
    s32 temp_a0_5;
    s32 temp_a0_6;
    s32 temp_a0_7;
    s32 temp_a0_8;
    s32 temp_a0_9;
    u32 temp_a0_2;
    u32 temp_v0_4;
    u32 temp_v0_8;
    void *temp_t4;
    void *temp_t4_2;
    void *temp_t4_3;
    void *temp_t9;
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v0_3;
    void *temp_v0_5;
    void *temp_v0_6;
    void *temp_v0_7;
    void *temp_v0_9;
    void *temp_v1;
    void *temp_v1_2;
    void *phi_v1;
    s32 phi_a0;
    void *phi_v1_2;
    void *phi_v0;
    u32 phi_a0_2;
    void *phi_v0_2;
    void *phi_v1_3;
    s32 phi_a0_3;
    void *phi_v1_4;
    u32 phi_v0_3;
    void *phi_v0_4;
    s32 phi_a0_4;
    void *phi_v0_5;
    void *phi_v1_5;
    s32 phi_a0_5;
    void *phi_v1_6;
    void *phi_v1_7;
    s32 phi_a0_6;
    void *phi_v1_8;
    void *phi_v1_9;
    s32 phi_a0_7;
    void *phi_v1_10;
    void *phi_v0_6;
    s32 phi_a0_8;
    void *phi_v0_7;
    void *phi_v0_8;
    s32 phi_a0_9;
    void *phi_v0_9;
    void *phi_v0_10;
    s32 phi_a0_10;
    void *phi_v0_11;
    void *phi_v1_11;
    u32 phi_v0_12;
    void *phi_v1_12;
    void *phi_v0_13;
    u32 phi_a0_11;
    s32 phi_a0_12;
    s32 phi_a0_13;
    s32 phi_a0_14;
    s32 phi_a0_15;
    s32 phi_a0_16;

    D_8004A54C = (s32) arg0->unk8;
    D_8004A550 = (s32) arg0->unk14;
    if (arg0->unk4 != 0) {
        gObjectThreadMaybe = (void *) arg0->unk0;
        phi_v1 = arg0->unk0;
        phi_a0 = 0;
        phi_v1_2 = arg0->unk0;
        if ((arg0->unk4 - 1) > 0) {
loop_2:
            temp_v0 = phi_v1 + 0x1C0;
            *phi_v1 = temp_v0;
            temp_a0 = phi_a0 + 1;
            phi_v1 = temp_v0;
            phi_a0 = temp_a0;
            if (temp_a0 < (arg0->unk4 - 1)) {
                goto loop_2;
            }
            phi_v1_2 = temp_v0;
        }
        *phi_v1_2 = 0;
    } else {
        gObjectThreadMaybe = 0;
        phi_a0_11 = 0U;
    }
    if ((arg0->unk10 != 0) && (arg0->unk8 != 0)) {
        gObjectThreadStackMaybe = (void *) arg0->unkC;
        phi_v0_2 = arg0->unkC;
        phi_a0_3 = (s32) phi_a0_11;
        if ((arg0->unk10 - 1) != 0) {
            phi_v0 = arg0->unkC;
            phi_a0_2 = phi_a0_11;
loop_10:
            *phi_v0 = (s32) ((phi_v0 + D_8004A54C) + 8);
            temp_a0_2 = phi_a0_2 + 1;
            temp_v0_2 = (phi_v0 + D_8004A54C) + 8;
            phi_v0 = temp_v0_2;
            phi_a0_2 = temp_a0_2;
            if (temp_a0_2 < (u32) (arg0->unk10 - 1)) {
                goto loop_10;
            }
            phi_v0_2 = temp_v0_2;
            phi_a0_3 = 0;
        }
        *phi_v0_2 = 0;
    } else {
        gObjectThreadStackMaybe = 0;
        phi_a0_3 = (s32) phi_a0_11;
    }
    if (arg0->unk1C != 0) {
        gObjectProcessMaybe = (void *) arg0->unk18;
        phi_v1_3 = arg0->unk18;
        phi_v1_4 = arg0->unk18;
        if ((arg0->unk1C - 1) > 0) {
loop_16:
            temp_v0_3 = phi_v1_3 + 0x24;
            *phi_v1_3 = temp_v0_3;
            temp_a0_3 = phi_a0_3 + 1;
            phi_v1_3 = temp_v0_3;
            phi_a0_3 = temp_a0_3;
            phi_v1_4 = temp_v0_3;
            if (temp_a0_3 < (arg0->unk1C - 1)) {
                goto loop_16;
            }
        }
        *phi_v1_4 = 0;
    } else {
        gObjectProcessMaybe = 0;
    }
    phi_v0_3 = (u32) &D_8004A560;
loop_20:
    temp_v0_4 = phi_v0_3 + 4;
    temp_v0_4->unk-4 = 0;
    phi_v0_3 = temp_v0_4;
    if (temp_v0_4 < (u32) &D_8004A570) {
        goto loop_20;
    }
    if (arg0->unk24 != 0) {
        D_8004A678 = (void *) arg0->unk20;
        phi_v0_4 = arg0->unk20;
        phi_a0_4 = 0;
        phi_v0_5 = arg0->unk20;
        if ((arg0->unk24 - 1) > 0) {
loop_23:
            temp_a0_4 = phi_a0_4 + 1;
            temp_t9 = phi_v0_4 + arg0->unk28;
            phi_v0_4->unk4 = temp_t9;
            phi_v0_4 = temp_t9;
            phi_a0_4 = temp_a0_4;
            if (temp_a0_4 < (arg0->unk24 - 1)) {
                goto loop_23;
            }
            phi_v0_5 = temp_t9;
        }
        phi_v0_5->unk4 = 0;
    } else {
        D_8004A678 = 0;
        phi_a0_12 = 0;
    }
    D_8004A798 = (s32) arg0->unk34;
    if (arg0->unk30 != 0) {
        D_8004A790 = (void *) arg0->unk2C;
        phi_v1_5 = arg0->unk2C;
        phi_a0_5 = phi_a0_12;
        phi_v1_6 = arg0->unk2C;
        phi_a0_13 = phi_a0_12;
        if ((arg0->unk30 - 1) > 0) {
loop_29:
            temp_v0_5 = phi_v1_5 + 0x48;
            *phi_v1_5 = temp_v0_5;
            temp_a0_5 = phi_a0_5 + 1;
            phi_v1_5 = temp_v0_5;
            phi_a0_5 = temp_a0_5;
            if (temp_a0_5 < (arg0->unk30 - 1)) {
                goto loop_29;
            }
            phi_v1_6 = temp_v0_5;
            phi_a0_13 = 0;
        }
        *phi_v1_6 = 0;
    } else {
        D_8004A790 = 0;
        phi_a0_13 = phi_a0_12;
    }
    if (arg0->unk3C != 0) {
        D_8004A79C = (void *) arg0->unk38;
        phi_v1_7 = arg0->unk38;
        phi_a0_6 = phi_a0_13;
        phi_v1_8 = arg0->unk38;
        phi_a0_14 = phi_a0_13;
        if ((arg0->unk3C - 1) > 0) {
loop_35:
            temp_v0_6 = phi_v1_7 + 0x24;
            *phi_v1_7 = temp_v0_6;
            temp_a0_6 = phi_a0_6 + 1;
            phi_v1_7 = temp_v0_6;
            phi_a0_6 = temp_a0_6;
            if (temp_a0_6 < (arg0->unk3C - 1)) {
                goto loop_35;
            }
            phi_v1_8 = temp_v0_6;
            phi_a0_14 = 0;
        }
        *phi_v1_8 = 0;
    } else {
        *(void *)0x80050000 = 0;
        phi_a0_14 = phi_a0_13;
    }
    if (arg0->unk44 != 0) {
        D_8004A7A4 = (void *) arg0->unk40;
        phi_v1_9 = arg0->unk40;
        phi_a0_7 = phi_a0_14;
        phi_v1_10 = arg0->unk40;
        phi_a0_15 = phi_a0_14;
        if ((arg0->unk44 - 1) > 0) {
loop_41:
            temp_v0_7 = phi_v1_9 + 0xA8;
            *phi_v1_9 = temp_v0_7;
            temp_a0_7 = phi_a0_7 + 1;
            phi_v1_9 = temp_v0_7;
            phi_a0_7 = temp_a0_7;
            if (temp_a0_7 < (arg0->unk44 - 1)) {
                goto loop_41;
            }
            phi_v1_10 = temp_v0_7;
            phi_a0_15 = 0;
        }
        *phi_v1_10 = 0;
    } else {
        *(void *)0x80050000 = 0;
        phi_a0_15 = phi_a0_14;
    }
    if (arg0->unk4C != 0) {
        D_8004A7AC = (void *) arg0->unk48;
        phi_v0_6 = arg0->unk48;
        phi_a0_8 = phi_a0_15;
        phi_v0_7 = arg0->unk48;
        phi_a0_16 = phi_a0_15;
        if ((arg0->unk4C - 1) > 0) {
loop_47:
            temp_a0_8 = phi_a0_8 + 1;
            temp_t4 = phi_v0_6 + arg0->unk50;
            *phi_v0_6 = temp_t4;
            phi_v0_6 = temp_t4;
            phi_a0_8 = temp_a0_8;
            if (temp_a0_8 < (arg0->unk4C - 1)) {
                goto loop_47;
            }
            phi_v0_7 = temp_t4;
            phi_a0_16 = 0;
        }
        *phi_v0_7 = 0;
    } else {
        *(void *)0x80050000 = 0;
        phi_a0_16 = phi_a0_15;
    }
    if (arg0->unk58 != 0) {
        D_8004A7B4 = (void *) arg0->unk54;
        phi_v0_8 = arg0->unk54;
        phi_a0_9 = phi_a0_16;
        phi_v0_9 = arg0->unk54;
        phi_a0_10 = phi_a0_16;
        if ((arg0->unk58 - 1) > 0) {
loop_53:
            temp_a0_9 = phi_a0_9 + 1;
            temp_t4_2 = phi_v0_8 + arg0->unk5C;
            *phi_v0_8 = temp_t4_2;
            phi_v0_8 = temp_t4_2;
            phi_a0_9 = temp_a0_9;
            if (temp_a0_9 < (arg0->unk58 - 1)) {
                goto loop_53;
            }
            phi_v0_9 = temp_t4_2;
            phi_a0_10 = 0;
        }
        *phi_v0_9 = 0;
    } else {
        *(void *)0x80050000 = 0;
        phi_a0_10 = phi_a0_16;
    }
    if (arg0->unk64 != 0) {
        D_8004A7BC = (void *) arg0->unk60;
        phi_v0_10 = arg0->unk60;
        phi_v0_11 = arg0->unk60;
        if ((arg0->unk64 - 1) > 0) {
loop_59:
            temp_a0_10 = phi_a0_10 + 1;
            temp_t4_3 = phi_v0_10 + arg0->unk68;
            *phi_v0_10 = temp_t4_3;
            phi_v0_10 = temp_t4_3;
            phi_a0_10 = temp_a0_10;
            phi_v0_11 = temp_t4_3;
            if (temp_a0_10 < (arg0->unk64 - 1)) {
                goto loop_59;
            }
        }
        *phi_v0_11 = 0;
    } else {
        *(void *)0x80050000 = 0;
    }
    phi_v1_11 = &D_8004A5F8;
    phi_v0_12 = (u32) &D_8004A578;
loop_63:
    temp_v0_8 = phi_v0_12 + 4;
    temp_v1 = phi_v1_11 + 4;
    temp_v1->unk-4 = 0;
    temp_v0_8->unk-4 = 0;
    phi_v1_11 = temp_v1;
    phi_v0_12 = temp_v0_8;
    if (temp_v0_8 < (u32) &D_8004A5F8) {
        goto loop_63;
    }
    D_8004A708 = 0;
    D_8004A680 = 0;
    phi_v1_12 = &D_8004A70C;
    phi_v0_13 = &D_8004A684;
loop_65:
    temp_v0_9 = phi_v0_13 + 0x10;
    phi_v1_12->unk4 = 0;
    temp_v0_9->unk-C = 0;
    phi_v1_12->unk8 = 0;
    temp_v0_9->unk-8 = 0;
    phi_v1_12->unkC = 0;
    temp_v0_9->unk-4 = 0;
    temp_v1_2 = phi_v1_12 + 0x10;
    temp_v1_2->unk-10 = 0;
    temp_v0_9->unk-10 = 0;
    phi_v1_12 = temp_v1_2;
    phi_v0_13 = temp_v0_9;
    if (temp_v0_9 != &D_8004A704) {
        goto loop_65;
    }
    func_8001479C(&D_8004A704, arg0, &D_8004A54C);
    osCreateMesgQueue(&D_8004A7E0, &D_8004A7D8, 1);
    D_8004A7C0 = 0;
    D_8004A7B8 = 0;
    D_8004A7B0 = 0;
    D_8004A7A0 = 0;
    D_8004A794 = 0;
    D_8004A78C = 0;
    D_8004A570 = 0;
    D_8004A544 = 0;
    D_8004A548 = 0;
    D_8004A558 = 0;
    func_80017B34(0, &D_8004A7B0, &D_8004A7A0, &D_8004A794);
    D_8003DE54 = 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000AE84.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B3E0(s32 arg0, void *arg1, ? arg2) {
    void *temp_s0;
    void *temp_s1;
    void *phi_s0;

    temp_s0 = (arg0 * 4) + 0x80050000;
    phi_s0 = temp_s0->unk-5A88;
    if (temp_s0->unk-5A88 != 0) {
loop_1:
        temp_s1 = phi_s0->unk4;
        arg1(phi_s0, arg2);
        phi_s0 = temp_s1;
        if (temp_s1 != 0) {
            goto loop_1;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B3E0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B448(void *arg0, ? arg1) {
    void *temp_s0;
    void *temp_s1;
    void *temp_s4;
    void *phi_s4;
    void *phi_s0;

    phi_s4 = &D_8004A578;
loop_1:
    temp_s0 = *phi_s4;
    phi_s0 = temp_s0;
    if (temp_s0 != 0) {
loop_2:
        temp_s1 = phi_s0->unk4;
        arg0(phi_s0, arg1);
        phi_s0 = temp_s1;
        if (temp_s1 != 0) {
            goto loop_2;
        }
    }
    temp_s4 = phi_s4 + 4;
    phi_s4 = temp_s4;
    if (temp_s4 != &D_8004A5F8) {
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B448.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000B4D4(s32 arg0, void *arg1, ? arg2, s32 arg3) {
    s32 temp_ret;
    s32 temp_v0;
    void *temp_s0;
    void *temp_s1;
    void *phi_s0;
    s32 phi_s3;
    s32 phi_s3_2;

    temp_s0 = (arg0 * 4) + 0x80050000;
    phi_s3 = 0;
    if (temp_s0->unk-5A88 != 0) {
        phi_s0 = temp_s0->unk-5A88;
        phi_s3_2 = 0;
loop_2:
        temp_s1 = phi_s0->unk4;
        temp_ret = arg1(phi_s0, arg2);
        temp_v0 = temp_ret;
        if (temp_v0 != 0) {
            phi_s3_2 = temp_v0;
            if (arg3 == 1) {
                return temp_ret;
            }
        }
        phi_s0 = temp_s1;
        phi_s3 = phi_s3_2;
        if (temp_s1 != 0) {
            goto loop_2;
        }
    }
    return phi_s3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B4D4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000B57C(void *arg0, ? arg1, s32 arg2) {
    s32 temp_ret;
    s32 temp_v0;
    void *temp_a0;
    void *temp_s0;
    void *temp_s6;
    void *phi_s6;
    void *phi_a0;
    s32 phi_s5;
    s32 phi_s5_2;
    s32 phi_s5_3;

    phi_s6 = &D_8004A578;
    phi_s5_3 = 0;
loop_1:
    temp_a0 = *phi_s6;
    phi_a0 = temp_a0;
    phi_s5 = phi_s5_3;
    phi_s5_2 = phi_s5_3;
    if (temp_a0 != 0) {
loop_2:
        temp_s0 = phi_a0->unk4;
        temp_ret = arg0(phi_a0, arg1);
        temp_v0 = temp_ret;
        if (temp_v0 != 0) {
            phi_s5_2 = temp_v0;
            if (arg2 == 1) {
                return temp_ret;
            }
        }
        phi_a0 = temp_s0;
        phi_s5 = phi_s5_2;
        if (temp_s0 != 0) {
            goto loop_2;
        }
    }
    temp_s6 = phi_s6 + 4;
    phi_s6 = temp_s6;
    phi_s5_3 = phi_s5;
    if (temp_s6 != &D_8004A5F8) {
        goto loop_1;
    }
    return phi_s5;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B57C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000B63C(void *arg0, s32 arg1) {
    if (arg1 == *arg0) {
        return arg0;
    }
    return NULL;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B63C.s")
#endif

extern u32 D_8000B63C;

void func_8000B4D4(u32, void*, s32, s32);

void func_8000B65C(u32 arg0, s32 arg1) {
    func_8000B4D4(arg0, &D_8000B63C, arg1, 1);
}

void func_8000B57C(void*, s32, s32);

void func_8000B688(s32 arg0) {
    func_8000B57C(&D_8000B63C, arg0, 1);
}

void func_8000B6B4(s32 arg0) {

}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000B6BC(s32 arg0) {
    s32 temp_s0;
    s32 phi_s0;
    void *phi_return;

    if ((D_8004A7D0->unk1C->unk1B8->unk38 != 0) || (phi_return = D_8004A7D0, (D_8004A7D0->unk1C->unk1B8->unk3C != 0xFEDCBA98))) {
        phi_return = fatal_printf(&D_80040670, *D_8004A7D0->unk18);
    } else {

    }
    if (arg0 != 0) {
        phi_s0 = arg0;
loop_5:
        osSendMesg(&D_8004A7E0, 1, 0);
        temp_s0 = phi_s0 - 1;
        phi_s0 = temp_s0;
        phi_return = osStopThread(0);
        if (temp_s0 != 0) {
            goto loop_5;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B6BC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000B758(void *arg0) {
    void *temp_v0;
    void *temp_v0_2;
    void *phi_a0;
    void *phi_v0;
    void *phi_return;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    temp_v0 = phi_a0->unk18;
    phi_v0 = temp_v0;
    phi_return = temp_v0;
    if (temp_v0 != 0) {
loop_3:
        phi_v0->unk15 = (u8)1;
        temp_v0_2 = phi_v0->unk0;
        phi_v0 = temp_v0_2;
        phi_return = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_3;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B758.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000B78C(void *arg0) {
    void *temp_v0;
    void *temp_v0_2;
    void *phi_a0;
    void *phi_v0;
    void *phi_return;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    temp_v0 = phi_a0->unk18;
    phi_v0 = temp_v0;
    phi_return = temp_v0;
    if (temp_v0 != 0) {
loop_3:
        phi_v0->unk15 = (u8)0;
        temp_v0_2 = phi_v0->unk0;
        phi_v0 = temp_v0_2;
        phi_return = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_3;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B78C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B7C0(void *arg0) {
    void *phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7D0;
    }
    phi_a0->unk15 = (u8)1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B7C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B7D8(void *arg0) {
    void *phi_a0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7D0;
    }
    phi_a0->unk15 = (u8)0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B7D8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000B7F0(void *arg0, s32 arg1) {
    void *temp_v0;
    void *temp_v0_2;
    void *phi_a0;
    void *phi_v0;
    void *phi_return;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    temp_v0 = phi_a0->unk18;
    phi_v0 = temp_v0;
    phi_return = temp_v0;
    if (temp_v0 != 0) {
loop_3:
        if (arg1 == phi_v0->unk20) {
            phi_v0->unk15 = (u8)1;
        }
        temp_v0_2 = phi_v0->unk0;
        phi_v0 = temp_v0_2;
        phi_return = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_3;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B7F0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000B830(void *arg0, s32 arg1) {
    void *temp_v0;
    void *temp_v0_2;
    void *phi_a0;
    void *phi_v0;
    void *phi_return;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    temp_v0 = phi_a0->unk18;
    phi_v0 = temp_v0;
    phi_return = temp_v0;
    if (temp_v0 != 0) {
loop_3:
        if (arg1 == phi_v0->unk20) {
            phi_v0->unk15 = (u8)0;
        }
        temp_v0_2 = phi_v0->unk0;
        phi_v0 = temp_v0_2;
        phi_return = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_3;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B830.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B870(void *arg0) {
    void *temp_s0;
    void *temp_s1;
    void *phi_a0;
    void *phi_s0;

    phi_a0 = arg0;
    if (arg0 == 0) {
        phi_a0 = D_8004A7C4;
    }
    temp_s0 = phi_a0->unk18;
    phi_s0 = temp_s0;
    if (temp_s0 != 0) {
loop_3:
        temp_s1 = *phi_s0;
        func_80008DA8(phi_s0);
        phi_s0 = temp_s1;
        if (temp_s1 != 0) {
            goto loop_3;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B870.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B8C0(s32 arg0) {
    func_80009628(0x12, 0);
    func_80009628(arg0, 0x15, 0);
    func_80009628(arg0, 0x20, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B8C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B908(s32 arg0) {
    func_80009628(0x12, 0);
    func_80009628(arg0, 0x1A, 0);
    func_80009628(arg0, 0x20, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B908.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B950(s32 arg0) {
    func_80009658(3, 0);
    func_80009658(arg0, 6, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B950.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000B988(void *arg0) {
    s32 temp_v0;
    s32 phi_s0;

    phi_s0 = arg0->unk3C;
    if (arg0->unk3C != 0) {
loop_1:
        func_80009B5C(phi_s0);
        temp_v0 = func_8000BE90(phi_s0);
        phi_s0 = temp_v0;
        if (temp_v0 != 0) {
            goto loop_1;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B988.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000B9CC(void) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_80009C38();
    sp1C = temp_v0;
    func_8000B8C0(temp_v0);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B9CC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000B9FC(void) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_80009CE8();
    sp1C = temp_v0;
    func_8000B8C0(temp_v0);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000B9FC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BA2C(void) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_80009D5C();
    sp1C = temp_v0;
    func_8000B8C0(temp_v0);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BA2C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BA5C(void) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_80009C38();
    sp1C = temp_v0;
    func_8000B908(temp_v0);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BA5C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BA8C(void) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_80009CE8();
    sp1C = temp_v0;
    func_8000B908(temp_v0);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BA8C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BABC(void) {
    s32 sp1C;
    s32 temp_v0;

    temp_v0 = func_80009D5C();
    sp1C = temp_v0;
    func_8000B908(temp_v0);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BABC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BAEC(s32 arg0, void *arg1, void *arg2) {
    ? sp80;
    ? sp40;
    ?32 sp3C;
    void *sp38;
    ? *temp_v0;
    s32 temp_v0_4;
    void *temp_v0_2;
    void *temp_v0_3;
    ? *phi_v0;
    s32 phi_v0_2;
    void *phi_s0;
    void *phi_v0_3;
    void *phi_s1;
    s32 phi_return;

    sp38 = NULL;
    sp3C = 0;
    phi_v0 = &sp40;
loop_1:
    temp_v0 = phi_v0 + 0x10;
    temp_v0->unk-C = 0;
    temp_v0->unk-8 = 0;
    temp_v0->unk-4 = 0;
    temp_v0->unk-10 = 0;
    phi_v0 = temp_v0;
    if (temp_v0 != &sp80) {
        goto loop_1;
    }
    phi_v0_2 = *arg1;
    phi_s0 = arg1;
    phi_s1 = arg2;
    phi_return = *arg1;
    if (0x12 != *arg1) {
loop_3:
        if (phi_v0_2 != 0) {
            temp_v0_2 = func_8000BA2C((&sp38 + (phi_v0_2 * 4))->unk-4, phi_s0->unk4);
            *(&sp38 + (phi_s0->unk0 * 4)) = temp_v0_2;
            phi_v0_3 = temp_v0_2;
        } else {
            temp_v0_3 = func_8000B9CC(arg0, phi_s0->unk4);
            sp38 = temp_v0_3;
            phi_v0_3 = temp_v0_3;
        }
        phi_v0_3->unk1C = (s32) phi_s0->unk8;
        phi_v0_3->unk20 = (s32) phi_s0->unkC;
        phi_v0_3->unk24 = (s32) phi_s0->unk10;
        if (phi_s1 != 0) {
            *phi_s1 = phi_v0_3;
            phi_s1 = phi_s1 + 4;
        }
        temp_v0_4 = phi_s0->unk14;
        phi_v0_2 = temp_v0_4;
        phi_s0 = phi_s0 + 0x14;
        phi_return = temp_v0_4;
        if (0x12 != temp_v0_4) {
            goto loop_3;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BAEC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000BBE0(void *arg0) {
    void *phi_s1;

    phi_s1 = arg0;
    if (arg0 == 0) {
        phi_s1 = D_8004A7C4;
    }
    if (phi_s1->unk3C != 0) {
loop_3:
        func_80009DF4(phi_s1->unk3C);
        if (phi_s1->unk3C != 0) {
            goto loop_3;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BBE0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8000BC34(void) {
    void *temp_s0;
    void *temp_s1;
    void *temp_s2;
    void *phi_s2;
    void *phi_s0;

    phi_s2 = &D_8004A578;
loop_1:
    temp_s0 = *phi_s2;
    phi_s0 = temp_s0;
    if (temp_s0 != 0) {
loop_2:
        temp_s1 = phi_s0->unk4;
        func_8000A29C(phi_s0);
        phi_s0 = temp_s1;
        if (temp_s1 != 0) {
            goto loop_2;
        }
    }
    temp_s2 = phi_s2 + 4;
    phi_s2 = temp_s2;
    if (temp_s2 != &D_8004A5F8) {
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BC34.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BCA4(s32 arg2, s32 arg4, u8 arg5, s32 arg6, s32 arg7, s32 arg8, s32 arg9, u8 argA, s32 argB, s32 argC) {
    s32 temp_v0;

    temp_v0 = func_8000A180(arg2 & 0xFF);
    if (temp_v0 == 0) {
        return 0;
    }
    func_8000A5FC(temp_v0, arg4, arg5, arg6, arg7);
    if (arg9 != 0) {
        func_8000B8C0(func_80009C38(temp_v0, arg8));
    }
    if (argB != 0) {
        func_80008A18(temp_v0, argB, argA, argC);
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BCA4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8000BD3C(s32 arg2, s32 arg4, s32 arg5, s32 arg6, s32 arg7, s32 arg8, u8 arg9, s32 argA, s32 argB, s32 argC) {
    void *sp28;
    s32 temp_v0;
    void *temp_v0_2;

    temp_v0 = func_8000A180(arg2 & 0xFF);
    if (temp_v0 == 0) {
        return 0;
    }
    func_8000A764(temp_v0, arg4, arg5, arg6, arg7);
    temp_v0_2 = func_80009F7C(temp_v0);
    sp28 = temp_v0_2;
    if (arg8 != 0) {
        func_8000B950(temp_v0_2);
    }
    if (argA != 0) {
        func_80008A18(temp_v0, argA, arg9, argB);
    }
    if (argC != 0) {
        sp28->unk80 = 7;
        sp28->unk84 = 0xFF;
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BD3C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8000BDF0(s32 arg0, ? arg1, s32 arg2, s32 arg3, s32 arg4) {
    void *temp_v0;

    temp_v0 = func_8000BD3C(-1, &D_8000B6B4, arg0, arg1, &D_8001806C, arg2, 0, 0, 0, 0, 0, 0, 0);
    if (temp_v0 == 0) {
        return NULL;
    }
    temp_v0->unk3C->unk80 = arg3;
    temp_v0->unk3C->unk84 = arg4;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_2_5/func_8000BDF0.s")
#endif
