#include <ultra64.h>
#include <macros.h>
#include "segments.h"

u32 D_8003F330 = 0x00000000;

u32 D_8003F334 = 0x00000000;

u32 D_8003F338 = 0x00000001;

u32 D_8003F33C = 0x00000000;

u32 D_8003F340 = 0x00000000;

u32 D_8003F344 = 0x00000001;

u16 D_8003F348[] = {
    0x0000, 0x0000, 0x0000, 0x0000
};

u32 D_8003F350 = 0x8004ADC0;
u32 D_8003F354 = 0x0004B000;
u32 D_8003F358 = 0x7D001018;
u32 D_8003F35C = 0x40400818;
u32 D_8003F360 = 0x00003214;

u32 *D_8003F364 = (u32*)_data_3E1400SegmentRomStart;
u32 *D_8003F368 = (u32*)_data_3E6BC0SegmentRomStart;
u32 *D_8003F36C = (u32*)_data_3E6BC0SegmentRomStart;
u32 *D_8003F370 = (u32*)_data_2A8CB0SegmentRomStart;
u32 *D_8003F374 = (u32*)_data_2B1510SegmentRomStart;
u32 *D_8003F378 = (u32*)_data_2B1510SegmentRomStart;
u32 *D_8003F37C = (u32*)_data_250320SegmentRomStart;

u32 D_8003F380 = 0x00100808;
u32 D_8003F384 = 0x00000000;
u32 D_8003F388 = 0x00000000;
u32 D_8003F38C = 0x00000000;

u32 D_8003F390 = 0x00000000;
u32 D_8003F394 = 0x00000000;
u32 D_8003F398 = 0x00000000;
u32 D_8003F39C = 0x00000000;

u32 *D_8003F3A0 = (u32*)_data_49F590SegmentRomStart;
u32 *D_8003F3A4 = (u32*)_data_49F590SegmentRomEnd;

u32 *D_8003F3A8 = (u32*)_data_4A0340SegmentRomStart;
u32 *D_8003F3AC = (u32*)_data_4A0340SegmentRomEnd;

u32 *D_8003F3B0 = (u32*)_data_4A3B60SegmentRomStart;
u32 *D_8003F3B4 = (u32*)_data_4A3B60SegmentRomEnd;

struct AudioHeap {
    u32 unk0;
    u32 unk4;
    u32 unk8;
    u32 unkC;
};

void func_8001E3A0(struct AudioHeap *arg0, s32 arg1, u32 arg2) {
    s32 temp_v0;

    temp_v0 = 0x10 - (arg1 & 0xF);
    if (temp_v0 != 0x10) {
        arg0->unk0 = arg1 + temp_v0;
    } else {
        arg0->unk0 = arg1;
    }
    arg0->unk8 = arg2;
    arg0->unkC = 0;
    arg0->unk4 = arg0->unk0;
}

extern const char D_80040CE0[];
// functionally equivalent
#ifdef NON_MATCHING
void *func_8001E3D4(s32 arg0, s32 arg1, struct AudioHeap *arg2, s32 byteSize, s32 size) {
    s32 temp_v1 = ALIGN16(byteSize * size);
    s32 temp_v0 = arg2->unk4;

    if ((arg2->unk0 + arg2->unk8) >= (temp_v0 + temp_v1)) {
        arg2->unk4 += temp_v1;
    } else {
        fatal_printf(&D_80040CE0); // "Audio Heap Overflow\n"
        while (1);
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E3D4.s")
#endif

#ifdef MIPS_TO_C
// TODO: struct
void func_8001E450(s16 *arg0, s32 arg1) {
    s32 phi_v0;

    for (phi_v0 = 0; phi_v0 < arg0[1]; phi_v0++) {
        arg0[2] += arg1;
        arg0 += 4;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E450.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001E490(void *arg0, ? arg1) {
    s32 temp_s2;
    void *temp_a0;
    void *phi_s0;
    s32 phi_s2;

    if (arg0->unk2 > 0) {
        phi_s0 = arg0;
        phi_s2 = 0;
loop_2:
        temp_a0 = phi_s0->unk4 + arg0;
        phi_s0->unk4 = temp_a0;
        if (temp_a0 != 0) {
            func_8001E510(temp_a0, arg0, arg1);
        }
        temp_s2 = phi_s2 + 1;
        phi_s0 = phi_s0 + 4;
        phi_s2 = temp_s2;
        if (temp_s2 < arg0->unk2) {
            goto loop_2;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E490.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001E510(void *arg0, s32 arg1, ? arg2) {
    s32 temp_a0;
    s32 temp_s1;
    s32 temp_t8;
    s32 temp_v0;
    void *phi_s0;
    s32 phi_s1;

    if (arg0->unk2 == 0) {
        temp_v0 = arg0->unk8;
        arg0->unk2 = 1;
        temp_t8 = temp_v0 + arg1;
        if (temp_v0 != 0) {
            arg0->unk8 = temp_t8;
            func_8001E5C8(temp_t8);
        }
        phi_s0 = arg0;
        phi_s1 = 0;
        if (arg0->unk0 > 0) {
loop_4:
            temp_a0 = phi_s0->unkC + arg1;
            phi_s0->unkC = temp_a0;
            if (temp_a0 != 0) {
                func_8001E5C8(temp_a0, arg1, arg2);
            }
            temp_s1 = phi_s1 + 1;
            phi_s0 = phi_s0 + 4;
            phi_s1 = temp_s1;
            if (temp_s1 < arg0->unk0) {
                goto loop_4;
            }
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E510.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001E5C8(void *arg0, s32 arg1, ? arg2) {
    s32 temp_a0;
    s32 temp_s1;
    void *phi_s0;
    s32 phi_s1;

    if (arg0->unk3 == 0) {
        arg0->unk3 = 1;
        if (arg0->unkE > 0) {
            phi_s0 = arg0;
            phi_s1 = 0;
loop_3:
            temp_a0 = phi_s0->unk10 + arg1;
            phi_s0->unk10 = temp_a0;
            func_8001E660(temp_a0, arg1, arg2);
            temp_s1 = phi_s1 + 1;
            phi_s0 = phi_s0 + 4;
            phi_s1 = temp_s1;
            if (temp_s1 < arg0->unkE) {
                goto loop_3;
            }
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E5C8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001E660(void *arg0, s32 arg1) {
    s32 temp_t3;

    if (arg0->unkE == 0) {
        temp_t3 = arg0->unk8 + arg1;
        arg0->unkE = 1;
        arg0->unk0 = arg0->unk0 + arg1;
        arg0->unk4 = arg0->unk4 + arg1;
        arg0->unk8 = temp_t3;
        func_8001E6B8(temp_t3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E660.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001E6B8(void *arg0, s32 arg1, s32 arg2) {
    s32 temp_v0_2;
    s32 temp_v0_3;
    u8 temp_v0;

    if (arg0->unk9 == 0) {
        temp_v0 = arg0->unk8;
        arg0->unk9 = 1;
        arg0->unk0 = arg0->unk0 + arg2;
        if (temp_v0 == 0) {
            temp_v0_2 = arg0->unkC;
            arg0->unk10 = arg0->unk10 + arg1;
            if (temp_v0_2 != 0) {
                arg0->unkC = temp_v0_2 + arg1;
                return;
            }
        } else {
            if (temp_v0 == 1) {
                temp_v0_3 = arg0->unkC;
                if (temp_v0_3 != 0) {
                    arg0->unkC = temp_v0_3 + arg1;
                }
            }
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E6B8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001E724(s32 arg0, s32 arg1, s32 arg2) {
    s32 sp28;
    s32 sp24;
    s32 sp20;
    void *sp1C;
    s8 sp1A;
    ? sp18;

    osInvalDCache(arg1, arg2);
    sp1A = 0;
    sp1C = &D_80095E30;
    sp20 = arg1;
    sp24 = arg0;
    sp28 = arg2;
    osEPiStartDma(gRomHandle, &sp18, 0);
    osRecvMesg(&D_80095E30, 0, 1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E724.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8001E7A4(u32 arg0, s32 arg1, void *arg2) {
    s32 sp2C;
    s32 sp24;
    s32 temp_t0;
    s32 temp_t1_2;
    s32 temp_t3;
    s32 temp_t7;
    s32 temp_v1;
    u32 temp_s0;
    u32 temp_t1;
    u32 temp_t6;
    void *temp_a1;
    void *temp_v0;
    void *temp_v0_2;
    u32 phi_v1;

    sp24 = 0;
    temp_v1 = arg2->unk4;
    temp_v0 = arg2 + (temp_v1 * 0x10);
    temp_t1 = temp_v0->unk8;
    temp_t7 = temp_v0->unkC;
    if ((arg0 >= temp_t1) && ((temp_t1 + temp_t7) >= (arg0 + arg1))) {
        sp2C = ((temp_v0 + 8)->unkC + arg0) - temp_t1;
    } else {
        temp_t6 = temp_v1 + 1;
        arg2->unk4 = temp_t6;
        phi_v1 = temp_t6;
        if (temp_t6 >= arg2->unk0) {
            arg2->unk4 = 0;
            phi_v1 = 0;
        }
        temp_v0_2 = arg2 + (phi_v1 * 0x10);
        temp_t3 = temp_v0_2->unk14;
        temp_t0 = arg0 & 1;
        sp24 = temp_t0;
        temp_s0 = arg0 - temp_t0;
        temp_v0_2->unk8 = temp_s0;
        temp_v0_2->unkC = temp_v0_2->unk10;
        temp_t1_2 = D_8003F334;
        temp_a1 = (temp_t1_2 * 0x18) + &D_80095F20;
        temp_a1->unk2 = 1;
        temp_a1->unk4 = &D_80095E18;
        temp_a1->unkC = temp_s0;
        temp_a1->unk8 = temp_t3;
        temp_a1->unk10 = temp_v0_2->unk10;
        D_8003F334 = temp_t1_2 + 1;
        sp2C = temp_t3;
        osEPiStartDma(gRomHandle, temp_a1, 0, arg2);
    }
    return osVirtualToPhysical(sp2C) + sp24;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E7A4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8001E8D0(void *arg0) {
    void *sp38;
    s32 temp_s1;
    void *temp_s0;
    void *temp_v0;
    void *phi_s0;
    s32 phi_s1;

    temp_v0 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x48);
    temp_v0->unk4 = 0;
    temp_v0->unk0 = 4;
    sp38 = temp_v0;
    phi_s0 = temp_v0;
    phi_s1 = 0;
loop_1:
    temp_s1 = phi_s1 + 1;
    temp_s0 = phi_s0 + 0x10;
    temp_s0->unk4 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x400);
    temp_s0->unk-8 = 0;
    temp_s0->unk-4 = 0;
    temp_s0->unk0 = 0x400;
    phi_s0 = temp_s0;
    phi_s1 = temp_s1;
    if (temp_s1 != 4) {
        goto loop_1;
    }
    *arg0 = sp38;
    return &D_8001E7A4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E8D0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
f32 func_8001E9A0(s32 arg0) {
    u32 temp_a0;
    u32 temp_a0_2;
    u32 phi_a0;
    f32 phi_f2;
    f32 phi_f2_2;
    f32 phi_f2_3;
    f32 phi_f0;

    temp_a0 = arg0 & 0xFF;
    phi_a0 = temp_a0;
    phi_f2 = 1.0f;
    phi_f2_3 = 1.0f;
    phi_f0 = D_80040CF8;
    if (temp_a0 != 0) {
loop_1:
        phi_f2_2 = phi_f2_3;
        if ((phi_a0 & 1) != 0) {
            phi_f2_2 = phi_f2_3 * phi_f0;
        }
        temp_a0_2 = (phi_a0 >> 1) & 0xFF;
        phi_a0 = temp_a0_2;
        phi_f2 = phi_f2_2;
        phi_f2_3 = phi_f2_2;
        phi_f0 = phi_f0 * phi_f0;
        if (temp_a0_2 != 0) {
            goto loop_1;
        }
    }
    return phi_f2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E9A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8001E9EC(void *arg0, void *arg1, s32 arg2, u8 arg3, u8 arg4, u8 arg5) {
    s32 sp28;
    s32 sp24;
    f32 temp_f0;
    s16 temp_t1;
    s16 temp_t6;
    s16 temp_t6_2;
    s16 temp_t9_2;
    s32 temp_a0;
    s32 temp_a0_2;
    s32 temp_a1;
    s32 temp_a1_2;
    s32 temp_f8;
    s32 temp_t3;
    s32 temp_t8;
    s8 temp_a2;
    s8 temp_t9;
    u8 temp_a3;
    u8 temp_t5;
    void *temp_v1;
    f32 phi_f0;

    temp_v1 = D_80096510;
    temp_a3 = arg3 & 0xFF;
    temp_a2 = arg2 & 0xFF;
    sp28 = 0;
    if (temp_v1 != 0) {
        D_80096510 = temp_v1->unk0;
        temp_v1->unk4 = temp_a2;
        *arg0 = temp_v1;
        sp28 = arg5 << 0xE;
        if (temp_a2 != 1) {
            if (temp_a2 != 2) {
                if (temp_a2 != 3) {
                    if (temp_a2 != 4) {
                        if (temp_a2 != 0x80) {
                            if (temp_a2 != 0x81) {
                                if (temp_a2 != 0x82) {
                                    if (temp_a2 != 0x83) {

                                    } else {
                                        temp_t6 = 0x100 - temp_a3;
                                        temp_v1->unk6 = temp_t6;
                                        temp_v1->unk8 = temp_t6;
                                        temp_f8 = func_8001E9A0(arg4, temp_a2, temp_a3);
                                        temp_a1 = temp_f8;
                                        temp_a0 = -temp_a1;
                                        temp_t8 = temp_a1 * 2;
                                        temp_v1->unkC = temp_a0;
                                        temp_v1->unk10 = temp_t8;
                                        phi_f0 = alCents2Ratio(temp_a0, temp_a1);
block_18:
                                        *arg1 = phi_f0;
                                    }
                                } else {
                                    temp_t1 = 0x100 - temp_a3;
                                    temp_v1->unk6 = temp_t1;
                                    temp_v1->unk8 = temp_t1;
                                    temp_a0_2 = func_8001E9A0(arg4, temp_a2, temp_a3);
                                    temp_v1->unk10 = temp_a0_2 * 2;
                                    temp_v1->unkC = temp_a0_2;
                                    phi_f0 = alCents2Ratio(temp_a0_2);
                                    goto block_18;
                                }
                            } else {
                                temp_t6_2 = 0x100 - temp_a3;
                                temp_v1->unk6 = temp_t6_2;
                                temp_v1->unk8 = temp_t6_2;
                                temp_v1->unk5 = 0;
                                temp_a1_2 = func_8001E9A0(arg4, temp_a2, temp_a3);
                                sp24 = temp_a1_2;
                                temp_v1->unkC = alCents2Ratio(-temp_a1_2, temp_a1_2);
                                temp_f0 = alCents2Ratio(sp24);
                                temp_v1->unk10 = temp_f0;
                                phi_f0 = temp_f0;
                                goto block_18;
                            }
                        } else {
                            arg3 = temp_a3;
                            temp_v1->unkC = func_8001E9A0(arg4, temp_a2, temp_a3);
                            temp_v1->unk8 = 0;
                            temp_v1->unk6 = 0x103 - arg3;
                            *arg1 = 1.0f;
                        }
                    } else {
                        temp_t9 = 0x7F - arg4;
                        temp_v1->unk6 = 0x100 - temp_a3;
                        temp_v1->unk8 = 0;
                        temp_v1->unkD = arg4;
                        temp_v1->unkC = temp_t9;
                        *arg1 = temp_t9 & 0xFF;
                    }
                } else {
                    temp_v1->unk6 = 0x100 - temp_a3;
                    temp_v1->unk8 = 0;
                    temp_v1->unkC = 0x7F;
                    temp_v1->unkD = arg4;
                    *arg1 = 0x7F & 0xFF;
                }
            } else {
                temp_t9_2 = 0x100 - temp_a3;
                temp_v1->unk6 = temp_t9_2;
                temp_v1->unk8 = temp_t9_2;
                temp_v1->unk5 = 0;
                temp_v1->unkE = 0x7F - arg4;
                temp_v1->unkD = 0x7F;
                temp_v1->unkC = 0x7F;
                *arg1 = 127.0f;
            }
        } else {
            temp_t3 = arg4 >> 1;
            temp_t5 = 0x7F - temp_t3;
            temp_v1->unk8 = 0;
            temp_v1->unk6 = 0x103 - temp_a3;
            temp_v1->unkC = temp_t3;
            temp_v1->unkD = temp_t5;
            *arg1 = temp_t5 & 0xFF;
        }
    }
    return sp28;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001E9EC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_8001ECC0(void *arg0, void *arg1) {
    s32 sp1C;
    f32 temp_f10;
    f32 temp_f10_2;
    f32 temp_f10_3;
    f32 temp_f10_4;
    f32 temp_f16;
    f32 temp_f16_2;
    f32 temp_f16_3;
    f32 temp_f6;
    s32 temp_v0_2;
    s32 temp_v0_3;
    s32 temp_v0_4;
    s32 temp_v0_5;
    s32 temp_v0_6;
    s32 temp_v0_7;
    u16 temp_t2;
    u16 temp_t3;
    u16 temp_t6;
    u16 temp_t8;
    u16 temp_t8_2;
    u16 temp_t8_3;
    u8 temp_t0;
    u8 temp_t0_2;
    u8 temp_t2_2;
    u8 temp_t3_2;
    u8 temp_t4;
    u8 temp_t4_2;
    u8 temp_t9;
    u8 temp_t9_2;
    u8 temp_v0;
    void *temp_a2;
    u32 phi_v0;
    u32 phi_v0_2;
    u32 phi_v0_3;
    f32 phi_f0;
    f32 phi_f10;
    u32 phi_v0_4;
    f32 phi_f16;
    f32 phi_f6;
    u32 phi_v0_5;
    f32 phi_f10_2;
    f32 phi_f10_3;
    f32 phi_f16_2;
    u32 phi_v0_6;
    f32 phi_f16_3;
    f32 phi_f10_4;

    sp1C = 0x3E80;
    temp_v0 = arg0->unk4;
    temp_a2 = arg0;
    if (temp_v0 != 1) {
        if (temp_v0 != 2) {
            if (temp_v0 != 3) {
                if (temp_v0 != 4) {
                    if (temp_v0 != 0x80) {
                        if (temp_v0 != 0x81) {
                            if (temp_v0 != 0x82) {
                                if (temp_v0 != 0x83) {

                                } else {
                                    temp_t8 = temp_a2->unk8 + 1;
                                    temp_v0_2 = temp_t8 & 0xFFFF;
                                    temp_a2->unk8 = temp_t8;
                                    phi_v0 = temp_v0_2;
                                    if (temp_a2->unk6 < temp_v0_2) {
                                        temp_a2->unk8 = 0;
                                        phi_v0 = 0 & 0xFFFF;
                                    }
                                    phi_f0 = alCents2Ratio(((phi_v0 / temp_a2->unk6) * temp_a2->unk10) + temp_a2->unkC, temp_a2);
block_51:
                                    *arg1 = phi_f0;
                                }
                            } else {
                                temp_t3 = temp_a2->unk8 + 1;
                                temp_v0_3 = temp_t3 & 0xFFFF;
                                temp_a2->unk8 = temp_t3;
                                phi_v0_2 = temp_v0_3;
                                if (temp_a2->unk6 < temp_v0_3) {
                                    temp_a2->unk8 = 0;
                                    phi_v0_2 = 0 & 0xFFFF;
                                }
                                phi_f0 = alCents2Ratio(temp_a2->unkC - ((phi_v0_2 / temp_a2->unk6) * temp_a2->unk10), temp_a2);
                                goto block_51;
                            }
                        } else {
                            if (temp_a2->unk5 == 0) {
                                temp_a2->unk5 = 1;
                                *arg1 = (bitwise f32) temp_a2->unkC;
                            } else {
                                temp_a2->unk5 = 0;
                                *arg1 = (bitwise f32) temp_a2->unk10;
                            }
                            sp1C = temp_a2->unk6 * 0x3E80;
                        }
                    } else {
                        temp_t6 = temp_a2->unk8 + 1;
                        temp_v0_4 = temp_t6 & 0xFFFF;
                        temp_a2->unk8 = temp_t6;
                        phi_v0_3 = temp_v0_4;
                        if (temp_v0_4 >= temp_a2->unk6) {
                            temp_a2->unk8 = 0;
                            phi_v0_3 = 0 & 0xFFFF;
                        }
                        arg0 = temp_a2;
                        phi_f0 = alCents2Ratio(sinf((phi_v0_3 / temp_a2->unk6) * D_80040D00, temp_a2) * arg0->unkC, arg0);
                        goto block_51;
                    }
                } else {
                    temp_t2 = temp_a2->unk8 + 1;
                    temp_v0_5 = temp_t2 & 0xFFFF;
                    temp_a2->unk8 = temp_t2;
                    phi_v0_4 = temp_v0_5;
                    if (temp_a2->unk6 < temp_v0_5) {
                        temp_a2->unk8 = 0;
                        phi_v0_4 = 0 & 0xFFFF;
                    }
                    temp_t3_2 = temp_a2->unkD;
                    temp_f16 = temp_t3_2;
                    phi_f16 = temp_f16;
                    if (temp_t3_2 < 0) {
                        phi_f16 = temp_f16 + 4294967296.0f;
                    }
                    temp_t4 = temp_a2->unkC;
                    temp_f10 = temp_t4;
                    phi_f10 = temp_f10;
                    if (temp_t4 < 0) {
                        phi_f10 = temp_f10 + 4294967296.0f;
                    }
                    *arg1 = phi_f10 + ((phi_v0_4 / temp_a2->unk6) * phi_f16);
                }
            } else {
                temp_t8_2 = temp_a2->unk8 + 1;
                temp_v0_6 = temp_t8_2 & 0xFFFF;
                temp_a2->unk8 = temp_t8_2;
                phi_v0_5 = temp_v0_6;
                if (temp_a2->unk6 < temp_v0_6) {
                    temp_a2->unk8 = 0;
                    phi_v0_5 = 0 & 0xFFFF;
                }
                temp_t9 = temp_a2->unkD;
                temp_f10_2 = temp_t9;
                phi_f10_2 = temp_f10_2;
                if (temp_t9 < 0) {
                    phi_f10_2 = temp_f10_2 + 4294967296.0f;
                }
                temp_t0 = temp_a2->unkC;
                temp_f6 = temp_t0;
                phi_f6 = temp_f6;
                if (temp_t0 < 0) {
                    phi_f6 = temp_f6 + 4294967296.0f;
                }
                *arg1 = phi_f6 - ((phi_v0_5 / temp_a2->unk6) * phi_f10_2);
            }
        } else {
            if (temp_a2->unk5 == 0) {
                temp_t2_2 = temp_a2->unkE;
                temp_f10_3 = temp_t2_2;
                phi_f10_3 = temp_f10_3;
                if (temp_t2_2 < 0) {
                    phi_f10_3 = temp_f10_3 + 4294967296.0f;
                }
                *arg1 = phi_f10_3;
                temp_a2->unk5 = 1;
            } else {
                temp_t4_2 = temp_a2->unkD;
                temp_f16_2 = temp_t4_2;
                phi_f16_2 = temp_f16_2;
                if (temp_t4_2 < 0) {
                    phi_f16_2 = temp_f16_2 + 4294967296.0f;
                }
                *arg1 = phi_f16_2;
                temp_a2->unk5 = 0;
            }
            sp1C = temp_a2->unk6 * 0x3E80;
        }
    } else {
        temp_t8_3 = temp_a2->unk8 + 1;
        temp_v0_7 = temp_t8_3 & 0xFFFF;
        temp_a2->unk8 = temp_t8_3;
        phi_v0_6 = temp_v0_7;
        if (temp_v0_7 >= temp_a2->unk6) {
            temp_a2->unk8 = 0;
            phi_v0_6 = 0 & 0xFFFF;
        }
        arg0 = temp_a2;
        temp_t9_2 = arg0->unkC;
        temp_f10_4 = temp_t9_2;
        phi_f10_4 = temp_f10_4;
        if (temp_t9_2 < 0) {
            phi_f10_4 = temp_f10_4 + 4294967296.0f;
        }
        temp_t0_2 = arg0->unkD;
        temp_f16_3 = temp_t0_2;
        phi_f16_3 = temp_f16_3;
        if (temp_t0_2 < 0) {
            phi_f16_3 = temp_f16_3 + 4294967296.0f;
        }
        *arg1 = phi_f16_3 + (phi_f10_4 * sinf((phi_v0_6 / temp_a2->unk6) * D_80040CFC, temp_a2));
    }
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001ECC0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8001F234(void *arg0) {
    *arg0 = D_80096510;
    D_80096510 = arg0;
    return &D_80096510;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001F234.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001F24C(void) {
    func_800009E8(&D_80095DE0, &D_80095DE8, &D_80095E48, 1);
    osCreateMesgQueue(&D_80095E18, &D_80095E58, 0x32);
    osCreateMesgQueue(&D_80095E30, &D_80095E50, 1);
    osCreateMesgQueue(&D_80095E00, &D_80095E4C, 1);
    osSendMesg(&D_80095E00, 0, 1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001F24C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s16 func_8001F2E0(void) {
    void *sp48;
    s32 sp44;
    void *sp3C;
    void *sp38;
    void *sp34;
    u32 sp30;
    s16 temp_s0_3;
    s16 temp_v0_13;
    s16 temp_v0_16;
    s16 temp_v0_17;
    s16 temp_v0_7;
    s32 temp_s0;
    s32 temp_s0_2;
    s32 temp_s0_4;
    s32 temp_s0_5;
    s32 temp_s0_6;
    s32 temp_t0;
    s32 temp_t0_2;
    s32 temp_t0_3;
    s32 temp_t2;
    s32 temp_t6;
    s32 temp_t6_2;
    s32 temp_v0_6;
    s32 temp_v0_8;
    s32 temp_v1;
    s32 temp_v1_2;
    u32 temp_v0;
    u32 temp_v0_11;
    u32 temp_v0_14;
    u32 temp_v0_3;
    u32 temp_v0_5;
    u32 temp_v1_3;
    u32 temp_v1_4;
    void *temp_a0;
    void *temp_a0_2;
    void *temp_a1;
    void *temp_a1_2;
    void *temp_a1_3;
    void *temp_t3;
    void *temp_t7;
    void *temp_t7_2;
    void *temp_v0_10;
    void *temp_v0_12;
    void *temp_v0_15;
    void *temp_v0_2;
    void *temp_v0_4;
    void *temp_v0_9;
    void *temp_v1_5;
    void *temp_v1_6;
    void *phi_v0;
    s32 phi_s0;
    s32 phi_a1;
    s32 phi_t0;
    u32 phi_v1;
    s32 phi_s0_2;
    s32 phi_v0_2;
    s32 phi_t0_2;
    s16 phi_v0_3;
    s32 phi_t0_3;
    s16 phi_return;
    s32 phi_s0_3;

    bzero(D_800964A0.unk0, D_800964A0.unk4);
    func_8001E3A0(&D_80095DC8, D_800964A0.unk0, D_800964A0.unk4);
    temp_v0 = D_800964A0.unk20;
    if (temp_v0 >= 0x80000000) {
        D_80096470 = temp_v0;
    } else {
        temp_s0 = D_800964A0.unk24 - temp_v0;
        temp_v0_2 = func_8001E3D4(0, 0, &D_80095DC8, 1, temp_s0);
        sp48 = temp_v0_2;
        func_8001E724(D_800964A0.unk20, temp_v0_2, temp_s0);
        func_8001E490(sp48, D_800964A0.unk28);
        D_80096470 = sp48->unk4;
    }
    temp_v0_3 = D_800964A0.unk14;
    if (temp_v0_3 >= 0x80000000) {
        D_80096468 = temp_v0_3;
    } else {
        temp_s0_2 = D_800964A0.unk18 - temp_v0_3;
        temp_v0_4 = func_8001E3D4(0, 0, &D_80095DC8, 1, temp_s0_2);
        sp48 = temp_v0_4;
        func_8001E724(D_800964A0.unk14, temp_v0_4, temp_s0_2);
        func_8001E490(sp48, D_800964A0.unk1C);
        D_80096468 = sp48->unk4;
    }
    temp_v0_5 = D_800964A0.unk2C;
    if (temp_v0_5 >= 0x80000000) {
        D_80096474 = temp_v0_5;
    } else {
        temp_v0_6 = func_8001E3D4(0, 0, &D_80095DC8, 1, 4);
        D_80096474 = temp_v0_6;
        func_8001E724(D_800964A0.unk2C, temp_v0_6, 4);
        temp_v0_7 = (D_80096474->unk2 * 8) + 4;
        temp_s0_3 = temp_v0_7;
        temp_v0_8 = func_8001E3D4(0, 0, &D_80095DC8, 1, temp_v0_7);
        D_80096474 = temp_v0_8;
        func_8001E724(D_800964A0.unk2C, temp_v0_8, temp_s0_3);
        func_8001E450(D_80096474, D_800964A0.unk2C);
    }
    temp_a0 = D_80096474;
    phi_s0_2 = 0;
    if (temp_a0->unk2 > 0) {
        phi_v0 = temp_a0;
        phi_s0 = 0;
        phi_a1 = 0;
        phi_t0 = 0;
loop_11:
        temp_v1 = phi_v0->unk8;
        phi_v0->unk8 = temp_v1 + (temp_v1 & 1);
        temp_a0_2 = D_80096474;
        temp_v0_9 = temp_a0_2 + phi_a1;
        temp_v1_2 = temp_v0_9->unk8;
        phi_s0_3 = phi_s0;
        if (phi_s0 < temp_v1_2) {
            phi_s0_3 = temp_v1_2;
        }
        temp_t0 = phi_t0 + 1;
        phi_v0 = temp_v0_9 + 8;
        phi_s0 = phi_s0_3;
        phi_a1 = phi_a1 + 8;
        phi_t0 = temp_t0;
        phi_s0_2 = phi_s0_3;
        if (temp_t0 < temp_a0_2->unk2) {
            goto loop_11;
        }
    }
    phi_v1 = &D_80096484;
loop_15:
    sp30 = phi_v1;
    temp_v1_3 = phi_v1 + 4;
    temp_v1_3->unk-4 = func_8001E3D4(0, 0, &D_80095DC8, 1, phi_s0_2);
    phi_v1 = temp_v1_3;
    if (temp_v1_3 < &D_80096488) {
        goto loop_15;
    }
    D_80096450.unk0 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x8000);
    D_80096450.unk4 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x8000);
    D_80096460.unk0 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x68);
    D_80096460.unk4 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x68);
    D_80096440.unk0 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0xE60);
    D_80096440.unk4 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0xE60);
    temp_v1_4 = D_800964A0.unk50;
    D_80096440.unk8 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0xE60);
    if (temp_v1_4 < 0x80000000) {
        temp_s0_4 = D_800964A0.unk54 - temp_v1_4;
        temp_v0_10 = func_8001E3D4(0, 0, &D_80095DC8, 1, temp_s0_4);
        temp_a1 = temp_v0_10;
        sp3C = temp_v0_10;
        func_8001E724(D_800964A0.unk50, temp_a1, temp_s0_4);
        temp_t2 = *sp3C;
        temp_t3 = sp3C + 4;
        D_800964A0.unk4C = temp_t2;
        D_8003F394 = temp_t2;
        D_800964A0.unk44 = temp_t3;
        D_8003F394 = temp_t3;
    }
    temp_v0_11 = D_800964A0.unk58;
    if (temp_v0_11 < 0x80000000) {
        temp_s0_5 = D_800964A0.unk5C - temp_v0_11;
        temp_v0_12 = func_8001E3D4(0, 0, &D_80095DC8, 1, temp_s0_5);
        temp_a1_2 = temp_v0_12;
        sp38 = temp_v0_12;
        func_8001E724(D_800964A0.unk58, temp_a1_2, temp_s0_5);
        temp_t6 = *sp38;
        temp_t7 = sp38 + 4;
        D_800964A0.unk4A = temp_t6;
        temp_v0_13 = temp_t6 & 0xFFFF;
        D_8003F390 = temp_v0_13;
        D_800964A0.unk40 = temp_t7;
        D_8003F390 = temp_t7;
        if (temp_v0_13 > 0) {
            phi_v0_2 = 0;
            phi_t0_2 = 0;
loop_21:
            temp_t0_2 = phi_t0_2 + 1;
            temp_v1_5 = D_800964A0.unk40 + phi_v0_2;
            *temp_v1_5 = *temp_v1_5 + sp38;
            phi_v0_2 = phi_v0_2 + 4;
            phi_t0_2 = temp_t0_2;
            if (temp_t0_2 < D_800964A0.unk4A) {
                goto loop_21;
            }
        }
    }
    temp_v0_14 = D_800964A0.unk60;
    phi_return = temp_v0_14;
    if (temp_v0_14 < 0x80000000) {
        temp_s0_6 = D_800964A0.unk64 - temp_v0_14;
        sp44 = 0;
        temp_v0_15 = func_8001E3D4(0, 0, &D_80095DC8, 1, temp_s0_6);
        temp_a1_3 = temp_v0_15;
        sp34 = temp_v0_15;
        func_8001E724(D_800964A0.unk60, temp_a1_3, temp_s0_6);
        temp_t6_2 = *sp34;
        temp_t7_2 = sp34 + 4;
        temp_v0_16 = temp_t6_2 & 0xFFFF;
        D_8003F350.unk48 = temp_v0_16;
        D_800964A0.unk3C = temp_t7_2;
        D_8003F350.unk3C = temp_t7_2;
        D_800964A0.unk48 = temp_t6_2;
        phi_return = temp_v0_16;
        if (temp_v0_16 > 0) {
            phi_v0_3 = 0;
            phi_t0_3 = sp44;
loop_25:
            temp_t0_3 = phi_t0_3 + 1;
            temp_v1_6 = D_800964A0.unk3C + phi_v0_3;
            temp_v0_17 = phi_v0_3 + 4;
            *temp_v1_6 = *temp_v1_6 + sp34;
            phi_v0_3 = temp_v0_17;
            phi_t0_3 = temp_t0_3;
            phi_return = temp_v0_17;
            if (temp_t0_3 < D_800964A0.unk48) {
                goto loop_25;
            }
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001F2E0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8001F81C(void) {
    u8 sp100;
    s32 spFC;
    void *spF8;
    void *spF4;
    ?32 spEC;
    ?32 spE8;
    ?32 spE4;
    void *spE0;
    void *spDC;
    void *spD8;
    void *spD4;
    s8 spD0;
    ?32 spCC;
    ?32 spC8;
    s16 spC4;
    s16 spC2;
    s16 spC0;
    s16 spBE;
    s16 spBC;
    s16 spBA;
    u8 spB8;
    void *spB4;
    s32 spB0;
    s32 spAC;
    s32 spA8;
    void *spA4;
    u16 spA0;
    u16 sp9E;
    u16 sp9C;
    u16 sp9A;
    s16 sp98;
    s16 sp96;
    s16 sp94;
    void *sp74;
    void *sp70;
    void *sp6C;
    ?32 *temp_fp;
    f32 temp_f0;
    s32 temp_f8;
    s32 temp_s1;
    s32 temp_s1_2;
    s32 temp_v0_8;
    s32 temp_v1;
    s32 temp_v1_3;
    u16 temp_a0;
    u8 temp_t4;
    void *temp_s5;
    void *temp_s6;
    void *temp_s7;
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v0_3;
    void *temp_v0_4;
    void *temp_v0_5;
    void *temp_v0_6;
    void *temp_v0_7;
    void *temp_v1_2;
    f32 phi_f2;
    s32 phi_v1;
    s32 phi_s0;
    s32 phi_s1;
    s32 phi_v1_2;
    void *phi_s3;
    void *phi_s2;
    void *phi_s4;
    s32 phi_s1_2;
    s32 phi_s0_2;
    void *phi_s5;
    void *phi_s6;
    void *phi_s7;

    D_80095DD8 = D_80095DC8.unk4;
    D_80095DDC = D_80095DC8.unkC;
    spF4 = &D_8001E8D0;
    spE4 = D_800964A0.unkB;
    spE8 = D_800964A0.unkA;
    spEC = D_800964A0.unkC;
    temp_t4 = D_800964D0;
    spFC = osAiSetFrequency(D_800964A0.unk8);
    spF8 = &D_80095DC8;
    D_8003F33C = temp_t4;
    sp100 = temp_t4;
    func_8002A178(&D_800963D0, &spE4);
    if (osTvType == 0) {
        phi_f2 = 50.0f;
    } else {
        phi_f2 = 60.0f;
    }
    temp_f0 = spFC / phi_f2;
    temp_f8 = temp_f0;
    D_8009642C = temp_f8;
    phi_v1 = temp_f8;
    if (temp_f8 < temp_f0) {
        temp_v1 = temp_f8 + 1;
        D_8009642C = temp_v1;
        phi_v1 = temp_v1;
    }
    D_80096438 = phi_v1;
    D_80096434 = phi_v1;
    D_80096430 = phi_v1;
    temp_a0 = D_800964A0.unk34;
    sp94 = D_800964A0.unk31;
    sp96 = D_800964A0.unk32;
    sp98 = D_800964A0.unk33;
    if (temp_a0 != 0) {
        sp9A = temp_a0;
        spA4 = D_800964A0.unk38;
    } else {
        temp_v1_2 = D_80096468;
        sp9A = temp_v1_2->unkC->unkE;
        spA4 = temp_v1_2->unkC + 0x10;
    }
    spA8 = D_800964A0.unk3C;
    spAC = D_800964A0.unk40;
    spB0 = D_800964A0.unk44;
    sp9C = D_800964A0.unk48;
    sp9E = D_800964A0.unk4A;
    spB4 = &D_80095DC8;
    spBA = 0xA;
    spBC = 0x14;
    spBE = 0x1E;
    spC0 = 0x28;
    spC2 = 0x32;
    spC4 = 0x3C;
    spA0 = D_800964A0.unk4C;
    spB8 = D_800964A0.unk12;
    func_800234F4(&sp94, &D_80096438, &D_80096434);
    D_8009646C = func_8001E3D4(0, 0, &D_80095DC8, 1, D_800964D3 * 4);
    if (D_800964A0.unk33 > 0) {
        phi_s0 = 0;
        phi_s1 = 0;
loop_10:
        temp_s1 = phi_s1 + 1;
        *(D_8009646C + phi_s0) = 0;
        phi_s0 = phi_s0 + 4;
        phi_s1 = temp_s1;
        if (temp_s1 < D_800964A0.unk33) {
            goto loop_10;
        }
    }
    D_80096488 = func_8001E3D4(0, 0, &D_80095DC8, 1, 1);
    D_8009648C = func_8001E3D4(0, 0, &D_80095DC8, 1, 4);
    D_80096480 = D_800964B3;
    temp_v0 = func_8001E3D4(0, 0, &D_80095DC8, 0x14, 0x20);
    D_80096510 = temp_v0;
    *temp_v0 = temp_v0 + 0x14;
    temp_v0_2 = D_80096510;
    temp_v0_2->unk14 = temp_v0_2 + 0x28;
    temp_v0_3 = D_80096510;
    temp_v0_3->unk28 = temp_v0_3 + 0x3C;
    phi_v1_2 = 0x3C;
loop_13:
    temp_v0_4 = D_80096510;
    *(temp_v0_4 + phi_v1_2) = (phi_v1_2 + temp_v0_4) + 0x14;
    temp_v0_5 = D_80096510;
    (temp_v0_5 + phi_v1_2)->unk14 = (phi_v1_2 + temp_v0_5) + 0x28;
    temp_v0_6 = D_80096510;
    (temp_v0_6 + phi_v1_2)->unk28 = (phi_v1_2 + temp_v0_6) + 0x3C;
    temp_v0_7 = D_80096510;
    temp_v1_3 = phi_v1_2 + 0x50;
    (temp_v0_7 + phi_v1_2)->unk3C = (phi_v1_2 + temp_v0_7) + 0x50;
    phi_v1_2 = temp_v1_3;
    if (temp_v1_3 != 0x26C) {
        goto loop_13;
    }
    *(D_80096510 + temp_v1_3) = 0;
    sp74 = &D_8001E9EC;
    sp70 = &D_8001ECC0;
    sp6C = &D_8001F234;
    temp_fp = &spC8;
    phi_s3 = &D_800964A0;
    phi_s2 = &D_80096478;
    phi_s4 = &D_8009647C;
    phi_s0_2 = 0;
    phi_s5 = &D_80096490;
    phi_s6 = &D_80096494;
    phi_s7 = &D_80096498;
loop_15:
    spD0 = 0x10;
    spD4 = &D_80095DC8;
    spDC = sp70;
    spC8 = phi_s3->unkF;
    spCC = D_800964AD;
    spD8 = sp74;
    spE0 = sp6C;
    temp_v0_8 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0x88);
    *phi_s2 = temp_v0_8;
    func_800296C0(temp_v0_8, temp_fp);
    func_8002CEC0(*phi_s2, D_80096470);
    *phi_s4 = func_8001E3D4(0, 0, &D_80095DC8, 1, 0xF8);
    *(D_80096488 + phi_s1_2) = 0;
    temp_s1_2 = phi_s1_2 + 1;
    *(D_8009648C + phi_s0_2) = -1;
    temp_s5 = phi_s5 + 4;
    temp_s6 = phi_s6 + 4;
    temp_s7 = phi_s7 + 4;
    temp_s5->unk-4 = 0;
    temp_s6->unk-4 = 30720.0f;
    temp_s7->unk-4 = 0.0f;
    phi_s3 = phi_s3 + 1;
    phi_s2 = phi_s2 + 4;
    phi_s4 = phi_s4 + 4;
    phi_s1_2 = temp_s1_2;
    phi_s0_2 = phi_s0_2 + 4;
    phi_s5 = temp_s5;
    phi_s6 = temp_s6;
    phi_s7 = temp_s7;
    if (temp_s1_2 != 1) {
        goto loop_15;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001F81C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void thread4_audio(s32 arg0) {
    s32 sp78;
    u32 sp70;
    s32 sp6C;
    f32 temp_f0;
    s32 temp_a0;
    s32 temp_hi;
    s32 temp_hi_2;
    s32 temp_s1;
    s32 temp_s1_4;
    s32 temp_s1_5;
    s32 temp_s1_6;
    s32 temp_s2;
    s32 temp_s2_2;
    s32 temp_s2_3;
    s32 temp_s2_4;
    s32 temp_s2_5;
    s32 temp_s2_6;
    s32 temp_s2_7;
    s32 temp_s2_8;
    s32 temp_t4_2;
    s32 temp_t5_2;
    s32 temp_t5_3;
    s32 temp_t7_2;
    s32 temp_t7_3;
    s32 temp_v0;
    s32 temp_v1_3;
    s32 temp_v1_4;
    s32 temp_v1_5;
    s32 temp_v1_6;
    s32 temp_v1_7;
    u32 temp_ret;
    u32 temp_v1;
    u8 temp_a0_2;
    u8 temp_a0_3;
    u8 temp_a0_4;
    u8 temp_a0_5;
    void *temp_a1;
    void *temp_s0;
    void *temp_s0_2;
    void *temp_s0_3;
    void *temp_s0_4;
    void *temp_s1_2;
    void *temp_s1_3;
    void *temp_s3;
    void *temp_t4;
    void *temp_t4_3;
    void *temp_t4_4;
    void *temp_t5;
    void *temp_t5_4;
    void *temp_t6;
    void *temp_t6_2;
    void *temp_t7;
    void *temp_t7_4;
    void *temp_t9;
    void *temp_v0_2;
    void *temp_v0_3;
    void *temp_v0_4;
    void *temp_v0_5;
    void *temp_v0_6;
    void *temp_v0_7;
    void *temp_v0_8;
    void *temp_v1_2;
    void *phi_t7;
    void *phi_t6;
    void *phi_t5;
    void *phi_t4;
    s16 phi_a1;
    s32 phi_v1;
    s32 phi_t8;
    s32 phi_s2;
    s32 phi_s2_2;
    s32 phi_s1;
    s32 phi_s2_3;
    s32 phi_a0;
    s32 phi_s2_4;
    s32 phi_v1_2;
    void *phi_s0;
    s32 phi_s1_2;
    void *phi_v0;
    s32 phi_s2_5;
    s32 phi_v1_3;
    void *phi_v0_2;
    s32 phi_s2_6;
    void *phi_t4_2;
    void *phi_t5_2;
    void *phi_t9;
    void *phi_t6_2;
    void *phi_v0_3;
    s32 phi_s2_7;
    s32 phi_v1_4;
    void *phi_v0_4;
    s32 phi_s2_8;
    void *phi_t4_3;
    void *phi_t7_2;
    s32 phi_a0_2;

    sp70 = 0;
    func_8001F24C();
    phi_t7 = &D_8003F350;
    phi_t6 = &D_800964A0;
loop_1:
    temp_t7 = phi_t7 + 0xC;
    temp_t6 = phi_t6 + 0xC;
    temp_t6->unk-C = *phi_t7;
    temp_t6->unk-8 = temp_t7->unk-8;
    temp_t6->unk-4 = temp_t7->unk-4;
    phi_t7 = temp_t7;
    phi_t6 = temp_t6;
    if (temp_t7 != (&D_8003F350 + 0x60)) {
        goto loop_1;
    }
    temp_t6->unk0 = temp_t7->unk0;
    temp_t6->unk4 = temp_t7->unk4;
    func_8001F2E0();
    func_8001F81C();
    phi_t5 = &D_800964A0;
    phi_t4 = &D_8003F350;
loop_3:
    temp_t5 = phi_t5 + 0xC;
    temp_t4 = phi_t4 + 0xC;
    temp_t4->unk-C = *phi_t5;
    temp_t4->unk-8 = temp_t5->unk-8;
    temp_t4->unk-4 = temp_t5->unk-4;
    phi_t5 = temp_t5;
    phi_t4 = temp_t4;
    if (temp_t5 != (&D_800964A0 + 0x60)) {
        goto loop_3;
    }
    temp_t4->unk0 = temp_t5->unk0;
    temp_t4->unk4 = temp_t5->unk4;
    osSendMesg(&gThreadInitializedMQ, 1, 0);
loop_5:
    temp_v0 = osGetCount();
    temp_a0 = D_8003F344;
    temp_hi = temp_a0 % 3;
    temp_s1 = (temp_a0 & 1) * 4;
    temp_s0 = temp_s1 + &D_80096450;
    D_80096458 = *(&D_80096460 + temp_s1);
    D_8009644C = *temp_s0;
    temp_t5_2 = D_80096434;
    temp_t4_2 = D_80096430;
    D_80096438 = temp_t5_2;
    D_80096434 = temp_t4_2;
    sp6C = temp_v0;
    temp_t7_2 = ((((D_8009642C * 3) - temp_t4_2) - temp_t5_2) - sp70) + 0x5C;
    D_80096430 = temp_t7_2;
    temp_t5_3 = ((temp_t7_2 / 0xB8) * 0xB8) + 0xB8;
    D_80096430 = temp_t5_3;
    phi_a1 = temp_t5_3;
    if (temp_t5_3 >= 0x399) {
        D_80096430 = 0x398;
        phi_a1 = 0x398;
    }
    temp_s1_2 = (temp_hi * 2) + &D_8003F348;
    *temp_s1_2 = phi_a1;
    temp_ret = osGetTime(temp_a0, phi_a1, 3, &D_80096430);
    temp_v1 = temp_ret;
    D_8009650C = temp_ret;
    D_8009650C = temp_v1;
    D_8009644C = func_800299F8(D_8009644C, &sp78, osVirtualToPhysical(*(&D_80096440 + (temp_hi * 4))), *temp_s1_2);
    D_80096458->unk0 = 2;
    D_80096458->unk4 = 0x50;
    D_80096458->unk14 = 0;
    D_80096458->unk18 = 1;
    D_80096458->unk1C = 0;
    D_80096458->unk20 = &D_80095E00;
    D_80096458->unk28 = 2;
    D_80096458->unk2C = 0;
    D_80096458->unk58 = *temp_s0;
    D_80096458->unk5C = ((D_8009644C - *temp_s0) >> 3) * 8;
    D_80096458->unk30 = &gRSPBootUcode;
    D_80096458->unk34 = 0x100;
    D_80096458->unk38 = &D_80039230;
    D_80096458->unk3C = 0x1000;
    D_80096458->unk40 = &D_80041D40;
    D_80096458->unk44 = 0x800;
    D_80096458->unk48 = 0;
    D_80096458->unk4C = 0;
    D_80096458->unk60 = 0;
    D_80096458->unk64 = 0;
    D_80096458->unk50 = 0;
    D_80096458->unk54 = 0;
    D_80095DC0 = (osGetCount() - sp6C) / 0xB9B;
    osRecvMesg(&D_80095DE8, 0, 1);
    sp70 = D_A4500004 >> 2;
    osRecvMesg(&D_80095E00, 0, 1);
    temp_hi_2 = (D_8003F344 - 1) % 3;
    if (D_8003F338 == 0) {
        temp_s1_3 = (temp_hi_2 * 2) + &D_8003F348;
        if ((*temp_s1_3 * 2) > 0) {
            temp_s0_2 = (temp_hi_2 * 4) + &D_80096440;
            phi_v1 = 0;
            phi_s2 = 0;
loop_10:
            temp_s2 = phi_s2 + 2;
            temp_v0_2 = *temp_s0_2 + phi_v1;
            temp_t7_3 = temp_v0_2->unk2 + temp_v0_2->unk0;
            phi_t8 = temp_t7_3 >> 1;
            if (temp_t7_3 < 0) {
                phi_t8 = (temp_t7_3 + 1) >> 1;
            }
            sp78 = phi_t8;
            temp_v0_2->unk0 = phi_t8;
            (*temp_s0_2 + phi_v1)->unk2 = sp78;
            phi_v1 = phi_v1 + 4;
            phi_s2 = temp_s2;
            if (temp_s2 < (*temp_s1_3 * 2)) {
                goto loop_10;
            }
        }
    }
    osWritebackDCacheAll();
    osAiSetNextBuffer(*((temp_hi_2 * 4) + &D_80096440), *((temp_hi_2 * 2) + &D_8003F348) * 4);
    phi_s2_2 = 0;
    if (D_8003F334 > 0) {
loop_14:
        osRecvMesg(&D_80095E18, 0, 0);
        temp_s2_2 = phi_s2_2 + 1;
        phi_s2_2 = temp_s2_2;
        if (temp_s2_2 < D_8003F334) {
            goto loop_14;
        }
    }
    osWritebackDCacheAll();
    osSendMesg(&gInterruptMesgQueue, D_80096458, 0);
    temp_a0_2 = D_800964D3;
    D_8003F344 = D_8003F344 + 1;
    D_8003F334 = 0;
    phi_s2_4 = 0;
    if (temp_a0_2 > 0) {
        phi_s1 = 0;
        phi_s2_3 = 0;
        phi_a0_2 = temp_a0_2;
loop_18:
        temp_s2_3 = phi_s2_3 + 1;
        temp_v0_3 = D_8009646C + phi_s1;
        temp_v1_2 = *temp_v0_3;
        phi_a0 = phi_a0_2;
        if (temp_v1_2 != 0) {
            phi_a0 = phi_a0_2;
            if (temp_v1_2->unk10 == 0) {
                *temp_v0_3 = NULL;
                phi_a0 = D_800964D3;
            }
        }
        phi_s1 = phi_s1 + 4;
        phi_s2_3 = temp_s2_3;
        phi_a0_2 = phi_a0;
        if (temp_s2_3 < phi_a0) {
            goto loop_18;
        }
        phi_s2_4 = 0;
    }
loop_23:
    temp_s1_4 = phi_s2_4 * 4;
    temp_v0_4 = D_80096488 + phi_s2_4;
    temp_a0_3 = *temp_v0_4;
    if (temp_a0_3 != 1) {
        temp_s1_5 = phi_s2_4 * 4;
        if (temp_a0_3 != 2) {
            temp_s1_6 = phi_s2_4 * 4;
            if (temp_a0_3 != 3) {

            } else {
                if ((*(&D_80096478 + temp_s1_6))->unk34 == 0) {
                    *temp_v0_4 = 0;
                    *(D_8009648C + temp_s1_6) = -1;
                }
            }
        } else {
            temp_s3 = temp_s1_5 + &D_8009647C;
            temp_s0_3 = &D_80096478 + temp_s1_5;
            func_80025B74(*temp_s3, *(&D_80096484 + temp_s1_5));
            func_8002CD60(*temp_s0_3, *temp_s3);
            func_8002D0A0(*temp_s0_3);
            phi_v1_2 = 0;
loop_33:
            sp78 = phi_v1_2;
            func_800232B0(*temp_s0_3, phi_v1_2 & 0xFF, D_80096480);
            temp_v1_3 = phi_v1_2 + 1;
            phi_v1_2 = temp_v1_3;
            if (temp_v1_3 < 0x10) {
                goto loop_33;
            }
            sp78 = temp_v1_3;
            temp_v0_5 = D_80096488 + phi_s2_4;
            *temp_v0_5 = *temp_v0_5 + 1;
        }
    } else {
        temp_a1 = *(&D_80096478 + temp_s1_4);
        if (temp_a1->unk34 != 0) {
            func_8002D180(temp_a1, temp_a1);
        } else {
            temp_v1_4 = *(D_8009648C + temp_s1_4);
            if (temp_v1_4 < 0) {
                *temp_v0_4 = temp_a0_3 - 1;
            } else {
                temp_v0_6 = D_80096474 + (temp_v1_4 * 8);
                func_8001E724(temp_v0_6->unk4, *(&D_80096484 + temp_s1_4), temp_v0_6->unk8);
                temp_v0_7 = D_80096488 + phi_s2_4;
                *temp_v0_7 = *temp_v0_7 + 1;
            }
        }
    }
    temp_s2_4 = phi_s2_4 + 1;
    phi_s2_4 = temp_s2_4;
    if (temp_s2_4 <= 0) {
        goto loop_23;
    }
    phi_s0 = &D_80096490;
    phi_s1_2 = 0;
loop_39:
    temp_v1_5 = *phi_s0;
    if (temp_v1_5 != 0) {
        *phi_s0 = temp_v1_5 - 1;
        temp_v0_8 = phi_s1_2 + &D_80096494;
        *temp_v0_8 = *temp_v0_8 + *(&D_80096498 + phi_s1_2);
        temp_f0 = *temp_v0_8;
        if (temp_f0 < 0.0f) {
            *temp_v0_8 = 0.0f;
block_44:
        } else {
            if (30720.0f < temp_f0) {
                *temp_v0_8 = 30720.0f;
                goto block_44;
            }
        }
        func_8002CF00(*(&D_80096478 + phi_s1_2), (*temp_v0_8 << 0x10) >> 0x10);
    }
    temp_s0_4 = phi_s0 + 4;
    phi_s0 = temp_s0_4;
    phi_s1_2 = phi_s1_2 + 4;
    if (temp_s0_4 < &D_80096494) {
        goto loop_39;
    }
    if (D_8003F330 != 0) {
        temp_a0_4 = D_800964D3;
        temp_v1_6 = temp_a0_4 + 1;
        phi_v1_3 = temp_v1_6;
        if (temp_a0_4 > 0) {
            sp78 = temp_v1_6;
            phi_v0 = D_8009646C;
            phi_s2_5 = 0;
loop_50:
            temp_s2_5 = phi_s2_5 + 1;
            if (*phi_v0 == 0) {
                sp78 = sp78 - 1;
            }
            phi_v0 = phi_v0 + 4;
            phi_s2_5 = temp_s2_5;
            if (temp_s2_5 < temp_a0_4) {
                goto loop_50;
            }
            phi_v1_3 = sp78;
        }
        sp78 = phi_v1_3;
        phi_v0_2 = D_80096488;
loop_55:
        temp_s2_6 = phi_s2_6 + 1;
        if (*phi_v0_2 == 0) {
            sp78 = sp78 - 1;
        }
        phi_v0_2 = phi_v0_2 + 1;
        phi_s2_6 = temp_s2_6;
        if (temp_s2_6 != 1) {
            goto loop_55;
        }
        sp78 = sp78;
        if (sp78 == 0) {
            osRecvMesg(&D_80095E00, 0, 1);
            osSendMesg(&D_80095E00, 0, 1);
            func_8002A138(&D_800963D0);
            phi_t4_2 = &D_8003F350;
            phi_t5_2 = &D_800964A0;
loop_60:
            temp_t4_3 = phi_t4_2 + 0xC;
            temp_t5_4 = phi_t5_2 + 0xC;
            temp_t5_4->unk-C = *phi_t4_2;
            temp_t5_4->unk-8 = temp_t4_3->unk-8;
            temp_t5_4->unk-4 = temp_t4_3->unk-4;
            phi_t4_2 = temp_t4_3;
            phi_t5_2 = temp_t5_4;
            if (temp_t4_3 != (&D_8003F350 + 0x60)) {
                goto loop_60;
            }
            temp_t5_4->unk0 = temp_t4_3->unk0;
            temp_t5_4->unk4 = temp_t4_3->unk4;
            func_8001F2E0();
            func_8001F81C();
            phi_t9 = &D_800964A0;
            phi_t6_2 = &D_8003F350;
loop_62:
            temp_t9 = phi_t9 + 0xC;
            temp_t6_2 = phi_t6_2 + 0xC;
            temp_t6_2->unk-C = *phi_t9;
            temp_t6_2->unk-8 = temp_t9->unk-8;
            temp_t6_2->unk-4 = temp_t9->unk-4;
            phi_t9 = temp_t9;
            phi_t6_2 = temp_t6_2;
            if (temp_t9 != (&D_800964A0 + 0x60)) {
                goto loop_62;
            }
            temp_t6_2->unk0 = temp_t9->unk0;
            temp_t6_2->unk4 = temp_t9->unk4;
            D_8003F330 = 0;
            sp70 = 0;
            osSendMesg(&gThreadInitializedMQ, 1, 0);
        } else {
            func_800208D4(temp_a0_4);
            func_80020C88();
        }
    }
    if (D_8003F340 == 0) {
        goto loop_5;
    }
    temp_a0_5 = D_800964D3;
    temp_v1_7 = temp_a0_5 + 1;
    phi_v1_4 = temp_v1_7;
    if (temp_a0_5 > 0) {
        sp78 = temp_v1_7;
        phi_v0_3 = D_8009646C;
        phi_s2_7 = 0;
loop_68:
        temp_s2_7 = phi_s2_7 + 1;
        if (*phi_v0_3 == 0) {
            sp78 = sp78 - 1;
        }
        phi_v0_3 = phi_v0_3 + 4;
        phi_s2_7 = temp_s2_7;
        if (temp_s2_7 < temp_a0_5) {
            goto loop_68;
        }
        phi_v1_4 = sp78;
    }
    sp78 = phi_v1_4;
    phi_v0_4 = D_80096488;
loop_73:
    temp_s2_8 = phi_s2_8 + 1;
    if (*phi_v0_4 == 0) {
        sp78 = sp78 - 1;
    }
    phi_v0_4 = phi_v0_4 + 1;
    phi_s2_8 = temp_s2_8;
    if (temp_s2_8 != 1) {
        goto loop_73;
    }
    sp78 = sp78;
    if (sp78 == 0) {
        osRecvMesg(&D_80095E00, 0, 1);
        osSendMesg(&D_80095E00, 0, 1);
        func_8002A138(&D_800963D0);
        D_80095DC8.unk4 = D_80095DD8;
        D_80095DC8.unkC = D_80095DDC;
        func_8001F81C();
        phi_t4_3 = &D_800964A0;
        phi_t7_2 = &D_8003F350;
loop_78:
        temp_t4_4 = phi_t4_3 + 0xC;
        temp_t7_4 = phi_t7_2 + 0xC;
        temp_t7_4->unk-C = *phi_t4_3;
        temp_t7_4->unk-8 = temp_t4_4->unk-8;
        temp_t7_4->unk-4 = temp_t4_4->unk-4;
        phi_t4_3 = temp_t4_4;
        phi_t7_2 = temp_t7_4;
        if (temp_t4_4 != (&D_800964A0 + 0x60)) {
            goto loop_78;
        }
        temp_t7_4->unk0 = temp_t4_4->unk0;
        temp_t7_4->unk4 = temp_t4_4->unk4;
        D_8003F340 = 0;
        sp70 = D_A4500004 >> 2;
        goto loop_5;
    }
    func_800208D4(temp_a0_5);
    func_80020C88();
    goto loop_5;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_8001FD64.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020878(void) {
    D_8003F338 = 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020878.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020888(void) {
    D_8003F338 = 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020888.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020894(s32 arg0) {
    D_8003F338 = arg0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020894.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800208A0(s8 arg0) {
    if (arg0 != D_8003F33C) {
        D_8003F340 = D_8003F340 + 1;
        D_800964D0 = arg0;
    }
    return &D_8003F340;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_800208A0.s")
#endif

void func_800208D4(void) {
    s32 i;
    
    for (i = 0; i < 1; i++) {
        func_80020968(i);
    }
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u32 func_80020914(s32 arg0, u32 arg1) {
    if (arg1 < D_80096474->unk2) {
        *(D_80096488 + arg0) = 1;
        *(D_8009648C + (arg0 * 4)) = arg1;
        return arg1;
    }
    return -1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020914.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020968(s32 arg0) {
    *(D_80096488 + arg0) = 1;
    *(D_8009648C + (arg0 * 4)) = -1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020968.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020998(s32 arg0, u32 arg1) {
    s32 sp1C;
    f32 temp_f6;
    s32 temp_v0;
    u32 phi_a2;
    f32 phi_f6;

    phi_a2 = arg1;
    if (arg1 >= 0x7801) {
        phi_a2 = 0x7800;
    }
    temp_v0 = arg0 * 4;
    sp1C = temp_v0;
    arg1 = phi_a2;
    func_8002CF00(*(&D_80096478 + temp_v0), (phi_a2 << 0x10) >> 0x10, phi_a2, arg0);
    temp_f6 = arg1;
    phi_f6 = temp_f6;
    if (arg1 < 0) {
        phi_f6 = temp_f6 + 4294967296.0f;
    }
    *(&D_80096494 + temp_v0) = phi_f6;
    *(&D_80096490 + temp_v0) = 0;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020998.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020A20(s32 arg0, u32 arg1, s32 arg2) {
    f32 temp_f4;
    s32 temp_v0;
    u32 phi_a1;
    f32 phi_f4;

    phi_a1 = arg1;
    if (arg1 >= 0x7801) {
        phi_a1 = 0x7800;
    }
    temp_v0 = arg0 * 4;
    if (arg2 != 0) {
        *(&D_80096490 + temp_v0) = arg2;
        temp_f4 = arg2;
        phi_f4 = temp_f4;
        if (arg2 < 0) {
            phi_f4 = temp_f4 + 4294967296.0f;
        }
        *(&D_80096498 + temp_v0) = (phi_a1 - *(&D_80096494 + temp_v0)) / phi_f4;
        return temp_v0;
    }
    return func_80020998(phi_a1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020A20.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020ABC(s32 arg0, u32 arg1) {
    s32 temp_s0;
    s32 phi_s0;
    u32 phi_a1;

    phi_a1 = arg1;
    if (arg1 >= 0x80) {
        phi_a1 = 0x7F;
    }
    phi_s0 = 0;
loop_3:
    func_80023300(*((arg0 * 4) + &D_80096478), phi_s0 & 0xFF, (phi_a1 & 0xFF) & 0xFF);
    temp_s0 = phi_s0 + 1;
    phi_s0 = temp_s0;
    if (temp_s0 != 0x10) {
        goto loop_3;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020ABC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020B34(s32 arg0, s32 arg1) {
    s32 temp_s0;
    s32 temp_s1;
    s8 phi_s1;
    s32 phi_s0;

    temp_s1 = arg1 & 0xFF;
    phi_s1 = temp_s1;
    if (temp_s1 >= 0x80) {
        phi_s1 = 0x7F;
    }
    D_80096480 = phi_s1;
    phi_s0 = 0;
loop_3:
    func_800232B0(*((arg0 * 4) + &D_80096478), phi_s0 & 0xFF, phi_s1 & 0xFF);
    temp_s0 = phi_s0 + 1;
    phi_s0 = temp_s0;
    if (temp_s0 != 0x10) {
        goto loop_3;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020B34.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_80020BB8(s32 arg0) {
    if ((*(&D_80096478 + (arg0 * 4)))->unk34 == 0) {
        return 0;
    }
    return 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020BB8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020BE8(s32 arg0) {
    s32 sp24;
    s32 sp1C;
    s32 temp_a1;
    u8 temp_a2;
    void *phi_v0;
    s32 phi_v1;
    s32 phi_a1;

    temp_a2 = D_800964D3;
    if (temp_a2 > 0) {
        phi_v0 = D_8009646C;
        phi_v1 = 0;
        phi_a1 = 0;
loop_2:
        if (*phi_v0 == 0) {
            sp1C = phi_v1;
            sp24 = phi_a1;
            *(D_8009646C + phi_v1) = func_80023CB0(arg0 & 0xFFFF, phi_a1, temp_a2, arg0);
            return phi_a1;
        }
        temp_a1 = phi_a1 + 1;
        phi_v0 = phi_v0 + 4;
        phi_v1 = phi_v1 + 4;
        phi_a1 = temp_a1;
        if (temp_a1 < temp_a2) {
            goto loop_2;
        }
    }
    return -1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020BE8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_80020C70(s32 arg0, ? arg1, ? arg2, ? arg3) {
    return -1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020C70.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_80020C88:

Label L80020CB0_ovl0_before refers to a delay slot; this is currently not supported.
Please modify the assembly to work around it (e.g. copy the instruction
to all jump sources and move the label, or add a nop to the delay slot).

This label was auto-generated as the target for a branch-likely
instruction (e.g. beql); you can also try to turn that into a non-likely
branch if that's equivalent in this context, i.e., if it's okay to
execute its delay slot unconditionally.
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020C88.s")
#endif

void func_80020CC4(u32 arg0) {
    s32 phi_a0;

    if (arg0 >= 0x7801) {
        phi_a0 = 0x7F;
    } else {
        phi_a0 = (arg0 >> 8) & 0xFF;
    }
    func_80023360(phi_a0, arg0);
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020D00(s32 arg0, u32 arg1) {
    s32 temp_a0;
    u32 phi_a2;

    phi_a2 = arg1;
    if (arg1 >= 0x8000) {
        phi_a2 = 0x7FFF;
    }
    temp_a0 = *(D_8009646C + (arg0 * 4));
    if (temp_a0 != 0) {
        func_80023464(temp_a0, (phi_a2 >> 8) & 0xFF, phi_a2, arg0);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020D00.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020D58(s32 arg0, s32 arg1) {
    s32 temp_a0;
    s32 phi_a2;

    phi_a2 = arg1 & 0xFF;
    if ((arg1 & 0xFF) >= 0x80) {
        phi_a2 = 0x7F;
    }
    temp_a0 = *(D_8009646C + (arg0 * 4));
    if (temp_a0 != 0) {
        func_800233F4(temp_a0, phi_a2 & 0xFF, phi_a2, arg0);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020D58.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020DAC(s32 arg0, s32 arg1) {
    s32 temp_a0;
    s32 phi_a2;

    phi_a2 = arg1 & 0xFF;
    if ((arg1 & 0xFF) >= 0x80) {
        phi_a2 = 0x7F;
    }
    temp_a0 = *(D_8009646C + (arg0 * 4));
    if (temp_a0 != 0) {
        func_80023384(temp_a0, phi_a2 & 0xFF, phi_a2, arg0);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020DAC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020E00(s32 arg0, ? arg1) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020E00.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020E0C(s32 arg0) {
    s32 sp1C;
    s32 temp_a1;
    s32 temp_v0;

    temp_v0 = arg0 * 4;
    temp_a1 = *(D_8009646C + temp_v0);
    if (temp_a1 != 0) {
        sp1C = temp_v0;
        func_80023A28(temp_a1, temp_a1);
        *(D_8009646C + temp_v0) = 0;
    }
    return arg0 * 4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020E0C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80020E5C(s32 arg0, s32 arg1) {
    void *temp_v0;

    temp_v0 = *(D_8009646C + (arg0 * 4));
    if (temp_v0 != 0) {
        temp_v0->unk1F = arg1 & 0xFF;
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020E5C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020E8C(void) {
    D_8003F330 = 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020E8C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020E9C(void) {
    return D_8003F330;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020E9C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020EA8(void) {
    return D_8003F340;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020EA8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80020EB4(void) {
    return D_8003F340 | D_8003F330;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020EB4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80020ECC(void) {
    osRecvMesg(&gThreadInitializedMQ, 0, 0);
    D_8003F330 = 1;
    osRecvMesg(&gThreadInitializedMQ, 0, 1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl0/ovl0_7/func_80020ECC.s")
#endif
