#include <ultra64.h>
#include <macros.h>

extern void func_800067B8(void);
extern void func_8000AD88(void);
extern u32 D_8015A694;

void func_80151100(void) {
    if (D_8015A694 != 0) {
        func_800067B8();
    }
    func_8000AD88();
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u32 func_80151138(s32 arg0) {
    s32 sp1C;
    void *temp_t1;
    s32 phi_v1;

    if (D_80048C5C != 0) {
        return 1;
    }
    sp1C = osViGetCurrentFramebuffer_0();
    if (gCurrFrameBuffer == gFrameBuffers[0]) {
        phi_v1 = 1;
    } else {
        if (gCurrFrameBuffer == gFrameBuffers[1]) {
            phi_v1 = 2;
        } else {
            if (gCurrFrameBuffer == gFrameBuffers[2]) {

            }
            phi_v1 = 0;
        }
    }
    temp_t1 = gFrameBuffers[phi_v1];
    if (osViGetCurrentFramebuffer() != *temp_t1) {
        if (sp1C != *temp_t1) {
            D_80048C5C = (s32) *temp_t1;
            D_80048C6C = func_800314D0_ovl6(*temp_t1, &gFrameBuffers);
            return 1;
        }
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80151138.s")
#endif

extern Gfx *gDisplayListHeads[4];
extern void func_8009E8F4_ovl6(u32 a, Gfx **b);

#ifdef MIPS_TO_C
void *func_80151204(void) {
    gDPPipeSync(gDisplayListHeads[1]++);
    gDPSetRenderMode(gDisplayListHeads[1]++, G_RM_ZB_CLD_SURF, G_RM_ZB_CLD_SURF2);
    func_8009E8F4_ovl6(2, &gDisplayListHeads[1]);
    gDPPipeSync(gDisplayListHeads[1]++);
    gDPSetColorDither(gDisplayListHeads[1]++, G_CD_MAGICSQ);
    gDPSetAlphaDither(gDisplayListHeads[1]++, G_AD_DISABLE);
    gDPSetRenderMode(gDisplayListHeads[1]++, G_RM_AA_ZB_XLU_SURF, G_RM_AA_ZB_XLU_SURF2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80151204.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_801512F0(void) {
    void *sp2C;
    void *sp24;
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v0_3;
    void *phi_v0;

    func_8009B99C_ovl6(0x200);
    func_800A04B8_ovl6(0x10);
    temp_v0 = func_8000A180_ovl6(0, 0, 0x18, 0x80000000);
    sp2C = temp_v0;
    sp24 = &D_80151204;
    func_8000A5FC_ovl6(temp_v0, &D_80151204, 0x10, 8, 0x10);
    sp2C->unk30 = 1;
    temp_v0_2 = func_8000A180_ovl6(0, 0, 0x18, 0x80000000);
    sp2C = temp_v0_2;
    func_8000A5FC_ovl6(temp_v0_2, &D_80151204, 0x10, 0x10, 0x10);
    sp2C->unk30 = 2;
    phi_v0 = &D_800D6AB8;
loop_1:
    temp_v0_3 = phi_v0 + 0x10;
    temp_v0_3->unk-C = 0;
    temp_v0_3->unk-8 = 0;
    temp_v0_3->unk-4 = 0;
    temp_v0_3->unk-10 = 0;
    phi_v0 = temp_v0_3;
    if (temp_v0_3 != &D_800D6AD8) {
        goto loop_1;
    }
    return temp_v0_3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801512F0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801513C8(void) {
    func_800A7A70_ovl6(0, 0x40001, 0x40002);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801513C8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801513F8(s32 arg0, s32 arg1, s32 arg2) {
    void *sp2C;
    f32 sp20;
    s32 temp_a1;
    s32 temp_a3;
    void *temp_v0;

    temp_a3 = arg0;
    if (arg1 == 0xD) {
        temp_a1 = arg2 & 0xFFFF;
        if (temp_a1 >= 0) {
            arg0 = temp_a3;
            temp_v0 = func_800A19EC_ovl6((arg2 >> 0x10) * 8, temp_a1, temp_a3);
            if (temp_v0 != 0) {
                if (temp_v0->unk4C == 0) {
                    temp_v0->unk48 = arg0;
                    return;
                }
                sp2C = temp_v0;
                func_800B2340_ovl6(&sp20, arg0, 0xFFFF, arg0);
                temp_v0->unk4C->unk4 = sp20;
                temp_v0->unk4C->unk8 = sp24;
                temp_v0->unk4C->unkC = sp28;
                return;
            }
        }
    } else {
        D_800B0F28_ovl6(temp_a3, arg2, temp_a3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801513F8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_801514A0(void *arg0, void *arg1) {
    u8 temp_v1;
    void *temp_v0;

    temp_v1 = arg0->unk3C->unk80->unk68;
    temp_v0 = arg0->unk3C->unk80 + 8;
    arg1->unkC = temp_v1;
    arg1->unk8 = temp_v1;
    arg1->unkD = (u8) temp_v0->unk61;
    arg1->unk9 = (u8) temp_v0->unk61;
    arg1->unkE = (u8) temp_v0->unk62;
    arg1->unkA = (u8) temp_v0->unk62;
    arg1->unk4 = (u8) temp_v0->unk64;
    arg1->unk0 = (u8) temp_v0->unk64;
    arg1->unk5 = (u8) temp_v0->unk65;
    arg1->unk1 = (u8) temp_v0->unk65;
    arg1->unkB = (u8)0;
    arg1->unkF = (u8)0;
    arg1->unk13 = (u8)0;
    arg1->unk3 = (u8)0;
    arg1->unk7 = (u8)0;
    arg1->unk6 = (u8) temp_v0->unk66;
    arg1->unk2 = (u8) temp_v0->unk66;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801514A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8015150C(void) {
    f32 sp3C;
    f32 sp38;
    f32 sp34;
    f32 sp30;
    f32 sp2C;
    f32 sp28;
    f32 sp24;
    f32 sp20;
    f32 temp_f0;
    f32 temp_f16;
    f32 temp_f18;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f6;
    f32 temp_f8;

    sp34.unk0 = (s32) D_8015A56C->unk3C->unk30;
    sp34.unk4 = (s32) D_8015A56C->unk3C->unk34;
    sp34.unk8 = (s32) D_8015A56C->unk3C->unk38;
    sp30 = func_8002D6E0_ovl6(sp34);
    sp2C = func_80035810_ovl6(sp34);
    sp28 = func_8002D6E0_ovl6(sp38);
    sp24 = func_80035810_ovl6(sp38);
    sp20 = func_8002D6E0_ovl6(sp3C);
    temp_f0 = func_80035810_ovl6(sp3C);
    temp_f2 = sp2C * sp28;
    temp_f16 = (temp_f2 * temp_f0) + (sp30 * sp20);
    temp_f6 = sp30 * temp_f0;
    sp34 = temp_f16;
    temp_f18 = (temp_f2 * sp20) - temp_f6;
    temp_f8 = sp2C * sp24;
    sp38 = temp_f18;
    sp3C = temp_f8;
    temp_f2_2 = 100.0f / func_80032B20_ovl6(((temp_f16 * temp_f16) + (temp_f18 * temp_f18)) + (temp_f8 * temp_f8), sp20);
    D_8015A670->unk10 = (s8) -(s32) (sp34 * temp_f2_2);
    D_8015A670->unk11 = (s8) -(s32) (sp38 * temp_f2_2);
    D_8015A670->unk12 = (s8) -(s32) (sp3C * temp_f2_2);
    return &D_8015A670;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015150C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8015166C(Gfx *dl) {
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v0_3;

    func_8015150C_ovl6();
    func_801514A0_ovl6(D_8015A56C, D_8015A670);
    gMoveWd(dl++, 2, G_MW_MATRIX, 0x00000018);

    temp_v0_2 = *arg0;
    *arg0 = (void *) (temp_v0_2 + 8);
    temp_v0_2->unk0 = 0xDC08060A;
    temp_v0_2->unk4 = (s32) (D_8015A670 + 8);
    temp_v0_3 = *arg0;
    *arg0 = (void *) (temp_v0_3 + 8);
    temp_v0_3->unk0 = 0xDC08090A;
    temp_v0_3->unk4 = (s32) D_8015A670;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015166C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_8015170C:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015170C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_8015198C:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015198C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80151CD0(s32 arg0, ? arg1) {
    f32 sp24;
    f32 temp_f0;
    f32 temp_f2;
    f32 temp_ret;

    func_80018DEC_ovl6(&sp24, ((arg0 * 4) + 0x80160000)->unk-5A90->unk3C + 0x1C, arg1, arg0);
    temp_ret = func_80032B20_ovl6(((sp24 * sp24) + (sp28 * sp28)) + (sp2C * sp2C), sp2C);
    temp_f0 = temp_ret;
    if (temp_f0 == 0.0f) {
        D_8004A3F8.unkC->unk12 = (u8)0;
        D_8004A3F8.unkC->unk10 = (s8) D_8004A3F8.unkC->unk12;
        D_8004A3F8.unkC->unk11 = (u8)0x64;
        return D_8004A3F8.unkC;
    }
    temp_f2 = 100.0f / temp_f0;
    D_8004A3F8.unkC->unk10 = (s8) (s32) (sp24 * temp_f2);
    D_8004A3F8.unkC->unk11 = (s8) (s32) (sp28 * temp_f2);
    D_8004A3F8.unkC->unk12 = (s8) (s32) (sp2C * temp_f2);
    return (bitwise void *) temp_ret;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80151CD0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80151DDC(s32 arg0) {
    func_80151CD0_ovl6(((arg0 * 4) + 0x800E0000)->unk-1CB0->unk3C + 0x1C);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80151DDC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80151E10(s32 arg0) {
    ? sp1C;

    func_800A4794_ovl6(&sp1C, ((arg0 * 4) + 0x800E0000)->unk-1CB0->unk3C->unk10->unk10);
    func_80151CD0_ovl6(arg0, &sp1C);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80151E10.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_80151E60:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80151E60.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_80152138:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152138.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_801524C8:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801524C8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80152B28(void *arg0) {
    s32 sp1C;
    s32 sp18;

    sp1C = *arg0;
    sp18 = D_8004A404;
    func_80151DDC_ovl6(*arg0, *arg0);
    func_801514A0_ovl6(((*arg0 * 4) + 0x80160000)->unk-5A90, sp18, *arg0);
    D_8004A3F8.unkC = (s32) (D_8004A3F8.unkC + 0x18);
    func_80151E60_ovl6(arg0, sp18);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152B28.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80152B9C(void *arg0) {
    s32 sp1C;
    s32 sp18;

    sp1C = *arg0;
    sp18 = D_8004A404;
    func_80151DDC_ovl6(*arg0, *arg0);
    func_801514A0_ovl6(((*arg0 * 4) + 0x80160000)->unk-5A90, sp18, *arg0);
    D_8004A3F8.unkC = (s32) (D_8004A3F8.unkC + 0x18);
    func_80152138_ovl6(arg0, sp18);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152B9C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80152C10(void *arg0) {
    s32 sp1C;
    s32 sp18;

    sp1C = *arg0;
    sp18 = D_8004A404;
    func_80151E10_ovl6(*arg0, *arg0);
    func_801514A0_ovl6(((*arg0 * 4) + 0x80160000)->unk-5A90, sp18, *arg0);
    D_8004A3F8.unkC = (s32) (D_8004A3F8.unkC + 0x18);
    func_80151E60_ovl6(arg0, sp18);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152C10.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80152C84(void *arg0) {
    s32 sp1C;
    s32 sp18;

    sp1C = *arg0;
    sp18 = D_8004A404;
    func_80151E10_ovl6(*arg0, *arg0);
    func_801514A0_ovl6(((*arg0 * 4) + 0x80160000)->unk-5A90, sp18, *arg0);
    D_8004A3F8.unkC = (s32) (D_8004A3F8.unkC + 0x18);
    func_80152138_ovl6(arg0, sp18);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152C84.s")
#endif

void func_80152CF8(s32 arg0) {

}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80152D00(void *arg0) {
    u32 temp_v1;
    u8 temp_a0;
    void *temp_a2;
    void *temp_v1_2;
    void *phi_v0;
    void *phi_a1;
    u32 phi_v1;
    u32 phi_a0;
    void *phi_v0_2;
    void *phi_return;
    void *phi_return_2;

    phi_v0 = arg0->unk3C;
    phi_return = arg0->unk3C;
    phi_return_2 = arg0->unk3C;
    if (arg0->unk3C != 0) {
loop_1:
        temp_a0 = phi_v0->unk56;
        phi_a1 = phi_v0;
        phi_v1 = 0U;
        phi_a0 = (u32) temp_a0;
        if (temp_a0 != 0) {
loop_2:
            temp_a2 = phi_a1->unk58;
            temp_v1 = phi_v1 + 1;
            if (0x1C == temp_a2->unk4) {
                temp_a2->unk5 = (u8)1;
                phi_a0 = (u32) phi_v0->unk56;
            }
            phi_a1 = phi_a1 + 4;
            phi_v1 = temp_v1;
            if (temp_v1 < phi_a0) {
                goto loop_2;
            }
        }
        if (phi_v0->unk10 != 0) {
block_15:
            phi_v0_2 = phi_v0;
        } else {
            if (phi_v0->unk8 != 0) {
                goto block_15;
loop_9:
block_10:
                temp_v1_2 = phi_v0->unk14;
                if (1 == temp_v1_2) {
                    phi_v0_2 = NULL;
                    phi_return_2 = NULL;
                } else {
                    if (temp_v1_2->unk8 != 0) {
                        phi_v0_2 = temp_v1_2->unk8;
                        phi_return_2 = temp_v1_2->unk8;
                    } else {
                        goto loop_9;
                    }
                }
            } else {
                goto block_10;
            }
        }
        phi_v0 = phi_v0_2;
        phi_return = phi_return_2;
        if (phi_v0_2 != 0) {
            goto loop_1;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152D00.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80152DB8(void) {
    void *sp2C;
    s32 sp28;
    s32 sp24;
    s32 temp_v0;
    s32 temp_v0_2;
    s32 temp_v1;
    void *temp_a0;

    sp2C = D_8004A7C4;
    temp_v0 = func_800AEC08_ovl6(0x11, D_8015A560->unk3, D_8015A560->unk3 + 1);
    temp_v1 = temp_v0 * 4;
    temp_a0 = temp_v1 + 0x800E0000;
    D_8004A7C4 = (void *) (temp_v1 + 0x800E0000)->unk-1CB0;
    sp28 = temp_v0;
    func_80008DA8_ovl6(temp_a0->unk-1AF0);
    temp_v0_2 = temp_v0 * 4;
    sp24 = temp_v0_2;
    func_80008DA8_ovl6((temp_v0_2 + 0x800E0000)->unk-1930);
    func_80008DA8_ovl6((temp_v0_2 + 0x800E0000)->unk-13F0);
    D_8004A7C4->unk48 = &D_801513F8;
    func_80008A18_ovl6(D_8004A7C4, &func_8000E324, 1, 3);
    func_800A9864_ovl6(D_8015A560->unk4, 0x1869F, 0x10);
    func_80152D00_ovl6(D_8004A7C4);
    D_8004A7C4 = sp2C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152DB8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_80152EA8:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80152EA8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80153040(void) {
    D_8015A7B0 = 0;
    D_8015A7AC = 0;
    *(void *)0x8015A7A8 = 0;
    return &D_8015A7B0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153040.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u32 func_80153064(void) {
    u32 temp_v0_2;
    u32 temp_v1;
    void *temp_v0;
    u32 phi_v0;
    u32 phi_return;

    if (D_8015A7AC != D_8015A7B0) {
loop_2:
        temp_v0 = &D_8015A6A8 + (D_8015A7B0 * 8);
        if (temp_v0->unk4 != 0) {
            func_800A8E54_ovl6(temp_v0->unk0, 3);
        } else {
            func_800A8D64_ovl6(temp_v0->unk0, 3);
        }
        temp_v0_2 = D_8015A7B0 + 1;
        if (temp_v0_2 >= 0x20U) {
            D_8015A7B0 = 0U;
        } else {
            D_8015A7B0 = temp_v0_2;
        }
        if (D_8015A7AC != D_8015A7B0) {
            goto loop_2;
        }
    }
    phi_v0 = D_8015A7AC;
    if (D_8015A7A8 != D_8015A7AC) {
loop_10:
        temp_v1 = phi_v0 + 1;
        if (temp_v1 >= 0x20U) {
            D_8015A7AC = 0U;
        } else {
            D_8015A7AC = temp_v1;
        }
        phi_v0 = D_8015A7AC;
        phi_return = D_8015A7AC;
        if (D_8015A7A8 != D_8015A7AC) {
            goto loop_10;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153064.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8015314C(s32 arg0, s32 arg1) {
    s8 temp_a1;
    u32 temp_v1;
    void *temp_v0;

    temp_a1 = arg1 & 0xFF;
    if (arg0 != -1) {
        if (D_8015A7B0 != D_8015A7AC) {
            if (D_8015A7B0 == D_8015A7A8) {
                fatal_printf(&D_8015A410, temp_a1, arg0);
                while (TRUE);
            }
        }
        temp_v0 = (D_8015A7A8 * 8) + &D_8015A6A8;
        temp_v0->unk0 = arg0;
        temp_v0->unk4 = temp_a1;
        temp_v1 = D_8015A7A8 + 1;
        if (temp_v1 >= 0x20U) {
            D_8015A7A8 = 0U;
            return;
        }
        D_8015A7A8 = temp_v1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015314C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_801531FC(void) {
    if (D_8015A7AC == D_8015A7B0) {
        return 0;
    }
    return 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801531FC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153228(s32 arg0) {
    s32 sp18;
    s32 temp_a2;
    s32 temp_v0;
    void *temp_v1;
    s32 phi_a2;

    temp_v0 = arg0 * 4;
    temp_v1 = temp_v0 + 0x800E0000;
    sp18 = (temp_v0 + 0x800E0000)->unk2D0;
    temp_a2 = arg0;
    if (&D_800AD1A0 == temp_v1->unk-1CB0->unk2C) {
block_2:
        phi_a2 = temp_a2;
        if (temp_v1->unk-1CB0->unk4C != 0) {
            arg0 = temp_a2;
            func_800ACB7C_ovl6(temp_v1->unk-1CB0->unk4C, temp_v1->unk-1CB0->unk2C, temp_a2);
            phi_a2 = arg0;
        }
        func_800B1900_ovl6(phi_a2 & 0xFFFF, phi_a2);
        func_8015314C_ovl6(sp18, 1);
        return;
    }
    if (&D_801548F8 == temp_v1->unk-1CB0->unk2C) {
        goto block_2;
    }
    func_800B1900_ovl6(temp_a2 & 0xFFFF, temp_v1->unk-1CB0->unk2C, temp_a2);
    func_8015314C_ovl6(sp18, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153228.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801532CC(void) {
    func_80153228_ovl6(D_8015A560->unk3);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801532CC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_801532F4(void *arg0) {
    u32 temp_a0;
    u8 temp_a1;
    void *temp_a3;
    void *temp_v1;
    void *phi_v0;
    void *phi_a2;
    s8 phi_v1;
    u32 phi_a0;
    u32 phi_a1;
    void *phi_v0_2;
    void *phi_return;
    void *phi_return_2;

    phi_v0 = arg0->unk3C;
    phi_return = arg0->unk3C;
    phi_return_2 = arg0->unk3C;
    if (arg0->unk3C != 0) {
loop_1:
        phi_v1 = (u8)0;
        if (phi_v0->unk70 == 0) {
            phi_v1 = (u8)1;
        }
        temp_a1 = phi_v0->unk56;
        phi_a2 = phi_v0;
        phi_a0 = 0U;
        phi_a1 = (u32) temp_a1;
        if (temp_a1 != 0) {
loop_4:
            temp_a3 = phi_a2->unk58;
            temp_a0 = phi_a0 + 1;
            if (0x1C == temp_a3->unk4) {
                temp_a3->unk5 = phi_v1;
                phi_a1 = (u32) phi_v0->unk56;
            }
            phi_a2 = phi_a2 + 4;
            phi_a0 = temp_a0;
            if (temp_a0 < phi_a1) {
                goto loop_4;
            }
        }
        if (phi_v0->unk10 != 0) {
block_17:
            phi_v0_2 = phi_v0;
        } else {
            if (phi_v0->unk8 != 0) {
                goto block_17;
loop_11:
block_12:
                temp_v1 = phi_v0->unk14;
                if (1 == temp_v1) {
                    phi_v0_2 = NULL;
                    phi_return_2 = NULL;
                } else {
                    if (temp_v1->unk8 != 0) {
                        phi_v0_2 = temp_v1->unk8;
                        phi_return_2 = temp_v1->unk8;
                    } else {
                        goto loop_11;
                    }
                }
            } else {
                goto block_12;
            }
        }
        phi_v0 = phi_v0_2;
        phi_return = phi_return_2;
        if (phi_v0_2 != 0) {
            goto loop_1;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801532F4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801533C0(void) {
    s32 sp1C;

    sp1C = D_8004A7C4;
    D_8004A7C4 = (s32) ((D_8015A560->unk3 * 4) + 0x800E0000)->unk-1CB0;
    func_800AA018_ovl6(D_8015A560->unk4);
    func_801532F4_ovl6(D_8004A7C4);
    *(void *)0x8004A7C4 = sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801533C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153424(void) {
    s32 sp1C;

    sp1C = D_8004A7C4;
    D_8004A7C4 = (s32) ((D_8015A560->unk3 * 4) + 0x800E0000)->unk-1CB0;
    func_800AA018_ovl6(D_8015A560->unk4);
    *(void *)0x8004A7C4 = sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153424.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8015347C(void) {
    ((D_8015A560->unk3 * 4) + 0x800E0000)->unk-1CB0->unk2C = &D_8015170C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015347C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801534A8(void) {
    ((D_8015A560->unk3 * 4) + 0x800E0000)->unk-1CB0->unk2C = &D_8015198C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801534A8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_801534D4(void) {
    (*(&D_800DE350 + (D_8015A560->unk3 * 4)))->unk2C = &D_80152B28;
    ((D_8015A560->unk3 * 4) + 0x80160000)->unk-5A90 = (s32) *(&D_800DE350 + (D_8015A560->unk4 * 4));
    return D_8015A560;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801534D4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80153530(void) {
    (*(&D_800DE350 + (D_8015A560->unk3 * 4)))->unk2C = &D_80152B9C;
    ((D_8015A560->unk3 * 4) + 0x80160000)->unk-5A90 = (s32) *(&D_800DE350 + (D_8015A560->unk4 * 4));
    return D_8015A560;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153530.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8015358C(void) {
    (*(&D_800DE350 + (D_8015A560->unk3 * 4)))->unk2C = &D_80152C10;
    ((D_8015A560->unk3 * 4) + 0x80160000)->unk-5A90 = (s32) *(&D_800DE350 + (D_8015A560->unk4 * 4));
    return D_8015A560;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015358C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_801535E8(void) {
    (*(&D_800DE350 + (D_8015A560->unk3 * 4)))->unk2C = &D_80152C84;
    ((D_8015A560->unk3 * 4) + 0x80160000)->unk-5A90 = (s32) *(&D_800DE350 + (D_8015A560->unk4 * 4));
    return D_8015A560;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801535E8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153644(void) {
    ((D_8015A560->unk3 * 4) + 0x800E0000)->unk-1CB0->unk2C = &D_801524C8;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153644.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153670(void) {
    func_800AAF34_ovl6(0x10, D_8015A560->unk4, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153670.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801536A0(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801536A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_801536A8(void) {
    void *temp_t9;

    temp_t9 = (D_8015A560->unk3 * 4) + 0x800E0000;
    D_8015A56C = (void *) temp_t9->unk-1CB0;
    temp_t9->unk-1CB0->unk2C = &D_801536A0;
    return &D_8015A56C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801536A8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801536E0(void) {
    ((D_8015A560->unk3 * 4) + 0x800E0000)->unk-1CB0->unk2C = &D_801536A0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801536E0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8015370C(void) {
    D_800D799C->unk3C->unk84 = (s32) D_8015A560->unk4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015370C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8015372C(void) {
    D_800D799C->unk3C->unk80 = (s32) (D_800D799C->unk3C->unk80 & -3);
    return D_800D799C->unk3C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015372C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8015374C(void *arg0) {
    u8 temp_t7;
    void *temp_a0;
    void *temp_a0_2;
    void *temp_a0_3;
    void *temp_a0_4;
    void *temp_a0_5;
    void *temp_a0_6;
    void *temp_a0_7;
    void *temp_v0;

    temp_t7 = arg0->unk3C->unk80->unk5B;
    temp_v0 = arg0->unk3C->unk80 + 8;
    if (temp_t7 != 0) {
        temp_a0 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0 + 8);
        temp_a0->unk4 = 0;
        temp_a0->unk0 = 0xE7000000;
        temp_a0_2 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_2 + 8);
        temp_a0_2->unk4 = 0xFFFDF6FB;
        temp_a0_2->unk0 = 0xFCFFFFFF;
        temp_a0_3 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_3 + 8);
        temp_a0_3->unk4 = 0x504340;
        temp_a0_3->unk0 = 0xE200001C;
        temp_a0_4 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_4 + 8);
        temp_a0_4->unk0 = 0xFA000000;
        temp_a0_4->unk4 = (s32) ((((temp_v0->unk50 << 0x18) | (temp_v0->unk51 << 0x10)) | (temp_v0->unk52 << 8)) | temp_v0->unk53);
        temp_a0_5 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_5 + 8);
        temp_a0_5->unk4 = 0xC0098;
        temp_a0_5->unk0 = 0xF6440328;
        temp_a0_6 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_6 + 8);
        temp_a0_6->unk4 = 0;
        temp_a0_6->unk0 = 0xE7000000;
        temp_a0_7 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_7 + 8);
        temp_a0_7->unk4 = 0x5049D8;
        temp_a0_7->unk0 = 0xE200001C;
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015374C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153868(void) {
    s32 sp1C;

    if (D_8015A690 == 0) {
        if (D_800DE44C == 0) {
            sp1C = D_8004A7C4;
            func_800AEC08_ovl6(0x11, 0x3F, 0x40);
            D_8004A7C4 = (s32) D_800DE44C;
            func_80008DA8_ovl6(D_800DE60C);
            func_80008DA8_ovl6(D_800DE7CC);
            func_80008DA8_ovl6(D_800DED0C);
            func_80008A18_ovl6(D_8004A7C4, &func_8000E324, 1, 3);
            func_800A9864_ovl6(D_8015A560->unk4, 0x1869F, 0xC);
            D_8004A7C4 = sp1C;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153868.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_8015392C(void *arg0) {
    u8 temp_t7;
    void *temp_a0;
    void *temp_a0_2;
    void *temp_a0_3;
    void *temp_a0_4;
    void *temp_a0_5;
    void *temp_a0_6;
    void *temp_a0_7;
    void *temp_v0;

    temp_t7 = arg0->unk3C->unk80->unk5B;
    temp_v0 = arg0->unk3C->unk80 + 8;
    if (temp_t7 != 0) {
        temp_a0 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0 + 8);
        temp_a0->unk4 = 0;
        temp_a0->unk0 = 0xE7000000;
        temp_a0_2 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_2 + 8);
        temp_a0_2->unk4 = 0xFFFDF6FB;
        temp_a0_2->unk0 = 0xFCFFFFFF;
        temp_a0_3 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_3 + 8);
        temp_a0_3->unk4 = 0x504340;
        temp_a0_3->unk0 = 0xE200001C;
        temp_a0_4 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_4 + 8);
        temp_a0_4->unk0 = 0xFA000000;
        temp_a0_4->unk4 = (s32) ((((temp_v0->unk50 << 0x18) | (temp_v0->unk51 << 0x10)) | (temp_v0->unk52 << 8)) | temp_v0->unk53);
        temp_a0_5 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_5 + 8);
        temp_a0_5->unk4 = 0x28028;
        temp_a0_5->unk0 = 0xF64D8398;
        temp_a0_6 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_6 + 8);
        temp_a0_6->unk4 = 0;
        temp_a0_6->unk0 = 0xE7000000;
        temp_a0_7 = gDisplayListHead.unk4;
        gDisplayListHead.unk4 = (void *) (temp_a0_7 + 8);
        temp_a0_7->unk4 = 0x5049D8;
        temp_a0_7->unk0 = 0xE200001C;
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015392C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153A48(void) {
    void *temp_t9;

    temp_t9 = (D_8015A560->unk3 * 4) + 0x800E0000;
    D_8015A668 = (s32) temp_t9->unk-1CB0;
    func_8000A904_ovl6(temp_t9->unk-1CB0, 0x10, 1);
    D_8015A668->unk2C = &D_8015374C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153A48.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80153AA8(void) {
    void *temp_t9;

    temp_t9 = (D_8015A560->unk3 * 4) + 0x800E0000;
    D_8015A66C = (void *) temp_t9->unk-1CB0;
    temp_t9->unk-1CB0->unk2C = &D_801536A0;
    D_800D799C->unk3C->unk80 = (s32) (D_800D799C->unk3C->unk80 | 2);
    return D_800D799C->unk3C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153AA8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153AF8(void) {
    func_800A75B0_ovl6(0, 0x99999999);
    func_800A75B0_ovl6(0, D_8015A560->unk4);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153AF8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153B34(void *arg0) {
    if (D_8015A554 == arg0->unk3C->unk80->unk98) {
        func_80153228_ovl6(0x3F);
        func_80154858_ovl6();
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153B34.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u16 func_80153B80(s32 arg0) {
    u16 phi_return;

    if ((D_80048F22 & 0x9000) != 0) {
        if ((D_8015A68C & 1) != 0) {
            return func_80153E1C_ovl6(1);
        }
    }
    if ((D_80048F22 & 0x1000) != 0) {
        if ((D_8015A68C & 2) != 0) {
            return func_80153E1C_ovl6(2);
        }
    }
    phi_return = D_80048F22;
    if ((D_80048F22 & 0x4000) != 0) {
        phi_return = D_80048F22;
        if ((D_8015A68C & 0x10) != 0) {
            phi_return = func_80153E1C_ovl6(3);
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153B80.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153C28(void) {
    void *sp1C;

    if (D_8015A690 == 0) {
        if (D_800DE44C != 0) {
            sp1C = D_800DE44C;
            func_80008A18_ovl6(D_800DE44C, &D_80153B34, 1, 3);
            func_8000A904_ovl6(D_800DE44C, 0xC, 0);
            D_800DE44C->unk2C = &D_8015392C;
            if (D_8015A6A0 == 0) {
                D_8015A6A0 = func_8000A180_ovl6(0, &D_80153B80, 0, 0x80000000);
            }
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153C28.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153CBC(void *arg0) {
    D_8015392C_ovl6();
    if (D_8015A558 == arg0->unk3C->unk80->unk98) {
        D_8015A698 = 2;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153CBC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80153D10(void) {
    s32 sp1C;
    s32 temp_t7;
    void *temp_ret;
    void *phi_return;

    phi_return = &D_8004A7C4;
    if (D_8015A690 == 0) {
        temp_t7 = D_8004A7C4;
        D_8004A7C4 = (s32) D_800DE44C;
        sp1C = temp_t7;
        temp_ret = func_800AA018_ovl6(D_8015A560->unk4);
        D_8004A7C4 = sp1C;
        phi_return = temp_ret;
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153D10.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153D6C(void) {
    void *sp1C;

    if (D_8015A690 == 0) {
        sp1C = D_800DE44C;
        func_8000A904_ovl6(D_800DE44C, 0xC, 0);
        D_800DE44C->unk2C = &D_80153CBC;
        func_801548A4_ovl6(D_800DE44C);
        D_8015A698 = 1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153D6C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153DC8(void *arg0) {
    D_8015392C_ovl6();
    if (D_8015A55C == arg0->unk3C->unk80->unk98) {
        D_8015A694 = 1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153DC8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153E1C(s32 arg0) {
    void *sp1C;
    void *sp18;
    void *temp_t2;
    void *temp_t6;

    if (D_800DE44C == 0) {
        temp_t6 = D_8015A560;
        D_8015A560 = &D_80154E48;
        sp18 = temp_t6;
        ((D_80154E48.unk2 * 4) + 0x80150000)->unk4DC0(D_800DE44C);
        temp_t2 = D_8015A560 + 8;
        D_8015A560 = temp_t2;
        ((temp_t2->unk2 * 4) + 0x80150000)->unk4DC0();
        D_8015A560 = temp_t6;
        sp1C = D_800DE44C;
        func_8000A904_ovl6(D_800DE44C, 0xC, 0, &D_800DE44C);
        sp1C->unk2C = &D_80153DC8;
        func_801548A4_ovl6(sp1C);
        D_8015A690 = arg0;
        D_8015A698 = 1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153E1C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80153F00(void) {
    func_800075DC_ovl6(1, D_8015A560->unk6);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153F00.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80153F2C(void) {
    s32 sp34;
    void *sp30;
    s32 sp2C;
    s32 sp24;
    s32 temp_t8;
    s32 temp_v0;
    s32 temp_v0_2;
    s32 temp_v1;
    void *temp_a0;
    void *temp_v0_3;

    sp34 = D_8004A7C4;
    temp_v0 = func_800AEC70_ovl6(0x11, D_8015A560->unk3, D_8015A560->unk3 + 1);
    temp_v1 = temp_v0 * 4;
    temp_t8 = (temp_v1 + 0x800E0000)->unk-1CB0;
    temp_a0 = temp_v1 + 0x800E0000;
    sp2C = temp_v0;
    D_8004A7C4 = temp_t8;
    func_80008DA8_ovl6(temp_a0->unk-1AF0);
    temp_v0_2 = temp_v0 * 4;
    sp24 = temp_v0_2;
    func_80008DA8_ovl6((temp_v0_2 + 0x800E0000)->unk-1930);
    func_80008DA8_ovl6((sp24 + 0x800E0000)->unk-13F0);
    (sp24 + 0x800E0000)->unk2D0 = (s32) D_8015A560->unk4;
    temp_v0_3 = func_800AC954_ovl6(D_8004A7C4, 1, func_800A8C40_ovl6(D_8015A560->unk4));
    sp30 = temp_v0_3;
    temp_v0_3->unk13 = (u8) (temp_v0_3->unk13 | 4);
    func_8000A5FC_ovl6(D_8004A7C4, &D_800AD1A0, 0xE, 0x10, 0xE);
    *(void *)0x8004A7C4 = sp34;
    return temp_v0_3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80153F2C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8015403C(void) {
    func_80153F2C_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015403C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_8015405C(void) {
    void *temp_v0;

    temp_v0 = func_80153F2C_ovl6();
    temp_v0->unk13 = (u8) (temp_v0->unk13 | 2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_8015405C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80154088(void) {
    void *temp_t8;

    temp_t8 = (D_8015A560->unk3 * 4) + 0x800E0000;
    temp_t8->unk-1CB0->unk4C->unk20 = (f32) (u32) ((u32) (D_8015A560->unk4 & 0xFFFF0000) >> 0x10);
    temp_t8->unk-1CB0->unk4C->unk24 = (f32) (u32) (D_8015A560->unk4 & 0xFFFF);
    return temp_t8->unk-1CB0->unk4C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154088.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80154100(void) {
    void *temp_t8;

    temp_t8 = (D_8015A560->unk3 * 4) + 0x800E0000;
    temp_t8->unk-1CB0->unk4C->unk14 = (s8) ((u32) (D_8015A560->unk4 & 0xFF000000) >> 0x18);
    temp_t8->unk-1CB0->unk4C->unk15 = (s8) ((u32) (D_8015A560->unk4 & 0xFF0000) >> 0x10);
    temp_t8->unk-1CB0->unk4C->unk16 = (s8) ((u32) (D_8015A560->unk4 & 0xFF00) >> 8);
    temp_t8->unk-1CB0->unk4C->unk17 = (s8) D_8015A560->unk4;
    return temp_t8->unk-1CB0->unk4C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154100.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80154158(void) {
    void *temp_t6;
    void *temp_v0;

    temp_v0 = D_8015A560;
    D_8015A7C0 = temp_v0;
    temp_t6 = temp_v0->unk4;
    D_8015A560 = temp_t6;
    D_8015A560 = (void *) (temp_t6 - 8);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154158.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154180(void) {
    func_80007C00_ovl6(D_800D799C->unk3C + 8, 0x41200000, 0x41200000, 0x439B0000, 230.0f);
    D_800D7998->unk44 = (s32) (D_800D7998->unk44 & -2);
    func_80153228_ovl6(0x3E);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154180.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801541EC(void) {
    func_8009C0E4_ovl6();
    func_800A2024_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801541EC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80154214(void) {
    D_8015A7B8.unk4 = (s8) ((u32) (D_8015A560->unk4 & 0xFF000000) >> 0x18);
    D_8015A7B8.unk5 = (s8) ((u32) (D_8015A560->unk4 & 0xFF0000) >> 0x10);
    D_8015A7B8.unk6 = (s8) ((u32) (D_8015A560->unk4 & 0xFF00) >> 8);
    return D_8015A560->unk4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154214.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154258(void) {
    D_8015A7B8.unk0 = (s16) ((u32) (D_8015A560->unk4 & 0xFFFF0000) >> 0x10);
    D_8015A7B8.unk2 = (s16) D_8015A560->unk4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154258.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_80154284(void) {
    void *temp_a0;
    void *phi_a0;
    s32 phi_v1;

    if (D_8015A69C != 0) {
        return 0;
    }
    if (*(void *)0x8015A698 == 0) {
        if (D_800DE350 != 0) {
            if (-1 != D_800DFF50) {
                if (((u32) D_800DD8D0 >> 0x1E) == 0) {
                    return 0;
                }
            }
        }
        if (*(void *)0x800DE354 != 0) {
            if (-1 != D_800DFF54) {
                if ((D_800DD8D4 & 0xC0000000) == 0) {
                    return 0;
                }
            }
        }
        phi_a0 = &D_800DE358;
        phi_v1 = 8;
loop_12:
        if (phi_a0->unk0 != 0) {
            if (-1 != *(&D_800DFF50 + phi_v1)) {
                if ((*(&D_800DD8D0 + phi_v1) & 0xC0000000) == 0) {
                    return 0;
                }
            }
        }
        if (phi_a0->unk4 != 0) {
            if (-1 != (&D_800DFF50 + phi_v1)->unk4) {
                if (((&D_800DD8D0 + phi_v1)->unk4 & 0xC0000000) == 0) {
                    return 0;
                }
            }
        }
        if (phi_a0->unk8 != 0) {
            if (-1 != (&D_800DFF50 + phi_v1)->unk8) {
                if (((&D_800DD8D0 + phi_v1)->unk8 & 0xC0000000) == 0) {
                    return 0;
                }
            }
        }
        temp_a0 = phi_a0 + 0x10;
        if (phi_a0->unkC != 0) {
            if (-1 != (&D_800DFF50 + phi_v1)->unkC) {
                if (((&D_800DD8D0 + phi_v1)->unkC & 0xC0000000) == 0) {
                    return 0;
                }
            }
        }
        phi_a0 = temp_a0;
        phi_v1 = phi_v1 + 0x10;
        if (temp_a0 != &D_800DE448) {
            goto loop_12;
        }
    } else {
        if (*(void *)0x8015A698 == 1) {
            return 0;
        }
    }
    return 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154284.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154464(void) {
    s32 temp_s0;
    void *phi_s1;
    s32 phi_s0;

    phi_s1 = &D_800DE350;
    phi_s0 = 0;
loop_1:
    if (*phi_s1 != 0) {
        func_80153228_ovl6(phi_s0);
    }
    temp_s0 = phi_s0 + 1;
    phi_s1 = phi_s1 + 4;
    phi_s0 = temp_s0;
    if (temp_s0 != 0x3E) {
        goto loop_1;
    }
    func_8009C0E4_ovl6();
    func_800A2024_ovl6();
    D_8015A560 = (s32) *D_8015A564;
    func_80154628_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154464.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801544E8(s32 arg0) {
    u8 temp_v0;
    void *temp_t0;
    void *temp_v1;
    void *temp_v1_2;
    void *phi_v1;
    void *phi_v1_2;

    if (0x22 == D_8015A560->unk2) {
        if (*D_8015A564 != 0) {
            if (func_80154284_ovl6() != 0) {
                temp_t0 = D_8015A564 + 4;
                D_8015A564 = temp_t0;
                if (*temp_t0 == 0) {
                    func_800067B8_ovl6();
                    return;
                }
                func_80154464_ovl6();
block_6:
                if (D_8015A568 == D_8015A560->unk0) {
                    phi_v1 = D_8015A560;
loop_8:
                    temp_v0 = phi_v1->unk2;
                    if (0x22 != temp_v0) {
                        *(&D_80154DC0 + (temp_v0 * 4))();
                        temp_v1 = D_8015A560 + 8;
                        D_8015A560 = temp_v1;
                        phi_v1_2 = temp_v1;
                        if (0x22 == temp_v1->unk2) {
                            phi_v1_2 = temp_v1;
                            if (D_8015A7C0 != 0) {
                                temp_v1_2 = D_8015A7C0 + 8;
                                D_8015A560 = temp_v1_2;
                                D_8015A7C0 = 0;
                                phi_v1_2 = temp_v1_2;
                            }
                        }
                        phi_v1 = phi_v1_2;
                        if (D_8015A568 == *phi_v1_2) {
                            goto loop_8;
                        }
block_13:
                        D_8015A568 = (s32) (D_8015A568 + 1);
                    }
                } else {
                    goto block_13;
                }
            }
        }
    } else {
        goto block_6;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801544E8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80154628(void) {
    void *temp_v1;
    void *phi_v1;

    D_8015A56C = 0;
    D_8015A668 = 0;
    D_8015A66C = 0;
    D_8015A574 = 0;
    D_8015A574 = 0;
    phi_v1 = &D_8015A578;
loop_1:
    temp_v1 = phi_v1 + 0x10;
    temp_v1->unk-C = 0;
    temp_v1->unk-8 = 0;
    temp_v1->unk-4 = 0;
    temp_v1->unk-10 = 0;
    phi_v1 = temp_v1;
    if (temp_v1 != &D_8015A668) {
        goto loop_1;
    }
    D_8015A568 = 0;
    D_8015A7C0 = 0;
    *(void *)0x8015A698 = 0;
    return &D_8015A668;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154628.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154690(void) {
    func_800A41B0_ovl6(0x3F800000);
    func_80154628_ovl6();
    func_8000A180_ovl6(1, &D_801544E8, 1, 0x80000000);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154690.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801546D8(void) {
    s32 temp_t5;

    if (D_8015A66C != 0) {
        temp_t5 = (((D_8015A66C->unk3C->unk80->unk58 << 0x18) | (D_8015A66C->unk3C->unk80->unk59 << 0x10)) | (D_8015A66C->unk3C->unk80->unk5A << 8)) | 0xFF;
        D_800D799C->unk3C->unk84 = temp_t5;
    }
    func_80010988_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801546D8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80154748(void) {
    func_800A6BC0_ovl6(2);
    D_800D799C->unk3C->unk80 = (s32) (D_800D799C->unk3C->unk80 | 1);
    D_800D799C->unk3C->unk68->unk4 = (u8)0xC;
    D_800D799C->unk3C->unk80 = (s32) (D_800D799C->unk3C->unk80 | 2);
    if ((D_8015A68C & 8) != 0) {
        D_800D799C->unk3C->unk84 = 0xFF0000FF;
    }
    D_800D799C->unk3C->unk84 = 0xFF;
    func_80008A18_ovl6(D_800D799C, &D_801546D8, 1, 0);
    D_800D7998->unk44 = (s32) (D_800D7998->unk44 | 1);
    return D_800D7998;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154748.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154810(void *arg0) {
    if (D_8015A684 == 0) {
        arg0->unk4C->unk13 = (u8) (arg0->unk4C->unk13 | 8);
        func_80008DA8_ovl6(0);
        D_8015A688 = 0;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154810.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154858(void) {
    if (D_800DE448 != 0) {
        D_8015A684 = 4;
        D_8015A688 = func_80008A18_ovl6(D_800DE448, &D_80154810, 1, 3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154858.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801548A4(void) {
    if (D_800DE448 != 0) {
        if (D_8015A688 != 0) {
            func_80008DA8_ovl6(D_8015A688);
            return;
        }
        D_800DE448->unk4C->unk13 = (u8) (D_800DE448->unk4C->unk13 & 0xFFF7);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801548A4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_801548F8(void) {
    if (D_8015A688 != 0) {
        D_8015A684 = (s32) (D_8015A684 - 1);
    }
    D_800AD1A0_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_801548F8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
f32 func_80154938(void) {
    s32 sp34;
    void *sp30;
    s32 sp2C;
    s32 sp20;
    s32 temp_t6;
    s32 temp_v0;
    s32 temp_v0_2;
    s32 temp_v1;
    void *temp_a0;
    ?32 phi_a0;

    temp_v0 = func_800AEC70_ovl6(0x11, 0x3E, 0x3F);
    temp_v1 = temp_v0 * 4;
    temp_t6 = (temp_v1 + 0x800E0000)->unk-1CB0;
    temp_a0 = temp_v1 + 0x800E0000;
    sp2C = temp_v0;
    sp34 = temp_t6;
    func_80008DA8_ovl6(temp_a0->unk-1AF0);
    temp_v0_2 = temp_v0 * 4;
    sp20 = temp_v0_2;
    func_80008DA8_ovl6((temp_v0_2 + 0x800E0000)->unk-1930);
    func_80008DA8_ovl6((sp20 + 0x800E0000)->unk-13F0);
    if ((D_8015A68C & 4) != 0) {
        phi_a0 = 0x40002;
    } else {
        phi_a0 = 0x40001;
    }
    (sp20 + 0x800E0000)->unk2D0 = phi_a0;
    sp30 = func_800AC954_ovl6(sp34, 0, func_800A8C40_ovl6(phi_a0));
    func_8000A5FC_ovl6(sp34, &D_801548F8, 0x12, 0x10, 0x12);
    sp30->unk20 = 10.0f;
    sp30->unk24 = 10.0f;
    D_8015A688 = 0;
    return 10.0f;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154938.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80154A40(void) {
    u32 temp_v0_3;
    u8 temp_t0;
    void *temp_t1;
    void *temp_v0;
    void *temp_v0_2;
    u8 phi_t0;
    u32 phi_a1;
    s32 phi_a3;
    s32 phi_a2;
    void *phi_v1;
    u8 phi_t0_2;
    void *phi_v0;
    void *phi_a0;
    u32 phi_a1_2;
    u32 phi_a1_3;
    s32 phi_a3_2;
    s32 phi_a3_3;
    s32 phi_a2_2;
    void *phi_v1_2;
    void *phi_v0_2;
    void *phi_a0_2;

    phi_t0 = D_8015A560->unk2;
    phi_a1 = 0U;
    phi_a3 = 0;
    phi_a2 = 0;
    phi_v1 = D_8015A564;
    phi_a0_2 = NULL;
    phi_v0_2 = D_8015A560;
loop_1:
    phi_t0_2 = phi_t0;
    phi_a1_3 = phi_a1;
    phi_a3_3 = phi_a3;
    phi_a2_2 = phi_a2;
    phi_v1_2 = phi_v1;
    if (0x22 != phi_t0) {
block_6:
        phi_t0 = phi_t0_2;
        phi_a1 = phi_a1_3;
        phi_a3 = phi_a3_3;
        phi_a2 = phi_a2_2;
        phi_v1 = phi_v1_2;
        if (0x22 == phi_t0_2) {
            goto loop_1;
        }
        if ((phi_t0_2 != 0x18) && (phi_t0_2 != 0x1F)) {
            if (phi_t0_2 != 0x21) {
                phi_v0 = phi_v0_2;
                phi_a0 = phi_a0_2;
                phi_a3_2 = phi_a3_3;
            } else {
                phi_v0 = phi_v0_2->unk4 - 8;
                phi_a0 = phi_v0_2;
                phi_a3_2 = phi_a3_3;
            }
        } else {
            phi_v0 = phi_v0_2;
            phi_a0 = phi_a0_2;
            phi_a3_2 = phi_a3_3 + 1;
        }
        temp_t0 = phi_v0->unkA;
        temp_v0 = phi_v0 + 8;
        phi_t0 = temp_t0;
        phi_a1 = phi_a1_3;
        phi_a3 = phi_a3_2;
        phi_a2 = phi_a2_2;
        phi_v1 = phi_v1_2;
        phi_a0_2 = phi_a0;
        phi_v0_2 = temp_v0;
        if (0x22 != temp_t0) {
            goto loop_1;
        }
        phi_t0 = temp_t0;
        phi_a1 = phi_a1_3;
        phi_a3 = phi_a3_2;
        phi_a2 = phi_a2_2;
        phi_v1 = phi_v1_2;
        phi_a0_2 = phi_a0;
        phi_v0_2 = temp_v0;
        if (phi_a0 == 0) {
            goto loop_1;
        }
        temp_v0_2 = phi_a0 + 8;
        phi_t0 = temp_v0_2->unk2;
        phi_a1 = phi_a1_3;
        phi_a3 = phi_a3_2;
        phi_a2 = phi_a2_2;
        phi_v1 = phi_v1_2;
        phi_a0_2 = NULL;
        phi_v0_2 = temp_v0_2;
        goto loop_1;
    }
    temp_v0_3 = phi_a3 + phi_a2;
    phi_a1_2 = phi_a1;
    if (phi_a1 < temp_v0_3) {
        phi_a1_2 = temp_v0_3;
    }
    temp_t1 = phi_v1->unk4;
    if (temp_t1 != 0) {
        phi_t0_2 = temp_t1->unk2;
        phi_a1_3 = phi_a1_2;
        phi_a3_3 = 0;
        phi_a2_2 = phi_a3;
        phi_v1_2 = phi_v1 + 4;
        phi_v0_2 = temp_t1;
        goto block_6;
    }
    return phi_a1_2 + 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154A40.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154B14(void) {
    D_8015A694 = 0;
    D_8015A690 = 0;
    D_8015A69C = 0;
    D_8015A6A0 = 0;
    func_80153040_ovl6();
    func_80154690_ovl6();
    func_800AE048_ovl6(func_80154A40_ovl6());
    func_800AE0F0_ovl6();
    func_800A6E64_ovl6();
    func_801512F0_ovl6();
    func_800A8724_ovl6(1);
    func_801513C8_ovl6();
    func_80154748_ovl6();
    func_80154938_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154B14.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154BA0(void *arg0) {
    gSPDisplayList(*arg0++, &D_80154E58);
    if (D_8015A56C != 0) {
        D_8015A670 = (s32) D_8004A3F8.unkC;
        D_8004A3F8.unkC = (s32) (D_8004A3F8.unkC + 0x18);
        func_8015166C_ovl6();
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154BA0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_80154C08(void) {
    func_8000AAE0_ovl6();
    func_80153064_ovl6();
    func_800AC610_ovl6();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154C08.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_80154C38(s32 arg0) {
    void *temp_t7;

    temp_t7 = (arg0 * 4) + 0x80160000;
    D_8015A564 = (void *) temp_t7->unk-5C4C;
    *(void *)0x8015A560 = (s32) *temp_t7->unk-5C4C;
    return &D_8015A564;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154C38.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u32 func_80154C64(void) {
    void *sp1C;
    u32 temp_v0;
    u32 temp_v0_2;
    void *temp_a0;
    void *temp_a0_2;
    void *temp_t6;
    u32 phi_v0;
    u32 phi_v0_2;
    u32 phi_return;

    temp_t6 = &gFrameBuffer + 0xFFFDA800;
    gFrameBuffers.unk0 = temp_t6;
    gFrameBuffers.unk4 = &gFrameBuffer;
    gFrameBuffers.unk8 = &D_803DA800;
    D_80154E80.unk0 = temp_t6;
    D_80154E80.unk4 = &gFrameBuffer;
    D_80154E80.unk8 = &D_803DA800;
    D_80154E80.unkC = (void *) (&D_8012EB00 - 0x1900);
    sp1C = temp_t6;
    func_80007BA4_ovl6(&D_80154E80, &gFrameBuffer);
    D_80154EAC = (s32) (sp1C - &D_8015A7D0);
    if ((D_8015A68C & 8) == 0) {
        temp_a0 = sp1C + 0x6EF00;
        phi_return = (u32) sp1C;
        if ((u32) sp1C < (u32) temp_a0) {
            phi_v0 = (u32) sp1C;
loop_3:
            temp_v0 = phi_v0 + 2;
            temp_v0->unk-2 = (u16)1;
            phi_v0 = temp_v0;
            if (temp_v0 < (u32) temp_a0) {
                goto loop_3;
            }
            return temp_v0;
        }
    } else {
        temp_a0_2 = sp1C + 0x25800;
        phi_return = (u32) sp1C;
        if ((u32) sp1C < (u32) temp_a0_2) {
            phi_v0_2 = (u32) sp1C;
loop_7:
            temp_v0_2 = phi_v0_2 + 2;
            temp_v0_2->unk-2 = (u16)1;
            phi_v0_2 = temp_v0_2;
            phi_return = temp_v0_2;
            if (temp_v0_2 < (u32) temp_a0_2) {
                goto loop_7;
            }
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154C64.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_80154D60(s32 arg0, ?32 arg1) {
    D_8015A68C = arg1;
    func_80005350_ovl6(&D_80151138);
    func_80154C64_ovl6();
    func_80154C38_ovl6(arg0);
    func_80007380_ovl6(&D_80154E9C);
    func_800A74D8_ovl6();
    func_80005350_ovl6(0);
    return D_8015A690;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl6/func_80154D60.s")
#endif
