.include "macros.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches
.set gp=64     # allow use of 64-bit general purpose registers

.section .text

.balign 16

/* Generated by spimdisasm 1.8.2 */
# new file
glabel func_801E44A0_ovl13 # 54
/* 1FC420 801E44A0 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 1FC424 801E44A4 AFB00018 */  sw          $s0, 0x18($sp)
/* 1FC428 801E44A8 3C108005 */  lui         $s0, %hi(D_8004A7C4)
/* 1FC42C 801E44AC 2610A7C4 */  addiu       $s0, $s0, %lo(D_8004A7C4)
/* 1FC430 801E44B0 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FC434 801E44B4 AFBF0024 */  sw          $ra, 0x24($sp)
/* 1FC438 801E44B8 AFB20020 */  sw          $s2, 0x20($sp)
/* 1FC43C 801E44BC AFB1001C */  sw          $s1, 0x1C($sp)
/* 1FC440 801E44C0 AFA40028 */  sw          $a0, 0x28($sp)
/* 1FC444 801E44C4 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FC448 801E44C8 3C02800E */  lui         $v0, %hi(D_800E1B50)
/* 1FC44C 801E44CC 3C01C448 */  lui         $at, (0xC4480000 >> 16)
/* 1FC450 801E44D0 000FC080 */  sll         $t8, $t7, 2
/* 1FC454 801E44D4 00581021 */  addu        $v0, $v0, $t8
/* 1FC458 801E44D8 8C421B50 */  lw          $v0, %lo(D_800E1B50)($v0)
/* 1FC45C 801E44DC 44812000 */  mtc1        $at, $f4
/* 1FC460 801E44E0 3C01800E */  lui         $at, %hi(D_800DEF90)
/* 1FC464 801E44E4 8C590080 */  lw          $t9, 0x80($v0)
/* 1FC468 801E44E8 3C08800B */  lui         $t0, %hi(D_800B6E84)
/* 1FC46C 801E44EC 25086E84 */  addiu       $t0, $t0, %lo(D_800B6E84)
/* 1FC470 801E44F0 E7240018 */  swc1        $f4, 0x18($t9)
/* 1FC474 801E44F4 8E110000 */  lw          $s1, 0x0($s0)
/* 1FC478 801E44F8 3C0B801E */  lui         $t3, %hi(func_801E47B0_ovl13)
/* 1FC47C 801E44FC 256B47B0 */  addiu       $t3, $t3, %lo(func_801E47B0_ovl13)
/* 1FC480 801E4500 8E290000 */  lw          $t1, 0x0($s1)
/* 1FC484 801E4504 3C04801E */  lui         $a0, %hi(func_801E45B8_ovl13)
/* 1FC488 801E4508 248445B8 */  addiu       $a0, $a0, %lo(func_801E45B8_ovl13)
/* 1FC48C 801E450C 00095080 */  sll         $t2, $t1, 2
/* 1FC490 801E4510 002A0821 */  addu        $at, $at, $t2
/* 1FC494 801E4514 AC28EF90 */  sw          $t0, %lo(D_800DEF90)($at)
/* 1FC498 801E4518 8E2C0000 */  lw          $t4, 0x0($s1)
/* 1FC49C 801E451C 3C01800E */  lui         $at, %hi(D_800DF150)
/* 1FC4A0 801E4520 000C6880 */  sll         $t5, $t4, 2
/* 1FC4A4 801E4524 002D0821 */  addu        $at, $at, $t5
/* 1FC4A8 801E4528 0C068354 */  jal         func_801A0D50
/* 1FC4AC 801E452C AC2BF150 */   sw         $t3, %lo(D_800DF150)($at)
/* 1FC4B0 801E4530 8E110000 */  lw          $s1, 0x0($s0)
/* 1FC4B4 801E4534 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FC4B8 801E4538 3C04800E */  lui         $a0, %hi(D_800E7880)
/* 1FC4BC 801E453C 8E2E0000 */  lw          $t6, 0x0($s1)
/* 1FC4C0 801E4540 3C06801E */  lui         $a2, %hi(D_801E5C00_ovl13)
/* 1FC4C4 801E4544 24C65C00 */  addiu       $a2, $a2, %lo(D_801E5C00_ovl13)
/* 1FC4C8 801E4548 000E7880 */  sll         $t7, $t6, 2
/* 1FC4CC 801E454C 002F0821 */  addu        $at, $at, $t7
/* 1FC4D0 801E4550 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FC4D4 801E4554 8E380000 */  lw          $t8, 0x0($s1)
/* 1FC4D8 801E4558 24050001 */  addiu       $a1, $zero, 0x1
/* 1FC4DC 801E455C 00982021 */  addu        $a0, $a0, $t8
/* 1FC4E0 801E4560 0C02911F */  jal         call_virtual_function
/* 1FC4E4 801E4564 90847880 */   lbu        $a0, %lo(D_800E7880)($a0)
/* 1FC4E8 801E4568 3C12801E */  lui         $s2, %hi(D_801E5C04_ovl13)
/* 1FC4EC 801E456C 3C11800E */  lui         $s1, %hi(gEntityVtableIndexArray)
/* 1FC4F0 801E4570 2631DC50 */  addiu       $s1, $s1, %lo(gEntityVtableIndexArray)
/* 1FC4F4 801E4574 26525C04 */  addiu       $s2, $s2, %lo(D_801E5C04_ovl13)
/* 1FC4F8 801E4578 8E190000 */  lw          $t9, 0x0($s0)
glabel L801E457C_ovl13
/* 1FC4FC 801E457C 24050001 */  addiu       $a1, $zero, 0x1
/* 1FC500 801E4580 02403025 */  move        $a2, $s2
/* 1FC504 801E4584 8F290000 */  lw          $t1, 0x0($t9)
/* 1FC508 801E4588 00094080 */  sll         $t0, $t1, 2
/* 1FC50C 801E458C 02285021 */  addu        $t2, $s1, $t0
/* 1FC510 801E4590 0C02911F */  jal         call_virtual_function
/* 1FC514 801E4594 8D440000 */   lw         $a0, 0x0($t2)
/* 1FC518 801E4598 1000FFF8 */  b           L801E457C_ovl13
/* 1FC51C 801E459C 8E190000 */   lw         $t9, 0x0($s0)
/* 1FC520 801E45A0 8FBF0024 */  lw          $ra, 0x24($sp)
/* 1FC524 801E45A4 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FC528 801E45A8 8FB1001C */  lw          $s1, 0x1C($sp)
/* 1FC52C 801E45AC 8FB20020 */  lw          $s2, 0x20($sp)
/* 1FC530 801E45B0 03E00008 */  jr          $ra
/* 1FC534 801E45B4 27BD0028 */   addiu      $sp, $sp, 0x28
.size func_801E44A0_ovl13, . - func_801E44A0_ovl13

glabel func_801E45B8_ovl13 # 55
/* 1FC538 801E45B8 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 1FC53C 801E45BC AFB20020 */  sw          $s2, 0x20($sp)
/* 1FC540 801E45C0 AFB1001C */  sw          $s1, 0x1C($sp)
/* 1FC544 801E45C4 AFB00018 */  sw          $s0, 0x18($sp)
/* 1FC548 801E45C8 3C10800E */  lui         $s0, %hi(gEntityVtableIndexArray)
/* 1FC54C 801E45CC 3C118005 */  lui         $s1, %hi(D_8004A7C4)
/* 1FC550 801E45D0 3C12801E */  lui         $s2, %hi(D_801E5C04_ovl13)
/* 1FC554 801E45D4 AFBF0024 */  sw          $ra, 0x24($sp)
/* 1FC558 801E45D8 AFA40028 */  sw          $a0, 0x28($sp)
/* 1FC55C 801E45DC 26525C04 */  addiu       $s2, $s2, %lo(D_801E5C04_ovl13)
/* 1FC560 801E45E0 2631A7C4 */  addiu       $s1, $s1, %lo(D_8004A7C4)
/* 1FC564 801E45E4 2610DC50 */  addiu       $s0, $s0, %lo(gEntityVtableIndexArray)
/* 1FC568 801E45E8 8E2E0000 */  lw          $t6, 0x0($s1)
glabel L801E45EC_ovl13
/* 1FC56C 801E45EC 24050001 */  addiu       $a1, $zero, 0x1
/* 1FC570 801E45F0 02403025 */  move        $a2, $s2
/* 1FC574 801E45F4 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FC578 801E45F8 000FC080 */  sll         $t8, $t7, 2
/* 1FC57C 801E45FC 0218C821 */  addu        $t9, $s0, $t8
/* 1FC580 801E4600 0C02911F */  jal         call_virtual_function
/* 1FC584 801E4604 8F240000 */   lw         $a0, 0x0($t9)
/* 1FC588 801E4608 1000FFF8 */  b           L801E45EC_ovl13
/* 1FC58C 801E460C 8E2E0000 */   lw         $t6, 0x0($s1)
/* 1FC590 801E4610 00000000 */  nop
/* 1FC594 801E4614 00000000 */  nop
/* 1FC598 801E4618 00000000 */  nop
/* 1FC59C 801E461C 00000000 */  nop
/* 1FC5A0 801E4620 8FBF0024 */  lw          $ra, 0x24($sp)
/* 1FC5A4 801E4624 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FC5A8 801E4628 8FB1001C */  lw          $s1, 0x1C($sp)
/* 1FC5AC 801E462C 8FB20020 */  lw          $s2, 0x20($sp)
/* 1FC5B0 801E4630 03E00008 */  jr          $ra
/* 1FC5B4 801E4634 27BD0028 */   addiu      $sp, $sp, 0x28
.size func_801E45B8_ovl13, . - func_801E45B8_ovl13

glabel func_801E4638_ovl13 # 56
/* 1FC5B8 801E4638 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 1FC5BC 801E463C AFB00018 */  sw          $s0, 0x18($sp)
/* 1FC5C0 801E4640 3C108005 */  lui         $s0, %hi(D_8004A7C4)
/* 1FC5C4 801E4644 2610A7C4 */  addiu       $s0, $s0, %lo(D_8004A7C4)
/* 1FC5C8 801E4648 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FC5CC 801E464C AFBF001C */  sw          $ra, 0x1C($sp)
/* 1FC5D0 801E4650 AFA40020 */  sw          $a0, 0x20($sp)
/* 1FC5D4 801E4654 24040070 */  addiu       $a0, $zero, 0x70
/* 1FC5D8 801E4658 0C02C67D */  jal         func_800B19F4
/* 1FC5DC 801E465C 8DC50000 */   lw         $a1, 0x0($t6)
/* 1FC5E0 801E4660 00002025 */  move        $a0, $zero
/* 1FC5E4 801E4664 0C02BEED */  jal         func_800AFBB4
/* 1FC5E8 801E4668 8E050000 */   lw         $a1, 0x0($s0)
/* 1FC5EC 801E466C 0C002DAF */  jal         finish_current_thread
/* 1FC5F0 801E4670 24040004 */   addiu      $a0, $zero, 0x4
/* 1FC5F4 801E4674 8E0F0000 */  lw          $t7, 0x0($s0)
/* 1FC5F8 801E4678 24040030 */  addiu       $a0, $zero, 0x30
/* 1FC5FC 801E467C 0C02C67D */  jal         func_800B19F4
/* 1FC600 801E4680 8DE50000 */   lw         $a1, 0x0($t7)
/* 1FC604 801E4684 24040001 */  addiu       $a0, $zero, 0x1
/* 1FC608 801E4688 0C02BEED */  jal         func_800AFBB4
/* 1FC60C 801E468C 8E050000 */   lw         $a1, 0x0($s0)
/* 1FC610 801E4690 8E030000 */  lw          $v1, 0x0($s0)
/* 1FC614 801E4694 3C07800E */  lui         $a3, %hi(D_800E0D50)
/* 1FC618 801E4698 24E70D50 */  addiu       $a3, $a3, %lo(D_800E0D50)
/* 1FC61C 801E469C 8C620000 */  lw          $v0, 0x0($v1)
/* 1FC620 801E46A0 3C08800E */  lui         $t0, %hi(D_800E6A10)
/* 1FC624 801E46A4 25086A10 */  addiu       $t0, $t0, %lo(D_800E6A10)
/* 1FC628 801E46A8 00021080 */  sll         $v0, $v0, 2
/* 1FC62C 801E46AC 00E2C021 */  addu        $t8, $a3, $v0
/* 1FC630 801E46B0 8F190000 */  lw          $t9, 0x0($t8)
/* 1FC634 801E46B4 01027021 */  addu        $t6, $t0, $v0
/* 1FC638 801E46B8 3C09800E */  lui         $t1, %hi(D_800E5F90)
/* 1FC63C 801E46BC 00196080 */  sll         $t4, $t9, 2
/* 1FC640 801E46C0 010C6821 */  addu        $t5, $t0, $t4
/* 1FC644 801E46C4 C5A40000 */  lwc1        $f4, 0x0($t5)
/* 1FC648 801E46C8 25295F90 */  addiu       $t1, $t1, %lo(D_800E5F90)
/* 1FC64C 801E46CC 3C0A800E */  lui         $t2, %hi(D_800E6BD0)
/* 1FC650 801E46D0 E5C40000 */  swc1        $f4, 0x0($t6)
/* 1FC654 801E46D4 8C620000 */  lw          $v0, 0x0($v1)
/* 1FC658 801E46D8 254A6BD0 */  addiu       $t2, $t2, %lo(D_800E6BD0)
/* 1FC65C 801E46DC 3C0B800E */  lui         $t3, %hi(gEntitiesNextPosYArray)
/* 1FC660 801E46E0 00021080 */  sll         $v0, $v0, 2
/* 1FC664 801E46E4 00E27821 */  addu        $t7, $a3, $v0
/* 1FC668 801E46E8 8DF80000 */  lw          $t8, 0x0($t7)
/* 1FC66C 801E46EC 01227021 */  addu        $t6, $t1, $v0
/* 1FC670 801E46F0 256B2790 */  addiu       $t3, $t3, %lo(gEntitiesNextPosYArray)
/* 1FC674 801E46F4 0018C880 */  sll         $t9, $t8, 2
/* 1FC678 801E46F8 01396021 */  addu        $t4, $t1, $t9
/* 1FC67C 801E46FC 8D8D0000 */  lw          $t5, 0x0($t4)
/* 1FC680 801E4700 3C0141A0 */  lui         $at, (0x41A00000 >> 16)
/* 1FC684 801E4704 44815000 */  mtc1        $at, $f10
/* 1FC688 801E4708 ADCD0000 */  sw          $t5, 0x0($t6)
/* 1FC68C 801E470C 8C620000 */  lw          $v0, 0x0($v1)
/* 1FC690 801E4710 3C014220 */  lui         $at, (0x42200000 >> 16)
/* 1FC694 801E4714 44812000 */  mtc1        $at, $f4
/* 1FC698 801E4718 00021080 */  sll         $v0, $v0, 2
/* 1FC69C 801E471C 00E27821 */  addu        $t7, $a3, $v0
/* 1FC6A0 801E4720 8DF80000 */  lw          $t8, 0x0($t7)
/* 1FC6A4 801E4724 01426821 */  addu        $t5, $t2, $v0
/* 1FC6A8 801E4728 0018C880 */  sll         $t9, $t8, 2
/* 1FC6AC 801E472C 01596021 */  addu        $t4, $t2, $t9
/* 1FC6B0 801E4730 C5860000 */  lwc1        $f6, 0x0($t4)
/* 1FC6B4 801E4734 E5A60000 */  swc1        $f6, 0x0($t5)
/* 1FC6B8 801E4738 8C620000 */  lw          $v0, 0x0($v1)
/* 1FC6BC 801E473C 00021080 */  sll         $v0, $v0, 2
/* 1FC6C0 801E4740 00E27021 */  addu        $t6, $a3, $v0
/* 1FC6C4 801E4744 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FC6C8 801E4748 01626021 */  addu        $t4, $t3, $v0
/* 1FC6CC 801E474C 000FC080 */  sll         $t8, $t7, 2
/* 1FC6D0 801E4750 0178C821 */  addu        $t9, $t3, $t8
/* 1FC6D4 801E4754 C7280000 */  lwc1        $f8, 0x0($t9)
/* 1FC6D8 801E4758 460A4401 */  sub.s       $f16, $f8, $f10
/* 1FC6DC 801E475C E5900000 */  swc1        $f16, 0x0($t4)
/* 1FC6E0 801E4760 8C620000 */  lw          $v0, 0x0($v1)
/* 1FC6E4 801E4764 00021080 */  sll         $v0, $v0, 2
/* 1FC6E8 801E4768 01026821 */  addu        $t5, $t0, $v0
/* 1FC6EC 801E476C C5B20000 */  lwc1        $f18, 0x0($t5)
/* 1FC6F0 801E4770 01222021 */  addu        $a0, $t1, $v0
/* 1FC6F4 801E4774 01422821 */  addu        $a1, $t2, $v0
/* 1FC6F8 801E4778 46049182 */  mul.s       $f6, $f18, $f4
/* 1FC6FC 801E477C 44063000 */  mfc1        $a2, $f6
/* 1FC700 801E4780 0C03E65D */  jal         func_800F9974
/* 1FC704 801E4784 00000000 */   nop
/* 1FC708 801E4788 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FC70C 801E478C 8FBF001C */  lw          $ra, 0x1C($sp)
/* 1FC710 801E4790 3C01800E */  lui         $at, %hi(gEntityVtableIndexArray)
/* 1FC714 801E4794 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FC718 801E4798 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FC71C 801E479C 27BD0020 */  addiu       $sp, $sp, 0x20
/* 1FC720 801E47A0 000FC080 */  sll         $t8, $t7, 2
/* 1FC724 801E47A4 00380821 */  addu        $at, $at, $t8
/* 1FC728 801E47A8 03E00008 */  jr          $ra
/* 1FC72C 801E47AC AC20DC50 */   sw         $zero, %lo(gEntityVtableIndexArray)($at)
.size func_801E4638_ovl13, . - func_801E4638_ovl13

glabel func_801E47B0_ovl13 # 57
/* 1FC730 801E47B0 3C0E8005 */  lui         $t6, %hi(D_8004A7C4)
/* 1FC734 801E47B4 8DCEA7C4 */  lw          $t6, %lo(D_8004A7C4)($t6)
/* 1FC738 801E47B8 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FC73C 801E47BC AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FC740 801E47C0 AFA40018 */  sw          $a0, 0x18($sp)
/* 1FC744 801E47C4 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FC748 801E47C8 3C04800E */  lui         $a0, %hi(D_800DDFD0)
/* 1FC74C 801E47CC 3C06801E */  lui         $a2, %hi(D_801E5C08_ovl13)
/* 1FC750 801E47D0 000FC080 */  sll         $t8, $t7, 2
/* 1FC754 801E47D4 00982021 */  addu        $a0, $a0, $t8
/* 1FC758 801E47D8 8C84DFD0 */  lw          $a0, %lo(D_800DDFD0)($a0)
/* 1FC75C 801E47DC 24C65C08 */  addiu       $a2, $a2, %lo(D_801E5C08_ovl13)
/* 1FC760 801E47E0 0C02911F */  jal         call_virtual_function
/* 1FC764 801E47E4 24050001 */   addiu      $a1, $zero, 0x1
/* 1FC768 801E47E8 8FBF0014 */  lw          $ra, 0x14($sp)
/* 1FC76C 801E47EC 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FC770 801E47F0 03E00008 */  jr          $ra
/* 1FC774 801E47F4 00000000 */   nop
.size func_801E47B0_ovl13, . - func_801E47B0_ovl13

glabel func_801E47F8_ovl13 # 58
/* 1FC778 801E47F8 27BDFFB8 */  addiu       $sp, $sp, -0x48
/* 1FC77C 801E47FC AFB2003C */  sw          $s2, 0x3C($sp)
/* 1FC780 801E4800 3C128005 */  lui         $s2, %hi(D_8004A7C4)
/* 1FC784 801E4804 2652A7C4 */  addiu       $s2, $s2, %lo(D_8004A7C4)
/* 1FC788 801E4808 8E420000 */  lw          $v0, 0x0($s2)
/* 1FC78C 801E480C AFBF0044 */  sw          $ra, 0x44($sp)
/* 1FC790 801E4810 AFB30040 */  sw          $s3, 0x40($sp)
/* 1FC794 801E4814 AFB10038 */  sw          $s1, 0x38($sp)
/* 1FC798 801E4818 AFB00034 */  sw          $s0, 0x34($sp)
/* 1FC79C 801E481C F7BA0028 */  sdc1        $f26, 0x28($sp)
/* 1FC7A0 801E4820 F7B80020 */  sdc1        $f24, 0x20($sp)
/* 1FC7A4 801E4824 F7B60018 */  sdc1        $f22, 0x18($sp)
/* 1FC7A8 801E4828 F7B40010 */  sdc1        $f20, 0x10($sp)
/* 1FC7AC 801E482C AFA40048 */  sw          $a0, 0x48($sp)
/* 1FC7B0 801E4830 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FC7B4 801E4834 3C014080 */  lui         $at, (0x40800000 >> 16)
/* 1FC7B8 801E4838 4481A000 */  mtc1        $at, $f20
/* 1FC7BC 801E483C 3C01800E */  lui         $at, %hi(D_800DDFD0)
/* 1FC7C0 801E4840 000E7880 */  sll         $t7, $t6, 2
/* 1FC7C4 801E4844 002F0821 */  addu        $at, $at, $t7
/* 1FC7C8 801E4848 AC20DFD0 */  sw          $zero, %lo(D_800DDFD0)($at)
/* 1FC7CC 801E484C 8C590000 */  lw          $t9, 0x0($v0)
/* 1FC7D0 801E4850 3C11800E */  lui         $s1, %hi(D_800E1B50)
/* 1FC7D4 801E4854 26311B50 */  addiu       $s1, $s1, %lo(D_800E1B50)
/* 1FC7D8 801E4858 00194080 */  sll         $t0, $t9, 2
/* 1FC7DC 801E485C 02284821 */  addu        $t1, $s1, $t0
/* 1FC7E0 801E4860 8D2A0000 */  lw          $t2, 0x0($t1)
/* 1FC7E4 801E4864 3C18801E */  lui         $t8, %hi(D_801DAD20)
/* 1FC7E8 801E4868 3C10800D */  lui         $s0, %hi(D_800D6B10)
/* 1FC7EC 801E486C 2718AD20 */  addiu       $t8, $t8, %lo(D_801DAD20)
/* 1FC7F0 801E4870 26106B10 */  addiu       $s0, $s0, %lo(D_800D6B10)
/* 1FC7F4 801E4874 AD580098 */  sw          $t8, 0x98($t2)
/* 1FC7F8 801E4878 C6040000 */  lwc1        $f4, 0x0($s0)
/* 1FC7FC 801E487C 46142302 */  mul.s       $f12, $f4, $f20
/* 1FC800 801E4880 0C02BB30 */  jal         func_800AECC0
/* 1FC804 801E4884 00000000 */   nop
/* 1FC808 801E4888 C6060000 */  lwc1        $f6, 0x0($s0)
/* 1FC80C 801E488C 46143302 */  mul.s       $f12, $f6, $f20
/* 1FC810 801E4890 0C02BB48 */  jal         func_800AED20
/* 1FC814 801E4894 00000000 */   nop
/* 1FC818 801E4898 0C02CCFD */  jal         func_800B33F4
/* 1FC81C 801E489C 00000000 */   nop
/* 1FC820 801E48A0 8E420000 */  lw          $v0, 0x0($s2)
/* 1FC824 801E48A4 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FC828 801E48A8 240DFFFF */  addiu       $t5, $zero, -0x1
/* 1FC82C 801E48AC 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FC830 801E48B0 3C10800F */  lui         $s0, %hi(D_800E9AA0)
/* 1FC834 801E48B4 26109AA0 */  addiu       $s0, $s0, %lo(D_800E9AA0)
/* 1FC838 801E48B8 000B6080 */  sll         $t4, $t3, 2
/* 1FC83C 801E48BC 002C0821 */  addu        $at, $at, $t4
/* 1FC840 801E48C0 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FC844 801E48C4 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FC848 801E48C8 3C01800F */  lui         $at, %hi(D_800E98E0)
/* 1FC84C 801E48CC 240A00F0 */  addiu       $t2, $zero, 0xF0
/* 1FC850 801E48D0 000E7880 */  sll         $t7, $t6, 2
/* 1FC854 801E48D4 022FC821 */  addu        $t9, $s1, $t7
/* 1FC858 801E48D8 8F280000 */  lw          $t0, 0x0($t9)
/* 1FC85C 801E48DC 3C040001 */  lui         $a0, (0x10158 >> 16)
/* 1FC860 801E48E0 34840158 */  ori         $a0, $a0, (0x10158 & 0xFFFF)
/* 1FC864 801E48E4 A10D0039 */  sb          $t5, 0x39($t0)
/* 1FC868 801E48E8 8E420000 */  lw          $v0, 0x0($s2)
/* 1FC86C 801E48EC 8C490000 */  lw          $t1, 0x0($v0)
/* 1FC870 801E48F0 0009C080 */  sll         $t8, $t1, 2
/* 1FC874 801E48F4 00380821 */  addu        $at, $at, $t8
/* 1FC878 801E48F8 AC2098E0 */  sw          $zero, %lo(D_800E98E0)($at)
/* 1FC87C 801E48FC 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FC880 801E4900 000B6080 */  sll         $t4, $t3, 2
/* 1FC884 801E4904 020C7021 */  addu        $t6, $s0, $t4
/* 1FC888 801E4908 0C02A806 */  jal         func_800AA018
/* 1FC88C 801E490C ADCA0000 */   sw         $t2, 0x0($t6)
/* 1FC890 801E4910 3C040001 */  lui         $a0, (0x10159 >> 16)
/* 1FC894 801E4914 0C02A806 */  jal         func_800AA018
/* 1FC898 801E4918 34840159 */   ori        $a0, $a0, (0x10159 & 0xFFFF)
/* 1FC89C 801E491C 8E4F0000 */  lw          $t7, 0x0($s2)
/* 1FC8A0 801E4920 3C01800E */  lui         $at, %hi(D_800E6A10)
/* 1FC8A4 801E4924 24040008 */  addiu       $a0, $zero, 0x8
/* 1FC8A8 801E4928 8DE30000 */  lw          $v1, 0x0($t7)
/* 1FC8AC 801E492C 00031880 */  sll         $v1, $v1, 2
/* 1FC8B0 801E4930 00230821 */  addu        $at, $at, $v1
/* 1FC8B4 801E4934 C4286A10 */  lwc1        $f8, %lo(D_800E6A10)($at)
/* 1FC8B8 801E4938 3C0140C0 */  lui         $at, (0x40C00000 >> 16)
/* 1FC8BC 801E493C 44815000 */  mtc1        $at, $f10
/* 1FC8C0 801E4940 3C01800E */  lui         $at, %hi(D_800E64D0)
/* 1FC8C4 801E4944 00230821 */  addu        $at, $at, $v1
/* 1FC8C8 801E4948 460A4402 */  mul.s       $f16, $f8, $f10
/* 1FC8CC 801E494C 0C002DAF */  jal         finish_current_thread
/* 1FC8D0 801E4950 E43064D0 */   swc1       $f16, %lo(D_800E64D0)($at)
/* 1FC8D4 801E4954 8E420000 */  lw          $v0, 0x0($s2)
/* 1FC8D8 801E4958 3C014100 */  lui         $at, (0x41000000 >> 16)
/* 1FC8DC 801E495C 4481D000 */  mtc1        $at, $f26
/* 1FC8E0 801E4960 8C590000 */  lw          $t9, 0x0($v0)
/* 1FC8E4 801E4964 3C11800E */  lui         $s1, %hi(D_800E3210)
/* 1FC8E8 801E4968 26313210 */  addiu       $s1, $s1, %lo(D_800E3210)
/* 1FC8EC 801E496C 00196880 */  sll         $t5, $t9, 2
/* 1FC8F0 801E4970 022D4021 */  addu        $t0, $s1, $t5
/* 1FC8F4 801E4974 E51A0000 */  swc1        $f26, 0x0($t0)
/* 1FC8F8 801E4978 8C490000 */  lw          $t1, 0x0($v0)
/* 1FC8FC 801E497C 3C01801E */  lui         $at, %hi(D_801E5E20_ovl13)
/* 1FC900 801E4980 C4325E20 */  lwc1        $f18, %lo(D_801E5E20_ovl13)($at)
/* 1FC904 801E4984 3C13800E */  lui         $s3, %hi(D_800E3750)
/* 1FC908 801E4988 26733750 */  addiu       $s3, $s3, %lo(D_800E3750)
/* 1FC90C 801E498C 0009C080 */  sll         $t8, $t1, 2
/* 1FC910 801E4990 02785821 */  addu        $t3, $s3, $t8
/* 1FC914 801E4994 E5720000 */  swc1        $f18, 0x0($t3)
/* 1FC918 801E4998 8C4C0000 */  lw          $t4, 0x0($v0)
/* 1FC91C 801E499C 3C014120 */  lui         $at, (0x41200000 >> 16)
/* 1FC920 801E49A0 44812000 */  mtc1        $at, $f4
/* 1FC924 801E49A4 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FC928 801E49A8 000C5080 */  sll         $t2, $t4, 2
/* 1FC92C 801E49AC 002A0821 */  addu        $at, $at, $t2
/* 1FC930 801E49B0 E4243C90 */  swc1        $f4, %lo(D_800E3C90)($at)
/* 1FC934 801E49B4 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FC938 801E49B8 3C01C100 */  lui         $at, (0xC1000000 >> 16)
/* 1FC93C 801E49BC 000E7880 */  sll         $t7, $t6, 2
/* 1FC940 801E49C0 020F2021 */  addu        $a0, $s0, $t7
/* 1FC944 801E49C4 8C990000 */  lw          $t9, 0x0($a0)
/* 1FC948 801E49C8 272DFFFF */  addiu       $t5, $t9, -0x1
/* 1FC94C 801E49CC AC8D0000 */  sw          $t5, 0x0($a0)
/* 1FC950 801E49D0 8C430000 */  lw          $v1, 0x0($v0)
/* 1FC954 801E49D4 00031880 */  sll         $v1, $v1, 2
/* 1FC958 801E49D8 02034021 */  addu        $t0, $s0, $v1
/* 1FC95C 801E49DC 8D090000 */  lw          $t1, 0x0($t0)
/* 1FC960 801E49E0 19200039 */  blez        $t1, L801E4AC8_ovl13
/* 1FC964 801E49E4 00000000 */   nop
/* 1FC968 801E49E8 4481C000 */  mtc1        $at, $f24
/* 1FC96C 801E49EC 4480B000 */  mtc1        $zero, $f22
/* 1FC970 801E49F0 4480A000 */  mtc1        $zero, $f20
/* 1FC974 801E49F4 00000000 */  nop
/* 1FC978 801E49F8 02631021 */  addu        $v0, $s3, $v1
glabel L801E49FC_ovl13
/* 1FC97C 801E49FC C4400000 */  lwc1        $f0, 0x0($v0)
/* 1FC980 801E4A00 0223C021 */  addu        $t8, $s1, $v1
/* 1FC984 801E4A04 02235821 */  addu        $t3, $s1, $v1
/* 1FC988 801E4A08 4616003C */  c.lt.s      $f0, $f22
/* 1FC98C 801E4A0C 00000000 */  nop
/* 1FC990 801E4A10 45020010 */  bc1fl       L801E4A54_ovl13
/* 1FC994 801E4A14 C56A0000 */   lwc1       $f10, 0x0($t3)
/* 1FC998 801E4A18 C7060000 */  lwc1        $f6, 0x0($t8)
/* 1FC99C 801E4A1C 4618303C */  c.lt.s      $f6, $f24
/* 1FC9A0 801E4A20 00000000 */  nop
/* 1FC9A4 801E4A24 45000019 */  bc1f        L801E4A8C_ovl13
/* 1FC9A8 801E4A28 00000000 */   nop
/* 1FC9AC 801E4A2C 4614003C */  c.lt.s      $f0, $f20
/* 1FC9B0 801E4A30 00000000 */  nop
/* 1FC9B4 801E4A34 45000004 */  bc1f        L801E4A48_ovl13
/* 1FC9B8 801E4A38 00000000 */   nop
/* 1FC9BC 801E4A3C 46000207 */  neg.s       $f8, $f0
/* 1FC9C0 801E4A40 10000012 */  b           L801E4A8C_ovl13
/* 1FC9C4 801E4A44 E4480000 */   swc1       $f8, 0x0($v0)
glabel L801E4A48_ovl13
/* 1FC9C8 801E4A48 10000010 */  b           L801E4A8C_ovl13
/* 1FC9CC 801E4A4C E4400000 */   swc1       $f0, 0x0($v0)
/* 1FC9D0 801E4A50 C56A0000 */  lwc1        $f10, 0x0($t3)
glabel L801E4A54_ovl13
/* 1FC9D4 801E4A54 460AD03C */  c.lt.s      $f26, $f10
/* 1FC9D8 801E4A58 00000000 */  nop
/* 1FC9DC 801E4A5C 4500000B */  bc1f        L801E4A8C_ovl13
/* 1FC9E0 801E4A60 00000000 */   nop
/* 1FC9E4 801E4A64 4614003C */  c.lt.s      $f0, $f20
/* 1FC9E8 801E4A68 00000000 */  nop
/* 1FC9EC 801E4A6C 45020006 */  bc1fl       L801E4A88_ovl13
/* 1FC9F0 801E4A70 46000107 */   neg.s      $f4, $f0
/* 1FC9F4 801E4A74 46000407 */  neg.s       $f16, $f0
/* 1FC9F8 801E4A78 46008487 */  neg.s       $f18, $f16
/* 1FC9FC 801E4A7C 10000003 */  b           L801E4A8C_ovl13
/* 1FCA00 801E4A80 E4520000 */   swc1       $f18, 0x0($v0)
/* 1FCA04 801E4A84 46000107 */  neg.s       $f4, $f0
glabel L801E4A88_ovl13
/* 1FCA08 801E4A88 E4440000 */  swc1        $f4, 0x0($v0)
glabel L801E4A8C_ovl13
/* 1FCA0C 801E4A8C 0C002DAF */  jal         finish_current_thread
/* 1FCA10 801E4A90 24040001 */   addiu      $a0, $zero, 0x1
/* 1FCA14 801E4A94 8E420000 */  lw          $v0, 0x0($s2)
/* 1FCA18 801E4A98 8C4C0000 */  lw          $t4, 0x0($v0)
/* 1FCA1C 801E4A9C 000C5080 */  sll         $t2, $t4, 2
/* 1FCA20 801E4AA0 020A2021 */  addu        $a0, $s0, $t2
/* 1FCA24 801E4AA4 8C8E0000 */  lw          $t6, 0x0($a0)
/* 1FCA28 801E4AA8 25CFFFFF */  addiu       $t7, $t6, -0x1
/* 1FCA2C 801E4AAC AC8F0000 */  sw          $t7, 0x0($a0)
/* 1FCA30 801E4AB0 8C430000 */  lw          $v1, 0x0($v0)
/* 1FCA34 801E4AB4 00031880 */  sll         $v1, $v1, 2
/* 1FCA38 801E4AB8 0203C821 */  addu        $t9, $s0, $v1
/* 1FCA3C 801E4ABC 8F2D0000 */  lw          $t5, 0x0($t9)
/* 1FCA40 801E4AC0 5DA0FFCE */  bgtzl       $t5, L801E49FC_ovl13
/* 1FCA44 801E4AC4 02631021 */   addu       $v0, $s3, $v1
glabel L801E4AC8_ovl13
/* 1FCA48 801E4AC8 3C01800E */  lui         $at, %hi(gEntityVtableIndexArray)
/* 1FCA4C 801E4ACC 00230821 */  addu        $at, $at, $v1
/* 1FCA50 801E4AD0 2408FFFF */  addiu       $t0, $zero, -0x1
/* 1FCA54 801E4AD4 AC28DC50 */  sw          $t0, %lo(gEntityVtableIndexArray)($at)
/* 1FCA58 801E4AD8 0C068FA0 */  jal         func_801A3E80
/* 1FCA5C 801E4ADC 8FA40048 */   lw         $a0, 0x48($sp)
/* 1FCA60 801E4AE0 8FBF0044 */  lw          $ra, 0x44($sp)
/* 1FCA64 801E4AE4 D7B40010 */  ldc1        $f20, 0x10($sp)
/* 1FCA68 801E4AE8 D7B60018 */  ldc1        $f22, 0x18($sp)
/* 1FCA6C 801E4AEC D7B80020 */  ldc1        $f24, 0x20($sp)
/* 1FCA70 801E4AF0 D7BA0028 */  ldc1        $f26, 0x28($sp)
/* 1FCA74 801E4AF4 8FB00034 */  lw          $s0, 0x34($sp)
/* 1FCA78 801E4AF8 8FB10038 */  lw          $s1, 0x38($sp)
/* 1FCA7C 801E4AFC 8FB2003C */  lw          $s2, 0x3C($sp)
/* 1FCA80 801E4B00 8FB30040 */  lw          $s3, 0x40($sp)
/* 1FCA84 801E4B04 03E00008 */  jr          $ra
/* 1FCA88 801E4B08 27BD0048 */   addiu      $sp, $sp, 0x48
.size func_801E47F8_ovl13, . - func_801E47F8_ovl13

glabel func_801E4B0C_ovl13 # 59
/* 1FCA8C 801E4B0C 3C038005 */  lui         $v1, %hi(D_8004A7C4)
/* 1FCA90 801E4B10 8C63A7C4 */  lw          $v1, %lo(D_8004A7C4)($v1)
/* 1FCA94 801E4B14 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FCA98 801E4B18 AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FCA9C 801E4B1C AFA40018 */  sw          $a0, 0x18($sp)
/* 1FCAA0 801E4B20 8C6E0000 */  lw          $t6, 0x0($v1)
/* 1FCAA4 801E4B24 3C05800F */  lui         $a1, %hi(D_800E98E0)
/* 1FCAA8 801E4B28 24A598E0 */  addiu       $a1, $a1, %lo(D_800E98E0)
/* 1FCAAC 801E4B2C 000E7880 */  sll         $t7, $t6, 2
/* 1FCAB0 801E4B30 00AF1021 */  addu        $v0, $a1, $t7
/* 1FCAB4 801E4B34 8C580000 */  lw          $t8, 0x0($v0)
/* 1FCAB8 801E4B38 24010006 */  addiu       $at, $zero, 0x6
/* 1FCABC 801E4B3C 3C0F800E */  lui         $t7, %hi(D_800DFBD0)
/* 1FCAC0 801E4B40 27190001 */  addiu       $t9, $t8, 0x1
/* 1FCAC4 801E4B44 AC590000 */  sw          $t9, 0x0($v0)
/* 1FCAC8 801E4B48 8C690000 */  lw          $t1, 0x0($v1)
/* 1FCACC 801E4B4C 24040006 */  addiu       $a0, $zero, 0x6
/* 1FCAD0 801E4B50 00095080 */  sll         $t2, $t1, 2
/* 1FCAD4 801E4B54 00AA1021 */  addu        $v0, $a1, $t2
/* 1FCAD8 801E4B58 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FCADC 801E4B5C 0161001A */  div         $zero, $t3, $at
/* 1FCAE0 801E4B60 00006010 */  mfhi        $t4
/* 1FCAE4 801E4B64 AC4C0000 */  sw          $t4, 0x0($v0)
/* 1FCAE8 801E4B68 8C680000 */  lw          $t0, 0x0($v1)
/* 1FCAEC 801E4B6C 00084080 */  sll         $t0, $t0, 2
/* 1FCAF0 801E4B70 00A86821 */  addu        $t5, $a1, $t0
/* 1FCAF4 801E4B74 8DAE0000 */  lw          $t6, 0x0($t5)
/* 1FCAF8 801E4B78 24050002 */  addiu       $a1, $zero, 0x2
/* 1FCAFC 801E4B7C 01E87821 */  addu        $t7, $t7, $t0
/* 1FCB00 801E4B80 15C00009 */  bnez        $t6, L801E4BA8_ovl13
/* 1FCB04 801E4B84 00000000 */   nop
/* 1FCB08 801E4B88 8DEFFBD0 */  lw          $t7, %lo(D_800DFBD0)($t7)
/* 1FCB0C 801E4B8C 00003025 */  move        $a2, $zero
/* 1FCB10 801E4B90 0C02A040 */  jal         func_800A8100
/* 1FCB14 801E4B94 8DE70000 */   lw         $a3, 0x0($t7)
/* 1FCB18 801E4B98 3C038005 */  lui         $v1, %hi(D_8004A7C4)
/* 1FCB1C 801E4B9C 8C63A7C4 */  lw          $v1, %lo(D_8004A7C4)($v1)
/* 1FCB20 801E4BA0 8C680000 */  lw          $t0, 0x0($v1)
/* 1FCB24 801E4BA4 00084080 */  sll         $t0, $t0, 2
glabel L801E4BA8_ovl13
/* 1FCB28 801E4BA8 3C18800E */  lui         $t8, %hi(gEntitiesNextPosYArray)
/* 1FCB2C 801E4BAC 27182790 */  addiu       $t8, $t8, %lo(gEntitiesNextPosYArray)
/* 1FCB30 801E4BB0 3C0141A0 */  lui         $at, (0x41A00000 >> 16)
/* 1FCB34 801E4BB4 01181021 */  addu        $v0, $t0, $t8
/* 1FCB38 801E4BB8 44810000 */  mtc1        $at, $f0
/* 1FCB3C 801E4BBC C4440000 */  lwc1        $f4, 0x0($v0)
/* 1FCB40 801E4BC0 4600203C */  c.lt.s      $f4, $f0
/* 1FCB44 801E4BC4 00000000 */  nop
/* 1FCB48 801E4BC8 45020017 */  bc1fl       L801E4C28_ovl13
/* 1FCB4C 801E4BCC 8FAE0018 */   lw         $t6, 0x18($sp)
/* 1FCB50 801E4BD0 E4400000 */  swc1        $f0, 0x0($v0)
/* 1FCB54 801E4BD4 8C790000 */  lw          $t9, 0x0($v1)
/* 1FCB58 801E4BD8 44803000 */  mtc1        $zero, $f6
/* 1FCB5C 801E4BDC 3C01800E */  lui         $at, %hi(D_800E3210)
/* 1FCB60 801E4BE0 00194880 */  sll         $t1, $t9, 2
/* 1FCB64 801E4BE4 00290821 */  addu        $at, $at, $t1
/* 1FCB68 801E4BE8 E4263210 */  swc1        $f6, %lo(D_800E3210)($at)
/* 1FCB6C 801E4BEC 8C6A0000 */  lw          $t2, 0x0($v1)
/* 1FCB70 801E4BF0 3C01801E */  lui         $at, %hi(D_801E5E24_ovl13)
/* 1FCB74 801E4BF4 C4285E24 */  lwc1        $f8, %lo(D_801E5E24_ovl13)($at)
/* 1FCB78 801E4BF8 3C01800E */  lui         $at, %hi(D_800E3750)
/* 1FCB7C 801E4BFC 000A5880 */  sll         $t3, $t2, 2
/* 1FCB80 801E4C00 002B0821 */  addu        $at, $at, $t3
/* 1FCB84 801E4C04 E4283750 */  swc1        $f8, %lo(D_800E3750)($at)
/* 1FCB88 801E4C08 8C6C0000 */  lw          $t4, 0x0($v1)
/* 1FCB8C 801E4C0C 3C014120 */  lui         $at, (0x41200000 >> 16)
/* 1FCB90 801E4C10 44815000 */  mtc1        $at, $f10
/* 1FCB94 801E4C14 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FCB98 801E4C18 000C6880 */  sll         $t5, $t4, 2
/* 1FCB9C 801E4C1C 002D0821 */  addu        $at, $at, $t5
/* 1FCBA0 801E4C20 E42A3C90 */  swc1        $f10, %lo(D_800E3C90)($at)
/* 1FCBA4 801E4C24 8FAE0018 */  lw          $t6, 0x18($sp)
glabel L801E4C28_ovl13
/* 1FCBA8 801E4C28 8DCF0044 */  lw          $t7, 0x44($t6)
/* 1FCBAC 801E4C2C 31F80001 */  andi        $t8, $t7, 0x1
/* 1FCBB0 801E4C30 57000004 */  bnel        $t8, $zero, L801E4C44_ovl13
/* 1FCBB4 801E4C34 8FBF0014 */   lw         $ra, 0x14($sp)
/* 1FCBB8 801E4C38 0C067CEC */  jal         func_8019F3B0
/* 1FCBBC 801E4C3C 00000000 */   nop
/* 1FCBC0 801E4C40 8FBF0014 */  lw          $ra, 0x14($sp)
glabel L801E4C44_ovl13
/* 1FCBC4 801E4C44 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FCBC8 801E4C48 03E00008 */  jr          $ra
/* 1FCBCC 801E4C4C 00000000 */   nop
.size func_801E4B0C_ovl13, . - func_801E4B0C_ovl13

glabel func_801E4C50_ovl13 # 60
/* 1FCBD0 801E4C50 3C028005 */  lui         $v0, %hi(D_8004A7C4)
/* 1FCBD4 801E4C54 8C42A7C4 */  lw          $v0, %lo(D_8004A7C4)($v0)
/* 1FCBD8 801E4C58 AFA40000 */  sw          $a0, 0x0($sp)
/* 1FCBDC 801E4C5C 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FCBE0 801E4C60 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FCBE4 801E4C64 44802000 */  mtc1        $zero, $f4
/* 1FCBE8 801E4C68 000E7880 */  sll         $t7, $t6, 2
/* 1FCBEC 801E4C6C 002F0821 */  addu        $at, $at, $t7
/* 1FCBF0 801E4C70 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FCBF4 801E4C74 8C580000 */  lw          $t8, 0x0($v0)
/* 1FCBF8 801E4C78 3C01800E */  lui         $at, %hi(D_800E3210)
/* 1FCBFC 801E4C7C 0018C880 */  sll         $t9, $t8, 2
/* 1FCC00 801E4C80 00390821 */  addu        $at, $at, $t9
/* 1FCC04 801E4C84 E4243210 */  swc1        $f4, %lo(D_800E3210)($at)
/* 1FCC08 801E4C88 8C480000 */  lw          $t0, 0x0($v0)
/* 1FCC0C 801E4C8C 3C01801E */  lui         $at, %hi(D_801E5E28_ovl13)
/* 1FCC10 801E4C90 C4265E28 */  lwc1        $f6, %lo(D_801E5E28_ovl13)($at)
/* 1FCC14 801E4C94 3C01800E */  lui         $at, %hi(D_800E3750)
/* 1FCC18 801E4C98 00084880 */  sll         $t1, $t0, 2
/* 1FCC1C 801E4C9C 00290821 */  addu        $at, $at, $t1
/* 1FCC20 801E4CA0 E4263750 */  swc1        $f6, %lo(D_800E3750)($at)
/* 1FCC24 801E4CA4 8C4A0000 */  lw          $t2, 0x0($v0)
/* 1FCC28 801E4CA8 3C014120 */  lui         $at, (0x41200000 >> 16)
/* 1FCC2C 801E4CAC 44814000 */  mtc1        $at, $f8
/* 1FCC30 801E4CB0 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FCC34 801E4CB4 000A5880 */  sll         $t3, $t2, 2
/* 1FCC38 801E4CB8 002B0821 */  addu        $at, $at, $t3
/* 1FCC3C 801E4CBC 03E00008 */  jr          $ra
/* 1FCC40 801E4CC0 E4283C90 */   swc1       $f8, %lo(D_800E3C90)($at)
.size func_801E4C50_ovl13, . - func_801E4C50_ovl13

glabel func_801E4CC4_ovl13 # 61
/* 1FCC44 801E4CC4 3C028005 */  lui         $v0, %hi(D_8004A7C4)
/* 1FCC48 801E4CC8 8C42A7C4 */  lw          $v0, %lo(D_8004A7C4)($v0)
/* 1FCC4C 801E4CCC AFA40000 */  sw          $a0, 0x0($sp)
/* 1FCC50 801E4CD0 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FCC54 801E4CD4 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FCC58 801E4CD8 44802000 */  mtc1        $zero, $f4
/* 1FCC5C 801E4CDC 000E7880 */  sll         $t7, $t6, 2
/* 1FCC60 801E4CE0 002F0821 */  addu        $at, $at, $t7
/* 1FCC64 801E4CE4 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FCC68 801E4CE8 8C580000 */  lw          $t8, 0x0($v0)
/* 1FCC6C 801E4CEC 3C01800E */  lui         $at, %hi(D_800E3210)
/* 1FCC70 801E4CF0 0018C880 */  sll         $t9, $t8, 2
/* 1FCC74 801E4CF4 00390821 */  addu        $at, $at, $t9
/* 1FCC78 801E4CF8 E4243210 */  swc1        $f4, %lo(D_800E3210)($at)
/* 1FCC7C 801E4CFC 8C480000 */  lw          $t0, 0x0($v0)
/* 1FCC80 801E4D00 3C01801E */  lui         $at, %hi(D_801E5E2C_ovl13)
/* 1FCC84 801E4D04 C4265E2C */  lwc1        $f6, %lo(D_801E5E2C_ovl13)($at)
/* 1FCC88 801E4D08 3C01800E */  lui         $at, %hi(D_800E3750)
/* 1FCC8C 801E4D0C 00084880 */  sll         $t1, $t0, 2
/* 1FCC90 801E4D10 00290821 */  addu        $at, $at, $t1
/* 1FCC94 801E4D14 E4263750 */  swc1        $f6, %lo(D_800E3750)($at)
/* 1FCC98 801E4D18 8C4A0000 */  lw          $t2, 0x0($v0)
/* 1FCC9C 801E4D1C 3C014120 */  lui         $at, (0x41200000 >> 16)
/* 1FCCA0 801E4D20 44814000 */  mtc1        $at, $f8
/* 1FCCA4 801E4D24 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FCCA8 801E4D28 000A5880 */  sll         $t3, $t2, 2
/* 1FCCAC 801E4D2C 002B0821 */  addu        $at, $at, $t3
/* 1FCCB0 801E4D30 03E00008 */  jr          $ra
/* 1FCCB4 801E4D34 E4283C90 */   swc1       $f8, %lo(D_800E3C90)($at)
.size func_801E4CC4_ovl13, . - func_801E4CC4_ovl13

glabel func_801E4D38_ovl13 # 62
/* 1FCCB8 801E4D38 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 1FCCBC 801E4D3C AFB00018 */  sw          $s0, 0x18($sp)
/* 1FCCC0 801E4D40 3C108005 */  lui         $s0, %hi(D_8004A7C4)
/* 1FCCC4 801E4D44 2610A7C4 */  addiu       $s0, $s0, %lo(D_8004A7C4)
/* 1FCCC8 801E4D48 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FCCCC 801E4D4C AFBF0024 */  sw          $ra, 0x24($sp)
/* 1FCCD0 801E4D50 AFB20020 */  sw          $s2, 0x20($sp)
/* 1FCCD4 801E4D54 AFB1001C */  sw          $s1, 0x1C($sp)
/* 1FCCD8 801E4D58 AFA40028 */  sw          $a0, 0x28($sp)
/* 1FCCDC 801E4D5C 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FCCE0 801E4D60 3C02800E */  lui         $v0, %hi(D_800E1B50)
/* 1FCCE4 801E4D64 3C01C448 */  lui         $at, (0xC4480000 >> 16)
/* 1FCCE8 801E4D68 000FC080 */  sll         $t8, $t7, 2
/* 1FCCEC 801E4D6C 00581021 */  addu        $v0, $v0, $t8
/* 1FCCF0 801E4D70 8C421B50 */  lw          $v0, %lo(D_800E1B50)($v0)
/* 1FCCF4 801E4D74 44812000 */  mtc1        $at, $f4
/* 1FCCF8 801E4D78 3C01800E */  lui         $at, %hi(D_800DEF90)
/* 1FCCFC 801E4D7C 8C590080 */  lw          $t9, 0x80($v0)
/* 1FCD00 801E4D80 3C08800B */  lui         $t0, %hi(D_800B6E84)
/* 1FCD04 801E4D84 25086E84 */  addiu       $t0, $t0, %lo(D_800B6E84)
/* 1FCD08 801E4D88 E7240018 */  swc1        $f4, 0x18($t9)
/* 1FCD0C 801E4D8C 8E110000 */  lw          $s1, 0x0($s0)
/* 1FCD10 801E4D90 3C0B801E */  lui         $t3, %hi(func_801E5050_ovl13)
/* 1FCD14 801E4D94 256B5050 */  addiu       $t3, $t3, %lo(func_801E5050_ovl13)
/* 1FCD18 801E4D98 8E290000 */  lw          $t1, 0x0($s1)
/* 1FCD1C 801E4D9C 3C04801E */  lui         $a0, %hi(func_801E4E58_ovl13)
/* 1FCD20 801E4DA0 24844E58 */  addiu       $a0, $a0, %lo(func_801E4E58_ovl13)
/* 1FCD24 801E4DA4 00095080 */  sll         $t2, $t1, 2
/* 1FCD28 801E4DA8 002A0821 */  addu        $at, $at, $t2
/* 1FCD2C 801E4DAC AC28EF90 */  sw          $t0, %lo(D_800DEF90)($at)
/* 1FCD30 801E4DB0 8E2C0000 */  lw          $t4, 0x0($s1)
/* 1FCD34 801E4DB4 3C01800E */  lui         $at, %hi(D_800DF150)
/* 1FCD38 801E4DB8 000C6880 */  sll         $t5, $t4, 2
/* 1FCD3C 801E4DBC 002D0821 */  addu        $at, $at, $t5
/* 1FCD40 801E4DC0 0C068354 */  jal         func_801A0D50
/* 1FCD44 801E4DC4 AC2BF150 */   sw         $t3, %lo(D_800DF150)($at)
/* 1FCD48 801E4DC8 8E110000 */  lw          $s1, 0x0($s0)
/* 1FCD4C 801E4DCC 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FCD50 801E4DD0 3C04800E */  lui         $a0, %hi(D_800E7880)
/* 1FCD54 801E4DD4 8E2E0000 */  lw          $t6, 0x0($s1)
/* 1FCD58 801E4DD8 3C06801E */  lui         $a2, %hi(D_801E5C0C_ovl13)
/* 1FCD5C 801E4DDC 24C65C0C */  addiu       $a2, $a2, %lo(D_801E5C0C_ovl13)
/* 1FCD60 801E4DE0 000E7880 */  sll         $t7, $t6, 2
/* 1FCD64 801E4DE4 002F0821 */  addu        $at, $at, $t7
/* 1FCD68 801E4DE8 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FCD6C 801E4DEC 8E380000 */  lw          $t8, 0x0($s1)
/* 1FCD70 801E4DF0 24050001 */  addiu       $a1, $zero, 0x1
/* 1FCD74 801E4DF4 00982021 */  addu        $a0, $a0, $t8
/* 1FCD78 801E4DF8 0C02911F */  jal         call_virtual_function
/* 1FCD7C 801E4DFC 90847880 */   lbu        $a0, %lo(D_800E7880)($a0)
/* 1FCD80 801E4E00 3C12801E */  lui         $s2, %hi(D_801E5C10_ovl13)
/* 1FCD84 801E4E04 3C11800E */  lui         $s1, %hi(gEntityVtableIndexArray)
/* 1FCD88 801E4E08 2631DC50 */  addiu       $s1, $s1, %lo(gEntityVtableIndexArray)
/* 1FCD8C 801E4E0C 26525C10 */  addiu       $s2, $s2, %lo(D_801E5C10_ovl13)
/* 1FCD90 801E4E10 8E190000 */  lw          $t9, 0x0($s0)
glabel L801E4E14_ovl13
/* 1FCD94 801E4E14 24050001 */  addiu       $a1, $zero, 0x1
/* 1FCD98 801E4E18 02403025 */  move        $a2, $s2
/* 1FCD9C 801E4E1C 8F290000 */  lw          $t1, 0x0($t9)
/* 1FCDA0 801E4E20 00094080 */  sll         $t0, $t1, 2
/* 1FCDA4 801E4E24 02285021 */  addu        $t2, $s1, $t0
/* 1FCDA8 801E4E28 0C02911F */  jal         call_virtual_function
/* 1FCDAC 801E4E2C 8D440000 */   lw         $a0, 0x0($t2)
/* 1FCDB0 801E4E30 1000FFF8 */  b           L801E4E14_ovl13
/* 1FCDB4 801E4E34 8E190000 */   lw         $t9, 0x0($s0)
/* 1FCDB8 801E4E38 00000000 */  nop
/* 1FCDBC 801E4E3C 00000000 */  nop
/* 1FCDC0 801E4E40 8FBF0024 */  lw          $ra, 0x24($sp)
/* 1FCDC4 801E4E44 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FCDC8 801E4E48 8FB1001C */  lw          $s1, 0x1C($sp)
/* 1FCDCC 801E4E4C 8FB20020 */  lw          $s2, 0x20($sp)
/* 1FCDD0 801E4E50 03E00008 */  jr          $ra
/* 1FCDD4 801E4E54 27BD0028 */   addiu      $sp, $sp, 0x28
.size func_801E4D38_ovl13, . - func_801E4D38_ovl13

glabel func_801E4E58_ovl13 # 63
/* 1FCDD8 801E4E58 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 1FCDDC 801E4E5C AFB20020 */  sw          $s2, 0x20($sp)
/* 1FCDE0 801E4E60 AFB1001C */  sw          $s1, 0x1C($sp)
/* 1FCDE4 801E4E64 AFB00018 */  sw          $s0, 0x18($sp)
/* 1FCDE8 801E4E68 3C10800E */  lui         $s0, %hi(gEntityVtableIndexArray)
/* 1FCDEC 801E4E6C 3C118005 */  lui         $s1, %hi(D_8004A7C4)
/* 1FCDF0 801E4E70 3C12801E */  lui         $s2, %hi(D_801E5C10_ovl13)
/* 1FCDF4 801E4E74 AFBF0024 */  sw          $ra, 0x24($sp)
/* 1FCDF8 801E4E78 AFA40028 */  sw          $a0, 0x28($sp)
/* 1FCDFC 801E4E7C 26525C10 */  addiu       $s2, $s2, %lo(D_801E5C10_ovl13)
/* 1FCE00 801E4E80 2631A7C4 */  addiu       $s1, $s1, %lo(D_8004A7C4)
/* 1FCE04 801E4E84 2610DC50 */  addiu       $s0, $s0, %lo(gEntityVtableIndexArray)
/* 1FCE08 801E4E88 8E2E0000 */  lw          $t6, 0x0($s1)
glabel L801E4E8C_ovl13
/* 1FCE0C 801E4E8C 24050001 */  addiu       $a1, $zero, 0x1
/* 1FCE10 801E4E90 02403025 */  move        $a2, $s2
/* 1FCE14 801E4E94 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FCE18 801E4E98 000FC080 */  sll         $t8, $t7, 2
/* 1FCE1C 801E4E9C 0218C821 */  addu        $t9, $s0, $t8
/* 1FCE20 801E4EA0 0C02911F */  jal         call_virtual_function
/* 1FCE24 801E4EA4 8F240000 */   lw         $a0, 0x0($t9)
/* 1FCE28 801E4EA8 1000FFF8 */  b           L801E4E8C_ovl13
/* 1FCE2C 801E4EAC 8E2E0000 */   lw         $t6, 0x0($s1)
/* 1FCE30 801E4EB0 00000000 */  nop
/* 1FCE34 801E4EB4 00000000 */  nop
/* 1FCE38 801E4EB8 00000000 */  nop
/* 1FCE3C 801E4EBC 00000000 */  nop
/* 1FCE40 801E4EC0 8FBF0024 */  lw          $ra, 0x24($sp)
/* 1FCE44 801E4EC4 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FCE48 801E4EC8 8FB1001C */  lw          $s1, 0x1C($sp)
/* 1FCE4C 801E4ECC 8FB20020 */  lw          $s2, 0x20($sp)
/* 1FCE50 801E4ED0 03E00008 */  jr          $ra
/* 1FCE54 801E4ED4 27BD0028 */   addiu      $sp, $sp, 0x28
.size func_801E4E58_ovl13, . - func_801E4E58_ovl13

glabel func_801E4ED8_ovl13 # 64
/* 1FCE58 801E4ED8 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 1FCE5C 801E4EDC AFB00018 */  sw          $s0, 0x18($sp)
/* 1FCE60 801E4EE0 3C108005 */  lui         $s0, %hi(D_8004A7C4)
/* 1FCE64 801E4EE4 2610A7C4 */  addiu       $s0, $s0, %lo(D_8004A7C4)
/* 1FCE68 801E4EE8 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FCE6C 801E4EEC AFBF001C */  sw          $ra, 0x1C($sp)
/* 1FCE70 801E4EF0 AFA40020 */  sw          $a0, 0x20($sp)
/* 1FCE74 801E4EF4 24040070 */  addiu       $a0, $zero, 0x70
/* 1FCE78 801E4EF8 0C02C67D */  jal         func_800B19F4
/* 1FCE7C 801E4EFC 8DC50000 */   lw         $a1, 0x0($t6)
/* 1FCE80 801E4F00 00002025 */  move        $a0, $zero
/* 1FCE84 801E4F04 0C02BEED */  jal         func_800AFBB4
/* 1FCE88 801E4F08 8E050000 */   lw         $a1, 0x0($s0)
/* 1FCE8C 801E4F0C 0C002DAF */  jal         finish_current_thread
/* 1FCE90 801E4F10 24040004 */   addiu      $a0, $zero, 0x4
/* 1FCE94 801E4F14 8E0F0000 */  lw          $t7, 0x0($s0)
/* 1FCE98 801E4F18 24040030 */  addiu       $a0, $zero, 0x30
/* 1FCE9C 801E4F1C 0C02C67D */  jal         func_800B19F4
/* 1FCEA0 801E4F20 8DE50000 */   lw         $a1, 0x0($t7)
/* 1FCEA4 801E4F24 24040001 */  addiu       $a0, $zero, 0x1
/* 1FCEA8 801E4F28 0C02BEED */  jal         func_800AFBB4
/* 1FCEAC 801E4F2C 8E050000 */   lw         $a1, 0x0($s0)
/* 1FCEB0 801E4F30 8E030000 */  lw          $v1, 0x0($s0)
/* 1FCEB4 801E4F34 3C07800E */  lui         $a3, %hi(D_800E0D50)
/* 1FCEB8 801E4F38 24E70D50 */  addiu       $a3, $a3, %lo(D_800E0D50)
/* 1FCEBC 801E4F3C 8C620000 */  lw          $v0, 0x0($v1)
/* 1FCEC0 801E4F40 3C08800E */  lui         $t0, %hi(D_800E6A10)
/* 1FCEC4 801E4F44 25086A10 */  addiu       $t0, $t0, %lo(D_800E6A10)
/* 1FCEC8 801E4F48 00021080 */  sll         $v0, $v0, 2
/* 1FCECC 801E4F4C 00E2C021 */  addu        $t8, $a3, $v0
/* 1FCED0 801E4F50 8F190000 */  lw          $t9, 0x0($t8)
/* 1FCED4 801E4F54 01027021 */  addu        $t6, $t0, $v0
/* 1FCED8 801E4F58 3C09800E */  lui         $t1, %hi(D_800E5F90)
/* 1FCEDC 801E4F5C 00196080 */  sll         $t4, $t9, 2
/* 1FCEE0 801E4F60 010C6821 */  addu        $t5, $t0, $t4
/* 1FCEE4 801E4F64 C5A40000 */  lwc1        $f4, 0x0($t5)
/* 1FCEE8 801E4F68 25295F90 */  addiu       $t1, $t1, %lo(D_800E5F90)
/* 1FCEEC 801E4F6C 3C0A800E */  lui         $t2, %hi(D_800E6BD0)
/* 1FCEF0 801E4F70 E5C40000 */  swc1        $f4, 0x0($t6)
/* 1FCEF4 801E4F74 8C620000 */  lw          $v0, 0x0($v1)
/* 1FCEF8 801E4F78 254A6BD0 */  addiu       $t2, $t2, %lo(D_800E6BD0)
/* 1FCEFC 801E4F7C 3C0B800E */  lui         $t3, %hi(gEntitiesNextPosYArray)
/* 1FCF00 801E4F80 00021080 */  sll         $v0, $v0, 2
/* 1FCF04 801E4F84 00E27821 */  addu        $t7, $a3, $v0
/* 1FCF08 801E4F88 8DF80000 */  lw          $t8, 0x0($t7)
/* 1FCF0C 801E4F8C 01227021 */  addu        $t6, $t1, $v0
/* 1FCF10 801E4F90 256B2790 */  addiu       $t3, $t3, %lo(gEntitiesNextPosYArray)
/* 1FCF14 801E4F94 0018C880 */  sll         $t9, $t8, 2
/* 1FCF18 801E4F98 01396021 */  addu        $t4, $t1, $t9
/* 1FCF1C 801E4F9C 8D8D0000 */  lw          $t5, 0x0($t4)
/* 1FCF20 801E4FA0 3C0141A0 */  lui         $at, (0x41A00000 >> 16)
/* 1FCF24 801E4FA4 44815000 */  mtc1        $at, $f10
/* 1FCF28 801E4FA8 ADCD0000 */  sw          $t5, 0x0($t6)
/* 1FCF2C 801E4FAC 8C620000 */  lw          $v0, 0x0($v1)
/* 1FCF30 801E4FB0 3C014220 */  lui         $at, (0x42200000 >> 16)
/* 1FCF34 801E4FB4 44812000 */  mtc1        $at, $f4
/* 1FCF38 801E4FB8 00021080 */  sll         $v0, $v0, 2
/* 1FCF3C 801E4FBC 00E27821 */  addu        $t7, $a3, $v0
/* 1FCF40 801E4FC0 8DF80000 */  lw          $t8, 0x0($t7)
/* 1FCF44 801E4FC4 01426821 */  addu        $t5, $t2, $v0
/* 1FCF48 801E4FC8 0018C880 */  sll         $t9, $t8, 2
/* 1FCF4C 801E4FCC 01596021 */  addu        $t4, $t2, $t9
/* 1FCF50 801E4FD0 C5860000 */  lwc1        $f6, 0x0($t4)
/* 1FCF54 801E4FD4 E5A60000 */  swc1        $f6, 0x0($t5)
/* 1FCF58 801E4FD8 8C620000 */  lw          $v0, 0x0($v1)
/* 1FCF5C 801E4FDC 00021080 */  sll         $v0, $v0, 2
/* 1FCF60 801E4FE0 00E27021 */  addu        $t6, $a3, $v0
/* 1FCF64 801E4FE4 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FCF68 801E4FE8 01626021 */  addu        $t4, $t3, $v0
/* 1FCF6C 801E4FEC 000FC080 */  sll         $t8, $t7, 2
/* 1FCF70 801E4FF0 0178C821 */  addu        $t9, $t3, $t8
/* 1FCF74 801E4FF4 C7280000 */  lwc1        $f8, 0x0($t9)
/* 1FCF78 801E4FF8 460A4401 */  sub.s       $f16, $f8, $f10
/* 1FCF7C 801E4FFC E5900000 */  swc1        $f16, 0x0($t4)
/* 1FCF80 801E5000 8C620000 */  lw          $v0, 0x0($v1)
/* 1FCF84 801E5004 00021080 */  sll         $v0, $v0, 2
/* 1FCF88 801E5008 01026821 */  addu        $t5, $t0, $v0
/* 1FCF8C 801E500C C5B20000 */  lwc1        $f18, 0x0($t5)
/* 1FCF90 801E5010 01222021 */  addu        $a0, $t1, $v0
/* 1FCF94 801E5014 01422821 */  addu        $a1, $t2, $v0
/* 1FCF98 801E5018 46049182 */  mul.s       $f6, $f18, $f4
/* 1FCF9C 801E501C 44063000 */  mfc1        $a2, $f6
/* 1FCFA0 801E5020 0C03E65D */  jal         func_800F9974
/* 1FCFA4 801E5024 00000000 */   nop
/* 1FCFA8 801E5028 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FCFAC 801E502C 8FBF001C */  lw          $ra, 0x1C($sp)
/* 1FCFB0 801E5030 3C01800E */  lui         $at, %hi(gEntityVtableIndexArray)
/* 1FCFB4 801E5034 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FCFB8 801E5038 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FCFBC 801E503C 27BD0020 */  addiu       $sp, $sp, 0x20
/* 1FCFC0 801E5040 000FC080 */  sll         $t8, $t7, 2
/* 1FCFC4 801E5044 00380821 */  addu        $at, $at, $t8
/* 1FCFC8 801E5048 03E00008 */  jr          $ra
/* 1FCFCC 801E504C AC20DC50 */   sw         $zero, %lo(gEntityVtableIndexArray)($at)
.size func_801E4ED8_ovl13, . - func_801E4ED8_ovl13

glabel func_801E5050_ovl13 # 65
/* 1FCFD0 801E5050 3C0E8005 */  lui         $t6, %hi(D_8004A7C4)
/* 1FCFD4 801E5054 8DCEA7C4 */  lw          $t6, %lo(D_8004A7C4)($t6)
/* 1FCFD8 801E5058 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FCFDC 801E505C AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FCFE0 801E5060 AFA40018 */  sw          $a0, 0x18($sp)
/* 1FCFE4 801E5064 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FCFE8 801E5068 3C04800E */  lui         $a0, %hi(D_800DDFD0)
/* 1FCFEC 801E506C 3C06801E */  lui         $a2, %hi(D_801E5C14_ovl13)
/* 1FCFF0 801E5070 000FC080 */  sll         $t8, $t7, 2
/* 1FCFF4 801E5074 00982021 */  addu        $a0, $a0, $t8
/* 1FCFF8 801E5078 8C84DFD0 */  lw          $a0, %lo(D_800DDFD0)($a0)
/* 1FCFFC 801E507C 24C65C14 */  addiu       $a2, $a2, %lo(D_801E5C14_ovl13)
/* 1FD000 801E5080 0C02911F */  jal         call_virtual_function
/* 1FD004 801E5084 24050001 */   addiu      $a1, $zero, 0x1
/* 1FD008 801E5088 8FBF0014 */  lw          $ra, 0x14($sp)
/* 1FD00C 801E508C 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FD010 801E5090 03E00008 */  jr          $ra
/* 1FD014 801E5094 00000000 */   nop
.size func_801E5050_ovl13, . - func_801E5050_ovl13

glabel func_801E5098_ovl13 # 66
/* 1FD018 801E5098 3C028005 */  lui         $v0, %hi(D_8004A7C4)
/* 1FD01C 801E509C 8C42A7C4 */  lw          $v0, %lo(D_8004A7C4)($v0)
/* 1FD020 801E50A0 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FD024 801E50A4 AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FD028 801E50A8 AFA40018 */  sw          $a0, 0x18($sp)
/* 1FD02C 801E50AC 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FD030 801E50B0 3C01800E */  lui         $at, %hi(D_800DDFD0)
/* 1FD034 801E50B4 3C09800E */  lui         $t1, %hi(D_800E1B50)
/* 1FD038 801E50B8 000E7880 */  sll         $t7, $t6, 2
/* 1FD03C 801E50BC 002F0821 */  addu        $at, $at, $t7
/* 1FD040 801E50C0 AC20DFD0 */  sw          $zero, %lo(D_800DDFD0)($at)
/* 1FD044 801E50C4 8C590000 */  lw          $t9, 0x0($v0)
/* 1FD048 801E50C8 3C18801E */  lui         $t8, %hi(D_801DAD44)
/* 1FD04C 801E50CC 2718AD44 */  addiu       $t8, $t8, %lo(D_801DAD44)
/* 1FD050 801E50D0 00194080 */  sll         $t0, $t9, 2
/* 1FD054 801E50D4 01284821 */  addu        $t1, $t1, $t0
/* 1FD058 801E50D8 8D291B50 */  lw          $t1, %lo(D_800E1B50)($t1)
/* 1FD05C 801E50DC 3C01800D */  lui         $at, %hi(D_800D6B10)
/* 1FD060 801E50E0 AD380098 */  sw          $t8, 0x98($t1)
/* 1FD064 801E50E4 0C02BB30 */  jal         func_800AECC0
/* 1FD068 801E50E8 C42C6B10 */   lwc1       $f12, %lo(D_800D6B10)($at)
/* 1FD06C 801E50EC 3C01800D */  lui         $at, %hi(D_800D6B10)
/* 1FD070 801E50F0 0C02BB48 */  jal         func_800AED20
/* 1FD074 801E50F4 C42C6B10 */   lwc1       $f12, %lo(D_800D6B10)($at)
/* 1FD078 801E50F8 0C02CCFD */  jal         func_800B33F4
/* 1FD07C 801E50FC 00000000 */   nop
/* 1FD080 801E5100 3C038005 */  lui         $v1, %hi(D_8004A7C4)
/* 1FD084 801E5104 2463A7C4 */  addiu       $v1, $v1, %lo(D_8004A7C4)
/* 1FD088 801E5108 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD08C 801E510C 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FD090 801E5110 3C0F800E */  lui         $t7, %hi(D_800E1B50)
/* 1FD094 801E5114 8C4A0000 */  lw          $t2, 0x0($v0)
/* 1FD098 801E5118 240CFFFF */  addiu       $t4, $zero, -0x1
/* 1FD09C 801E511C 24180168 */  addiu       $t8, $zero, 0x168
/* 1FD0A0 801E5120 000A5880 */  sll         $t3, $t2, 2
/* 1FD0A4 801E5124 002B0821 */  addu        $at, $at, $t3
/* 1FD0A8 801E5128 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FD0AC 801E512C 8C4D0000 */  lw          $t5, 0x0($v0)
/* 1FD0B0 801E5130 3C01800F */  lui         $at, %hi(D_800E98E0)
/* 1FD0B4 801E5134 3C040001 */  lui         $a0, (0x1055C >> 16)
/* 1FD0B8 801E5138 000D7080 */  sll         $t6, $t5, 2
/* 1FD0BC 801E513C 01EE7821 */  addu        $t7, $t7, $t6
/* 1FD0C0 801E5140 8DEF1B50 */  lw          $t7, %lo(D_800E1B50)($t7)
/* 1FD0C4 801E5144 3484055C */  ori         $a0, $a0, (0x1055C & 0xFFFF)
/* 1FD0C8 801E5148 A1EC0039 */  sb          $t4, 0x39($t7)
/* 1FD0CC 801E514C 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD0D0 801E5150 8C590000 */  lw          $t9, 0x0($v0)
/* 1FD0D4 801E5154 00194080 */  sll         $t0, $t9, 2
/* 1FD0D8 801E5158 00280821 */  addu        $at, $at, $t0
/* 1FD0DC 801E515C AC2098E0 */  sw          $zero, %lo(D_800E98E0)($at)
/* 1FD0E0 801E5160 8C490000 */  lw          $t1, 0x0($v0)
/* 1FD0E4 801E5164 3C01800F */  lui         $at, %hi(D_800E9AA0)
/* 1FD0E8 801E5168 00095080 */  sll         $t2, $t1, 2
/* 1FD0EC 801E516C 002A0821 */  addu        $at, $at, $t2
/* 1FD0F0 801E5170 0C02A806 */  jal         func_800AA018
/* 1FD0F4 801E5174 AC389AA0 */   sw         $t8, %lo(D_800E9AA0)($at)
/* 1FD0F8 801E5178 3C028005 */  lui         $v0, %hi(D_8004A7C4)
/* 1FD0FC 801E517C 8C42A7C4 */  lw          $v0, %lo(D_8004A7C4)($v0)
/* 1FD100 801E5180 3C01800E */  lui         $at, %hi(D_800E6A10)
/* 1FD104 801E5184 3C04800F */  lui         $a0, %hi(D_800E9AA0)
/* 1FD108 801E5188 8C430000 */  lw          $v1, 0x0($v0)
/* 1FD10C 801E518C 00031880 */  sll         $v1, $v1, 2
/* 1FD110 801E5190 00230821 */  addu        $at, $at, $v1
/* 1FD114 801E5194 C4246A10 */  lwc1        $f4, %lo(D_800E6A10)($at)
/* 1FD118 801E5198 3C014080 */  lui         $at, (0x40800000 >> 16)
/* 1FD11C 801E519C 44813000 */  mtc1        $at, $f6
/* 1FD120 801E51A0 3C01800E */  lui         $at, %hi(D_800E64D0)
/* 1FD124 801E51A4 00230821 */  addu        $at, $at, $v1
/* 1FD128 801E51A8 46062202 */  mul.s       $f8, $f4, $f6
/* 1FD12C 801E51AC E42864D0 */  swc1        $f8, %lo(D_800E64D0)($at)
/* 1FD130 801E51B0 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FD134 801E51B4 000B6880 */  sll         $t5, $t3, 2
/* 1FD138 801E51B8 008D2021 */  addu        $a0, $a0, $t5
/* 1FD13C 801E51BC 0C002DAF */  jal         finish_current_thread
/* 1FD140 801E51C0 8C849AA0 */   lw         $a0, %lo(D_800E9AA0)($a0)
/* 1FD144 801E51C4 3C0C8005 */  lui         $t4, %hi(D_8004A7C4)
/* 1FD148 801E51C8 8D8CA7C4 */  lw          $t4, %lo(D_8004A7C4)($t4)
/* 1FD14C 801E51CC 3C01800E */  lui         $at, %hi(gEntityVtableIndexArray)
/* 1FD150 801E51D0 240EFFFF */  addiu       $t6, $zero, -0x1
/* 1FD154 801E51D4 8D8F0000 */  lw          $t7, 0x0($t4)
/* 1FD158 801E51D8 8FA40018 */  lw          $a0, 0x18($sp)
/* 1FD15C 801E51DC 000FC880 */  sll         $t9, $t7, 2
/* 1FD160 801E51E0 00390821 */  addu        $at, $at, $t9
/* 1FD164 801E51E4 0C068FA0 */  jal         func_801A3E80
/* 1FD168 801E51E8 AC2EDC50 */   sw         $t6, %lo(gEntityVtableIndexArray)($at)
/* 1FD16C 801E51EC 8FBF0014 */  lw          $ra, 0x14($sp)
/* 1FD170 801E51F0 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FD174 801E51F4 03E00008 */  jr          $ra
/* 1FD178 801E51F8 00000000 */   nop
.size func_801E5098_ovl13, . - func_801E5098_ovl13

glabel func_801E51FC_ovl13 # 67
/* 1FD17C 801E51FC 3C038005 */  lui         $v1, %hi(D_8004A7C4)
/* 1FD180 801E5200 8C63A7C4 */  lw          $v1, %lo(D_8004A7C4)($v1)
/* 1FD184 801E5204 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FD188 801E5208 AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FD18C 801E520C AFA40018 */  sw          $a0, 0x18($sp)
/* 1FD190 801E5210 8C6E0000 */  lw          $t6, 0x0($v1)
/* 1FD194 801E5214 3C05800F */  lui         $a1, %hi(D_800E98E0)
/* 1FD198 801E5218 24A598E0 */  addiu       $a1, $a1, %lo(D_800E98E0)
/* 1FD19C 801E521C 000E7880 */  sll         $t7, $t6, 2
/* 1FD1A0 801E5220 00AF1021 */  addu        $v0, $a1, $t7
/* 1FD1A4 801E5224 8C580000 */  lw          $t8, 0x0($v0)
/* 1FD1A8 801E5228 24010005 */  addiu       $at, $zero, 0x5
/* 1FD1AC 801E522C 3C0F800E */  lui         $t7, %hi(D_800DFBD0)
/* 1FD1B0 801E5230 27190001 */  addiu       $t9, $t8, 0x1
/* 1FD1B4 801E5234 AC590000 */  sw          $t9, 0x0($v0)
/* 1FD1B8 801E5238 8C690000 */  lw          $t1, 0x0($v1)
/* 1FD1BC 801E523C 24040006 */  addiu       $a0, $zero, 0x6
/* 1FD1C0 801E5240 00095080 */  sll         $t2, $t1, 2
/* 1FD1C4 801E5244 00AA1021 */  addu        $v0, $a1, $t2
/* 1FD1C8 801E5248 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FD1CC 801E524C 0161001A */  div         $zero, $t3, $at
/* 1FD1D0 801E5250 00006010 */  mfhi        $t4
/* 1FD1D4 801E5254 AC4C0000 */  sw          $t4, 0x0($v0)
/* 1FD1D8 801E5258 8C680000 */  lw          $t0, 0x0($v1)
/* 1FD1DC 801E525C 00084080 */  sll         $t0, $t0, 2
/* 1FD1E0 801E5260 00A86821 */  addu        $t5, $a1, $t0
/* 1FD1E4 801E5264 8DAE0000 */  lw          $t6, 0x0($t5)
/* 1FD1E8 801E5268 24050002 */  addiu       $a1, $zero, 0x2
/* 1FD1EC 801E526C 01E87821 */  addu        $t7, $t7, $t0
/* 1FD1F0 801E5270 55C00006 */  bnel        $t6, $zero, L801E528C_ovl13
/* 1FD1F4 801E5274 8FB80018 */   lw         $t8, 0x18($sp)
/* 1FD1F8 801E5278 8DEFFBD0 */  lw          $t7, %lo(D_800DFBD0)($t7)
/* 1FD1FC 801E527C 00003025 */  move        $a2, $zero
/* 1FD200 801E5280 0C02A040 */  jal         func_800A8100
/* 1FD204 801E5284 8DE70004 */   lw         $a3, 0x4($t7)
/* 1FD208 801E5288 8FB80018 */  lw          $t8, 0x18($sp)
glabel L801E528C_ovl13
/* 1FD20C 801E528C 8F190044 */  lw          $t9, 0x44($t8)
/* 1FD210 801E5290 33290001 */  andi        $t1, $t9, 0x1
/* 1FD214 801E5294 55200004 */  bnel        $t1, $zero, L801E52A8_ovl13
/* 1FD218 801E5298 8FBF0014 */   lw         $ra, 0x14($sp)
/* 1FD21C 801E529C 0C067CEC */  jal         func_8019F3B0
/* 1FD220 801E52A0 00000000 */   nop
/* 1FD224 801E52A4 8FBF0014 */  lw          $ra, 0x14($sp)
glabel L801E52A8_ovl13
/* 1FD228 801E52A8 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FD22C 801E52AC 03E00008 */  jr          $ra
/* 1FD230 801E52B0 00000000 */   nop
.size func_801E51FC_ovl13, . - func_801E51FC_ovl13

glabel func_801E52B4_ovl13 # 68
/* 1FD234 801E52B4 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 1FD238 801E52B8 AFB00018 */  sw          $s0, 0x18($sp)
/* 1FD23C 801E52BC 3C108005 */  lui         $s0, %hi(D_8004A7C4)
/* 1FD240 801E52C0 2610A7C4 */  addiu       $s0, $s0, %lo(D_8004A7C4)
/* 1FD244 801E52C4 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FD248 801E52C8 AFBF0024 */  sw          $ra, 0x24($sp)
/* 1FD24C 801E52CC AFB20020 */  sw          $s2, 0x20($sp)
/* 1FD250 801E52D0 AFB1001C */  sw          $s1, 0x1C($sp)
/* 1FD254 801E52D4 AFA40028 */  sw          $a0, 0x28($sp)
/* 1FD258 801E52D8 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FD25C 801E52DC 3C02800E */  lui         $v0, %hi(D_800E1B50)
/* 1FD260 801E52E0 3C01C448 */  lui         $at, (0xC4480000 >> 16)
/* 1FD264 801E52E4 000FC080 */  sll         $t8, $t7, 2
/* 1FD268 801E52E8 00581021 */  addu        $v0, $v0, $t8
/* 1FD26C 801E52EC 8C421B50 */  lw          $v0, %lo(D_800E1B50)($v0)
/* 1FD270 801E52F0 44812000 */  mtc1        $at, $f4
/* 1FD274 801E52F4 3C01800E */  lui         $at, %hi(D_800DEF90)
/* 1FD278 801E52F8 8C590080 */  lw          $t9, 0x80($v0)
/* 1FD27C 801E52FC 3C08800B */  lui         $t0, %hi(D_800B6FD8)
/* 1FD280 801E5300 25086FD8 */  addiu       $t0, $t0, %lo(D_800B6FD8)
/* 1FD284 801E5304 E7240018 */  swc1        $f4, 0x18($t9)
/* 1FD288 801E5308 8E110000 */  lw          $s1, 0x0($s0)
/* 1FD28C 801E530C 3C0B801E */  lui         $t3, %hi(func_801E55D0_ovl13)
/* 1FD290 801E5310 256B55D0 */  addiu       $t3, $t3, %lo(func_801E55D0_ovl13)
/* 1FD294 801E5314 8E290000 */  lw          $t1, 0x0($s1)
/* 1FD298 801E5318 3C04801E */  lui         $a0, %hi(func_801E53D8_ovl13)
/* 1FD29C 801E531C 248453D8 */  addiu       $a0, $a0, %lo(func_801E53D8_ovl13)
/* 1FD2A0 801E5320 00095080 */  sll         $t2, $t1, 2
/* 1FD2A4 801E5324 002A0821 */  addu        $at, $at, $t2
/* 1FD2A8 801E5328 AC28EF90 */  sw          $t0, %lo(D_800DEF90)($at)
/* 1FD2AC 801E532C 8E2C0000 */  lw          $t4, 0x0($s1)
/* 1FD2B0 801E5330 3C01800E */  lui         $at, %hi(D_800DF150)
/* 1FD2B4 801E5334 000C6880 */  sll         $t5, $t4, 2
/* 1FD2B8 801E5338 002D0821 */  addu        $at, $at, $t5
/* 1FD2BC 801E533C 0C068354 */  jal         func_801A0D50
/* 1FD2C0 801E5340 AC2BF150 */   sw         $t3, %lo(D_800DF150)($at)
/* 1FD2C4 801E5344 8E110000 */  lw          $s1, 0x0($s0)
/* 1FD2C8 801E5348 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FD2CC 801E534C 3C04800E */  lui         $a0, %hi(D_800E7880)
/* 1FD2D0 801E5350 8E2E0000 */  lw          $t6, 0x0($s1)
/* 1FD2D4 801E5354 3C06801E */  lui         $a2, %hi(D_801E5C18_ovl13)
/* 1FD2D8 801E5358 24C65C18 */  addiu       $a2, $a2, %lo(D_801E5C18_ovl13)
/* 1FD2DC 801E535C 000E7880 */  sll         $t7, $t6, 2
/* 1FD2E0 801E5360 002F0821 */  addu        $at, $at, $t7
/* 1FD2E4 801E5364 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FD2E8 801E5368 8E380000 */  lw          $t8, 0x0($s1)
/* 1FD2EC 801E536C 24050001 */  addiu       $a1, $zero, 0x1
/* 1FD2F0 801E5370 00982021 */  addu        $a0, $a0, $t8
/* 1FD2F4 801E5374 0C02911F */  jal         call_virtual_function
/* 1FD2F8 801E5378 90847880 */   lbu        $a0, %lo(D_800E7880)($a0)
/* 1FD2FC 801E537C 3C12801E */  lui         $s2, %hi(D_801E5C1C_ovl13)
/* 1FD300 801E5380 3C11800E */  lui         $s1, %hi(gEntityVtableIndexArray)
/* 1FD304 801E5384 2631DC50 */  addiu       $s1, $s1, %lo(gEntityVtableIndexArray)
/* 1FD308 801E5388 26525C1C */  addiu       $s2, $s2, %lo(D_801E5C1C_ovl13)
/* 1FD30C 801E538C 8E190000 */  lw          $t9, 0x0($s0)
glabel L801E5390_ovl13
/* 1FD310 801E5390 24050001 */  addiu       $a1, $zero, 0x1
/* 1FD314 801E5394 02403025 */  move        $a2, $s2
/* 1FD318 801E5398 8F290000 */  lw          $t1, 0x0($t9)
/* 1FD31C 801E539C 00094080 */  sll         $t0, $t1, 2
/* 1FD320 801E53A0 02285021 */  addu        $t2, $s1, $t0
/* 1FD324 801E53A4 0C02911F */  jal         call_virtual_function
/* 1FD328 801E53A8 8D440000 */   lw         $a0, 0x0($t2)
/* 1FD32C 801E53AC 1000FFF8 */  b           L801E5390_ovl13
/* 1FD330 801E53B0 8E190000 */   lw         $t9, 0x0($s0)
/* 1FD334 801E53B4 00000000 */  nop
/* 1FD338 801E53B8 00000000 */  nop
/* 1FD33C 801E53BC 00000000 */  nop
/* 1FD340 801E53C0 8FBF0024 */  lw          $ra, 0x24($sp)
/* 1FD344 801E53C4 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FD348 801E53C8 8FB1001C */  lw          $s1, 0x1C($sp)
/* 1FD34C 801E53CC 8FB20020 */  lw          $s2, 0x20($sp)
/* 1FD350 801E53D0 03E00008 */  jr          $ra
/* 1FD354 801E53D4 27BD0028 */   addiu      $sp, $sp, 0x28
.size func_801E52B4_ovl13, . - func_801E52B4_ovl13

glabel func_801E53D8_ovl13 # 69
/* 1FD358 801E53D8 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 1FD35C 801E53DC AFB20020 */  sw          $s2, 0x20($sp)
/* 1FD360 801E53E0 AFB1001C */  sw          $s1, 0x1C($sp)
/* 1FD364 801E53E4 AFB00018 */  sw          $s0, 0x18($sp)
/* 1FD368 801E53E8 3C10800E */  lui         $s0, %hi(gEntityVtableIndexArray)
/* 1FD36C 801E53EC 3C118005 */  lui         $s1, %hi(D_8004A7C4)
/* 1FD370 801E53F0 3C12801E */  lui         $s2, %hi(D_801E5C1C_ovl13)
/* 1FD374 801E53F4 AFBF0024 */  sw          $ra, 0x24($sp)
/* 1FD378 801E53F8 AFA40028 */  sw          $a0, 0x28($sp)
/* 1FD37C 801E53FC 26525C1C */  addiu       $s2, $s2, %lo(D_801E5C1C_ovl13)
/* 1FD380 801E5400 2631A7C4 */  addiu       $s1, $s1, %lo(D_8004A7C4)
/* 1FD384 801E5404 2610DC50 */  addiu       $s0, $s0, %lo(gEntityVtableIndexArray)
/* 1FD388 801E5408 8E2E0000 */  lw          $t6, 0x0($s1)
glabel L801E540C_ovl13
/* 1FD38C 801E540C 24050001 */  addiu       $a1, $zero, 0x1
/* 1FD390 801E5410 02403025 */  move        $a2, $s2
/* 1FD394 801E5414 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FD398 801E5418 000FC080 */  sll         $t8, $t7, 2
/* 1FD39C 801E541C 0218C821 */  addu        $t9, $s0, $t8
/* 1FD3A0 801E5420 0C02911F */  jal         call_virtual_function
/* 1FD3A4 801E5424 8F240000 */   lw         $a0, 0x0($t9)
/* 1FD3A8 801E5428 1000FFF8 */  b           L801E540C_ovl13
/* 1FD3AC 801E542C 8E2E0000 */   lw         $t6, 0x0($s1)
/* 1FD3B0 801E5430 00000000 */  nop
/* 1FD3B4 801E5434 00000000 */  nop
/* 1FD3B8 801E5438 00000000 */  nop
/* 1FD3BC 801E543C 00000000 */  nop
/* 1FD3C0 801E5440 8FBF0024 */  lw          $ra, 0x24($sp)
/* 1FD3C4 801E5444 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FD3C8 801E5448 8FB1001C */  lw          $s1, 0x1C($sp)
/* 1FD3CC 801E544C 8FB20020 */  lw          $s2, 0x20($sp)
/* 1FD3D0 801E5450 03E00008 */  jr          $ra
/* 1FD3D4 801E5454 27BD0028 */   addiu      $sp, $sp, 0x28
.size func_801E53D8_ovl13, . - func_801E53D8_ovl13

glabel func_801E5458_ovl13 # 70
/* 1FD3D8 801E5458 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 1FD3DC 801E545C AFB00018 */  sw          $s0, 0x18($sp)
/* 1FD3E0 801E5460 3C108005 */  lui         $s0, %hi(D_8004A7C4)
/* 1FD3E4 801E5464 2610A7C4 */  addiu       $s0, $s0, %lo(D_8004A7C4)
/* 1FD3E8 801E5468 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FD3EC 801E546C AFBF001C */  sw          $ra, 0x1C($sp)
/* 1FD3F0 801E5470 AFA40020 */  sw          $a0, 0x20($sp)
/* 1FD3F4 801E5474 24040070 */  addiu       $a0, $zero, 0x70
/* 1FD3F8 801E5478 0C02C67D */  jal         func_800B19F4
/* 1FD3FC 801E547C 8DC50000 */   lw         $a1, 0x0($t6)
/* 1FD400 801E5480 00002025 */  move        $a0, $zero
/* 1FD404 801E5484 0C02BEED */  jal         func_800AFBB4
/* 1FD408 801E5488 8E050000 */   lw         $a1, 0x0($s0)
/* 1FD40C 801E548C 0C002DAF */  jal         finish_current_thread
/* 1FD410 801E5490 24040004 */   addiu      $a0, $zero, 0x4
/* 1FD414 801E5494 8E0F0000 */  lw          $t7, 0x0($s0)
/* 1FD418 801E5498 24040030 */  addiu       $a0, $zero, 0x30
/* 1FD41C 801E549C 0C02C67D */  jal         func_800B19F4
/* 1FD420 801E54A0 8DE50000 */   lw         $a1, 0x0($t7)
/* 1FD424 801E54A4 24040001 */  addiu       $a0, $zero, 0x1
/* 1FD428 801E54A8 0C02BEED */  jal         func_800AFBB4
/* 1FD42C 801E54AC 8E050000 */   lw         $a1, 0x0($s0)
/* 1FD430 801E54B0 8E030000 */  lw          $v1, 0x0($s0)
/* 1FD434 801E54B4 3C07800E */  lui         $a3, %hi(D_800E0D50)
/* 1FD438 801E54B8 24E70D50 */  addiu       $a3, $a3, %lo(D_800E0D50)
/* 1FD43C 801E54BC 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD440 801E54C0 3C08800E */  lui         $t0, %hi(D_800E6A10)
/* 1FD444 801E54C4 25086A10 */  addiu       $t0, $t0, %lo(D_800E6A10)
/* 1FD448 801E54C8 00021080 */  sll         $v0, $v0, 2
/* 1FD44C 801E54CC 00E2C021 */  addu        $t8, $a3, $v0
/* 1FD450 801E54D0 8F190000 */  lw          $t9, 0x0($t8)
/* 1FD454 801E54D4 01027021 */  addu        $t6, $t0, $v0
/* 1FD458 801E54D8 3C09800E */  lui         $t1, %hi(D_800E5F90)
/* 1FD45C 801E54DC 00196080 */  sll         $t4, $t9, 2
/* 1FD460 801E54E0 010C6821 */  addu        $t5, $t0, $t4
/* 1FD464 801E54E4 C5A40000 */  lwc1        $f4, 0x0($t5)
/* 1FD468 801E54E8 25295F90 */  addiu       $t1, $t1, %lo(D_800E5F90)
/* 1FD46C 801E54EC 3C0A800E */  lui         $t2, %hi(D_800E6BD0)
/* 1FD470 801E54F0 E5C40000 */  swc1        $f4, 0x0($t6)
/* 1FD474 801E54F4 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD478 801E54F8 254A6BD0 */  addiu       $t2, $t2, %lo(D_800E6BD0)
/* 1FD47C 801E54FC 3C0B800E */  lui         $t3, %hi(gEntitiesNextPosYArray)
/* 1FD480 801E5500 00021080 */  sll         $v0, $v0, 2
/* 1FD484 801E5504 00E27821 */  addu        $t7, $a3, $v0
/* 1FD488 801E5508 8DF80000 */  lw          $t8, 0x0($t7)
/* 1FD48C 801E550C 01227021 */  addu        $t6, $t1, $v0
/* 1FD490 801E5510 256B2790 */  addiu       $t3, $t3, %lo(gEntitiesNextPosYArray)
/* 1FD494 801E5514 0018C880 */  sll         $t9, $t8, 2
/* 1FD498 801E5518 01396021 */  addu        $t4, $t1, $t9
/* 1FD49C 801E551C 8D8D0000 */  lw          $t5, 0x0($t4)
/* 1FD4A0 801E5520 3C0141A0 */  lui         $at, (0x41A00000 >> 16)
/* 1FD4A4 801E5524 44815000 */  mtc1        $at, $f10
/* 1FD4A8 801E5528 ADCD0000 */  sw          $t5, 0x0($t6)
/* 1FD4AC 801E552C 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD4B0 801E5530 3C014220 */  lui         $at, (0x42200000 >> 16)
/* 1FD4B4 801E5534 44812000 */  mtc1        $at, $f4
/* 1FD4B8 801E5538 00021080 */  sll         $v0, $v0, 2
/* 1FD4BC 801E553C 00E27821 */  addu        $t7, $a3, $v0
/* 1FD4C0 801E5540 8DF80000 */  lw          $t8, 0x0($t7)
/* 1FD4C4 801E5544 01426821 */  addu        $t5, $t2, $v0
/* 1FD4C8 801E5548 0018C880 */  sll         $t9, $t8, 2
/* 1FD4CC 801E554C 01596021 */  addu        $t4, $t2, $t9
/* 1FD4D0 801E5550 C5860000 */  lwc1        $f6, 0x0($t4)
/* 1FD4D4 801E5554 E5A60000 */  swc1        $f6, 0x0($t5)
/* 1FD4D8 801E5558 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD4DC 801E555C 00021080 */  sll         $v0, $v0, 2
/* 1FD4E0 801E5560 00E27021 */  addu        $t6, $a3, $v0
/* 1FD4E4 801E5564 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FD4E8 801E5568 01626021 */  addu        $t4, $t3, $v0
/* 1FD4EC 801E556C 000FC080 */  sll         $t8, $t7, 2
/* 1FD4F0 801E5570 0178C821 */  addu        $t9, $t3, $t8
/* 1FD4F4 801E5574 C7280000 */  lwc1        $f8, 0x0($t9)
/* 1FD4F8 801E5578 460A4401 */  sub.s       $f16, $f8, $f10
/* 1FD4FC 801E557C E5900000 */  swc1        $f16, 0x0($t4)
/* 1FD500 801E5580 8C620000 */  lw          $v0, 0x0($v1)
/* 1FD504 801E5584 00021080 */  sll         $v0, $v0, 2
/* 1FD508 801E5588 01026821 */  addu        $t5, $t0, $v0
/* 1FD50C 801E558C C5B20000 */  lwc1        $f18, 0x0($t5)
/* 1FD510 801E5590 01222021 */  addu        $a0, $t1, $v0
/* 1FD514 801E5594 01422821 */  addu        $a1, $t2, $v0
/* 1FD518 801E5598 46049182 */  mul.s       $f6, $f18, $f4
/* 1FD51C 801E559C 44063000 */  mfc1        $a2, $f6
/* 1FD520 801E55A0 0C03E65D */  jal         func_800F9974
/* 1FD524 801E55A4 00000000 */   nop
/* 1FD528 801E55A8 8E0E0000 */  lw          $t6, 0x0($s0)
/* 1FD52C 801E55AC 8FBF001C */  lw          $ra, 0x1C($sp)
/* 1FD530 801E55B0 3C01800E */  lui         $at, %hi(gEntityVtableIndexArray)
/* 1FD534 801E55B4 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FD538 801E55B8 8FB00018 */  lw          $s0, 0x18($sp)
/* 1FD53C 801E55BC 27BD0020 */  addiu       $sp, $sp, 0x20
/* 1FD540 801E55C0 000FC080 */  sll         $t8, $t7, 2
/* 1FD544 801E55C4 00380821 */  addu        $at, $at, $t8
/* 1FD548 801E55C8 03E00008 */  jr          $ra
/* 1FD54C 801E55CC AC20DC50 */   sw         $zero, %lo(gEntityVtableIndexArray)($at)
.size func_801E5458_ovl13, . - func_801E5458_ovl13

glabel func_801E55D0_ovl13 # 71
/* 1FD550 801E55D0 3C0E8005 */  lui         $t6, %hi(D_8004A7C4)
/* 1FD554 801E55D4 8DCEA7C4 */  lw          $t6, %lo(D_8004A7C4)($t6)
/* 1FD558 801E55D8 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FD55C 801E55DC AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FD560 801E55E0 AFA40018 */  sw          $a0, 0x18($sp)
/* 1FD564 801E55E4 8DCF0000 */  lw          $t7, 0x0($t6)
/* 1FD568 801E55E8 3C04800E */  lui         $a0, %hi(D_800DDFD0)
/* 1FD56C 801E55EC 3C06801E */  lui         $a2, %hi(D_801E5C20_ovl13)
/* 1FD570 801E55F0 000FC080 */  sll         $t8, $t7, 2
/* 1FD574 801E55F4 00982021 */  addu        $a0, $a0, $t8
/* 1FD578 801E55F8 8C84DFD0 */  lw          $a0, %lo(D_800DDFD0)($a0)
/* 1FD57C 801E55FC 24C65C20 */  addiu       $a2, $a2, %lo(D_801E5C20_ovl13)
/* 1FD580 801E5600 0C02911F */  jal         call_virtual_function
/* 1FD584 801E5604 24050001 */   addiu      $a1, $zero, 0x1
/* 1FD588 801E5608 8FBF0014 */  lw          $ra, 0x14($sp)
/* 1FD58C 801E560C 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FD590 801E5610 03E00008 */  jr          $ra
/* 1FD594 801E5614 00000000 */   nop
.size func_801E55D0_ovl13, . - func_801E55D0_ovl13

glabel func_801E5618_ovl13 # 72
/* 1FD598 801E5618 27BDFFC0 */  addiu       $sp, $sp, -0x40
/* 1FD59C 801E561C AFB30038 */  sw          $s3, 0x38($sp)
/* 1FD5A0 801E5620 3C138005 */  lui         $s3, %hi(D_8004A7C4)
/* 1FD5A4 801E5624 2673A7C4 */  addiu       $s3, $s3, %lo(D_8004A7C4)
/* 1FD5A8 801E5628 8E620000 */  lw          $v0, 0x0($s3)
/* 1FD5AC 801E562C AFBF003C */  sw          $ra, 0x3C($sp)
/* 1FD5B0 801E5630 AFB20034 */  sw          $s2, 0x34($sp)
/* 1FD5B4 801E5634 AFB10030 */  sw          $s1, 0x30($sp)
/* 1FD5B8 801E5638 AFB0002C */  sw          $s0, 0x2C($sp)
/* 1FD5BC 801E563C F7B80020 */  sdc1        $f24, 0x20($sp)
/* 1FD5C0 801E5640 F7B60018 */  sdc1        $f22, 0x18($sp)
/* 1FD5C4 801E5644 F7B40010 */  sdc1        $f20, 0x10($sp)
/* 1FD5C8 801E5648 AFA40040 */  sw          $a0, 0x40($sp)
/* 1FD5CC 801E564C 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FD5D0 801E5650 3C01800E */  lui         $at, %hi(D_800DDFD0)
/* 1FD5D4 801E5654 3C10800E */  lui         $s0, %hi(D_800E1B50)
/* 1FD5D8 801E5658 000E7880 */  sll         $t7, $t6, 2
/* 1FD5DC 801E565C 002F0821 */  addu        $at, $at, $t7
/* 1FD5E0 801E5660 AC20DFD0 */  sw          $zero, %lo(D_800DDFD0)($at)
/* 1FD5E4 801E5664 8C590000 */  lw          $t9, 0x0($v0)
/* 1FD5E8 801E5668 26101B50 */  addiu       $s0, $s0, %lo(D_800E1B50)
/* 1FD5EC 801E566C 3C18801E */  lui         $t8, %hi(D_801DAD68)
/* 1FD5F0 801E5670 00194080 */  sll         $t0, $t9, 2
/* 1FD5F4 801E5674 02084821 */  addu        $t1, $s0, $t0
/* 1FD5F8 801E5678 8D2A0000 */  lw          $t2, 0x0($t1)
/* 1FD5FC 801E567C 3C11800D */  lui         $s1, %hi(D_800D6B10)
/* 1FD600 801E5680 2718AD68 */  addiu       $t8, $t8, %lo(D_801DAD68)
/* 1FD604 801E5684 26316B10 */  addiu       $s1, $s1, %lo(D_800D6B10)
/* 1FD608 801E5688 AD580098 */  sw          $t8, 0x98($t2)
/* 1FD60C 801E568C 0C02BB30 */  jal         func_800AECC0
/* 1FD610 801E5690 C62C0000 */   lwc1       $f12, 0x0($s1)
/* 1FD614 801E5694 0C02BB48 */  jal         func_800AED20
/* 1FD618 801E5698 C62C0000 */   lwc1       $f12, 0x0($s1)
/* 1FD61C 801E569C 0C02CCFD */  jal         func_800B33F4
/* 1FD620 801E56A0 00000000 */   nop
/* 1FD624 801E56A4 8E620000 */  lw          $v0, 0x0($s3)
/* 1FD628 801E56A8 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FD62C 801E56AC 240DFFFF */  addiu       $t5, $zero, -0x1
/* 1FD630 801E56B0 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FD634 801E56B4 240A01E0 */  addiu       $t2, $zero, 0x1E0
/* 1FD638 801E56B8 3C040001 */  lui         $a0, (0x1001F >> 16)
/* 1FD63C 801E56BC 000B6080 */  sll         $t4, $t3, 2
/* 1FD640 801E56C0 002C0821 */  addu        $at, $at, $t4
/* 1FD644 801E56C4 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FD648 801E56C8 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FD64C 801E56CC 3C01800F */  lui         $at, %hi(D_800E98E0)
/* 1FD650 801E56D0 3484001F */  ori         $a0, $a0, (0x1001F & 0xFFFF)
/* 1FD654 801E56D4 000E7880 */  sll         $t7, $t6, 2
/* 1FD658 801E56D8 020FC821 */  addu        $t9, $s0, $t7
/* 1FD65C 801E56DC 8F280000 */  lw          $t0, 0x0($t9)
/* 1FD660 801E56E0 A10D0039 */  sb          $t5, 0x39($t0)
/* 1FD664 801E56E4 8E620000 */  lw          $v0, 0x0($s3)
/* 1FD668 801E56E8 8C490000 */  lw          $t1, 0x0($v0)
/* 1FD66C 801E56EC 0009C080 */  sll         $t8, $t1, 2
/* 1FD670 801E56F0 00380821 */  addu        $at, $at, $t8
/* 1FD674 801E56F4 AC2098E0 */  sw          $zero, %lo(D_800E98E0)($at)
/* 1FD678 801E56F8 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FD67C 801E56FC 3C01800F */  lui         $at, %hi(D_800E9AA0)
/* 1FD680 801E5700 000B6080 */  sll         $t4, $t3, 2
/* 1FD684 801E5704 002C0821 */  addu        $at, $at, $t4
/* 1FD688 801E5708 0C02A806 */  jal         func_800AA018
/* 1FD68C 801E570C AC2A9AA0 */   sw         $t2, %lo(D_800E9AA0)($at)
/* 1FD690 801E5710 8E620000 */  lw          $v0, 0x0($s3)
/* 1FD694 801E5714 3C01801E */  lui         $at, %hi(D_801E5E30_ovl13)
/* 1FD698 801E5718 C4345E30 */  lwc1        $f20, %lo(D_801E5E30_ovl13)($at)
/* 1FD69C 801E571C 8C430000 */  lw          $v1, 0x0($v0)
/* 1FD6A0 801E5720 3C013F80 */  lui         $at, (0x3F800000 >> 16)
/* 1FD6A4 801E5724 4481C000 */  mtc1        $at, $f24
/* 1FD6A8 801E5728 3C01800E */  lui         $at, %hi(D_800E6A10)
/* 1FD6AC 801E572C 00031880 */  sll         $v1, $v1, 2
/* 1FD6B0 801E5730 00230821 */  addu        $at, $at, $v1
/* 1FD6B4 801E5734 C4246A10 */  lwc1        $f4, %lo(D_800E6A10)($at)
/* 1FD6B8 801E5738 3C014020 */  lui         $at, (0x40200000 >> 16)
/* 1FD6BC 801E573C 44813000 */  mtc1        $at, $f6
/* 1FD6C0 801E5740 4618A03C */  c.lt.s      $f20, $f24
/* 1FD6C4 801E5744 3C01800E */  lui         $at, %hi(D_800E64D0)
/* 1FD6C8 801E5748 46062202 */  mul.s       $f8, $f4, $f6
/* 1FD6CC 801E574C 00230821 */  addu        $at, $at, $v1
/* 1FD6D0 801E5750 3C12800E */  lui         $s2, %hi(gEntitiesScaleYArray)
/* 1FD6D4 801E5754 3C11800E */  lui         $s1, %hi(gEntitiesScaleXArray)
/* 1FD6D8 801E5758 26314550 */  addiu       $s1, $s1, %lo(gEntitiesScaleXArray)
/* 1FD6DC 801E575C 26524710 */  addiu       $s2, $s2, %lo(gEntitiesScaleYArray)
/* 1FD6E0 801E5760 4500001C */  bc1f        L801E57D4_ovl13
/* 1FD6E4 801E5764 E42864D0 */   swc1       $f8, %lo(D_800E64D0)($at)
/* 1FD6E8 801E5768 3C01801E */  lui         $at, %hi(D_801E5E34_ovl13)
/* 1FD6EC 801E576C 3C10800E */  lui         $s0, %hi(gEntitiesScaleZArray)
/* 1FD6F0 801E5770 261048D0 */  addiu       $s0, $s0, %lo(gEntitiesScaleZArray)
/* 1FD6F4 801E5774 C4365E34 */  lwc1        $f22, %lo(D_801E5E34_ovl13)($at)
/* 1FD6F8 801E5778 8E620000 */  lw          $v0, 0x0($s3)
glabel L801E577C_ovl13
/* 1FD6FC 801E577C 24040001 */  addiu       $a0, $zero, 0x1
/* 1FD700 801E5780 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FD704 801E5784 000E7880 */  sll         $t7, $t6, 2
/* 1FD708 801E5788 020FC821 */  addu        $t9, $s0, $t7
/* 1FD70C 801E578C E7340000 */  swc1        $f20, 0x0($t9)
/* 1FD710 801E5790 8C430000 */  lw          $v1, 0x0($v0)
/* 1FD714 801E5794 00031880 */  sll         $v1, $v1, 2
/* 1FD718 801E5798 02036821 */  addu        $t5, $s0, $v1
/* 1FD71C 801E579C C5A00000 */  lwc1        $f0, 0x0($t5)
/* 1FD720 801E57A0 02434021 */  addu        $t0, $s2, $v1
/* 1FD724 801E57A4 E5000000 */  swc1        $f0, 0x0($t0)
/* 1FD728 801E57A8 8C490000 */  lw          $t1, 0x0($v0)
/* 1FD72C 801E57AC 0009C080 */  sll         $t8, $t1, 2
/* 1FD730 801E57B0 02385821 */  addu        $t3, $s1, $t8
/* 1FD734 801E57B4 0C002DAF */  jal         finish_current_thread
/* 1FD738 801E57B8 E5600000 */   swc1       $f0, 0x0($t3)
/* 1FD73C 801E57BC 4616A500 */  add.s       $f20, $f20, $f22
/* 1FD740 801E57C0 4618A03C */  c.lt.s      $f20, $f24
/* 1FD744 801E57C4 00000000 */  nop
/* 1FD748 801E57C8 4503FFEC */  bc1tl       L801E577C_ovl13
/* 1FD74C 801E57CC 8E620000 */   lw         $v0, 0x0($s3)
/* 1FD750 801E57D0 8E620000 */  lw          $v0, 0x0($s3)
glabel L801E57D4_ovl13
/* 1FD754 801E57D4 8C4A0000 */  lw          $t2, 0x0($v0)
/* 1FD758 801E57D8 3C11800E */  lui         $s1, %hi(gEntitiesScaleXArray)
/* 1FD75C 801E57DC 26314550 */  addiu       $s1, $s1, %lo(gEntitiesScaleXArray)
/* 1FD760 801E57E0 000A6080 */  sll         $t4, $t2, 2
/* 1FD764 801E57E4 022C7021 */  addu        $t6, $s1, $t4
/* 1FD768 801E57E8 E5D80000 */  swc1        $f24, 0x0($t6)
/* 1FD76C 801E57EC 8C4F0000 */  lw          $t7, 0x0($v0)
/* 1FD770 801E57F0 44805000 */  mtc1        $zero, $f10
/* 1FD774 801E57F4 3C01800E */  lui         $at, %hi(D_800E3210)
/* 1FD778 801E57F8 000FC880 */  sll         $t9, $t7, 2
/* 1FD77C 801E57FC 02391821 */  addu        $v1, $s1, $t9
/* 1FD780 801E5800 C4600000 */  lwc1        $f0, 0x0($v1)
/* 1FD784 801E5804 3C04800F */  lui         $a0, %hi(D_800E9AA0)
/* 1FD788 801E5808 E4600000 */  swc1        $f0, 0x0($v1)
/* 1FD78C 801E580C 8C4D0000 */  lw          $t5, 0x0($v0)
/* 1FD790 801E5810 000D4080 */  sll         $t0, $t5, 2
/* 1FD794 801E5814 02284821 */  addu        $t1, $s1, $t0
/* 1FD798 801E5818 E5200000 */  swc1        $f0, 0x0($t1)
/* 1FD79C 801E581C 8C580000 */  lw          $t8, 0x0($v0)
/* 1FD7A0 801E5820 00185880 */  sll         $t3, $t8, 2
/* 1FD7A4 801E5824 002B0821 */  addu        $at, $at, $t3
/* 1FD7A8 801E5828 E42A3210 */  swc1        $f10, %lo(D_800E3210)($at)
/* 1FD7AC 801E582C 8C4A0000 */  lw          $t2, 0x0($v0)
/* 1FD7B0 801E5830 3C01801E */  lui         $at, %hi(D_801E5E38_ovl13)
/* 1FD7B4 801E5834 C4305E38 */  lwc1        $f16, %lo(D_801E5E38_ovl13)($at)
/* 1FD7B8 801E5838 3C01800E */  lui         $at, %hi(D_800E3750)
/* 1FD7BC 801E583C 000A6080 */  sll         $t4, $t2, 2
/* 1FD7C0 801E5840 002C0821 */  addu        $at, $at, $t4
/* 1FD7C4 801E5844 E4303750 */  swc1        $f16, %lo(D_800E3750)($at)
/* 1FD7C8 801E5848 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FD7CC 801E584C 3C0140B0 */  lui         $at, (0x40B00000 >> 16)
/* 1FD7D0 801E5850 44819000 */  mtc1        $at, $f18
/* 1FD7D4 801E5854 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FD7D8 801E5858 000E7880 */  sll         $t7, $t6, 2
/* 1FD7DC 801E585C 002F0821 */  addu        $at, $at, $t7
/* 1FD7E0 801E5860 E4323C90 */  swc1        $f18, %lo(D_800E3C90)($at)
/* 1FD7E4 801E5864 8C590000 */  lw          $t9, 0x0($v0)
/* 1FD7E8 801E5868 00196880 */  sll         $t5, $t9, 2
/* 1FD7EC 801E586C 008D2021 */  addu        $a0, $a0, $t5
/* 1FD7F0 801E5870 0C002DAF */  jal         finish_current_thread
/* 1FD7F4 801E5874 8C849AA0 */   lw         $a0, %lo(D_800E9AA0)($a0)
/* 1FD7F8 801E5878 8E690000 */  lw          $t1, 0x0($s3)
/* 1FD7FC 801E587C 3C01800E */  lui         $at, %hi(gEntityVtableIndexArray)
/* 1FD800 801E5880 2408FFFF */  addiu       $t0, $zero, -0x1
/* 1FD804 801E5884 8D380000 */  lw          $t8, 0x0($t1)
/* 1FD808 801E5888 8FA40040 */  lw          $a0, 0x40($sp)
/* 1FD80C 801E588C 00185880 */  sll         $t3, $t8, 2
/* 1FD810 801E5890 002B0821 */  addu        $at, $at, $t3
/* 1FD814 801E5894 0C068FA0 */  jal         func_801A3E80
/* 1FD818 801E5898 AC28DC50 */   sw         $t0, %lo(gEntityVtableIndexArray)($at)
/* 1FD81C 801E589C 8FBF003C */  lw          $ra, 0x3C($sp)
/* 1FD820 801E58A0 D7B40010 */  ldc1        $f20, 0x10($sp)
/* 1FD824 801E58A4 D7B60018 */  ldc1        $f22, 0x18($sp)
/* 1FD828 801E58A8 D7B80020 */  ldc1        $f24, 0x20($sp)
/* 1FD82C 801E58AC 8FB0002C */  lw          $s0, 0x2C($sp)
/* 1FD830 801E58B0 8FB10030 */  lw          $s1, 0x30($sp)
/* 1FD834 801E58B4 8FB20034 */  lw          $s2, 0x34($sp)
/* 1FD838 801E58B8 8FB30038 */  lw          $s3, 0x38($sp)
/* 1FD83C 801E58BC 03E00008 */  jr          $ra
/* 1FD840 801E58C0 27BD0040 */   addiu      $sp, $sp, 0x40
.size func_801E5618_ovl13, . - func_801E5618_ovl13

glabel func_801E58C4_ovl13 # 73
/* 1FD844 801E58C4 3C038005 */  lui         $v1, %hi(D_8004A7C4)
/* 1FD848 801E58C8 8C63A7C4 */  lw          $v1, %lo(D_8004A7C4)($v1)
/* 1FD84C 801E58CC 27BDFFE8 */  addiu       $sp, $sp, -0x18
/* 1FD850 801E58D0 AFBF0014 */  sw          $ra, 0x14($sp)
/* 1FD854 801E58D4 AFA40018 */  sw          $a0, 0x18($sp)
/* 1FD858 801E58D8 8C6E0000 */  lw          $t6, 0x0($v1)
/* 1FD85C 801E58DC 3C05800F */  lui         $a1, %hi(D_800E98E0)
/* 1FD860 801E58E0 24A598E0 */  addiu       $a1, $a1, %lo(D_800E98E0)
/* 1FD864 801E58E4 000E7880 */  sll         $t7, $t6, 2
/* 1FD868 801E58E8 00AF1021 */  addu        $v0, $a1, $t7
/* 1FD86C 801E58EC 8C580000 */  lw          $t8, 0x0($v0)
/* 1FD870 801E58F0 24010005 */  addiu       $at, $zero, 0x5
/* 1FD874 801E58F4 3C0F800E */  lui         $t7, %hi(D_800DFBD0)
/* 1FD878 801E58F8 27190001 */  addiu       $t9, $t8, 0x1
/* 1FD87C 801E58FC AC590000 */  sw          $t9, 0x0($v0)
/* 1FD880 801E5900 8C690000 */  lw          $t1, 0x0($v1)
/* 1FD884 801E5904 24040006 */  addiu       $a0, $zero, 0x6
/* 1FD888 801E5908 00095080 */  sll         $t2, $t1, 2
/* 1FD88C 801E590C 00AA1021 */  addu        $v0, $a1, $t2
/* 1FD890 801E5910 8C4B0000 */  lw          $t3, 0x0($v0)
/* 1FD894 801E5914 0161001A */  div         $zero, $t3, $at
/* 1FD898 801E5918 00006010 */  mfhi        $t4
/* 1FD89C 801E591C AC4C0000 */  sw          $t4, 0x0($v0)
/* 1FD8A0 801E5920 8C680000 */  lw          $t0, 0x0($v1)
/* 1FD8A4 801E5924 00084080 */  sll         $t0, $t0, 2
/* 1FD8A8 801E5928 00A86821 */  addu        $t5, $a1, $t0
/* 1FD8AC 801E592C 8DAE0000 */  lw          $t6, 0x0($t5)
/* 1FD8B0 801E5930 24050002 */  addiu       $a1, $zero, 0x2
/* 1FD8B4 801E5934 01E87821 */  addu        $t7, $t7, $t0
/* 1FD8B8 801E5938 15C00009 */  bnez        $t6, L801E5960_ovl13
/* 1FD8BC 801E593C 00000000 */   nop
/* 1FD8C0 801E5940 8DEFFBD0 */  lw          $t7, %lo(D_800DFBD0)($t7)
/* 1FD8C4 801E5944 00003025 */  move        $a2, $zero
/* 1FD8C8 801E5948 0C02A040 */  jal         func_800A8100
/* 1FD8CC 801E594C 8DE70000 */   lw         $a3, 0x0($t7)
/* 1FD8D0 801E5950 3C038005 */  lui         $v1, %hi(D_8004A7C4)
/* 1FD8D4 801E5954 8C63A7C4 */  lw          $v1, %lo(D_8004A7C4)($v1)
/* 1FD8D8 801E5958 8C680000 */  lw          $t0, 0x0($v1)
/* 1FD8DC 801E595C 00084080 */  sll         $t0, $t0, 2
glabel L801E5960_ovl13
/* 1FD8E0 801E5960 3C18800E */  lui         $t8, %hi(gEntitiesNextPosYArray)
/* 1FD8E4 801E5964 27182790 */  addiu       $t8, $t8, %lo(gEntitiesNextPosYArray)
/* 1FD8E8 801E5968 3C014190 */  lui         $at, (0x41900000 >> 16)
/* 1FD8EC 801E596C 01181021 */  addu        $v0, $t0, $t8
/* 1FD8F0 801E5970 44811000 */  mtc1        $at, $f2
/* 1FD8F4 801E5974 C4440000 */  lwc1        $f4, 0x0($v0)
/* 1FD8F8 801E5978 3C0140B0 */  lui         $at, (0x40B00000 >> 16)
/* 1FD8FC 801E597C 4602203C */  c.lt.s      $f4, $f2
/* 1FD900 801E5980 00000000 */  nop
/* 1FD904 801E5984 45020015 */  bc1fl       L801E59DC_ovl13
/* 1FD908 801E5988 8FAE0018 */   lw         $t6, 0x18($sp)
/* 1FD90C 801E598C E4420000 */  swc1        $f2, 0x0($v0)
/* 1FD910 801E5990 8C790000 */  lw          $t9, 0x0($v1)
/* 1FD914 801E5994 44810000 */  mtc1        $at, $f0
/* 1FD918 801E5998 3C01800E */  lui         $at, %hi(D_800E3210)
/* 1FD91C 801E599C 00194880 */  sll         $t1, $t9, 2
/* 1FD920 801E59A0 00290821 */  addu        $at, $at, $t1
/* 1FD924 801E59A4 E4203210 */  swc1        $f0, %lo(D_800E3210)($at)
/* 1FD928 801E59A8 8C6A0000 */  lw          $t2, 0x0($v1)
/* 1FD92C 801E59AC 3C01801E */  lui         $at, %hi(D_801E5E3C_ovl13)
/* 1FD930 801E59B0 C4265E3C */  lwc1        $f6, %lo(D_801E5E3C_ovl13)($at)
/* 1FD934 801E59B4 3C01800E */  lui         $at, %hi(D_800E3750)
/* 1FD938 801E59B8 000A5880 */  sll         $t3, $t2, 2
/* 1FD93C 801E59BC 002B0821 */  addu        $at, $at, $t3
/* 1FD940 801E59C0 E4263750 */  swc1        $f6, %lo(D_800E3750)($at)
/* 1FD944 801E59C4 8C6C0000 */  lw          $t4, 0x0($v1)
/* 1FD948 801E59C8 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FD94C 801E59CC 000C6880 */  sll         $t5, $t4, 2
/* 1FD950 801E59D0 002D0821 */  addu        $at, $at, $t5
/* 1FD954 801E59D4 E4203C90 */  swc1        $f0, %lo(D_800E3C90)($at)
/* 1FD958 801E59D8 8FAE0018 */  lw          $t6, 0x18($sp)
glabel L801E59DC_ovl13
/* 1FD95C 801E59DC 8DCF0044 */  lw          $t7, 0x44($t6)
/* 1FD960 801E59E0 31F80001 */  andi        $t8, $t7, 0x1
/* 1FD964 801E59E4 57000004 */  bnel        $t8, $zero, L801E59F8_ovl13
/* 1FD968 801E59E8 8FBF0014 */   lw         $ra, 0x14($sp)
/* 1FD96C 801E59EC 0C067CEC */  jal         func_8019F3B0
/* 1FD970 801E59F0 00000000 */   nop
/* 1FD974 801E59F4 8FBF0014 */  lw          $ra, 0x14($sp)
glabel L801E59F8_ovl13
/* 1FD978 801E59F8 27BD0018 */  addiu       $sp, $sp, 0x18
/* 1FD97C 801E59FC 03E00008 */  jr          $ra
/* 1FD980 801E5A00 00000000 */   nop
.size func_801E58C4_ovl13, . - func_801E58C4_ovl13

glabel func_801E5A04_ovl13 # 74
/* 1FD984 801E5A04 3C028005 */  lui         $v0, %hi(D_8004A7C4)
/* 1FD988 801E5A08 8C42A7C4 */  lw          $v0, %lo(D_8004A7C4)($v0)
/* 1FD98C 801E5A0C AFA40000 */  sw          $a0, 0x0($sp)
/* 1FD990 801E5A10 3C0140B0 */  lui         $at, (0x40B00000 >> 16)
/* 1FD994 801E5A14 8C4E0000 */  lw          $t6, 0x0($v0)
/* 1FD998 801E5A18 44810000 */  mtc1        $at, $f0
/* 1FD99C 801E5A1C 3C01800F */  lui         $at, %hi(D_800E8920)
/* 1FD9A0 801E5A20 000E7880 */  sll         $t7, $t6, 2
/* 1FD9A4 801E5A24 002F0821 */  addu        $at, $at, $t7
/* 1FD9A8 801E5A28 AC208920 */  sw          $zero, %lo(D_800E8920)($at)
/* 1FD9AC 801E5A2C 8C580000 */  lw          $t8, 0x0($v0)
/* 1FD9B0 801E5A30 3C01800E */  lui         $at, %hi(D_800E3210)
/* 1FD9B4 801E5A34 0018C880 */  sll         $t9, $t8, 2
/* 1FD9B8 801E5A38 00390821 */  addu        $at, $at, $t9
/* 1FD9BC 801E5A3C E4203210 */  swc1        $f0, %lo(D_800E3210)($at)
/* 1FD9C0 801E5A40 8C480000 */  lw          $t0, 0x0($v0)
/* 1FD9C4 801E5A44 3C01801E */  lui         $at, %hi(D_801E5E40_ovl13)
/* 1FD9C8 801E5A48 C4245E40 */  lwc1        $f4, %lo(D_801E5E40_ovl13)($at)
/* 1FD9CC 801E5A4C 3C01800E */  lui         $at, %hi(D_800E3750)
/* 1FD9D0 801E5A50 00084880 */  sll         $t1, $t0, 2
/* 1FD9D4 801E5A54 00290821 */  addu        $at, $at, $t1
/* 1FD9D8 801E5A58 E4243750 */  swc1        $f4, %lo(D_800E3750)($at)
/* 1FD9DC 801E5A5C 8C4A0000 */  lw          $t2, 0x0($v0)
/* 1FD9E0 801E5A60 3C01800E */  lui         $at, %hi(D_800E3C90)
/* 1FD9E4 801E5A64 000A5880 */  sll         $t3, $t2, 2
/* 1FD9E8 801E5A68 002B0821 */  addu        $at, $at, $t3
/* 1FD9EC 801E5A6C 03E00008 */  jr          $ra
/* 1FD9F0 801E5A70 E4203C90 */   swc1       $f0, %lo(D_800E3C90)($at)
/* 1FD9F4 801E5A74 00000000 */  nop
/* 1FD9F8 801E5A78 00000000 */  nop
/* 1FD9FC 801E5A7C 00000000 */  nop
.size func_801E5A04_ovl13, . - func_801E5A04_ovl13
