MISC_BANK_0_FILES := \
    assets/misc/bank_0/1/block.bin \
    assets/misc/bank_0/2/block.bin \
    assets/misc/bank_0/3/block.bin \
    assets/misc/bank_0/4/block.bin

MISC_BANK_1_FILES := \
    assets/misc/bank_1/1/block.bin \
    assets/misc/bank_1/2/block.bin

MISC_BANK_2_FILES := \
    assets/misc/bank_2/1/block.bin \
    assets/misc/bank_2/2/block.bin

MISC_BANK_3_FILES := \
    assets/misc/bank_3/1/block.bin \
    assets/misc/bank_3/2/block.bin \
    assets/misc/bank_3/3/block.bin \
    assets/misc/bank_3/4/block.bin \
    assets/misc/bank_3/5/block.bin \
    assets/misc/bank_3/6/block.bin \
    assets/misc/bank_3/7/block.bin \
    assets/misc/bank_3/8/block.bin \
    assets/misc/bank_3/9/block.bin \
    assets/misc/bank_3/10/block.bin \
    assets/misc/bank_3/11/block.bin \
    assets/misc/bank_3/12/block.bin \
    assets/misc/bank_3/13/block.bin \
    assets/misc/bank_3/14/block.bin \
    assets/misc/bank_3/15/block.bin \
    assets/misc/bank_3/16/block.bin \
    assets/misc/bank_3/17/block.bin \
    assets/misc/bank_3/18/block.bin \
    assets/misc/bank_3/19/block.bin \
    assets/misc/bank_3/20/block.bin \
    assets/misc/bank_3/21/block.bin

MISC_BANK_4_FILES := \
    assets/misc/bank_4/1/block.bin \
    assets/misc/bank_4/2/block.bin

MISC_BANK_6_FILES := \
    assets/misc/bank_6/1/block.bin \
    assets/misc/bank_6/2/block.bin \
    assets/misc/bank_6/3/block.bin \
    assets/misc/bank_6/4/block.bin \
    assets/misc/bank_6/5/block.bin \
    assets/misc/bank_6/6/block.bin \
    assets/misc/bank_6/7/block.bin \
    assets/misc/bank_6/8/block.bin \
    assets/misc/bank_6/9/block.bin \
    assets/misc/bank_6/10/block.bin \
    assets/misc/bank_6/11/block.bin \
    assets/misc/bank_6/12/block.bin \
    assets/misc/bank_6/13/block.bin \
    assets/misc/bank_6/14/block.bin \
    assets/misc/bank_6/15/block.bin \
    assets/misc/bank_6/16/block.bin \
    assets/misc/bank_6/17/block.bin \
    assets/misc/bank_6/18/block.bin \
    assets/misc/bank_6/19/block.bin \
    assets/misc/bank_6/20/block.bin \
    assets/misc/bank_6/21/block.bin \
    assets/misc/bank_6/22/block.bin \
    assets/misc/bank_6/23/block.bin \
    assets/misc/bank_6/24/block.bin \
    assets/misc/bank_6/25/block.bin \
    assets/misc/bank_6/26/block.bin \
    assets/misc/bank_6/27/block.bin \
    assets/misc/bank_6/28/block.bin \
    assets/misc/bank_6/29/block.bin \
    assets/misc/bank_6/30/block.bin \
    assets/misc/bank_6/31/block.bin \
    assets/misc/bank_6/32/block.bin \
    assets/misc/bank_6/33/block.bin \
    assets/misc/bank_6/34/block.bin \
    assets/misc/bank_6/35/block.bin \
    assets/misc/bank_6/36/block.bin \
    assets/misc/bank_6/37/block.bin \
    assets/misc/bank_6/38/block.bin \
    assets/misc/bank_6/39/block.bin \
    assets/misc/bank_6/40/block.bin \
    assets/misc/bank_6/41/block.bin \
    assets/misc/bank_6/42/block.bin \
    assets/misc/bank_6/43/block.bin \
    assets/misc/bank_6/44/block.bin \
    assets/misc/bank_6/45/block.bin \
    assets/misc/bank_6/46/block.bin \
    assets/misc/bank_6/47/block.bin \
    assets/misc/bank_6/48/block.bin \
    assets/misc/bank_6/49/block.bin \
    assets/misc/bank_6/50/block.bin \
    assets/misc/bank_6/51/block.bin \
    assets/misc/bank_6/52/block.bin \
    assets/misc/bank_6/53/block.bin \
    assets/misc/bank_6/54/block.bin \
    assets/misc/bank_6/55/block.bin \
    assets/misc/bank_6/56/block.bin \
    assets/misc/bank_6/57/block.bin \
    assets/misc/bank_6/58/block.bin \
    assets/misc/bank_6/59/block.bin \
    assets/misc/bank_6/60/block.bin \
    assets/misc/bank_6/61/block.bin \
    assets/misc/bank_6/62/block.bin \
    assets/misc/bank_6/63/block.bin \
    assets/misc/bank_6/64/block.bin \
    assets/misc/bank_6/65/block.bin \
    assets/misc/bank_6/66/block.bin \
    assets/misc/bank_6/67/block.bin \
    assets/misc/bank_6/68/block.bin \
    assets/misc/bank_6/69/block.bin \
    assets/misc/bank_6/70/block.bin \
    assets/misc/bank_6/71/block.bin \
    assets/misc/bank_6/72/block.bin \
    assets/misc/bank_6/73/block.bin \
    assets/misc/bank_6/74/block.bin \
    assets/misc/bank_6/75/block.bin \
    assets/misc/bank_6/76/block.bin \
    assets/misc/bank_6/77/block.bin \
    assets/misc/bank_6/78/block.bin \
    assets/misc/bank_6/79/block.bin \
    assets/misc/bank_6/80/block.bin \
    assets/misc/bank_6/81/block.bin \
    assets/misc/bank_6/82/block.bin \
    assets/misc/bank_6/83/block.bin \
    assets/misc/bank_6/84/block.bin \
    assets/misc/bank_6/85/block.bin \
    assets/misc/bank_6/86/block.bin \
    assets/misc/bank_6/87/block.bin \
    assets/misc/bank_6/88/block.bin \
    assets/misc/bank_6/89/block.bin \
    assets/misc/bank_6/90/block.bin \
    assets/misc/bank_6/91/block.bin \
    assets/misc/bank_6/92/block.bin \
    assets/misc/bank_6/93/block.bin \
    assets/misc/bank_6/94/block.bin \
    assets/misc/bank_6/95/block.bin \
    assets/misc/bank_6/96/block.bin \
    assets/misc/bank_6/97/block.bin \
    assets/misc/bank_6/98/block.bin \
    assets/misc/bank_6/99/block.bin \
    assets/misc/bank_6/100/block.bin \
    assets/misc/bank_6/101/block.bin \
    assets/misc/bank_6/102/block.bin \
    assets/misc/bank_6/103/block.bin \
    assets/misc/bank_6/104/block.bin \
    assets/misc/bank_6/105/block.bin \
    assets/misc/bank_6/106/block.bin \
    assets/misc/bank_6/107/block.bin \
    assets/misc/bank_6/108/block.bin \
    assets/misc/bank_6/109/block.bin \
    assets/misc/bank_6/110/block.bin \
    assets/misc/bank_6/111/block.bin \
    assets/misc/bank_6/112/block.bin \
    assets/misc/bank_6/113/block.bin \
    assets/misc/bank_6/114/block.bin \
    assets/misc/bank_6/115/block.bin \
    assets/misc/bank_6/116/block.bin \
    assets/misc/bank_6/117/block.bin \
    assets/misc/bank_6/118/block.bin \
    assets/misc/bank_6/119/block.bin \
    assets/misc/bank_6/120/block.bin \
    assets/misc/bank_6/121/block.bin \
    assets/misc/bank_6/122/block.bin \
    assets/misc/bank_6/123/block.bin \
    assets/misc/bank_6/124/block.bin \
    assets/misc/bank_6/125/block.bin \
    assets/misc/bank_6/126/block.bin \
    assets/misc/bank_6/127/block.bin \
    assets/misc/bank_6/128/block.bin \
    assets/misc/bank_6/129/block.bin \
    assets/misc/bank_6/130/block.bin \
    assets/misc/bank_6/131/block.bin \
    assets/misc/bank_6/132/block.bin \
    assets/misc/bank_6/133/block.bin \
    assets/misc/bank_6/134/block.bin \
    assets/misc/bank_6/135/block.bin \
    assets/misc/bank_6/136/block.bin \
    assets/misc/bank_6/137/block.bin \
    assets/misc/bank_6/138/block.bin \
    assets/misc/bank_6/139/block.bin \
    assets/misc/bank_6/140/block.bin \
    assets/misc/bank_6/141/block.bin \
    assets/misc/bank_6/142/block.bin \
    assets/misc/bank_6/143/block.bin \
    assets/misc/bank_6/144/block.bin \
    assets/misc/bank_6/145/block.bin \
    assets/misc/bank_6/146/block.bin \
    assets/misc/bank_6/147/block.bin \
    assets/misc/bank_6/148/block.bin \
    assets/misc/bank_6/149/block.bin \
    assets/misc/bank_6/150/block.bin \
    assets/misc/bank_6/151/block.bin \
    assets/misc/bank_6/152/block.bin \
    assets/misc/bank_6/153/block.bin \
    assets/misc/bank_6/154/block.bin \
    assets/misc/bank_6/155/block.bin \
    assets/misc/bank_6/156/block.bin \
    assets/misc/bank_6/157/block.bin \
    assets/misc/bank_6/158/block.bin \
    assets/misc/bank_6/159/block.bin \
    assets/misc/bank_6/160/block.bin \
    assets/misc/bank_6/161/block.bin \
    assets/misc/bank_6/162/block.bin \
    assets/misc/bank_6/163/block.bin \
    assets/misc/bank_6/164/block.bin \
    assets/misc/bank_6/165/block.bin \
    assets/misc/bank_6/166/block.bin \
    assets/misc/bank_6/167/block.bin \
    assets/misc/bank_6/168/block.bin \
    assets/misc/bank_6/169/block.bin \
    assets/misc/bank_6/170/block.bin \
    assets/misc/bank_6/171/block.bin \
    assets/misc/bank_6/172/block.bin \
    assets/misc/bank_6/173/block.bin \
    assets/misc/bank_6/174/block.bin \
    assets/misc/bank_6/175/block.bin \
    assets/misc/bank_6/176/block.bin \
    assets/misc/bank_6/177/block.bin \
    assets/misc/bank_6/178/block.bin \
    assets/misc/bank_6/179/block.bin \
    assets/misc/bank_6/180/block.bin \
    assets/misc/bank_6/181/block.bin \
    assets/misc/bank_6/182/block.bin \
    assets/misc/bank_6/183/block.bin \
    assets/misc/bank_6/184/block.bin \
    assets/misc/bank_6/185/block.bin \
    assets/misc/bank_6/186/block.bin \
    assets/misc/bank_6/187/block.bin \
    assets/misc/bank_6/188/block.bin \
    assets/misc/bank_6/189/block.bin \
    assets/misc/bank_6/190/block.bin \
    assets/misc/bank_6/191/block.bin \
    assets/misc/bank_6/192/block.bin \
    assets/misc/bank_6/193/block.bin \
    assets/misc/bank_6/194/block.bin \
    assets/misc/bank_6/195/block.bin \
    assets/misc/bank_6/196/block.bin \
    assets/misc/bank_6/197/block.bin \
    assets/misc/bank_6/198/block.bin \
    assets/misc/bank_6/199/block.bin \
    assets/misc/bank_6/200/block.bin \
    assets/misc/bank_6/201/block.bin \
    assets/misc/bank_6/202/block.bin \
    assets/misc/bank_6/203/block.bin \
    assets/misc/bank_6/204/block.bin \
    assets/misc/bank_6/205/block.bin \
    assets/misc/bank_6/206/block.bin \
    assets/misc/bank_6/207/block.bin \
    assets/misc/bank_6/208/block.bin \
    assets/misc/bank_6/209/block.bin \
    assets/misc/bank_6/210/block.bin \
    assets/misc/bank_6/211/block.bin \
    assets/misc/bank_6/212/block.bin \
    assets/misc/bank_6/213/block.bin \
    assets/misc/bank_6/214/block.bin \
    assets/misc/bank_6/215/block.bin \
    assets/misc/bank_6/216/block.bin \
    assets/misc/bank_6/217/block.bin \
    assets/misc/bank_6/218/block.bin \
    assets/misc/bank_6/219/block.bin \
    assets/misc/bank_6/220/block.bin \
    assets/misc/bank_6/221/block.bin \
    assets/misc/bank_6/222/block.bin \
    assets/misc/bank_6/223/block.bin \
    assets/misc/bank_6/224/block.bin \
    assets/misc/bank_6/225/block.bin \
    assets/misc/bank_6/226/block.bin \
    assets/misc/bank_6/227/block.bin \
    assets/misc/bank_6/228/block.bin \
    assets/misc/bank_6/229/block.bin \
    assets/misc/bank_6/230/block.bin \
    assets/misc/bank_6/231/block.bin \
    assets/misc/bank_6/232/block.bin \
    assets/misc/bank_6/233/block.bin \
    assets/misc/bank_6/234/block.bin \
    assets/misc/bank_6/235/block.bin \
    assets/misc/bank_6/236/block.bin \
    assets/misc/bank_6/237/block.bin \
    assets/misc/bank_6/238/block.bin \
    assets/misc/bank_6/239/block.bin \
    assets/misc/bank_6/240/block.bin \
    assets/misc/bank_6/241/block.bin \
    assets/misc/bank_6/242/block.bin \
    assets/misc/bank_6/243/block.bin \
    assets/misc/bank_6/244/block.bin \
    assets/misc/bank_6/245/block.bin \
    assets/misc/bank_6/246/block.bin \
    assets/misc/bank_6/247/block.bin \
    assets/misc/bank_6/248/block.bin \
    assets/misc/bank_6/249/block.bin \
    assets/misc/bank_6/250/block.bin \
    assets/misc/bank_6/251/block.bin \
    assets/misc/bank_6/252/block.bin \
    assets/misc/bank_6/253/block.bin \
    assets/misc/bank_6/254/block.bin \
    assets/misc/bank_6/255/block.bin \
    assets/misc/bank_6/256/block.bin \
    assets/misc/bank_6/257/block.bin \
    assets/misc/bank_6/258/block.bin \
    assets/misc/bank_6/259/block.bin \
    assets/misc/bank_6/260/block.bin \
    assets/misc/bank_6/261/block.bin \
    assets/misc/bank_6/262/block.bin \
    assets/misc/bank_6/263/block.bin \
    assets/misc/bank_6/264/block.bin \
    assets/misc/bank_6/265/block.bin \
    assets/misc/bank_6/266/block.bin \
    assets/misc/bank_6/267/block.bin \
    assets/misc/bank_6/268/block.bin \
    assets/misc/bank_6/269/block.bin \
    assets/misc/bank_6/270/block.bin \
    assets/misc/bank_6/271/block.bin \
    assets/misc/bank_6/272/block.bin \
    assets/misc/bank_6/273/block.bin \
    assets/misc/bank_6/274/block.bin \
    assets/misc/bank_6/275/block.bin \
    assets/misc/bank_6/276/block.bin

MISC_BANK_7_FILES := \
    assets/misc/bank_7/1/block.bin \
    assets/misc/bank_7/2/block.bin \
    assets/misc/bank_7/3/block.bin \
    assets/misc/bank_7/4/block.bin \
    assets/misc/bank_7/5/block.bin \
    assets/misc/bank_7/6/block.bin \
    assets/misc/bank_7/7/block.bin \
    assets/misc/bank_7/8/block.bin \
    assets/misc/bank_7/9/block.bin \
    assets/misc/bank_7/10/block.bin \
    assets/misc/bank_7/11/block.bin \
    assets/misc/bank_7/12/block.bin \
    assets/misc/bank_7/13/block.bin \
    assets/misc/bank_7/14/block.bin \
    assets/misc/bank_7/15/block.bin \
    assets/misc/bank_7/16/block.bin \
    assets/misc/bank_7/17/block.bin \
    assets/misc/bank_7/18/block.bin \
    assets/misc/bank_7/19/block.bin \
    assets/misc/bank_7/20/block.bin \
    assets/misc/bank_7/21/block.bin \
    assets/misc/bank_7/22/block.bin \
    assets/misc/bank_7/23/block.bin \
    assets/misc/bank_7/24/block.bin \
    assets/misc/bank_7/25/block.bin \
    assets/misc/bank_7/26/block.bin \
    assets/misc/bank_7/27/block.bin \
    assets/misc/bank_7/28/block.bin \
    assets/misc/bank_7/29/block.bin \
    assets/misc/bank_7/30/block.bin \
    assets/misc/bank_7/31/block.bin \
    assets/misc/bank_7/32/block.bin \
    assets/misc/bank_7/33/block.bin \
    assets/misc/bank_7/34/block.bin \
    assets/misc/bank_7/35/block.bin \
    assets/misc/bank_7/36/block.bin \
    assets/misc/bank_7/37/block.bin \
    assets/misc/bank_7/38/block.bin \
    assets/misc/bank_7/39/block.bin \
    assets/misc/bank_7/40/block.bin \
    assets/misc/bank_7/41/block.bin \
    assets/misc/bank_7/42/block.bin \
    assets/misc/bank_7/43/block.bin \
    assets/misc/bank_7/44/block.bin \
    assets/misc/bank_7/45/block.bin \
    assets/misc/bank_7/46/block.bin \
    assets/misc/bank_7/47/block.bin \
    assets/misc/bank_7/48/block.bin \
    assets/misc/bank_7/49/block.bin \
    assets/misc/bank_7/50/block.bin \
    assets/misc/bank_7/51/block.bin \
    assets/misc/bank_7/52/block.bin \
    assets/misc/bank_7/53/block.bin \
    assets/misc/bank_7/54/block.bin \
    assets/misc/bank_7/55/block.bin \
    assets/misc/bank_7/56/block.bin \
    assets/misc/bank_7/57/block.bin \
    assets/misc/bank_7/58/block.bin \
    assets/misc/bank_7/59/level.bin \
    assets/misc/bank_7/60/level.bin \
    assets/misc/bank_7/61/level.bin \
    assets/misc/bank_7/62/level.bin \
    assets/misc/bank_7/63/level.bin \
    assets/misc/bank_7/64/level.bin \
    assets/misc/bank_7/65/level.bin \
    assets/misc/bank_7/66/level.bin \
    assets/misc/bank_7/67/level.bin \
    assets/misc/bank_7/68/level.bin \
    assets/misc/bank_7/69/level.bin \
    assets/misc/bank_7/70/level.bin \
    assets/misc/bank_7/71/level.bin \
    assets/misc/bank_7/72/level.bin \
    assets/misc/bank_7/73/level.bin \
    assets/misc/bank_7/74/level.bin \
    assets/misc/bank_7/75/level.bin \
    assets/misc/bank_7/76/level.bin \
    assets/misc/bank_7/77/level.bin \
    assets/misc/bank_7/78/level.bin \
    assets/misc/bank_7/79/level.bin \
    assets/misc/bank_7/80/level.bin \
    assets/misc/bank_7/81/level.bin \
    assets/misc/bank_7/82/level.bin \
    assets/misc/bank_7/83/level.bin \
    assets/misc/bank_7/84/level.bin \
    assets/misc/bank_7/85/level.bin \
    assets/misc/bank_7/86/level.bin \
    assets/misc/bank_7/87/level.bin \
    assets/misc/bank_7/88/level.bin \
    assets/misc/bank_7/89/level.bin \
    assets/misc/bank_7/90/level.bin \
    assets/misc/bank_7/91/level.bin \
    assets/misc/bank_7/92/level.bin \
    assets/misc/bank_7/93/level.bin \
    assets/misc/bank_7/94/level.bin \
    assets/misc/bank_7/95/level.bin \
    assets/misc/bank_7/96/level.bin \
    assets/misc/bank_7/97/level.bin \
    assets/misc/bank_7/98/level.bin \
    assets/misc/bank_7/99/level.bin \
    assets/misc/bank_7/100/level.bin \
    assets/misc/bank_7/101/level.bin \
    assets/misc/bank_7/102/level.bin \
    assets/misc/bank_7/103/level.bin \
    assets/misc/bank_7/104/level.bin \
    assets/misc/bank_7/105/level.bin \
    assets/misc/bank_7/106/level.bin \
    assets/misc/bank_7/107/level.bin \
    assets/misc/bank_7/108/level.bin \
    assets/misc/bank_7/109/level.bin \
    assets/misc/bank_7/110/level.bin \
    assets/misc/bank_7/111/level.bin \
    assets/misc/bank_7/112/level.bin \
    assets/misc/bank_7/113/level.bin \
    assets/misc/bank_7/114/level.bin \
    assets/misc/bank_7/115/level.bin \
    assets/misc/bank_7/116/level.bin \
    assets/misc/bank_7/117/level.bin \
    assets/misc/bank_7/118/level.bin \
    assets/misc/bank_7/119/level.bin \
    assets/misc/bank_7/120/level.bin \
    assets/misc/bank_7/121/level.bin \
    assets/misc/bank_7/122/level.bin \
    assets/misc/bank_7/123/level.bin \
    assets/misc/bank_7/124/level.bin \
    assets/misc/bank_7/125/level.bin \
    assets/misc/bank_7/126/level.bin \
    assets/misc/bank_7/127/level.bin \
    assets/misc/bank_7/128/level.bin \
    assets/misc/bank_7/129/level.bin \
    assets/misc/bank_7/130/level.bin \
    assets/misc/bank_7/131/level.bin \
    assets/misc/bank_7/132/level.bin \
    assets/misc/bank_7/133/level.bin \
    assets/misc/bank_7/134/level.bin \
    assets/misc/bank_7/135/level.bin \
    assets/misc/bank_7/136/level.bin \
    assets/misc/bank_7/137/level.bin \
    assets/misc/bank_7/138/level.bin \
    assets/misc/bank_7/139/level.bin \
    assets/misc/bank_7/140/level.bin \
    assets/misc/bank_7/141/level.bin \
    assets/misc/bank_7/142/level.bin \
    assets/misc/bank_7/143/level.bin \
    assets/misc/bank_7/144/level.bin \
    assets/misc/bank_7/145/level.bin \
    assets/misc/bank_7/146/level.bin \
    assets/misc/bank_7/147/level.bin \
    assets/misc/bank_7/148/level.bin \
    assets/misc/bank_7/149/level.bin \
    assets/misc/bank_7/150/level.bin \
    assets/misc/bank_7/151/level.bin \
    assets/misc/bank_7/152/level.bin \
    assets/misc/bank_7/153/level.bin \
    assets/misc/bank_7/154/level.bin \
    assets/misc/bank_7/155/level.bin \
    assets/misc/bank_7/156/level.bin \
    assets/misc/bank_7/157/level.bin \
    assets/misc/bank_7/158/level.bin \
    assets/misc/bank_7/159/level.bin \
    assets/misc/bank_7/160/level.bin \
    assets/misc/bank_7/161/level.bin \
    assets/misc/bank_7/162/level.bin \
    assets/misc/bank_7/163/level.bin \
    assets/misc/bank_7/164/level.bin \
    assets/misc/bank_7/165/level.bin \
    assets/misc/bank_7/166/level.bin \
    assets/misc/bank_7/167/level.bin \
    assets/misc/bank_7/168/level.bin \
    assets/misc/bank_7/169/level.bin \
    assets/misc/bank_7/170/level.bin \
    assets/misc/bank_7/171/level.bin \
    assets/misc/bank_7/172/level.bin \
    assets/misc/bank_7/173/level.bin \
    assets/misc/bank_7/174/level.bin \
    assets/misc/bank_7/175/level.bin \
    assets/misc/bank_7/176/level.bin \
    assets/misc/bank_7/177/level.bin \
    assets/misc/bank_7/178/level.bin \
    assets/misc/bank_7/179/level.bin \
    assets/misc/bank_7/180/level.bin \
    assets/misc/bank_7/181/level.bin \
    assets/misc/bank_7/182/level.bin \
    assets/misc/bank_7/183/level.bin \
    assets/misc/bank_7/184/level.bin \
    assets/misc/bank_7/185/level.bin \
    assets/misc/bank_7/186/level.bin \
    assets/misc/bank_7/187/level.bin \
    assets/misc/bank_7/188/level.bin \
    assets/misc/bank_7/189/level.bin \
    assets/misc/bank_7/190/level.bin \
    assets/misc/bank_7/191/level.bin \
    assets/misc/bank_7/192/level.bin \
    assets/misc/bank_7/193/level.bin \
    assets/misc/bank_7/194/level.bin \
    assets/misc/bank_7/195/level.bin \
    assets/misc/bank_7/196/level.bin \
    assets/misc/bank_7/197/level.bin \
    assets/misc/bank_7/198/level.bin \
    assets/misc/bank_7/199/level.bin \
    assets/misc/bank_7/200/level.bin \
    assets/misc/bank_7/201/level.bin \
    assets/misc/bank_7/202/level.bin \
    assets/misc/bank_7/203/level.bin \
    assets/misc/bank_7/204/level.bin \
    assets/misc/bank_7/205/level.bin \
    assets/misc/bank_7/206/level.bin \
    assets/misc/bank_7/207/level.bin \
    assets/misc/bank_7/208/level.bin \
    assets/misc/bank_7/209/level.bin \
    assets/misc/bank_7/210/level.bin \
    assets/misc/bank_7/211/level.bin \
    assets/misc/bank_7/212/level.bin \
    assets/misc/bank_7/213/level.bin \
    assets/misc/bank_7/214/level.bin \
    assets/misc/bank_7/215/level.bin \
    assets/misc/bank_7/216/level.bin \
    assets/misc/bank_7/217/level.bin \
    assets/misc/bank_7/218/level.bin \
    assets/misc/bank_7/219/level.bin \
    assets/misc/bank_7/220/level.bin \
    assets/misc/bank_7/221/level.bin \
    assets/misc/bank_7/222/level.bin \
    assets/misc/bank_7/223/level.bin \
    assets/misc/bank_7/224/level.bin \
    assets/misc/bank_7/225/level.bin \
    assets/misc/bank_7/226/level.bin \
    assets/misc/bank_7/227/level.bin \
    assets/misc/bank_7/228/level.bin \
    assets/misc/bank_7/229/level.bin \
    assets/misc/bank_7/230/level.bin \
    assets/misc/bank_7/231/level.bin \
    assets/misc/bank_7/232/level.bin \
    assets/misc/bank_7/233/level.bin \
    assets/misc/bank_7/234/level.bin \
    assets/misc/bank_7/235/level.bin \
    assets/misc/bank_7/236/level.bin \
    assets/misc/bank_7/237/level.bin \
    assets/misc/bank_7/238/level.bin \
    assets/misc/bank_7/239/level.bin
