GEO_BANK_0_FILES := \
    assets/geo/bank_0/1/geo.bin \
    assets/geo/bank_0/2/geo.bin \
    assets/geo/bank_0/3/geo.bin \
    assets/geo/bank_0/4/geo.bin \
    assets/geo/bank_0/5/geo.bin \
    assets/geo/bank_0/6/geo.bin \
    assets/geo/bank_0/7/geo.bin \
    assets/geo/bank_0/8/geo.bin \
    assets/geo/bank_0/9/geo.bin \
    assets/geo/bank_0/10/geo.bin

GEO_BANK_1_FILES := \
    assets/geo/bank_1/1/geo.bin \
    assets/geo/bank_1/2/geo.bin \
    assets/geo/bank_1/3/geo.bin \
    assets/geo/bank_1/4/geo.bin \
    assets/geo/bank_1/5/geo.bin \
    assets/geo/bank_1/6/geo.bin \
    assets/geo/bank_1/7/geo.bin \
    assets/geo/bank_1/8/geo.bin \
    assets/geo/bank_1/9/geo.bin \
    assets/geo/bank_1/10/geo.bin \
    assets/geo/bank_1/11/geo.bin \
    assets/geo/bank_1/12/geo.bin \
    assets/geo/bank_1/13/geo.bin \
    assets/geo/bank_1/14/geo.bin \
    assets/geo/bank_1/15/geo.bin \
    assets/geo/bank_1/16/geo.bin \
    assets/geo/bank_1/17/geo.bin \
    assets/geo/bank_1/18/geo.bin \
    assets/geo/bank_1/19/geo.bin \
    assets/geo/bank_1/20/geo.bin \
    assets/geo/bank_1/21/geo.bin \
    assets/geo/bank_1/22/geo.bin \
    assets/geo/bank_1/23/geo.bin \
    assets/geo/bank_1/24/geo.bin \
    assets/geo/bank_1/25/geo.bin \
    assets/geo/bank_1/26/geo.bin \
    assets/geo/bank_1/27/geo.bin \
    assets/geo/bank_1/28/geo.bin \
    assets/geo/bank_1/29/geo.bin \
    assets/geo/bank_1/30/geo.bin \
    assets/geo/bank_1/31/geo.bin \
    assets/geo/bank_1/32/geo.bin \
    assets/geo/bank_1/33/geo.bin \
    assets/geo/bank_1/34/geo.bin \
    assets/geo/bank_1/35/geo.bin \
    assets/geo/bank_1/36/geo.bin \
    assets/geo/bank_1/37/geo.bin \
    assets/geo/bank_1/38/geo.bin \
    assets/geo/bank_1/39/geo.bin \
    assets/geo/bank_1/40/geo.bin \
    assets/geo/bank_1/41/geo.bin \
    assets/geo/bank_1/42/geo.bin \
    assets/geo/bank_1/43/geo.bin \
    assets/geo/bank_1/44/geo.bin \
    assets/geo/bank_1/45/geo.bin \
    assets/geo/bank_1/46/geo.bin \
    assets/geo/bank_1/47/geo.bin \
    assets/geo/bank_1/48/geo.bin \
    assets/geo/bank_1/49/geo.bin \
    assets/geo/bank_1/50/geo.bin \
    assets/geo/bank_1/51/geo.bin \
    assets/geo/bank_1/52/geo.bin \
    assets/geo/bank_1/53/geo.bin \
    assets/geo/bank_1/54/geo.bin \
    assets/geo/bank_1/55/geo.bin \
    assets/geo/bank_1/56/geo.bin \
    assets/geo/bank_1/57/geo.bin \
    assets/geo/bank_1/58/geo.bin \
    assets/geo/bank_1/59/geo.bin \
    assets/geo/bank_1/60/geo.bin \
    assets/geo/bank_1/61/geo.bin \
    assets/geo/bank_1/62/geo.bin \
    assets/geo/bank_1/63/geo.bin \
    assets/geo/bank_1/64/geo.bin \
    assets/geo/bank_1/65/geo.bin \
    assets/geo/bank_1/66/geo.bin \
    assets/geo/bank_1/67/geo.bin \
    assets/geo/bank_1/68/geo.bin \
    assets/geo/bank_1/69/geo.bin \
    assets/geo/bank_1/70/geo.bin \
    assets/geo/bank_1/71/geo.bin \
    assets/geo/bank_1/72/geo.bin \
    assets/geo/bank_1/73/geo.bin \
    assets/geo/bank_1/74/geo.bin \
    assets/geo/bank_1/75/geo.bin \
    assets/geo/bank_1/76/geo.bin \
    assets/geo/bank_1/77/geo.bin \
    assets/geo/bank_1/78/geo.bin \
    assets/geo/bank_1/79/geo.bin \
    assets/geo/bank_1/80/geo.bin \
    assets/geo/bank_1/81/geo.bin \
    assets/geo/bank_1/82/geo.bin \
    assets/geo/bank_1/83/geo.bin \
    assets/geo/bank_1/84/geo.bin \
    assets/geo/bank_1/85/geo.bin \
    assets/geo/bank_1/86/geo.bin \
    assets/geo/bank_1/87/geo.bin \
    assets/geo/bank_1/88/geo.bin \
    assets/geo/bank_1/89/geo.bin \
    assets/geo/bank_1/90/geo.bin \
    assets/geo/bank_1/91/geo.bin \
    assets/geo/bank_1/92/geo.bin \
    assets/geo/bank_1/93/geo.bin \
    assets/geo/bank_1/94/geo.bin \
    assets/geo/bank_1/95/geo.bin \
    assets/geo/bank_1/96/geo.bin \
    assets/geo/bank_1/97/geo.bin \
    assets/geo/bank_1/98/geo.bin \
    assets/geo/bank_1/99/geo.bin \
    assets/geo/bank_1/100/geo.bin \
    assets/geo/bank_1/101/geo.bin \
    assets/geo/bank_1/102/geo.bin \
    assets/geo/bank_1/103/geo.bin \
    assets/geo/bank_1/104/geo.bin \
    assets/geo/bank_1/105/geo.bin \
    assets/geo/bank_1/106/geo.bin \
    assets/geo/bank_1/107/geo.bin \
    assets/geo/bank_1/108/geo.bin \
    assets/geo/bank_1/109/geo.bin \
    assets/geo/bank_1/110/geo.bin \
    assets/geo/bank_1/111/geo.bin \
    assets/geo/bank_1/112/geo.bin \
    assets/geo/bank_1/113/geo.bin \
    assets/geo/bank_1/114/geo.bin \
    assets/geo/bank_1/115/geo.bin \
    assets/geo/bank_1/116/geo.bin \
    assets/geo/bank_1/117/geo.bin \
    assets/geo/bank_1/118/geo.bin \
    assets/geo/bank_1/119/geo.bin \
    assets/geo/bank_1/120/geo.bin \
    assets/geo/bank_1/121/geo.bin \
    assets/geo/bank_1/122/geo.bin \
    assets/geo/bank_1/123/geo.bin \
    assets/geo/bank_1/124/geo.bin \
    assets/geo/bank_1/125/geo.bin \
    assets/geo/bank_1/126/geo.bin \
    assets/geo/bank_1/127/geo.bin \
    assets/geo/bank_1/128/geo.bin \
    assets/geo/bank_1/129/geo.bin \
    assets/geo/bank_1/130/geo.bin \
    assets/geo/bank_1/131/geo.bin \
    assets/geo/bank_1/132/geo.bin \
    assets/geo/bank_1/133/geo.bin \
    assets/geo/bank_1/134/geo.bin \
    assets/geo/bank_1/135/geo.bin \
    assets/geo/bank_1/136/geo.bin \
    assets/geo/bank_1/137/geo.bin \
    assets/geo/bank_1/138/geo.bin \
    assets/geo/bank_1/139/geo.bin \
    assets/geo/bank_1/140/geo.bin \
    assets/geo/bank_1/141/geo.bin \
    assets/geo/bank_1/142/geo.bin \
    assets/geo/bank_1/143/geo.bin \
    assets/geo/bank_1/144/geo.bin \
    assets/geo/bank_1/145/geo.bin \
    assets/geo/bank_1/146/geo.bin \
    assets/geo/bank_1/147/geo.bin \
    assets/geo/bank_1/148/geo.bin \
    assets/geo/bank_1/149/geo.bin \
    assets/geo/bank_1/150/geo.bin \
    assets/geo/bank_1/151/geo.bin \
    assets/geo/bank_1/152/geo.bin \
    assets/geo/bank_1/153/geo.bin \
    assets/geo/bank_1/154/geo.bin \
    assets/geo/bank_1/155/geo.bin \
    assets/geo/bank_1/156/geo.bin \
    assets/geo/bank_1/157/geo.bin \
    assets/geo/bank_1/158/geo.bin \
    assets/geo/bank_1/159/geo.bin \
    assets/geo/bank_1/160/geo.bin \
    assets/geo/bank_1/161/geo.bin \
    assets/geo/bank_1/162/geo.bin \
    assets/geo/bank_1/163/geo.bin \
    assets/geo/bank_1/164/geo.bin \
    assets/geo/bank_1/165/geo.bin \
    assets/geo/bank_1/166/geo.bin \
    assets/geo/bank_1/167/geo.bin \
    assets/geo/bank_1/168/geo.bin \
    assets/geo/bank_1/169/geo.bin \
    assets/geo/bank_1/170/geo.bin \
    assets/geo/bank_1/171/geo.bin \
    assets/geo/bank_1/172/geo.bin \
    assets/geo/bank_1/173/geo.bin \
    assets/geo/bank_1/174/geo.bin \
    assets/geo/bank_1/175/geo.bin \
    assets/geo/bank_1/176/geo.bin \
    assets/geo/bank_1/177/geo.bin \
    assets/geo/bank_1/178/geo.bin \
    assets/geo/bank_1/179/geo.bin \
    assets/geo/bank_1/180/geo.bin \
    assets/geo/bank_1/181/geo.bin \
    assets/geo/bank_1/182/geo.bin \
    assets/geo/bank_1/183/geo.bin \
    assets/geo/bank_1/184/geo.bin \
    assets/geo/bank_1/185/geo.bin \
    assets/geo/bank_1/186/geo.bin \
    assets/geo/bank_1/187/geo.bin \
    assets/geo/bank_1/188/geo.bin \
    assets/geo/bank_1/189/geo.bin \
    assets/geo/bank_1/190/geo.bin \
    assets/geo/bank_1/191/geo.bin \
    assets/geo/bank_1/192/geo.bin \
    assets/geo/bank_1/193/geo.bin \
    assets/geo/bank_1/194/geo.bin \
    assets/geo/bank_1/195/geo.bin \
    assets/geo/bank_1/196/geo.bin \
    assets/geo/bank_1/197/geo.bin \
    assets/geo/bank_1/198/geo.bin \
    assets/geo/bank_1/199/geo.bin \
    assets/geo/bank_1/200/geo.bin \
    assets/geo/bank_1/201/geo.bin \
    assets/geo/bank_1/202/geo.bin \
    assets/geo/bank_1/203/geo.bin \
    assets/geo/bank_1/204/geo.bin \
    assets/geo/bank_1/205/geo.bin \
    assets/geo/bank_1/206/geo.bin \
    assets/geo/bank_1/207/geo.bin \
    assets/geo/bank_1/208/geo.bin \
    assets/geo/bank_1/209/geo.bin \
    assets/geo/bank_1/210/geo.bin \
    assets/geo/bank_1/211/geo.bin \
    assets/geo/bank_1/212/geo.bin \
    assets/geo/bank_1/213/geo.bin \
    assets/geo/bank_1/214/geo.bin \
    assets/geo/bank_1/215/geo.bin \
    assets/geo/bank_1/216/geo.bin \
    assets/geo/bank_1/217/geo.bin \
    assets/geo/bank_1/218/geo.bin \
    assets/geo/bank_1/219/geo.bin \
    assets/geo/bank_1/220/geo.bin \
    assets/geo/bank_1/221/geo.bin \
    assets/geo/bank_1/222/geo.bin \
    assets/geo/bank_1/223/geo.bin \
    assets/geo/bank_1/224/geo.bin \
    assets/geo/bank_1/225/geo.bin \
    assets/geo/bank_1/226/geo.bin \
    assets/geo/bank_1/227/geo.bin \
    assets/geo/bank_1/228/geo.bin \
    assets/geo/bank_1/229/geo.bin \
    assets/geo/bank_1/230/geo.bin \
    assets/geo/bank_1/231/geo.bin \
    assets/geo/bank_1/232/geo.bin \
    assets/geo/bank_1/233/geo.bin \
    assets/geo/bank_1/234/geo.bin \
    assets/geo/bank_1/235/geo.bin \
    assets/geo/bank_1/236/geo.bin \
    assets/geo/bank_1/237/geo.bin \
    assets/geo/bank_1/238/geo.bin \
    assets/geo/bank_1/239/geo.bin \
    assets/geo/bank_1/240/geo.bin \
    assets/geo/bank_1/241/geo.bin \
    assets/geo/bank_1/242/geo.bin \
    assets/geo/bank_1/243/geo.bin

GEO_BANK_2_FILES := \
    assets/geo/bank_2/1/geo.bin \
    assets/geo/bank_2/2/geo.bin \
    assets/geo/bank_2/3/geo.bin \
    assets/geo/bank_2/4/geo.bin \
    assets/geo/bank_2/5/geo.bin \
    assets/geo/bank_2/6/geo.bin \
    assets/geo/bank_2/7/geo.bin \
    assets/geo/bank_2/8/geo.bin \
    assets/geo/bank_2/9/geo.bin \
    assets/geo/bank_2/10/geo.bin \
    assets/geo/bank_2/11/geo.bin \
    assets/geo/bank_2/12/geo.bin \
    assets/geo/bank_2/13/geo.bin \
    assets/geo/bank_2/14/geo.bin \
    assets/geo/bank_2/15/geo.bin \
    assets/geo/bank_2/16/geo.bin \
    assets/geo/bank_2/17/geo.bin \
    assets/geo/bank_2/18/geo.bin \
    assets/geo/bank_2/19/geo.bin \
    assets/geo/bank_2/20/geo.bin \
    assets/geo/bank_2/21/geo.bin \
    assets/geo/bank_2/22/geo.bin \
    assets/geo/bank_2/23/geo.bin \
    assets/geo/bank_2/24/geo.bin \
    assets/geo/bank_2/25/geo.bin \
    assets/geo/bank_2/26/geo.bin \
    assets/geo/bank_2/27/geo.bin \
    assets/geo/bank_2/28/geo.bin \
    assets/geo/bank_2/29/geo.bin \
    assets/geo/bank_2/30/geo.bin \
    assets/geo/bank_2/31/geo.bin \
    assets/geo/bank_2/32/geo.bin \
    assets/geo/bank_2/33/geo.bin \
    assets/geo/bank_2/34/geo.bin \
    assets/geo/bank_2/35/geo.bin \
    assets/geo/bank_2/36/geo.bin \
    assets/geo/bank_2/37/geo.bin \
    assets/geo/bank_2/38/geo.bin \
    assets/geo/bank_2/39/geo.bin \
    assets/geo/bank_2/40/geo.bin \
    assets/geo/bank_2/41/geo.bin \
    assets/geo/bank_2/42/geo.bin \
    assets/geo/bank_2/43/geo.bin \
    assets/geo/bank_2/44/geo.bin \
    assets/geo/bank_2/45/geo.bin \
    assets/geo/bank_2/46/geo.bin \
    assets/geo/bank_2/47/geo.bin \
    assets/geo/bank_2/48/geo.bin \
    assets/geo/bank_2/49/geo.bin \
    assets/geo/bank_2/50/geo.bin \
    assets/geo/bank_2/51/geo.bin \
    assets/geo/bank_2/52/geo.bin \
    assets/geo/bank_2/53/geo.bin \
    assets/geo/bank_2/54/geo.bin \
    assets/geo/bank_2/55/geo.bin \
    assets/geo/bank_2/56/geo.bin \
    assets/geo/bank_2/57/geo.bin \
    assets/geo/bank_2/58/geo.bin \
    assets/geo/bank_2/59/geo.bin \
    assets/geo/bank_2/60/geo.bin \
    assets/geo/bank_2/61/geo.bin \
    assets/geo/bank_2/62/geo.bin \
    assets/geo/bank_2/63/geo.bin \
    assets/geo/bank_2/64/geo.bin \
    assets/geo/bank_2/65/geo.bin \
    assets/geo/bank_2/66/geo.bin \
    assets/geo/bank_2/67/geo.bin \
    assets/geo/bank_2/68/geo.bin \
    assets/geo/bank_2/69/geo.bin \
    assets/geo/bank_2/70/geo.bin \
    assets/geo/bank_2/71/geo.bin \
    assets/geo/bank_2/72/geo.bin \
    assets/geo/bank_2/73/geo.bin \
    assets/geo/bank_2/74/geo.bin \
    assets/geo/bank_2/75/geo.bin \
    assets/geo/bank_2/76/geo.bin \
    assets/geo/bank_2/77/geo.bin \
    assets/geo/bank_2/78/geo.bin \
    assets/geo/bank_2/79/geo.bin \
    assets/geo/bank_2/80/geo.bin \
    assets/geo/bank_2/81/geo.bin \
    assets/geo/bank_2/82/geo.bin \
    assets/geo/bank_2/83/geo.bin \
    assets/geo/bank_2/84/geo.bin \
    assets/geo/bank_2/85/geo.bin \
    assets/geo/bank_2/86/geo.bin \
    assets/geo/bank_2/87/geo.bin \
    assets/geo/bank_2/88/geo.bin \
    assets/geo/bank_2/89/geo.bin \
    assets/geo/bank_2/90/geo.bin \
    assets/geo/bank_2/91/geo.bin \
    assets/geo/bank_2/92/geo.bin \
    assets/geo/bank_2/93/geo.bin \
    assets/geo/bank_2/94/geo.bin \
    assets/geo/bank_2/95/geo.bin \
    assets/geo/bank_2/96/geo.bin \
    assets/geo/bank_2/97/geo.bin \
    assets/geo/bank_2/98/geo.bin \
    assets/geo/bank_2/99/geo.bin \
    assets/geo/bank_2/100/geo.bin \
    assets/geo/bank_2/101/geo.bin \
    assets/geo/bank_2/102/geo.bin \
    assets/geo/bank_2/103/geo.bin \
    assets/geo/bank_2/104/geo.bin \
    assets/geo/bank_2/105/geo.bin \
    assets/geo/bank_2/106/geo.bin \
    assets/geo/bank_2/107/geo.bin \
    assets/geo/bank_2/108/geo.bin \
    assets/geo/bank_2/109/geo.bin \
    assets/geo/bank_2/110/geo.bin \
    assets/geo/bank_2/111/geo.bin \
    assets/geo/bank_2/112/geo.bin \
    assets/geo/bank_2/113/geo.bin \
    assets/geo/bank_2/114/geo.bin \
    assets/geo/bank_2/115/geo.bin \
    assets/geo/bank_2/116/geo.bin \
    assets/geo/bank_2/117/geo.bin \
    assets/geo/bank_2/118/geo.bin \
    assets/geo/bank_2/119/geo.bin \
    assets/geo/bank_2/120/geo.bin \
    assets/geo/bank_2/121/geo.bin \
    assets/geo/bank_2/122/geo.bin \
    assets/geo/bank_2/123/geo.bin \
    assets/geo/bank_2/124/geo.bin \
    assets/geo/bank_2/125/geo.bin \
    assets/geo/bank_2/126/geo.bin \
    assets/geo/bank_2/127/geo.bin \
    assets/geo/bank_2/128/geo.bin

GEO_BANK_3_FILES := \
    assets/geo/bank_3/1/geo.bin \
    assets/geo/bank_3/2/geo.bin \
    assets/geo/bank_3/3/geo.bin \
    assets/geo/bank_3/4/geo.bin \
    assets/geo/bank_3/5/geo.bin \
    assets/geo/bank_3/6/geo.bin \
    assets/geo/bank_3/7/geo.bin \
    assets/geo/bank_3/8/geo.bin \
    assets/geo/bank_3/9/geo.bin \
    assets/geo/bank_3/10/geo.bin \
    assets/geo/bank_3/11/geo.bin \
    assets/geo/bank_3/12/geo.bin \
    assets/geo/bank_3/13/geo.bin \
    assets/geo/bank_3/14/geo.bin \
    assets/geo/bank_3/15/geo.bin \
    assets/geo/bank_3/16/geo.bin \
    assets/geo/bank_3/17/geo.bin \
    assets/geo/bank_3/18/geo.bin \
    assets/geo/bank_3/19/geo.bin \
    assets/geo/bank_3/20/geo.bin \
    assets/geo/bank_3/21/geo.bin \
    assets/geo/bank_3/22/geo.bin \
    assets/geo/bank_3/23/geo.bin \
    assets/geo/bank_3/24/geo.bin \
    assets/geo/bank_3/25/geo.bin \
    assets/geo/bank_3/26/geo.bin \
    assets/geo/bank_3/27/geo.bin \
    assets/geo/bank_3/28/geo.bin \
    assets/geo/bank_3/29/geo.bin \
    assets/geo/bank_3/30/geo.bin \
    assets/geo/bank_3/31/geo.bin \
    assets/geo/bank_3/32/geo.bin \
    assets/geo/bank_3/33/geo.bin \
    assets/geo/bank_3/34/geo.bin \
    assets/geo/bank_3/35/geo.bin \
    assets/geo/bank_3/36/geo.bin \
    assets/geo/bank_3/37/geo.bin \
    assets/geo/bank_3/38/geo.bin \
    assets/geo/bank_3/39/geo.bin \
    assets/geo/bank_3/40/geo.bin \
    assets/geo/bank_3/41/geo.bin \
    assets/geo/bank_3/42/geo.bin \
    assets/geo/bank_3/43/geo.bin \
    assets/geo/bank_3/44/geo.bin \
    assets/geo/bank_3/45/geo.bin \
    assets/geo/bank_3/46/geo.bin \
    assets/geo/bank_3/47/geo.bin \
    assets/geo/bank_3/48/geo.bin \
    assets/geo/bank_3/49/geo.bin \
    assets/geo/bank_3/50/geo.bin \
    assets/geo/bank_3/51/geo.bin \
    assets/geo/bank_3/52/geo.bin \
    assets/geo/bank_3/53/geo.bin \
    assets/geo/bank_3/54/geo.bin \
    assets/geo/bank_3/55/geo.bin \
    assets/geo/bank_3/56/geo.bin \
    assets/geo/bank_3/57/geo.bin \
    assets/geo/bank_3/58/geo.bin \
    assets/geo/bank_3/59/geo.bin \
    assets/geo/bank_3/60/geo.bin \
    assets/geo/bank_3/61/geo.bin \
    assets/geo/bank_3/62/geo.bin \
    assets/geo/bank_3/63/geo.bin \
    assets/geo/bank_3/64/geo.bin \
    assets/geo/bank_3/65/geo.bin \
    assets/geo/bank_3/66/geo.bin \
    assets/geo/bank_3/67/geo.bin \
    assets/geo/bank_3/68/geo.bin \
    assets/geo/bank_3/69/geo.bin \
    assets/geo/bank_3/70/geo.bin \
    assets/geo/bank_3/71/geo.bin \
    assets/geo/bank_3/72/geo.bin \
    assets/geo/bank_3/73/geo.bin \
    assets/geo/bank_3/74/geo.bin \
    assets/geo/bank_3/75/geo.bin \
    assets/geo/bank_3/76/geo.bin \
    assets/geo/bank_3/77/geo.bin \
    assets/geo/bank_3/78/geo.bin \
    assets/geo/bank_3/79/geo.bin \
    assets/geo/bank_3/80/geo.bin \
    assets/geo/bank_3/81/geo.bin \
    assets/geo/bank_3/82/geo.bin \
    assets/geo/bank_3/83/geo.bin \
    assets/geo/bank_3/84/geo.bin \
    assets/geo/bank_3/85/geo.bin \
    assets/geo/bank_3/86/geo.bin \
    assets/geo/bank_3/87/geo.bin \
    assets/geo/bank_3/88/geo.bin \
    assets/geo/bank_3/89/geo.bin \
    assets/geo/bank_3/90/geo.bin \
    assets/geo/bank_3/91/geo.bin \
    assets/geo/bank_3/92/geo.bin \
    assets/geo/bank_3/93/geo.bin \
    assets/geo/bank_3/94/geo.bin \
    assets/geo/bank_3/95/geo.bin \
    assets/geo/bank_3/96/geo.bin \
    assets/geo/bank_3/97/geo.bin \
    assets/geo/bank_3/98/geo.bin \
    assets/geo/bank_3/99/block.bin \
    assets/geo/bank_3/100/block.bin \
    assets/geo/bank_3/101/block.bin \
    assets/geo/bank_3/102/block.bin \
    assets/geo/bank_3/103/block.bin \
    assets/geo/bank_3/104/block.bin \
    assets/geo/bank_3/105/block.bin \
    assets/geo/bank_3/106/block.bin \
    assets/geo/bank_3/107/block.bin \
    assets/geo/bank_3/108/block.bin \
    assets/geo/bank_3/109/block.bin \
    assets/geo/bank_3/110/block.bin \
    assets/geo/bank_3/111/block.bin \
    assets/geo/bank_3/112/block.bin \
    assets/geo/bank_3/113/block.bin \
    assets/geo/bank_3/114/block.bin \
    assets/geo/bank_3/115/block.bin \
    assets/geo/bank_3/116/block.bin \
    assets/geo/bank_3/117/block.bin \
    assets/geo/bank_3/118/block.bin \
    assets/geo/bank_3/119/block.bin \
    assets/geo/bank_3/120/block.bin \
    assets/geo/bank_3/121/block.bin \
    assets/geo/bank_3/122/block.bin \
    assets/geo/bank_3/123/block.bin \
    assets/geo/bank_3/124/block.bin \
    assets/geo/bank_3/125/block.bin \
    assets/geo/bank_3/126/block.bin \
    assets/geo/bank_3/127/block.bin \
    assets/geo/bank_3/128/block.bin \
    assets/geo/bank_3/129/block.bin \
    assets/geo/bank_3/130/block.bin \
    assets/geo/bank_3/131/block.bin \
    assets/geo/bank_3/132/block.bin \
    assets/geo/bank_3/133/block.bin \
    assets/geo/bank_3/134/block.bin \
    assets/geo/bank_3/135/block.bin \
    assets/geo/bank_3/136/block.bin \
    assets/geo/bank_3/137/block.bin \
    assets/geo/bank_3/138/block.bin \
    assets/geo/bank_3/139/block.bin \
    assets/geo/bank_3/140/block.bin \
    assets/geo/bank_3/141/block.bin \
    assets/geo/bank_3/142/block.bin \
    assets/geo/bank_3/143/block.bin \
    assets/geo/bank_3/144/block.bin \
    assets/geo/bank_3/145/block.bin \
    assets/geo/bank_3/146/block.bin \
    assets/geo/bank_3/147/block.bin \
    assets/geo/bank_3/148/block.bin \
    assets/geo/bank_3/149/block.bin \
    assets/geo/bank_3/150/block.bin \
    assets/geo/bank_3/151/block.bin \
    assets/geo/bank_3/152/block.bin \
    assets/geo/bank_3/153/block.bin \
    assets/geo/bank_3/154/block.bin \
    assets/geo/bank_3/155/block.bin \
    assets/geo/bank_3/156/block.bin \
    assets/geo/bank_3/157/block.bin \
    assets/geo/bank_3/158/block.bin \
    assets/geo/bank_3/159/block.bin \
    assets/geo/bank_3/160/block.bin \
    assets/geo/bank_3/161/block.bin \
    assets/geo/bank_3/162/block.bin \
    assets/geo/bank_3/163/block.bin \
    assets/geo/bank_3/164/block.bin \
    assets/geo/bank_3/165/block.bin \
    assets/geo/bank_3/166/block.bin \
    assets/geo/bank_3/167/block.bin \
    assets/geo/bank_3/168/block.bin \
    assets/geo/bank_3/169/block.bin \
    assets/geo/bank_3/170/block.bin \
    assets/geo/bank_3/171/block.bin \
    assets/geo/bank_3/172/block.bin \
    assets/geo/bank_3/173/block.bin \
    assets/geo/bank_3/174/block.bin \
    assets/geo/bank_3/175/block.bin \
    assets/geo/bank_3/176/block.bin \
    assets/geo/bank_3/177/block.bin \
    assets/geo/bank_3/178/block.bin \
    assets/geo/bank_3/179/block.bin \
    assets/geo/bank_3/180/block.bin \
    assets/geo/bank_3/181/block.bin \
    assets/geo/bank_3/182/block.bin \
    assets/geo/bank_3/183/block.bin \
    assets/geo/bank_3/184/block.bin \
    assets/geo/bank_3/185/block.bin \
    assets/geo/bank_3/186/block.bin \
    assets/geo/bank_3/187/block.bin \
    assets/geo/bank_3/188/block.bin \
    assets/geo/bank_3/189/block.bin \
    assets/geo/bank_3/190/block.bin \
    assets/geo/bank_3/191/block.bin \
    assets/geo/bank_3/192/block.bin \
    assets/geo/bank_3/193/block.bin \
    assets/geo/bank_3/194/block.bin \
    assets/geo/bank_3/195/block.bin \
    assets/geo/bank_3/196/block.bin

GEO_BANK_4_FILES := \
    assets/geo/bank_4/1/block.bin \
    assets/geo/bank_4/2/block.bin \
    assets/geo/bank_4/3/block.bin \
    assets/geo/bank_4/4/block.bin \
    assets/geo/bank_4/5/block.bin \
    assets/geo/bank_4/6/block.bin \
    assets/geo/bank_4/7/block.bin \
    assets/geo/bank_4/8/block.bin \
    assets/geo/bank_4/9/block.bin \
    assets/geo/bank_4/10/block.bin \
    assets/geo/bank_4/11/block.bin \
    assets/geo/bank_4/12/block.bin \
    assets/geo/bank_4/13/block.bin \
    assets/geo/bank_4/14/block.bin \
    assets/geo/bank_4/15/block.bin \
    assets/geo/bank_4/16/block.bin \
    assets/geo/bank_4/17/block.bin \
    assets/geo/bank_4/18/block.bin \
    assets/geo/bank_4/19/block.bin \
    assets/geo/bank_4/20/block.bin \
    assets/geo/bank_4/21/block.bin \
    assets/geo/bank_4/22/block.bin \
    assets/geo/bank_4/23/block.bin \
    assets/geo/bank_4/24/block.bin \
    assets/geo/bank_4/25/block.bin \
    assets/geo/bank_4/26/block.bin \
    assets/geo/bank_4/27/block.bin \
    assets/geo/bank_4/28/block.bin \
    assets/geo/bank_4/29/block.bin \
    assets/geo/bank_4/30/block.bin \
    assets/geo/bank_4/31/block.bin \
    assets/geo/bank_4/32/block.bin \
    assets/geo/bank_4/33/block.bin \
    assets/geo/bank_4/34/block.bin \
    assets/geo/bank_4/35/block.bin \
    assets/geo/bank_4/36/block.bin \
    assets/geo/bank_4/37/block.bin \
    assets/geo/bank_4/38/block.bin \
    assets/geo/bank_4/39/block.bin \
    assets/geo/bank_4/40/block.bin \
    assets/geo/bank_4/41/block.bin \
    assets/geo/bank_4/42/block.bin \
    assets/geo/bank_4/43/block.bin \
    assets/geo/bank_4/44/block.bin \
    assets/geo/bank_4/45/block.bin \
    assets/geo/bank_4/46/block.bin \
    assets/geo/bank_4/47/block.bin \
    assets/geo/bank_4/48/block.bin \
    assets/geo/bank_4/49/block.bin \
    assets/geo/bank_4/50/block.bin \
    assets/geo/bank_4/51/block.bin \
    assets/geo/bank_4/52/block.bin \
    assets/geo/bank_4/53/block.bin \
    assets/geo/bank_4/54/block.bin \
    assets/geo/bank_4/55/block.bin \
    assets/geo/bank_4/56/block.bin \
    assets/geo/bank_4/57/block.bin \
    assets/geo/bank_4/58/block.bin \
    assets/geo/bank_4/59/block.bin \
    assets/geo/bank_4/60/block.bin \
    assets/geo/bank_4/61/block.bin \
    assets/geo/bank_4/62/block.bin \
    assets/geo/bank_4/63/block.bin \
    assets/geo/bank_4/64/block.bin \
    assets/geo/bank_4/65/block.bin \
    assets/geo/bank_4/66/block.bin \
    assets/geo/bank_4/67/block.bin \
    assets/geo/bank_4/68/block.bin \
    assets/geo/bank_4/69/block.bin \
    assets/geo/bank_4/70/block.bin \
    assets/geo/bank_4/71/block.bin \
    assets/geo/bank_4/72/block.bin \
    assets/geo/bank_4/73/block.bin \
    assets/geo/bank_4/74/block.bin \
    assets/geo/bank_4/75/block.bin \
    assets/geo/bank_4/76/block.bin \
    assets/geo/bank_4/77/block.bin \
    assets/geo/bank_4/78/block.bin \
    assets/geo/bank_4/79/block.bin \
    assets/geo/bank_4/80/block.bin \
    assets/geo/bank_4/81/block.bin \
    assets/geo/bank_4/82/block.bin \
    assets/geo/bank_4/83/block.bin \
    assets/geo/bank_4/84/block.bin \
    assets/geo/bank_4/85/block.bin \
    assets/geo/bank_4/86/block.bin \
    assets/geo/bank_4/87/block.bin \
    assets/geo/bank_4/88/block.bin \
    assets/geo/bank_4/89/block.bin \
    assets/geo/bank_4/90/block.bin \
    assets/geo/bank_4/91/block.bin \
    assets/geo/bank_4/92/block.bin \
    assets/geo/bank_4/93/block.bin \
    assets/geo/bank_4/94/block.bin \
    assets/geo/bank_4/95/block.bin \
    assets/geo/bank_4/96/block.bin \
    assets/geo/bank_4/97/block.bin \
    assets/geo/bank_4/98/block.bin \
    assets/geo/bank_4/99/block.bin \
    assets/geo/bank_4/100/block.bin \
    assets/geo/bank_4/101/block.bin \
    assets/geo/bank_4/102/block.bin \
    assets/geo/bank_4/103/block.bin \
    assets/geo/bank_4/104/block.bin \
    assets/geo/bank_4/105/block.bin \
    assets/geo/bank_4/106/block.bin \
    assets/geo/bank_4/107/block.bin \
    assets/geo/bank_4/108/block.bin \
    assets/geo/bank_4/109/block.bin \
    assets/geo/bank_4/110/block.bin \
    assets/geo/bank_4/111/block.bin \
    assets/geo/bank_4/112/block.bin \
    assets/geo/bank_4/113/block.bin \
    assets/geo/bank_4/114/block.bin \
    assets/geo/bank_4/115/block.bin \
    assets/geo/bank_4/116/block.bin \
    assets/geo/bank_4/117/block.bin \
    assets/geo/bank_4/118/block.bin \
    assets/geo/bank_4/119/block.bin \
    assets/geo/bank_4/120/block.bin \
    assets/geo/bank_4/121/block.bin \
    assets/geo/bank_4/122/block.bin \
    assets/geo/bank_4/123/block.bin \
    assets/geo/bank_4/124/block.bin \
    assets/geo/bank_4/125/block.bin \
    assets/geo/bank_4/126/block.bin \
    assets/geo/bank_4/127/block.bin \
    assets/geo/bank_4/128/block.bin \
    assets/geo/bank_4/129/block.bin \
    assets/geo/bank_4/130/block.bin \
    assets/geo/bank_4/131/block.bin \
    assets/geo/bank_4/132/block.bin \
    assets/geo/bank_4/133/block.bin \
    assets/geo/bank_4/134/block.bin \
    assets/geo/bank_4/135/block.bin \
    assets/geo/bank_4/136/block.bin \
    assets/geo/bank_4/137/block.bin \
    assets/geo/bank_4/138/block.bin \
    assets/geo/bank_4/139/block.bin \
    assets/geo/bank_4/140/block.bin \
    assets/geo/bank_4/141/block.bin \
    assets/geo/bank_4/142/block.bin \
    assets/geo/bank_4/143/block.bin \
    assets/geo/bank_4/144/block.bin \
    assets/geo/bank_4/145/block.bin \
    assets/geo/bank_4/146/block.bin \
    assets/geo/bank_4/147/block.bin \
    assets/geo/bank_4/148/block.bin \
    assets/geo/bank_4/149/block.bin \
    assets/geo/bank_4/150/block.bin \
    assets/geo/bank_4/151/block.bin \
    assets/geo/bank_4/152/block.bin \
    assets/geo/bank_4/153/block.bin

GEO_BANK_6_FILES := \
    assets/geo/bank_6/1/block.bin \
    assets/geo/bank_6/2/block.bin \
    assets/geo/bank_6/3/block.bin \
    assets/geo/bank_6/4/block.bin \
    assets/geo/bank_6/5/block.bin \
    assets/geo/bank_6/6/block.bin \
    assets/geo/bank_6/7/block.bin \
    assets/geo/bank_6/8/block.bin \
    assets/geo/bank_6/9/block.bin \
    assets/geo/bank_6/10/block.bin \
    assets/geo/bank_6/11/block.bin \
    assets/geo/bank_6/12/block.bin \
    assets/geo/bank_6/13/block.bin \
    assets/geo/bank_6/14/block.bin \
    assets/geo/bank_6/15/block.bin \
    assets/geo/bank_6/16/block.bin \
    assets/geo/bank_6/17/block.bin \
    assets/geo/bank_6/18/block.bin \
    assets/geo/bank_6/19/block.bin \
    assets/geo/bank_6/20/block.bin \
    assets/geo/bank_6/21/block.bin \
    assets/geo/bank_6/22/block.bin \
    assets/geo/bank_6/23/block.bin \
    assets/geo/bank_6/24/block.bin \
    assets/geo/bank_6/25/block.bin \
    assets/geo/bank_6/26/block.bin \
    assets/geo/bank_6/27/block.bin \
    assets/geo/bank_6/28/block.bin \
    assets/geo/bank_6/29/block.bin \
    assets/geo/bank_6/30/block.bin \
    assets/geo/bank_6/31/block.bin \
    assets/geo/bank_6/32/block.bin \
    assets/geo/bank_6/33/block.bin \
    assets/geo/bank_6/34/block.bin \
    assets/geo/bank_6/35/block.bin \
    assets/geo/bank_6/36/block.bin \
    assets/geo/bank_6/37/block.bin \
    assets/geo/bank_6/38/block.bin \
    assets/geo/bank_6/39/block.bin \
    assets/geo/bank_6/40/block.bin \
    assets/geo/bank_6/41/block.bin \
    assets/geo/bank_6/42/block.bin \
    assets/geo/bank_6/43/block.bin \
    assets/geo/bank_6/44/block.bin \
    assets/geo/bank_6/45/block.bin \
    assets/geo/bank_6/46/block.bin \
    assets/geo/bank_6/47/block.bin \
    assets/geo/bank_6/48/block.bin \
    assets/geo/bank_6/49/block.bin \
    assets/geo/bank_6/50/block.bin \
    assets/geo/bank_6/51/block.bin \
    assets/geo/bank_6/52/block.bin \
    assets/geo/bank_6/53/block.bin \
    assets/geo/bank_6/54/block.bin \
    assets/geo/bank_6/55/block.bin \
    assets/geo/bank_6/56/block.bin \
    assets/geo/bank_6/57/block.bin \
    assets/geo/bank_6/58/block.bin \
    assets/geo/bank_6/59/block.bin \
    assets/geo/bank_6/60/block.bin \
    assets/geo/bank_6/61/block.bin \
    assets/geo/bank_6/62/block.bin \
    assets/geo/bank_6/63/block.bin \
    assets/geo/bank_6/64/block.bin \
    assets/geo/bank_6/65/block.bin \
    assets/geo/bank_6/66/block.bin \
    assets/geo/bank_6/67/block.bin \
    assets/geo/bank_6/68/block.bin \
    assets/geo/bank_6/69/block.bin \
    assets/geo/bank_6/70/block.bin \
    assets/geo/bank_6/71/block.bin \
    assets/geo/bank_6/72/block.bin \
    assets/geo/bank_6/73/block.bin \
    assets/geo/bank_6/74/block.bin \
    assets/geo/bank_6/75/block.bin \
    assets/geo/bank_6/76/block.bin \
    assets/geo/bank_6/77/block.bin \
    assets/geo/bank_6/78/block.bin \
    assets/geo/bank_6/79/block.bin \
    assets/geo/bank_6/80/block.bin \
    assets/geo/bank_6/81/block.bin \
    assets/geo/bank_6/82/block.bin \
    assets/geo/bank_6/83/block.bin \
    assets/geo/bank_6/84/block.bin \
    assets/geo/bank_6/85/block.bin \
    assets/geo/bank_6/86/block.bin \
    assets/geo/bank_6/87/block.bin \
    assets/geo/bank_6/88/block.bin \
    assets/geo/bank_6/89/block.bin \
    assets/geo/bank_6/90/block.bin \
    assets/geo/bank_6/91/block.bin \
    assets/geo/bank_6/92/block.bin \
    assets/geo/bank_6/93/block.bin \
    assets/geo/bank_6/94/block.bin \
    assets/geo/bank_6/95/block.bin \
    assets/geo/bank_6/96/block.bin \
    assets/geo/bank_6/97/block.bin \
    assets/geo/bank_6/98/block.bin \
    assets/geo/bank_6/99/block.bin \
    assets/geo/bank_6/100/block.bin \
    assets/geo/bank_6/101/block.bin \
    assets/geo/bank_6/102/block.bin \
    assets/geo/bank_6/103/block.bin \
    assets/geo/bank_6/104/block.bin \
    assets/geo/bank_6/105/block.bin \
    assets/geo/bank_6/106/block.bin \
    assets/geo/bank_6/107/block.bin \
    assets/geo/bank_6/108/block.bin \
    assets/geo/bank_6/109/block.bin \
    assets/geo/bank_6/110/block.bin \
    assets/geo/bank_6/111/block.bin \
    assets/geo/bank_6/112/block.bin \
    assets/geo/bank_6/113/block.bin \
    assets/geo/bank_6/114/block.bin \
    assets/geo/bank_6/115/block.bin \
    assets/geo/bank_6/116/block.bin \
    assets/geo/bank_6/117/block.bin \
    assets/geo/bank_6/118/block.bin \
    assets/geo/bank_6/119/block.bin \
    assets/geo/bank_6/120/block.bin \
    assets/geo/bank_6/121/block.bin \
    assets/geo/bank_6/122/block.bin \
    assets/geo/bank_6/123/block.bin \
    assets/geo/bank_6/124/block.bin \
    assets/geo/bank_6/125/block.bin \
    assets/geo/bank_6/126/block.bin \
    assets/geo/bank_6/127/block.bin \
    assets/geo/bank_6/128/block.bin \
    assets/geo/bank_6/129/block.bin \
    assets/geo/bank_6/130/block.bin \
    assets/geo/bank_6/131/block.bin \
    assets/geo/bank_6/132/block.bin \
    assets/geo/bank_6/133/block.bin \
    assets/geo/bank_6/134/block.bin \
    assets/geo/bank_6/135/block.bin \
    assets/geo/bank_6/136/block.bin \
    assets/geo/bank_6/137/block.bin \
    assets/geo/bank_6/138/block.bin \
    assets/geo/bank_6/139/block.bin \
    assets/geo/bank_6/140/block.bin \
    assets/geo/bank_6/141/block.bin \
    assets/geo/bank_6/142/block.bin \
    assets/geo/bank_6/143/block.bin \
    assets/geo/bank_6/144/block.bin \
    assets/geo/bank_6/145/block.bin \
    assets/geo/bank_6/146/block.bin \
    assets/geo/bank_6/147/block.bin \
    assets/geo/bank_6/148/block.bin \
    assets/geo/bank_6/149/block.bin \
    assets/geo/bank_6/150/block.bin \
    assets/geo/bank_6/151/block.bin \
    assets/geo/bank_6/152/block.bin \
    assets/geo/bank_6/153/block.bin \
    assets/geo/bank_6/154/block.bin \
    assets/geo/bank_6/155/block.bin \
    assets/geo/bank_6/156/block.bin \
    assets/geo/bank_6/157/block.bin \
    assets/geo/bank_6/158/block.bin \
    assets/geo/bank_6/159/block.bin \
    assets/geo/bank_6/160/block.bin \
    assets/geo/bank_6/161/block.bin \
    assets/geo/bank_6/162/block.bin \
    assets/geo/bank_6/163/block.bin \
    assets/geo/bank_6/164/block.bin \
    assets/geo/bank_6/165/block.bin \
    assets/geo/bank_6/166/block.bin \
    assets/geo/bank_6/167/block.bin \
    assets/geo/bank_6/168/block.bin \
    assets/geo/bank_6/169/block.bin \
    assets/geo/bank_6/170/block.bin \
    assets/geo/bank_6/171/block.bin \
    assets/geo/bank_6/172/block.bin \
    assets/geo/bank_6/173/block.bin \
    assets/geo/bank_6/174/block.bin \
    assets/geo/bank_6/175/block.bin \
    assets/geo/bank_6/176/block.bin \
    assets/geo/bank_6/177/block.bin \
    assets/geo/bank_6/178/block.bin \
    assets/geo/bank_6/179/block.bin \
    assets/geo/bank_6/180/block.bin \
    assets/geo/bank_6/181/block.bin \
    assets/geo/bank_6/182/block.bin \
    assets/geo/bank_6/183/block.bin \
    assets/geo/bank_6/184/block.bin \
    assets/geo/bank_6/185/block.bin \
    assets/geo/bank_6/186/block.bin \
    assets/geo/bank_6/187/block.bin \
    assets/geo/bank_6/188/block.bin \
    assets/geo/bank_6/189/block.bin \
    assets/geo/bank_6/190/block.bin \
    assets/geo/bank_6/191/block.bin \
    assets/geo/bank_6/192/block.bin \
    assets/geo/bank_6/193/block.bin \
    assets/geo/bank_6/194/block.bin \
    assets/geo/bank_6/195/block.bin \
    assets/geo/bank_6/196/block.bin \
    assets/geo/bank_6/197/block.bin \
    assets/geo/bank_6/198/block.bin \
    assets/geo/bank_6/199/block.bin \
    assets/geo/bank_6/200/block.bin \
    assets/geo/bank_6/201/block.bin \
    assets/geo/bank_6/202/block.bin \
    assets/geo/bank_6/203/block.bin \
    assets/geo/bank_6/204/block.bin \
    assets/geo/bank_6/205/block.bin \
    assets/geo/bank_6/206/block.bin \
    assets/geo/bank_6/207/block.bin \
    assets/geo/bank_6/208/block.bin \
    assets/geo/bank_6/209/block.bin \
    assets/geo/bank_6/210/block.bin \
    assets/geo/bank_6/211/block.bin \
    assets/geo/bank_6/212/block.bin \
    assets/geo/bank_6/213/block.bin \
    assets/geo/bank_6/214/block.bin \
    assets/geo/bank_6/215/block.bin \
    assets/geo/bank_6/216/block.bin \
    assets/geo/bank_6/217/block.bin \
    assets/geo/bank_6/218/block.bin \
    assets/geo/bank_6/219/block.bin \
    assets/geo/bank_6/220/block.bin \
    assets/geo/bank_6/221/block.bin \
    assets/geo/bank_6/222/block.bin \
    assets/geo/bank_6/223/block.bin \
    assets/geo/bank_6/224/block.bin \
    assets/geo/bank_6/225/block.bin \
    assets/geo/bank_6/226/block.bin \
    assets/geo/bank_6/227/block.bin \
    assets/geo/bank_6/228/block.bin \
    assets/geo/bank_6/229/block.bin \
    assets/geo/bank_6/230/block.bin \
    assets/geo/bank_6/231/block.bin \
    assets/geo/bank_6/232/block.bin \
    assets/geo/bank_6/233/block.bin \
    assets/geo/bank_6/234/block.bin \
    assets/geo/bank_6/235/block.bin \
    assets/geo/bank_6/236/block.bin \
    assets/geo/bank_6/237/block.bin \
    assets/geo/bank_6/238/block.bin \
    assets/geo/bank_6/239/block.bin \
    assets/geo/bank_6/240/block.bin \
    assets/geo/bank_6/241/block.bin \
    assets/geo/bank_6/242/block.bin \
    assets/geo/bank_6/243/block.bin \
    assets/geo/bank_6/244/block.bin \
    assets/geo/bank_6/245/block.bin \
    assets/geo/bank_6/246/block.bin \
    assets/geo/bank_6/247/block.bin \
    assets/geo/bank_6/248/block.bin \
    assets/geo/bank_6/249/block.bin \
    assets/geo/bank_6/250/block.bin \
    assets/geo/bank_6/251/block.bin \
    assets/geo/bank_6/252/block.bin \
    assets/geo/bank_6/253/block.bin \
    assets/geo/bank_6/254/block.bin \
    assets/geo/bank_6/255/block.bin \
    assets/geo/bank_6/256/block.bin \
    assets/geo/bank_6/257/block.bin \
    assets/geo/bank_6/258/block.bin \
    assets/geo/bank_6/259/block.bin \
    assets/geo/bank_6/260/block.bin \
    assets/geo/bank_6/261/block.bin \
    assets/geo/bank_6/262/block.bin \
    assets/geo/bank_6/263/block.bin \
    assets/geo/bank_6/264/block.bin \
    assets/geo/bank_6/265/block.bin \
    assets/geo/bank_6/266/block.bin \
    assets/geo/bank_6/267/block.bin \
    assets/geo/bank_6/268/block.bin \
    assets/geo/bank_6/269/block.bin \
    assets/geo/bank_6/270/block.bin \
    assets/geo/bank_6/271/block.bin \
    assets/geo/bank_6/272/block.bin \
    assets/geo/bank_6/273/block.bin \
    assets/geo/bank_6/274/block.bin \
    assets/geo/bank_6/275/block.bin \
    assets/geo/bank_6/276/block.bin \
    assets/geo/bank_6/277/block.bin \
    assets/geo/bank_6/278/block.bin \
    assets/geo/bank_6/279/block.bin \
    assets/geo/bank_6/280/block.bin \
    assets/geo/bank_6/281/block.bin \
    assets/geo/bank_6/282/block.bin \
    assets/geo/bank_6/283/block.bin \
    assets/geo/bank_6/284/block.bin \
    assets/geo/bank_6/285/block.bin \
    assets/geo/bank_6/286/block.bin \
    assets/geo/bank_6/287/block.bin \
    assets/geo/bank_6/288/block.bin \
    assets/geo/bank_6/289/block.bin \
    assets/geo/bank_6/290/block.bin \
    assets/geo/bank_6/291/block.bin \
    assets/geo/bank_6/292/block.bin \
    assets/geo/bank_6/293/block.bin \
    assets/geo/bank_6/294/block.bin

GEO_BANK_7_FILES := \
    assets/geo/bank_7/1/geo.bin \
    assets/geo/bank_7/2/geo.bin \
    assets/geo/bank_7/3/geo.bin \
    assets/geo/bank_7/4/geo.bin \
    assets/geo/bank_7/5/geo.bin \
    assets/geo/bank_7/6/geo.bin \
    assets/geo/bank_7/7/geo.bin \
    assets/geo/bank_7/8/geo.bin \
    assets/geo/bank_7/9/geo.bin \
    assets/geo/bank_7/10/geo.bin \
    assets/geo/bank_7/11/geo.bin \
    assets/geo/bank_7/12/geo.bin \
    assets/geo/bank_7/13/geo.bin \
    assets/geo/bank_7/14/geo.bin \
    assets/geo/bank_7/15/geo.bin \
    assets/geo/bank_7/16/geo.bin \
    assets/geo/bank_7/17/geo.bin \
    assets/geo/bank_7/18/geo.bin \
    assets/geo/bank_7/19/geo.bin \
    assets/geo/bank_7/20/geo.bin \
    assets/geo/bank_7/21/geo.bin \
    assets/geo/bank_7/22/geo.bin \
    assets/geo/bank_7/23/geo.bin \
    assets/geo/bank_7/24/geo.bin \
    assets/geo/bank_7/25/geo.bin \
    assets/geo/bank_7/26/geo.bin \
    assets/geo/bank_7/27/geo.bin \
    assets/geo/bank_7/28/geo.bin \
    assets/geo/bank_7/29/geo.bin \
    assets/geo/bank_7/30/geo.bin \
    assets/geo/bank_7/31/geo.bin \
    assets/geo/bank_7/32/geo.bin \
    assets/geo/bank_7/33/geo.bin \
    assets/geo/bank_7/34/geo.bin \
    assets/geo/bank_7/35/geo.bin \
    assets/geo/bank_7/36/geo.bin \
    assets/geo/bank_7/37/geo.bin \
    assets/geo/bank_7/38/geo.bin \
    assets/geo/bank_7/39/geo.bin \
    assets/geo/bank_7/40/geo.bin \
    assets/geo/bank_7/41/geo.bin \
    assets/geo/bank_7/42/geo.bin \
    assets/geo/bank_7/43/geo.bin \
    assets/geo/bank_7/44/geo.bin \
    assets/geo/bank_7/45/geo.bin \
    assets/geo/bank_7/46/geo.bin \
    assets/geo/bank_7/47/geo.bin \
    assets/geo/bank_7/48/geo.bin \
    assets/geo/bank_7/49/geo.bin \
    assets/geo/bank_7/50/geo.bin \
    assets/geo/bank_7/51/geo.bin \
    assets/geo/bank_7/52/geo.bin \
    assets/geo/bank_7/53/geo.bin \
    assets/geo/bank_7/54/geo.bin \
    assets/geo/bank_7/55/geo.bin \
    assets/geo/bank_7/56/geo.bin \
    assets/geo/bank_7/57/geo.bin \
    assets/geo/bank_7/58/geo.bin \
    assets/geo/bank_7/59/geo.bin \
    assets/geo/bank_7/60/geo.bin \
    assets/geo/bank_7/61/geo.bin \
    assets/geo/bank_7/62/geo.bin \
    assets/geo/bank_7/63/geo.bin \
    assets/geo/bank_7/64/geo.bin \
    assets/geo/bank_7/65/geo.bin \
    assets/geo/bank_7/66/geo.bin \
    assets/geo/bank_7/67/geo.bin \
    assets/geo/bank_7/68/geo.bin \
    assets/geo/bank_7/69/geo.bin \
    assets/geo/bank_7/70/geo.bin \
    assets/geo/bank_7/71/geo.bin \
    assets/geo/bank_7/72/geo.bin \
    assets/geo/bank_7/73/geo.bin \
    assets/geo/bank_7/74/geo.bin \
    assets/geo/bank_7/75/geo.bin \
    assets/geo/bank_7/76/geo.bin \
    assets/geo/bank_7/77/geo.bin \
    assets/geo/bank_7/78/geo.bin \
    assets/geo/bank_7/79/geo.bin \
    assets/geo/bank_7/80/geo.bin \
    assets/geo/bank_7/81/geo.bin \
    assets/geo/bank_7/82/geo.bin \
    assets/geo/bank_7/83/geo.bin \
    assets/geo/bank_7/84/geo.bin \
    assets/geo/bank_7/85/geo.bin \
    assets/geo/bank_7/86/geo.bin \
    assets/geo/bank_7/87/geo.bin \
    assets/geo/bank_7/88/geo.bin \
    assets/geo/bank_7/89/geo.bin \
    assets/geo/bank_7/90/geo.bin \
    assets/geo/bank_7/91/geo.bin \
    assets/geo/bank_7/92/geo.bin \
    assets/geo/bank_7/93/geo.bin \
    assets/geo/bank_7/94/geo.bin \
    assets/geo/bank_7/95/geo.bin \
    assets/geo/bank_7/96/geo.bin \
    assets/geo/bank_7/97/geo.bin \
    assets/geo/bank_7/98/geo.bin \
    assets/geo/bank_7/99/geo.bin \
    assets/geo/bank_7/100/geo.bin \
    assets/geo/bank_7/101/geo.bin \
    assets/geo/bank_7/102/geo.bin \
    assets/geo/bank_7/103/geo.bin \
    assets/geo/bank_7/104/geo.bin \
    assets/geo/bank_7/105/geo.bin \
    assets/geo/bank_7/106/geo.bin \
    assets/geo/bank_7/107/geo.bin \
    assets/geo/bank_7/108/geo.bin \
    assets/geo/bank_7/109/geo.bin \
    assets/geo/bank_7/110/geo.bin \
    assets/geo/bank_7/111/geo.bin \
    assets/geo/bank_7/112/geo.bin \
    assets/geo/bank_7/113/geo.bin \
    assets/geo/bank_7/114/geo.bin \
    assets/geo/bank_7/115/geo.bin \
    assets/geo/bank_7/116/geo.bin \
    assets/geo/bank_7/117/geo.bin \
    assets/geo/bank_7/118/geo.bin \
    assets/geo/bank_7/119/geo.bin \
    assets/geo/bank_7/120/geo.bin \
    assets/geo/bank_7/121/geo.bin \
    assets/geo/bank_7/122/geo.bin \
    assets/geo/bank_7/123/geo.bin \
    assets/geo/bank_7/124/geo.bin \
    assets/geo/bank_7/125/geo.bin \
    assets/geo/bank_7/126/geo.bin \
    assets/geo/bank_7/127/geo.bin \
    assets/geo/bank_7/128/geo.bin \
    assets/geo/bank_7/129/geo.bin \
    assets/geo/bank_7/130/geo.bin \
    assets/geo/bank_7/131/geo.bin \
    assets/geo/bank_7/132/geo.bin \
    assets/geo/bank_7/133/geo.bin \
    assets/geo/bank_7/134/geo.bin \
    assets/geo/bank_7/135/geo.bin \
    assets/geo/bank_7/136/geo.bin \
    assets/geo/bank_7/137/geo.bin \
    assets/geo/bank_7/138/geo.bin \
    assets/geo/bank_7/139/geo.bin \
    assets/geo/bank_7/140/geo.bin \
    assets/geo/bank_7/141/geo.bin \
    assets/geo/bank_7/142/geo.bin \
    assets/geo/bank_7/143/geo.bin \
    assets/geo/bank_7/144/geo.bin \
    assets/geo/bank_7/145/geo.bin \
    assets/geo/bank_7/146/geo.bin \
    assets/geo/bank_7/147/geo.bin \
    assets/geo/bank_7/148/geo.bin \
    assets/geo/bank_7/149/geo.bin \
    assets/geo/bank_7/150/geo.bin \
    assets/geo/bank_7/151/geo.bin \
    assets/geo/bank_7/152/geo.bin \
    assets/geo/bank_7/153/geo.bin \
    assets/geo/bank_7/154/geo.bin \
    assets/geo/bank_7/155/geo.bin \
    assets/geo/bank_7/156/geo.bin \
    assets/geo/bank_7/157/geo.bin \
    assets/geo/bank_7/158/geo.bin \
    assets/geo/bank_7/159/geo.bin \
    assets/geo/bank_7/160/geo.bin \
    assets/geo/bank_7/161/geo.bin \
    assets/geo/bank_7/162/geo.bin \
    assets/geo/bank_7/163/geo.bin \
    assets/geo/bank_7/164/geo.bin \
    assets/geo/bank_7/165/geo.bin \
    assets/geo/bank_7/166/geo.bin \
    assets/geo/bank_7/167/geo.bin \
    assets/geo/bank_7/168/geo.bin \
    assets/geo/bank_7/169/geo.bin \
    assets/geo/bank_7/170/geo.bin \
    assets/geo/bank_7/171/geo.bin \
    assets/geo/bank_7/172/geo.bin \
    assets/geo/bank_7/173/geo.bin \
    assets/geo/bank_7/174/geo.bin \
    assets/geo/bank_7/175/geo.bin \
    assets/geo/bank_7/176/geo.bin \
    assets/geo/bank_7/177/geo.bin \
    assets/geo/bank_7/178/geo.bin \
    assets/geo/bank_7/179/geo.bin \
    assets/geo/bank_7/180/geo.bin \
    assets/geo/bank_7/181/geo.bin \
    assets/geo/bank_7/182/geo.bin \
    assets/geo/bank_7/183/geo.bin \
    assets/geo/bank_7/184/geo.bin \
    assets/geo/bank_7/185/geo.bin \
    assets/geo/bank_7/186/geo.bin \
    assets/geo/bank_7/187/geo.bin \
    assets/geo/bank_7/188/geo.bin \
    assets/geo/bank_7/189/geo.bin \
    assets/geo/bank_7/190/geo.bin \
    assets/geo/bank_7/191/geo.bin \
    assets/geo/bank_7/192/geo.bin \
    assets/geo/bank_7/193/geo.bin \
    assets/geo/bank_7/194/geo.bin \
    assets/geo/bank_7/195/geo.bin \
    assets/geo/bank_7/196/geo.bin \
    assets/geo/bank_7/197/geo.bin \
    assets/geo/bank_7/198/geo.bin \
    assets/geo/bank_7/199/geo.bin \
    assets/geo/bank_7/200/geo.bin \
    assets/geo/bank_7/201/geo.bin \
    assets/geo/bank_7/202/geo.bin \
    assets/geo/bank_7/203/geo.bin \
    assets/geo/bank_7/204/geo.bin \
    assets/geo/bank_7/205/geo.bin \
    assets/geo/bank_7/206/geo.bin \
    assets/geo/bank_7/207/geo.bin \
    assets/geo/bank_7/208/geo.bin \
    assets/geo/bank_7/209/geo.bin \
    assets/geo/bank_7/210/geo.bin
