#include <ultra64.h>
#include <macros.h>

#include "D_8004A7C4.h"
#include "unk_structs/D_800E1B50.h"
#include "ovl1/ovl1_6.h"
// #include "buffers.h"

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_802199D8_ovl9(s32 arg0) {
    struct UnkStruct8004A7C4 *temp_v1;
    u32 temp_v0;
    u32 temp_v0_2;

    temp_v0 = D_8004A7C4->objId;
    D_800DF150[temp_v0] = &D_801ACF5C;
    D_800E1B50[temp_v0]->unk98 = &D_801CB548;
    D_800E8920[D_8004A7C4->objId] = 0;
    func_800A9864(0x10087, 0x23, 0x10);
    func_8019BAC8_ovl9();
    temp_v1 = D_8004A7C4;
    temp_v0_2 = temp_v1->objId;
    if (D_800E98E0[temp_v0_2] == 1) {
        D_800E64D0[temp_v0_2] = D_800E6A10[temp_v0_2] * 6.0f;
        D_800E3210[temp_v1->objId] = 12.0f;
        D_800E3750[temp_v1->objId] = -1.0f;
        D_800E3C90[temp_v1->objId] = D_8021DEB0;
    }
    func_8000B6BC(0x3C);
    D_801ACF84_ovl9(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl9/ovl9_13/func_802199D8_ovl9.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80219B1C_ovl9(s32 arg0) {
    s32 temp_a0;
    struct UnkStruct8004A7C4 *temp_v1;
    u32 temp_v0;
    u32 temp_v0_2;
    f32 phi_f18;
    f32 *phi_at;

    temp_v0 = D_8004A7C4->objId;
    D_800DF150[temp_v0] = &D_801ACF5C;
    D_800E1B50[temp_v0]->unk98 = &D_801CB4DC;
    D_800E8920[D_8004A7C4->objId] = 0;
    func_800A9864(0x10087, 0x23, 0x10);
    func_8019BAC8_ovl9();
    temp_v1 = D_8004A7C4;
    temp_v0_2 = temp_v1->objId;
    temp_a0 = D_800E98E0[temp_v0_2];
    if (temp_a0 != 2) {
        if (temp_a0 != 3) {

        } else {
            D_800E64D0[temp_v0_2] = D_800E6A10[temp_v0_2] * 3.0f;
            D_800E3210[temp_v1->objId] = D_8021DEBC;
            D_800E3750[temp_v1->objId] = -1.0f;
            phi_f18 = D_8021DEC0;
            phi_at = &D_800E3C90[temp_v1->objId];
block_5:
            *phi_at = phi_f18;
        }
    } else {
        D_800E64D0[temp_v0_2] = D_800E6A10[temp_v0_2] * 4.5f;
        D_800E3210[temp_v1->objId] = D_8021DEB4;
        D_800E3750[temp_v1->objId] = -1.0f;
        phi_f18 = D_8021DEB8;
        phi_at = &D_800E3C90[temp_v1->objId];
        goto block_5;
    }
    func_8000B6BC(0x3C);
    D_801ACF84_ovl9(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl9/ovl9_13/func_80219B1C_ovl9.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
? func_80219CE8_ovl9(void) {
    f32 temp_f0;
    f32 temp_f12;
    f32 temp_f2;
    u32 temp_v0;

    temp_v0 = D_8004A7C4->objId;
    if (D_800DD710[D_800E0D50[temp_v0]] == -1) {
        return 0;
    }
    temp_f2 = D_8021DEC4;
    temp_f0 = D_800EC660[temp_v0];
    if (temp_f0 <= temp_f2) {
        return 1;
    }
    temp_f12 = D_8021DEC8;
    if (temp_f12 <= temp_f0) {
        return 1;
    }
    if ((temp_f0 <= D_8021DECC_ovl9) && (D_8021DED0 <= temp_f0)) {
        return 2;
    }
    if ((temp_f0 <= D_8021DED4) && (temp_f2 <= temp_f0)) {
        return 3;
    }
    if ((temp_f0 <= temp_f12) && (D_8021DED8 <= temp_f0)) {
        return 4;
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl9/ovl9_13/func_80219CE8_ovl9.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80219E0C_ovl9(s32 arg0, s32 arg1) {
    f32 sp1C;
    f32 temp_f12;
    struct UnkStruct8004A7C4 *temp_v0_3;
    u32 temp_v0;
    u32 temp_v0_2;
    f32 phi_f2;

    if (arg1 != 0) {
        phi_f2 = 6.0f;
    } else {
        phi_f2 = 12.0f;
    }
    if (arg0 == 1) {
        temp_v0_2 = D_8004A7C4->objId;
        temp_f12 = D_800EC660[temp_v0_2];
        if (temp_f12 != 0.0f) {
            sp1C = phi_f2;
            temp_v0_3 = D_8004A7C4;
            D_800E64D0[temp_v0_3->objId] = -sinf(temp_f12) * phi_f2;
            D_800E3210[D_8004A7C4->objId] = cosf(D_800EC660[temp_v0_3->objId]) * phi_f2;
            return;
        }
        D_800E3210[temp_v0_2] = phi_f2;
        return;
    }
    if (arg0 == 2) {
        D_800E3210[D_8004A7C4->objId] = -phi_f2;
        return;
    }
    if ((arg0 != 3) && (arg0 != 4)) {
        return;
    }
    temp_v0 = D_8004A7C4->objId;
    D_800E64D0[temp_v0] = D_800E6A10[temp_v0] * phi_f2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl9/ovl9_13/func_80219E0C_ovl9.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80219F70_ovl9(s32 arg0) {
    s32 temp_a2;
    s32 temp_v1_3;
    struct UnkStruct8004A7C4 *temp_a3;
    struct UnkStruct8004A7C4 *temp_a3_2;
    u32 temp_v1;
    u32 temp_v1_2;
    u32 temp_v1_4;
    u32 temp_v1_5;
    s32 phi_a2;
    s32 phi_v1;
    s32 *phi_a2_2;

    temp_a3 = D_8004A7C4;
    temp_v1 = temp_a3->objId;
    D_800E9FE0[temp_v1] = 0;
    D_800DF150[temp_a3->objId] = &D_8021A118;
    D_800E1B50[temp_v1]->unk98 = &D_801CB4DC;
    D_800E8920[D_8004A7C4->objId] = 0;
    func_800A9864(0x10088, 0x23, 0x10);
    temp_a3_2 = D_8004A7C4;
    D_800E9E20[temp_a3_2->objId] = func_80219CE8_ovl9();
    temp_v1_2 = temp_a3_2->objId;
    temp_v1_3 = temp_v1_2 * 4;
    temp_a2 = D_800E9E20[temp_v1_2];
    phi_a2 = temp_a2;
    phi_v1 = temp_v1_3;
    if (temp_a2 != 1) {
        phi_a2 = temp_a2;
        phi_v1 = temp_v1_3;
        if (temp_a2 != 2) {
            if (temp_a2 != 3) {
                if (temp_a2 != 4) {
                    phi_a2 = temp_a2;
                    phi_v1 = temp_v1_3;
                } else {
                    D_800E6A10[temp_v1_2] = 1.0f;
                    temp_v1_4 = temp_a3_2->objId;
                    phi_a2_2 = &D_800E9E20[temp_v1_4];
                    phi_v1 = temp_v1_4 * 4;
block_7:
                    phi_a2 = *phi_a2_2;
                }
            } else {
                D_800E6A10[temp_v1_2] = -1.0f;
                temp_v1_5 = temp_a3_2->objId;
                phi_a2_2 = &D_800E9E20[temp_v1_5];
                phi_v1 = temp_v1_5 * 4;
                goto block_7;
            }
        }
    }
    func_80219E0C_ovl9(phi_a2, *(D_800E8AE0 + phi_v1) & 1, phi_a2, temp_a3_2);
    func_8000B6BC(2);
    D_800E9FE0[D_8004A7C4->objId] = 1;
    func_8000B6BC(0x3C);
    D_801ACF84_ovl9(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl9/ovl9_13/func_80219F70_ovl9.s")
#endif

// #ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_8021A118_ovl9(void) {
    func_801A0D74_ovl9();
    if (D_800E8AE0[D_8004A7C4->objId] & 0x10) {
        func_80219E0C_ovl9(D_800E9E20[D_8004A7C4->objId], D_800E8AE0[D_8004A7C4->objId] & 1);
    }
    if (D_800E9FE0[D_8004A7C4->objId] != 0) {
        func_801A03B4_ovl9();
    }
}
// #else
// GLOBAL_ASM("asm/non_matchings/ovl9/ovl9_13/func_8021A118_ovl9.s")
// #endif
