#include <ultra64.h>
#include <macros.h>

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_801BBE50(s32 arg0, s32 arg1, u32 arg2) {
    s32 sp34;
    f32 sp28;
    f32 sp1C;
    s32 sp18;
    s32 temp_v0;
    s32 temp_v1;

    temp_v0 = func_800AEC08_ovl7(0x1F, 0x1E, 0x3C);
    if (temp_v0 == -1) {
        print_error_stub(&D_801CE4A0, temp_v0);
        return -1;
    }
    temp_v1 = temp_v0 * 4;
    D_800E0D50[temp_v0] = arg2;
    *(&D_800E76C0 + temp_v0) = 0xFF;
    *(&D_800E7730 + temp_v0) = 6;
    *(&D_800E77A0 + (temp_v0 * 2)) = 0;
    D_800E7880[temp_v0] = 0;
    *(&D_800E8E60 + temp_v1) = 1;
    sp18 = temp_v1;
    sp34 = temp_v0;
    *(&D_800E1D10 + temp_v1) = arg1;
    func_800A4794_ovl7(&sp28, arg0, temp_v0);
    D_800E25D0[temp_v0] = sp28;
    D_800E2790[temp_v0] = sp2C;
    D_800E2950[temp_v0] = sp30;
    func_800A4DB8_ovl7(&sp1C, arg0);
    *(&D_800E4010 + temp_v1) = sp1C;
    D_800E41D0[temp_v0] = sp20 + D_801CE578;
    *(&D_800E4390 + temp_v1) = sp24;
    D_800E17D0[temp_v0] = D_800E17D0[arg2];
    D_800E6A10[temp_v0] = D_800E6A10[arg2];
    return sp34;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BBE50.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_801BBFE4_ovl7(s32 arg0) {
    s32 sp1C;
    s32 temp_ret;
    s32 temp_v0;
    u32 temp_v0_2;
    u32 temp_v1;
    s32 phi_v1;

    temp_ret = func_800AEC08_ovl7(0x1F, 0x1E, 0x3C);
    temp_v0 = temp_ret;
    if (temp_v0 == -1) {
        print_error_stub(&D_801CE4C8, temp_v0);
        return -1;
    }
    *(&D_800E76C0 + temp_v0) = 0xFF;
    *(&D_800E7730 + temp_v0) = 6;
    temp_v1 = D_800E0D50[temp_v0];
    *(&D_800E77A0 + (temp_v0 * 2)) = arg0;
    D_800E7880[temp_v0] = 0;
    D_800E5F90[temp_v0] = D_800E5F90[temp_v1];
    D_800E6BD0[temp_v0] = D_800E6BD0[temp_v1];
    D_800E6A10[temp_v0] = D_800E6A10[temp_v1];
    if (temp_v1 == 0) {
        sp1C = temp_v0;
        D_800E2790[temp_v0] = func_8019B144_ovl7(temp_v0 * 4, temp_v1 * 4, temp_v0, D_800E5F90);
        phi_v1 = temp_v0 * 4;
    } else {
        D_800E2790[temp_v0] = D_800E2790[temp_v1];
        phi_v1 = temp_v0 * 4;
    }
    temp_v0_2 = *(D_800E0D50 + phi_v1);
    temp_v0_2 = temp_v0_2 * 4;
    *(&D_800E4010 + phi_v1) = *(&D_800E4010 + temp_v0_2);
    *(D_800E41D0 + phi_v1) = D_800E41D0[temp_v0_2];
    *(&D_800E4390 + phi_v1) = *(&D_800E4390 + temp_v0_2);
    *(&D_800E8E60 + phi_v1) = 0;
    *(&D_800E8220 + (D_8004A7C4->unk0 * 4)) = 1;
    sp1C = temp_ret;
    func_801BC1AC_ovl7(arg0, &D_800E4010, temp_ret, D_800E41D0);
    D_800D7090 = sp1C;
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BBFE4_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_801BC1AC_ovl7(s32 arg0) {
    if (*(&D_800E8220 + (D_8004A7C4->unk0 * 4)) == 0) {
        D_801D0A58.unk0 = D_801CA6F4.unk0;
        D_801D0A58.unk4 = D_801CA6F4.unk4;
        D_801D0A58.unk8 = D_801CA6F4.unk8;
        D_801D0A58.unkC = D_801CA6F4.unkC;
        D_801D0A58.unk10 = D_801CA6F4.unk10;
        D_801D0A58.unk14 = D_801CA6F4.unk14;
        D_801D0A58.unk18 = D_801CA6F4.unk18;
        D_801D0A58.unk1C = D_801CA6F4.unk1C;
    } else {
        D_801D0A58.unk0 = D_801CA738.unk0;
        D_801D0A58.unk4 = D_801CA738.unk4;
        D_801D0A58.unk8 = D_801CA738.unk8;
        D_801D0A58.unkC = D_801CA738.unkC;
        D_801D0A58.unk10 = D_801CA738.unk10;
        D_801D0A58.unk14 = D_801CA738.unk14;
        D_801D0A58.unk18 = D_801CA738.unk18;
        D_801D0A58.unk1C = D_801CA738.unk1C;
    }
    D_801D0A58.unk1C = arg0;
    return &D_801D0A58;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC1AC_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_801BC27C_ovl7(s32 arg0, s32 arg1) {
    s32 sp1C;
    s32 temp_ret;
    s32 temp_v0;
    u32 temp_v0_2;
    u32 temp_v1;
    s32 phi_v1;

    temp_ret = func_800AEC08_ovl7(0x1F, 0x1E, 0x3C);
    temp_v0 = temp_ret;
    if (temp_v0 == -1) {
        print_error_stub(&D_801CE4F4, temp_v0);
        return -1;
    }
    *(&D_800E76C0 + temp_v0) = 0xFF;
    *(&D_800E7730 + temp_v0) = 6;
    temp_v1 = D_800E0D50[temp_v0];
    *(&D_800E77A0 + (temp_v0 * 2)) = arg0;
    D_800E7880[temp_v0] = arg1;
    D_800E5F90[temp_v0] = D_800E5F90[temp_v1];
    D_800E6BD0[temp_v0] = D_800E6BD0[temp_v1];
    D_800E6A10[temp_v0] = D_800E6A10[temp_v1];
    if (temp_v1 == 0) {
        sp1C = temp_v0;
        D_800E2790[temp_v0] = func_8019B144_ovl7(temp_v0 * 4, temp_v1 * 4, temp_v0, D_800E5F90);
        phi_v1 = temp_v0 * 4;
    } else {
        D_800E2790[temp_v0] = D_800E2790[temp_v1];
        phi_v1 = temp_v0 * 4;
    }
    temp_v0_2 = *(D_800E0D50 + phi_v1);
    temp_v0_2 = temp_v0_2 * 4;
    *(&D_800E4010 + phi_v1) = *(&D_800E4010 + temp_v0_2);
    *(D_800E41D0 + phi_v1) = D_800E41D0[temp_v0_2];
    *(&D_800E4390 + phi_v1) = *(&D_800E4390 + temp_v0_2);
    *(&D_800E8E60 + phi_v1) = 0;
    *(&D_800E8220 + (D_8004A7C4->unk0 * 4)) = 1;
    sp1C = temp_ret;
    func_801BC44C_ovl7(arg0, &D_800E4010, temp_ret, D_800E41D0);
    D_800D7090 = sp1C;
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC27C_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_801BC44C_ovl7(s32 arg0) {
    D_801CE750.unk0 = D_801C7DDC.unk0;
    D_801CE750.unk4 = D_801C7DDC.unk4;
    D_801CE750.unk8 = D_801C7DDC.unk8;
    D_801CE750.unkC = D_801C7DDC.unkC;
    D_801CE750.unk10 = D_801C7DDC.unk10;
    D_801CE750.unk14 = D_801C7DDC.unk14;
    D_801CE750.unk18 = D_801C7DDC.unk18;
    D_801CE750.unk1C = D_801C7DDC.unk1C;
    D_801CE750.unk1C = *(&D_801CD820 + (arg0 * 4));
    if (*(&D_800E8220 + (D_8004A7C4->unk0 * 4)) == 0) {
        D_801D0A38.unk0 = D_801CA7DC.unk0;
        D_801D0A38.unk4 = D_801CA7DC.unk4;
        D_801D0A38.unk8 = D_801CA7DC.unk8;
        D_801D0A38.unkC = D_801CA7DC.unkC;
        D_801D0A38.unk10 = D_801CA7DC.unk10;
        D_801D0A38.unk14 = D_801CA7DC.unk14;
        D_801D0A38.unk18 = D_801CA7DC.unk18;
        D_801D0A38.unk1C = D_801CA7DC.unk1C;
    } else {
        D_801D0A38.unk0 = D_801CA7FC.unk0;
        D_801D0A38.unk4 = D_801CA7FC.unk4;
        D_801D0A38.unk8 = D_801CA7FC.unk8;
        D_801D0A38.unkC = D_801CA7FC.unkC;
        D_801D0A38.unk10 = D_801CA7FC.unk10;
        D_801D0A38.unk14 = D_801CA7FC.unk14;
        D_801D0A38.unk18 = D_801CA7FC.unk18;
        D_801D0A38.unk1C = D_801CA7FC.unk1C;
    }
    D_801D0A38.unk1C = arg0;
    return &D_801D0A38;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC44C_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_801BC580_ovl7(s32 arg0) {
    s32 sp1C;
    s32 temp_ret;
    s32 temp_v0;
    u32 temp_v0_2;
    u32 temp_v1;
    s32 phi_v1;

    temp_ret = func_800AEC08_ovl7(0x1F, 0x1E, 0x3C);
    temp_v0 = temp_ret;
    if (temp_v0 == -1) {
        print_error_stub(&D_801CE520, temp_v0);
        return -1;
    }
    *(&D_800E76C0 + temp_v0) = 0xFF;
    *(&D_800E7730 + temp_v0) = 6;
    temp_v1 = D_800E0D50[temp_v0];
    *(&D_800E77A0 + (temp_v0 * 2)) = arg0 + 0x24;
    D_800E7880[temp_v0] = 0;
    D_800E5F90[temp_v0] = D_800E5F90[temp_v1];
    D_800E6BD0[temp_v0] = D_800E6BD0[temp_v1];
    D_800E6A10[temp_v0] = D_800E6A10[temp_v1];
    if (temp_v1 == 0) {
        sp1C = temp_v0;
        D_800E2790[temp_v0] = func_8019B144_ovl7(temp_v0 * 4, temp_v1 * 4, temp_v0, D_800E5F90);
        phi_v1 = temp_v0 * 4;
    } else {
        D_800E2790[temp_v0] = D_800E2790[temp_v1];
        phi_v1 = temp_v0 * 4;
    }
    temp_v0_2 = *(D_800E0D50 + phi_v1);
    temp_v0_2 = temp_v0_2 * 4;
    *(&D_800E4010 + phi_v1) = *(&D_800E4010 + temp_v0_2);
    *(D_800E41D0 + phi_v1) = D_800E41D0[temp_v0_2];
    *(&D_800E4390 + phi_v1) = *(&D_800E4390 + temp_v0_2);
    *(&D_800E8E60 + phi_v1) = 0;
    sp1C = temp_ret;
    func_801BC72C_ovl7(arg0, &D_800E4010, temp_ret, D_800E41D0);
    D_800D7090 = sp1C;
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC580_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_801BC72C_ovl7(s32 arg0) {
    D_801CE770.unk0 = D_801C7E84.unk0;
    D_801CE770.unk4 = D_801C7E84.unk4;
    D_801CE770.unk8 = D_801C7E84.unk8;
    D_801CE770.unkC = D_801C7E84.unkC;
    D_801CE770.unk10 = D_801C7E84.unk10;
    D_801CE770.unk14 = D_801C7E84.unk14;
    D_801CE770.unk18 = D_801C7E84.unk18;
    D_801CE770.unk1C = D_801C7E84.unk1C;
    D_801CE770.unk1C = *(&D_801CD820 + (arg0 * 4));
    return &D_801CE770;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC72C_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_801BC794_ovl7(s32 arg0) {
    s32 sp1C;
    f32 *temp_a2;
    s32 temp_ret;
    s32 temp_v0;
    u32 temp_a0;
    u32 temp_v1;
    s32 phi_a0;
    f32 *phi_a2;

    temp_ret = func_800AEC08_ovl7(0x1C, 0x1E, 0x3C);
    temp_v0 = temp_ret;
    if (temp_v0 == -1) {
        print_error_stub(&D_801CE54C, temp_v0);
        return -1;
    }
    *(&D_800E76C0 + temp_v0) = 0xFF;
    *(&D_800E7730 + temp_v0) = 3;
    temp_a0 = D_800E0D50[temp_v0];
    *(&D_800E77A0 + (temp_v0 * 2)) = 8;
    D_800E7880[temp_v0] = arg0;
    D_800E5F90[temp_v0] = D_800E5F90[temp_a0];
    D_800E6BD0[temp_v0] = D_800E6BD0[temp_a0];
    D_800E6A10[temp_v0] = D_800E6A10[temp_a0];
    if (temp_a0 == 0) {
        sp1C = temp_v0;
        temp_a2 = &D_800E2790[temp_v0];
        *temp_a2 = func_8019B144_ovl7(temp_a0, temp_a0 * 4, D_800E5F90, temp_v0);
        phi_a0 = temp_v0 * 4;
        phi_a2 = temp_a2;
    } else {
        D_800E2790[temp_v0] = D_800E2790[temp_a0];
        phi_a0 = temp_v0 * 4;
        phi_a2 = &D_800E2790[temp_v0];
    }
    temp_v1 = *(D_800E0D50 + phi_a0);
    temp_v1 = temp_v1 * 4;
    *(&D_800E4010 + phi_a0) = *(&D_800E4010 + temp_v1);
    *(D_800E41D0 + phi_a0) = D_800E41D0[temp_v1];
    *(&D_800E4390 + phi_a0) = *(&D_800E4390 + temp_v1);
    *(&D_800E8E60 + phi_a0) = *(&D_800E8E60 + temp_v1);
    *(D_800E25D0 + phi_a0) = D_800E25D0[temp_v1];
    *phi_a2 = *(D_800E2790 + temp_v1);
    *(D_800E2950 + phi_a0) = D_800E2950[temp_v1];
    return temp_ret;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC794_ovl7.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
Failed to decompile function func_801BC978_ovl7:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl7/ovl7_15/func_801BC978_ovl7.s")
#endif
