#include <ultra64.h>
#include <macros.h>

struct UnkWhat {
    u32 unk0;
    u32 unk4;
    u32 unk8;
    u32 unkC;
    u32 unk10[0x10000 - 0x10];
};
extern f32 D_800D5DD8;
extern u32 D_800E02D0[];
extern u32 *D_8004A7C4;
extern u32 D_800DF4D0[];
extern struct UnkWhat D_800D00C4[][1];

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A82C0(void) {
    s32 temp_t8;

    temp_t8 = (D_8004A408.unkC + 0xFF) & -0x100;
    D_800D7BB4 = temp_t8;
    D_800D7BB0 = temp_t8;
    D_800D7BB8 = (s32) (D_8004A408.unk8 - temp_t8);
    *(void *)0x800D7C10 = 0x80400000;
    return &D_800D7BB4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A82C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8310(s32 arg0) {
    s32 temp_a0;
    s32 temp_t0;
    s32 temp_t7;

    temp_a0 = arg0 & -0x10;
    temp_t7 = D_800D7BB8 - temp_a0;
    D_800D7BB8 = temp_t7;
    if (temp_t7 < 0) {
        return 0;
    }
    temp_t0 = D_800D7BB4 + temp_a0;
    D_800D7BB4 = temp_t0;
    return temp_t0 - temp_a0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8310.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A8358(s32 arg0) {
    s32 temp_v1;
    u32 temp_a0;
    void *temp_a2;
    void *phi_a1;

    temp_v1 = arg0 & 3;
    temp_a0 = ((arg0 - temp_v1) + 0xC) & -0x10;
    phi_a1 = *(&D_800D7BD0 + (temp_v1 * 4));
loop_1:
    if (phi_a1->unkC != 0) {
block_3:
        phi_a1 = phi_a1->unk4;
        goto loop_1;
    }
    if ((u32) phi_a1->unk8 < (u32) (temp_a0 + 0x10)) {
        goto block_3;
    }
    temp_a2 = phi_a1 + temp_a0;
    temp_a2->unk10 = phi_a1;
    temp_a2 = temp_a2 + 0x10;
    temp_a2->unk4 = (void *) phi_a1->unk4;
    temp_a2->unkC = 0;
    temp_a2->unk8 = (s32) ((phi_a1->unk8 - temp_a0) - 0x10);
    phi_a1->unk4 = temp_a2;
    *temp_a2->unk4 = temp_a2;
    *(&D_800D7BD0 + (temp_v1 * 4)) = (s32) *temp_a2->unk4;
    D_800D7BBC = phi_a1;
    phi_a1->unk8 = temp_a0;
    phi_a1->unkC = 1;
    return phi_a1 + 0x10;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8358.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A840C(u32 arg0, s32 arg1) {
    void *sp1C;
    void *temp_v0;
    void *temp_v0_2;

    if ((((arg1 & 3) * 4) + 0x800D0000)->unk7BD0 != 0) {
        return NULL;
    }
    if (arg0 < 0x40U) {
        return NULL;
    }
    temp_v0 = func_800A8310_ovl1();
    if (temp_v0 == 0) {
        return NULL;
    }
    ((arg1 * 4) + 0x800D0000)->unk7BD0 = temp_v0;
    temp_v0_2 = (temp_v0 + arg0) - 0x20;
    temp_v0->unk0 = temp_v0_2;
    temp_v0->unk4 = temp_v0_2;
    temp_v0->unk8 = (s32) (arg0 - 0x30);
    temp_v0->unkC = 0;
    temp_v0_2->unk4 = temp_v0;
    temp_v0->unk4->unk0 = (s32) temp_v0->unk4->unk4;
    temp_v0->unk4->unk8 = 0x10;
    temp_v0->unk4->unkC = 0xFF000000;
    sp1C = temp_v0;
    memcpy(temp_v0->unk4 + 0x10, &D_800C4640, 0x10, temp_v0->unk4);
    return sp1C;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A840C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A84F0(s32 arg0) {
    s32 temp_v0;

    temp_v0 = D_800D7C10;
    D_800D7C10 = (s32) (temp_v0 + ((arg0 + 0xF) & 0xFFFFF0));
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A84F0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A8518(s32 arg0) {
    s32 temp_t7;
    void *temp_v0;

    temp_v0 = arg0 - 0x10;
    temp_t7 = temp_v0->unkC & 0xFFFFFF;
    temp_v0->unkC = temp_t7;
    temp_v0->unkC = (s32) (temp_t7 | 0x99000000);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8518.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A8540(s32 arg0) {
    void *temp_v0;

    temp_v0 = arg0 - 0x10;
    temp_v0->unkC = (s32) (temp_v0->unkC & 0xFFFFFF);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8540.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A855C(void *arg0, ?32 arg1) {
    arg0->unk-4 = arg1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A855C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A8564(s32 arg0, s32 arg1) {
    void *temp_v0;

    temp_v0 = arg0 - 0x10;
    temp_v0->unkC += arg1;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8564.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
u32 func_800A8578(s32 arg0) {
    s32 temp_v1;
    u32 temp_v0;
    void *temp_a1;
    void *temp_v1_2;
    void *temp_v1_3;
    void *phi_v0;
    void *phi_v1;
    void *phi_v1_2;

    temp_v1 = (arg0 - 0x10) & -4;
    if (0x99000000U == (temp_v1->unkC & 0xFF000000)) {
        return 0x99000000U;
    }
    if ((u32) temp_v1->unkC >= 2U) {
        temp_v0 = temp_v1->unkC - 1;
        temp_v1->unkC = temp_v0;
        return temp_v0;
    }
    temp_v1->unkC = 0U;
    phi_v0 = (void *) temp_v1;
    if (temp_v1->unk0->unkC == 0) {
        phi_v0 = temp_v1->unk0;
    }
    temp_v1_2 = phi_v0->unk4;
    temp_a1 = ((arg0 & 3) * 4) + &D_800D7BD0;
    phi_v1 = temp_v1_2;
    if (temp_v1_2->unkC == 0) {
loop_7:
        phi_v1_2 = phi_v1;
        if (phi_v1 == *temp_a1) {
            *temp_a1 = phi_v0;
            phi_v1_2 = phi_v0->unk4;
        }
        phi_v0->unk8 = (s32) ((phi_v0->unk8 + phi_v1_2->unk8) + 0x10);
        *phi_v1_2->unk4 = phi_v0;
        temp_v1_3 = phi_v0->unk4->unk4;
        phi_v0->unk4 = temp_v1_3;
        phi_v1 = temp_v1_3;
        if (temp_v1_3->unkC == 0) {
            goto loop_7;
        }
    }
    return 0U;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8578.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8648(void) {
    s32 temp_s0;
    s32 temp_s3;
    s32 phi_s0;
    void *phi_s1;
    void *phi_s2;
    s32 phi_s3;

    phi_s0 = 0;
    phi_s1 = &D_800D7BF0;
    phi_s2 = &D_800D7C00;
    phi_s3 = 0;
loop_1:
    temp_s0 = phi_s0 + 1;
    temp_s3 = phi_s3 + func_800A86C8_ovl1(phi_s0, phi_s1, phi_s2);
    phi_s0 = temp_s0;
    phi_s1 = phi_s1 + 4;
    phi_s2 = phi_s2 + 4;
    phi_s3 = temp_s3;
    if (temp_s0 != 4) {
        goto loop_1;
    }
    return temp_s3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8648.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A86C8(s32 arg0, void *arg1, void *arg2) {
    void *temp_t0;
    void *temp_v0;
    void *phi_t0;
    s32 phi_a3;
    s32 phi_v1;
    s32 phi_a3_2;
    s32 phi_v1_2;

    temp_v0 = ((arg0 & 3) * 4) + 0x800D0000;
    phi_t0 = temp_v0->unk7BC0;
    phi_a3_2 = 0x30;
    phi_v1_2 = 0;
loop_1:
    phi_a3 = phi_a3_2;
    phi_v1 = phi_v1_2;
    if ((phi_t0->unkC & 0xFF) != 0) {
        phi_a3 = (phi_a3_2 + phi_t0->unk8) + 0x10;
        phi_v1 = phi_v1_2 + 1;
    }
    temp_t0 = phi_t0->unk4;
    phi_t0 = temp_t0;
    phi_a3_2 = phi_a3;
    phi_v1_2 = phi_v1;
    if (temp_t0 != temp_v0->unk7BC0) {
        goto loop_1;
    }
    *arg1 = phi_a3;
    *arg2 = phi_v1;
    return phi_a3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A86C8.s")
#endif

extern u32 D_800D00E4, D_800D0124;
extern u32 D_800D6E78;
extern u32 D_800D6E68;
extern u32 D_800D6E7C;
extern u32 D_800D6E6C;
extern u32 D_800D6E80;
extern u32 D_800D6E70;
extern u32 D_800D6E84;
extern u32 D_800D6E74;

struct UnkStruct800C4654{
    u32 unk0;
    u32 unk4;
    u32 unk8;
    u32 unkC;
} ; extern struct UnkStruct800C4654 D_800C4654[5];
extern u32 D_800D7BC0;
extern u32 D_800D7BD0;
extern u32 D_800D7BE0;
extern u32 *D_800D0104[][16];
extern u32 D_800D0144;
extern u32 D_800D7BB8;
// doozy / 10
#ifdef MIPS_TO_C
s32 func_800A8724(s32 arg0) {
    s32 temp_a2;
    s32 temp_v0;
    u32 *phi_a2;
    s32 phi_a3;
    u32 *phi_a1;
    s32 phi_a0;
    u32 *phi_s0;
    u32 *phi_s1;
    struct UnkStruct800C4654 *phi_s2;
    u32 *phi_s3;
    u32 *phi_s4;
    s32 count;
    u32 j;

    func_800A82C0_ovl1();
    phi_a2 = D_800D00E4;
    phi_a3 = 0;
    phi_a1 = D_800D0124;
    while (*phi_a1 < D_800D0144) {
        if (phi_a2 != 0) {
            for (j = 0; j < *phi_a2; j++) {
                D_800D00C4[phi_a3][j].unk0 = 0;
            }
        }
        if (phi_a1 != 0) {
            for (j = 0; j < *phi_a1; j++) {
                D_800D0104[phi_a3][j] = 0;
            }
        }
        phi_a1++;
        phi_a2++;
        phi_a3++;
    }
    // phi_s0 = &D_800D7BD0;
    phi_a0 = D_800D7BB8;
    phi_s2 = &D_800C4654[arg0];
    phi_s4 = &D_800D7BE0;
    phi_s3 = &D_800D7BC0;
    count = 0;
    phi_s1 = 0;
    while (*phi_s1 < 4) {
        temp_a2 = phi_s2;
        // *phi_s0 = 0;
        if (temp_a2 != 0) {
            if (temp_a2 == -1) {
                // *phi_s0 = temp_v0;
                if (func_800A840C_ovl1(D_800D7BB8, phi_s1) == 0) {
                    count++;
                }
            } else {
                // *phi_s0 = temp_v0;
                if (func_800A840C_ovl1(temp_a2, phi_s1) == 0) {
                    count++;
                }
            }
        }
        // phi_s0++;
        phi_s1++;
        phi_s2++;
        phi_s3++;
        phi_s4++;
        phi_s4 = (s32) (phi_a0 - D_800D7BB8);
        phi_s3 = (s32) *phi_s0;
    }

    D_800D6E78 = 0;
    D_800D6E68 = 0;
    D_800D6E7C = 0;
    D_800D6E6C = 0;
    D_800D6E80 = 0;
    D_800D6E70 = 0;
    D_800D6E84 = 0;
    D_800D6E74 = 0;
    return count;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8724.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8934(u32 arg0, s32 arg1, s32 arg2, ? arg3) {
    s32 temp_a2;
    void *temp_v0;
    void *temp_v1;
    s32 phi_a2;

    temp_v1 = ((arg0 >> 0x10) * 4) + 0x800D0000;
    temp_v0 = temp_v1->unk184->unk8 + ((arg0 & 0xFFFF) * 4);
    if (arg2 == 0) {
        temp_a2 = (((temp_v0->unk4 - temp_v0->unk0) + 3) & 0xFFFFFC) - arg1;
        phi_a2 = temp_a2;
        if (temp_a2 < 0x10) {
            return -1;
        }
    } else {
        phi_a2 = (arg2 + 3) & 0xFFFFFC;
    }
    arg2 = phi_a2;
    func_80002E48_ovl1((temp_v0->unk0 + temp_v1->unk184->unkC) + arg1, arg3, phi_a2);
    return arg2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8934.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A89E0(u32 arg0) {
    s32 sp24;
    s32 sp20;
    void *sp1C;
    s32 sp18;
    s32 temp_a0;
    s32 temp_a1;
    s32 temp_a3;
    s32 temp_v0_2;
    void *temp_v0;
    void *temp_v1;

    temp_v0 = ((arg0 >> 0x10) * 4) + 0x800D0000;
    temp_a1 = arg0 & 0xFFFF;
    temp_v1 = temp_v0->unk184->unk8 + (temp_a1 * 4);
    sp18 = temp_v0->unk184->unkC;
    temp_a3 = (temp_v1->unk4 - temp_v1->unk0) + 3;
    temp_a0 = temp_a3 & 0xFFFFFC;
    sp24 = temp_a0;
    sp1C = temp_v1;
    temp_v0_2 = func_800A84F0_ovl1(temp_a0, temp_a1, temp_a3);
    sp20 = temp_v0_2;
    func_80002E48_ovl1(temp_v1->unk0 + sp18, temp_v0_2, sp24 & 0xFFFFFC, sp24);
    return temp_v0_2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A89E0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8A7C(u32 arg0) {
    void *sp1C;
    s32 sp18;
    s32 temp_a3;
    s32 temp_t7;
    void *temp_t0;
    void *temp_v1;

    temp_t7 = (arg0 >> 0x10) * 4;
    temp_v1 = temp_t7 + &D_800D0104;
    temp_a3 = arg0 & 0xFFFF;
    temp_a3 = temp_a3 * 4;
    temp_t0 = *temp_v1 + temp_a3;
    if (*temp_t0 != 0) {
        sp1C = temp_v1;
        sp18 = temp_a3;
        func_800A8564_ovl1(*temp_t0, 1, *temp_t0, temp_a3);
    } else {
        sp1C = temp_v1;
        sp18 = temp_a3;
        *(*temp_v1 + temp_a3) = func_800A89E0_ovl1(1, *temp_t0, temp_a3);
    }
    return *(*(temp_t7 + &D_800D0104) + (temp_a3 * 4));
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8A7C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8B0C(u32 arg0, s32 arg1) {
    s32 sp24;
    s32 sp20;
    void *sp1C;
    s32 sp18;
    s32 temp_a2;
    s32 temp_a3;
    s32 temp_v0_2;
    void *temp_v0;
    void *temp_v1;

    temp_v0 = ((arg0 >> 0x10) * 4) + 0x800D0000;
    temp_a2 = arg0 & 0xFFFF;
    temp_v1 = temp_v0->unk184->unk8 + (temp_a2 * 4);
    sp18 = temp_v0->unk184->unkC;
    temp_a3 = ((temp_v1->unk4 - temp_v1->unk0) + 3) & 0xFFFFFC;
    sp24 = temp_a3;
    sp1C = temp_v1;
    temp_v0_2 = func_800A8358_ovl1(temp_a3 | arg1, temp_a2, temp_a3);
    sp20 = temp_v0_2;
    func_80002E48_ovl1(temp_v1->unk0 + sp18, temp_v0_2, temp_a3 & 0xFFFFFC, temp_a3);
    return temp_v0_2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8B0C.s")
#endif

#ifdef MIPS_TO_C
s32 func_800A8BAC(u32 arg0) {
    s32 temp_a3;

    
    if (*D_800D0104[arg0 >> 10][arg0 & 0xFFFF] != 0) {
        // sp1C = temp_v1;
        // sp18 = temp_a3;
        temp_a3 = func_800A8564(*D_800D0104[arg0 >> 10][arg0 & 0xFFFF], temp_a3);
    } else {
        // sp1C = temp_v1;
        // sp18 = temp_a3;
        temp_a3 = func_800A8B0C_ovl1(3, *D_800D0104[arg0 >> 10][arg0 & 0xFFFF], temp_a3);
    }
    return *(D_800D0104[arg0 >> 10][temp_a3]);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8BAC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8C40(u32 arg0) {
    void *sp20;
    s32 sp1C;
    s32 temp_a3;
    void *temp_a2;
    void *temp_t0;
    void *temp_t4;
    s32 phi_a1;

    temp_a2 = ((arg0 >> 0x10) * 4) + &D_800D0104;
    temp_a3 = (arg0 & 0xFFFF) * 4;
    temp_t0 = *temp_a2 + temp_a3;
    phi_a1 = *temp_t0;
    if (*temp_t0 == 0) {
        sp20 = temp_a2;
        sp1C = temp_a3;
        *(*temp_a2 + temp_a3) = func_800A8B0C_ovl1(3, temp_a2, temp_a3);
        temp_t4 = *temp_a2 + temp_a3;
        (*temp_t4)->unk8 = (void *) ((*temp_t4)->unk8 + *temp_t4);
        (*temp_t4)->unkC = (void *) ((*temp_t4)->unkC + *temp_t4);
        phi_a1 = *(*temp_a2 + temp_a3);
    }
    return phi_a1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8C40.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8CE0(u32 arg0, s32 arg1) {
    s32 sp2C;
    s32 sp20;
    void *sp1C;
    s32 temp_a0;
    s32 temp_a2;
    s32 temp_v0;
    void *temp_v1;

    temp_a2 = arg0 & 0xFFFF;
    temp_v1 = *(((arg0 >> 0x10) * 4) + 0x800D0000)->unk184 + (temp_a2 * 8);
    sp1C = temp_v1;
    temp_a0 = (temp_v1->unk4 - temp_v1->unk0) | arg1;
    sp2C = temp_a0;
    temp_v0 = func_800A8358_ovl1(temp_a0, temp_a2 * 2);
    sp20 = temp_v0;
    func_80002E48_ovl1(temp_v1->unk0, temp_v0, sp2C & 0xFFFFFC, sp2C);
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8CE0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A8D64(u32 arg0, s32 arg1) {
    s32 sp20;
    s32 temp_s1;
    s32 temp_v1;
    u32 temp_v0;
    u32 temp_v1_2;
    void *temp_s0;
    void *temp_t0;
    void *temp_t9;
    u32 phi_v1;
    void *phi_s0;

    temp_s0 = ((arg0 >> 0x10) * 4) + &D_800D00C4;
    temp_v1 = (arg0 & 0xFFFF) * 4;
    temp_t0 = *temp_s0 + temp_v1;
    temp_s1 = *temp_t0;
    if (temp_s1 != 0) {
        sp20 = temp_v1;
        if (func_800A8578_ovl1(temp_s1 | arg1) == 0) {
            *(*temp_s0 + temp_v1) = 0;
            phi_v1 = *temp_s1->unkC;
            phi_s0 = temp_s1->unkC;
            if (*temp_s1->unkC != 0) {
loop_3:
                temp_t9 = *(&D_800D0104 + ((phi_v1 >> 0x10) * 4)) + ((phi_v1 & 0xFFFF) * 4);
                if (*temp_t9 != 0) {
                    if (func_800A8578_ovl1(*temp_t9 | 3, *temp_t9) == 0) {
                        temp_v0 = phi_s0->unk0;
                        *(*(&D_800D0104 + ((temp_v0 >> 0x10) * 4)) + ((temp_v0 & 0xFFFF) * 4)) = 0;
                    }
                }
                temp_v1_2 = phi_s0->unk4;
                phi_v1 = temp_v1_2;
                phi_s0 = phi_s0 + 4;
                if (temp_v1_2 != 0) {
                    goto loop_3;
                }
            }
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8D64.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A8E54(u32 arg0, s32 arg1) {
    void *sp1C;
    s32 sp18;
    s32 temp_a2;
    s32 temp_ret;
    void *temp_t0;
    void *temp_v1;
    s32 phi_return;

    temp_v1 = ((arg0 >> 0x10) * 4) + &D_800D0104;
    temp_a2 = (arg0 & 0xFFFF) * 4;
    temp_t0 = *temp_v1 + temp_a2;
    phi_return = *temp_t0;
    if (*temp_t0 != 0) {
        sp1C = temp_v1;
        sp18 = temp_a2;
        temp_ret = func_800A8578_ovl1(*temp_t0 | arg1, temp_a2);
        phi_return = temp_ret;
        if (temp_ret == 0) {
            *(*temp_v1 + temp_a2) = 0;
            phi_return = temp_ret;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8E54.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A8EC0(u32 arg0) {
    void *sp18;
    s32 temp_t7;
    s32 temp_v0_2;
    s32 temp_v1;
    s32 temp_v1_2;
    u32 temp_a3;
    void *temp_a2;
    void *temp_t5;
    void *temp_v0;
    void *phi_v0;
    s32 phi_v1;
    s32 phi_a1;
    s32 phi_v1_2;
    s32 phi_v0_2;
    void *phi_v0_3;
    u32 phi_a3;
    void *phi_a2;
    s32 phi_v0_4;
    void *phi_at;
    void *phi_v1_3;

    temp_a3 = arg0;
    phi_v0 = &D_800D6E68;
    phi_v1 = 0;
    phi_a1 = -1;
loop_1:
    if (temp_a3 == *phi_v0) {
        phi_a1 = phi_v1;
    }
    temp_v1 = phi_v1 + 1;
    phi_v0 = phi_v0 + 4;
    phi_v1 = temp_v1;
    if (temp_v1 < 3) {
        goto loop_1;
    }
    if (phi_a1 != -1) {
        phi_v1_2 = 2;
        phi_v0_2 = 2;
loop_6:
        if (phi_a1 != phi_v1_2) {
            *(&D_800D6E68 + (phi_v0_2 * 4)) = (s32) *(&D_800D6E68 + (phi_v1_2 * 4));
            phi_v0_2 = phi_v0_2 - 1;
        }
        temp_v1_2 = phi_v1_2 - 1;
        phi_v1_2 = temp_v1_2;
        if (temp_v1_2 >= 0) {
            goto loop_6;
        }
        phi_a3 = temp_a3;
        phi_a2 = &D_800D6E68;
    } else {
        phi_a3 = temp_a3;
        phi_a2 = (void *)0x800D6E68;
        if ((void *)0x800D6E68->unk8 != 0) {
            arg0 = temp_a3;
            func_800A8D64_ovl1((void *)0x800D6E68->unk8, 3, (void *)0x800D6E68, temp_a3);
            phi_a3 = arg0;
            phi_a2 = &D_800D6E68;
        }
        phi_v0_3 = &D_800D6E6C;
loop_13:
        temp_v0 = phi_v0_3 - 4;
        temp_v0->unk8 = (s32) *phi_v0_3;
        phi_v0_3 = temp_v0;
        if ((u32) temp_v0 >= (u32) &D_800D6E68) {
            goto loop_13;
        }
    }
    *phi_a2 = phi_a3;
    temp_t5 = ((phi_a3 >> 0x10) * 4) + 0x800D0000;
    temp_t7 = (phi_a3 & 0xFFFF) * 4;
    ((*D_8004A7C4 * 4) + 0x800E0000)->unk2D0 = phi_a3;
    temp_a2 = temp_t5->unkC4 + temp_t7;
    if (*temp_a2 != 0) {
        phi_v0_4 = *temp_a2;
        phi_at = (*D_8004A7C4 * 4) + 0x800E0000;
        phi_v1_3 = D_8004A7C4;
    } else {
        sp18 = temp_a2;
        temp_v0_2 = func_800A9250_ovl1(phi_a3, 3, temp_a2, phi_a3);
        *temp_a2 = temp_v0_2;
        phi_v0_4 = temp_v0_2;
        phi_at = (*D_8004A7C4 * 4) + 0x800E0000;
        phi_v1_3 = D_8004A7C4;
    }
    phi_at->unk-B30 = phi_v0_4;
    func_800A9D64_ovl1(*phi_v1_3, temp_t5->unkC4 + temp_t7);
    func_800A99E4_ovl1(*D_8004A7C4);
    func_800A9A2C_ovl1(*D_8004A7C4);
    func_800A9648_ovl1(((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A8EC0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A9088(u32 arg0) {
    void *sp20;
    void *sp1C;
    s32 temp_t7;
    s32 temp_v1;
    s32 temp_v1_2;
    u32 temp_a3;
    void *temp_a2;
    void *temp_t5;
    void *temp_v0;
    void *temp_v0_2;
    void *phi_v0;
    s32 phi_v1;
    s32 phi_a1;
    s32 phi_v1_2;
    s32 phi_v0_2;
    void *phi_v0_3;
    u32 phi_a3;
    void *phi_a2;
    void *phi_v1_3;

    temp_a3 = arg0;
    phi_v0 = &D_800D6E78;
    phi_v1 = 0;
    phi_a1 = -1;
loop_1:
    if (temp_a3 == *phi_v0) {
        phi_a1 = phi_v1;
    }
    temp_v1 = phi_v1 + 1;
    phi_v0 = phi_v0 + 4;
    phi_v1 = temp_v1;
    if (temp_v1 < 3) {
        goto loop_1;
    }
    if (phi_a1 != -1) {
        phi_v1_2 = 2;
        phi_v0_2 = 2;
loop_6:
        if (phi_a1 != phi_v1_2) {
            *(&D_800D6E78 + (phi_v0_2 * 4)) = (s32) *(&D_800D6E78 + (phi_v1_2 * 4));
            phi_v0_2 = phi_v0_2 - 1;
        }
        temp_v1_2 = phi_v1_2 - 1;
        phi_v1_2 = temp_v1_2;
        if (temp_v1_2 >= 0) {
            goto loop_6;
        }
        phi_a3 = temp_a3;
        phi_a2 = &D_800D6E78;
    } else {
        phi_a3 = temp_a3;
        phi_a2 = (void *)0x800D6E78;
        if ((void *)0x800D6E78->unk8 != 0) {
            arg0 = temp_a3;
            func_800A8D64_ovl1((void *)0x800D6E78->unk8, 3, (void *)0x800D6E78, temp_a3);
            phi_a3 = arg0;
            phi_a2 = &D_800D6E78;
        }
        phi_v0_3 = &D_800D6E7C;
loop_13:
        temp_v0 = phi_v0_3 - 4;
        temp_v0->unk8 = (s32) *phi_v0_3;
        phi_v0_3 = temp_v0;
        if ((u32) temp_v0 >= (u32) &D_800D6E78) {
            goto loop_13;
        }
    }
    *phi_a2 = phi_a3;
    temp_t5 = ((phi_a3 >> 0x10) * 4) + 0x800D0000;
    temp_t7 = (phi_a3 & 0xFFFF) * 4;
    ((*D_8004A7C4 * 4) + 0x800E0000)->unk2D0 = phi_a3;
    temp_a2 = temp_t5->unkC4 + temp_t7;
    if (*temp_a2 != 0) {
        sp1C = *temp_a2;
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 = (void *) *temp_a2;
        phi_v1_3 = D_8004A7C4;
    } else {
        sp20 = temp_a2;
        temp_v0_2 = func_800A9250_ovl1(phi_a3, 3, temp_a2, phi_a3);
        *temp_a2 = temp_v0_2;
        sp1C = temp_v0_2;
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 = temp_v0_2;
        phi_v1_3 = D_8004A7C4;
    }
    func_800A9D64_ovl1(*phi_v1_3, temp_t5->unkC4 + temp_t7);
    func_800AF9B8_ovl1(sp1C->unkA, 0x10);
    func_800A99E4_ovl1(*D_8004A7C4);
    func_800A9A2C_ovl1(*D_8004A7C4);
    func_800A9648_ovl1(sp1C);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9088.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_800A9250:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9250.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A94F4(s32 arg0) {
    s32 sp2C;
    void *sp24;
    void *sp1C;
    s32 sp18;
    s32 temp_a0;
    s32 temp_a0_2;
    s32 temp_a0_3;
    s32 temp_a1;
    s32 temp_v1_2;
    void *temp_t1;
    void *temp_t3;
    void *temp_t5;
    void *temp_t7;
    void *temp_t9;
    void *temp_v0;
    void *temp_v0_2;
    void *temp_v0_3;
    void *temp_v0_4;
    void *temp_v0_5;
    void *temp_v1;
    void *phi_v0;
    s32 phi_a0;
    void *phi_v0_2;
    s32 phi_a0_2;

    temp_v0 = ((arg0 >> 0x10) * 4) + 0x800D0000;
    temp_a1 = arg0 & 0xFFFF;
    temp_v1 = temp_v0->unk184->unk10 + (temp_a1 * 4);
    sp18 = temp_v0->unk184->unk14;
    sp1C = temp_v1;
    temp_a0 = (temp_v1->unk4 - temp_v1->unk0) | 2;
    sp2C = temp_a0;
    temp_v0_2 = func_800A8358_ovl1(temp_a0, temp_a1);
    sp24 = temp_v0_2;
    func_80002E48_ovl1(temp_v1->unk0 + sp18, temp_v0_2, sp2C & 0xFFFFFC);
    temp_v0_3 = sp24 + 0xC;
    sp24->unk0 = (void *) (sp24->unk0 + sp24);
    if (sp24->unk8 != 0) {
        temp_v1_2 = -(s32) (sp24->unk8 & 3);
        phi_v0 = temp_v0_3;
        phi_a0 = sp24->unk8;
        phi_v0_2 = temp_v0_3;
        phi_a0_2 = sp24->unk8;
        if (((temp_v1_2 == 0) || (temp_a0_3 = phi_a0 - 1, temp_v0_5 = phi_v0 + 4, temp_t7 = *phi_v0 + sp24, temp_v0_5->unk-4 = temp_t7, *temp_t7 = (void *) (*temp_t7 + sp24), phi_v0 = temp_v0_5, phi_a0 = temp_a0_3, ((temp_v1_2 + sp24->unk8) != temp_a0_3))) || (phi_v0_2 = temp_v0_5, phi_a0_2 = temp_a0_3, (temp_a0_3 != 0))) {
loop_4:
            temp_a0_2 = phi_a0_2 - 4;
            temp_v0_4 = phi_v0_2 + 0x10;
            temp_t1 = *phi_v0_2 + sp24;
            temp_v0_4->unk-10 = temp_t1;
            *temp_t1 = (void *) (*temp_t1 + sp24);
            temp_t5 = temp_v0_4->unk-C + sp24;
            temp_v0_4->unk-C = temp_t5;
            *temp_t5 = (void *) (*temp_t5 + sp24);
            temp_t9 = temp_v0_4->unk-8 + sp24;
            temp_v0_4->unk-8 = temp_t9;
            *temp_t9 = (void *) (*temp_t9 + sp24);
            temp_t3 = temp_v0_4->unk-4 + sp24;
            temp_v0_4->unk-4 = temp_t3;
            *temp_t3 = (void *) (*temp_t3 + sp24);
            phi_v0_2 = temp_v0_4;
            phi_a0_2 = temp_a0_2;
            if (temp_a0_2 != 0) {
                goto loop_4;
            }
        } else {

        }
    }
    return sp24;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A94F4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
Failed to decompile function func_800A9648:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl".
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9648.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A9760(u32 arg0) {
    void *sp1C;
    s32 temp_v0;
    void *temp_a2;
    void *phi_v1;

    ((*D_8004A7C4 * 4) + 0x800E0000)->unk2D0 = arg0;
    temp_a2 = (((arg0 >> 0x10) * 4) + 0x800D0000)->unkC4 + ((arg0 & 0xFFFF) * 4);
    if (*temp_a2 != 0) {
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 = (s32) *temp_a2;
        func_800A8564_ovl1(*temp_a2, 1, temp_a2);
        phi_v1 = D_8004A7C4;
    } else {
        sp1C = temp_a2;
        temp_v0 = func_800A9250_ovl1(3, temp_a2);
        *temp_a2 = temp_v0;
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 = temp_v0;
        phi_v1 = D_8004A7C4;
    }
    func_800A9D64_ovl1(*phi_v1);
    func_800A99E4_ovl1(*D_8004A7C4);
    func_800A9A2C_ovl1(*D_8004A7C4);
    func_800A9648_ovl1(((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9760.s")
#endif



#ifdef MIPS_TO_C
void func_800A9864(u32 addr, s32 arg1, s32 arg2) {
    struct UnkWhat *sp1C;
    struct UnkWhat *sp18;
    f32 temp_f16;
    f32 temp_f6;
    struct UnkWhat **temp_a3;
    struct UnkWhat *temp_v0;
    f32 phi_f6;
    f32 phi_f16;

    D_800E02D0[*D_8004A7C4] = addr;
    temp_a3 = &(D_800D00C4[addr >> 0x10][addr & 0xFFFF]);
    if (*temp_a3) {
        sp1C = *temp_a3;
        D_800DF4D0[*D_8004A7C4] = *temp_a3;
        func_800A8564_ovl1(*temp_a3, 1, temp_a3);
    } else {
        sp18 = temp_a3;
        temp_v0 = func_800A9250_ovl1(3, temp_a3);
        *temp_a3 = temp_v0;
        sp1C = temp_v0;
        D_800DF4D0[*D_8004A7C4] = temp_v0;
    }
    func_800A9D64_ovl1(*D_8004A7C4);

    temp_f6 = (f32) arg1;
    phi_f6 = temp_f6;
    if (arg1 < 0) {
        phi_f6 = temp_f6 + 4294967296.0f;
    }
    if (D_800D5DD8 == phi_f6) {
        arg1 = sp1C->unk8;
    }

    temp_f16 = (f32) arg2;
    phi_f16 = temp_f16;
    if (arg2 < 0) {
        phi_f16 = temp_f16 + 4294967296.0f;
    }
    if (D_800D5DD8 == phi_f16) {
        arg2 = 0x10;
    }
    func_800AF9B8_ovl1((u16) arg1, (u8) arg2);
    func_800A99E4_ovl1(*D_8004A7C4);
    func_800A9A2C_ovl1(*D_8004A7C4);
    func_800A9648_ovl1(sp1C);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9864.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A99E4(s32 arg0) {
    void *sp1C;
    s32 temp_t6;
    void *temp_v0;

    temp_t6 = arg0 * 4;
    temp_v0 = temp_t6 + &D_800DFBD0;
    if (*temp_v0 != -1) {
        sp1C = temp_v0;
        func_800A8578_ovl1(*temp_v0 | 1);
    }
    *(temp_t6 + &D_800DFBD0) = -1;
    return temp_t6 + &D_800DFBD0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A99E4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800A9A2C(s32 arg0) {
    void *temp_ret;
    void *temp_v0;

    temp_v0 = (arg0 * 4) + 0x800E0000;
    if (temp_v0->unk-B30->unk1C == 0) {
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-430 = -1;
        return temp_v0->unk-B30;
    }
    temp_ret = func_800A8358_ovl1((temp_v0->unk-B30->unk1C * 4) | 1);
    ((*D_8004A7C4 * 4) + 0x800E0000)->unk-430 = temp_ret;
    return temp_ret;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9A2C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A9AA8(u32 arg0, s32 arg1) {
    s32 sp24;
    s32 sp20;
    void *sp1C;
    s32 sp18;
    s32 temp_a2;
    s32 temp_a3;
    s32 temp_v0_2;
    void *temp_v0;
    void *temp_v1;

    temp_v0 = ((arg0 >> 0x10) * 4) + 0x800D0000;
    temp_a2 = arg0 & 0xFFFF;
    temp_v1 = temp_v0->unk184->unk18 + (temp_a2 * 4);
    sp18 = temp_v0->unk184->unk1C;
    temp_a3 = ((temp_v1->unk4 - temp_v1->unk0) + 3) & 0xFFFFFC;
    sp24 = temp_a3;
    sp1C = temp_v1;
    temp_v0_2 = func_800A8358_ovl1(temp_a3 | arg1, temp_a2, temp_a3);
    sp20 = temp_v0_2;
    func_80002E48_ovl1(temp_v1->unk0 + sp18, temp_v0_2, temp_a3 & 0xFFFFFC, temp_a3);
    return temp_v0_2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9AA8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A9B48(s32 arg0) {
    s32 sp24;
    void *sp1C;
    void *temp_a0;
    void *temp_a0_2;
    void *temp_ret;
    void *temp_v0;
    void *phi_a0;
    void *phi_v1;
    void *phi_a0_2;
    void *phi_v1_2;
    s32 phi_a2;

    temp_ret = func_800A94F4_ovl1();
    temp_v0 = temp_ret;
    if (temp_v0->unk4 != 0) {
        temp_a0 = (*D_8004A7C4 * 4) + &D_800DF850;
        phi_a0 = temp_a0;
        phi_v1 = D_8004A7C4;
        if (*temp_a0 != -1) {
            sp1C = temp_v0;
            sp24 = temp_v0->unk4;
            func_800A8578_ovl1(*temp_a0 | 2, temp_v0, temp_v0->unk4);
            phi_a0 = (*D_8004A7C4 * 4) + &D_800DF850;
            phi_v1 = D_8004A7C4;
        }
        *phi_a0 = temp_ret;
        ((*phi_v1 * 4) + 0x800E0000)->unk110 = arg0;
    } else {
        temp_a0_2 = (*D_8004A7C4 * 4) + &D_800DF690;
        phi_a0_2 = temp_a0_2;
        phi_v1_2 = D_8004A7C4;
        if (*temp_a0_2 != -1) {
            sp1C = temp_v0;
            sp24 = temp_v0->unk4;
            func_800A8578_ovl1(*temp_a0_2 | 2, temp_v0, temp_v0->unk4);
            phi_a0_2 = (*D_8004A7C4 * 4) + &D_800DF690;
            phi_v1_2 = D_8004A7C4;
        }
        *phi_a0_2 = temp_ret;
        ((*phi_v1_2 * 4) + 0x800E0000)->unk-B0 = arg0;
    }
    return phi_a2;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9B48.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A9C78(s32 arg0, s32 arg1) {
    s32 sp2C;
    void *sp24;
    s32 sp20;
    void *sp1C;
    s32 temp_a3;
    s32 temp_v1;
    s32 temp_v1_2;
    void *temp_a1;
    void *temp_a1_2;
    void *temp_a2;
    void *temp_v0;
    s32 phi_a3;

    temp_v0 = func_800A94F4_ovl1();
    temp_a3 = temp_v0->unk4;
    temp_a2 = temp_v0;
    temp_v1 = arg1 * 4;
    if (temp_a3 != 0) {
        temp_a1 = temp_v1 + &D_800DF850;
        if (*temp_a1 != -1) {
            sp20 = temp_v1;
            sp1C = temp_a1;
            sp24 = temp_a2;
            sp2C = temp_a3;
            func_800A8578_ovl1(*temp_a1 | 2, temp_a1, temp_a2, temp_a3);
        }
        *(temp_v1 + &D_800DF850) = temp_a2;
        ((arg1 * 4) + 0x800E0000)->unk110 = arg0;
    } else {
        temp_v1_2 = arg1 * 4;
        temp_a1_2 = temp_v1_2 + &D_800DF690;
        if (*temp_a1_2 != -1) {
            sp20 = temp_v1_2;
            sp1C = temp_a1_2;
            sp24 = temp_a2;
            sp2C = temp_a3;
            func_800A8578_ovl1(*temp_a1_2 | 2, temp_a1_2, temp_a2, temp_a3);
        }
        *(temp_v1_2 + &D_800DF690) = temp_a2;
        ((arg1 * 4) + 0x800E0000)->unk-B0 = arg0;
    }
    return phi_a3;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9C78.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A9D64(s32 arg0) {
    s32 sp1C;
    void *sp18;
    s32 temp_ret;
    s32 temp_v0;
    void *temp_v1;
    void *temp_v1_2;
    s32 phi_return;

    temp_v0 = arg0 * 4;
    temp_v1 = temp_v0 + &D_800DF690;
    if (-1 != *temp_v1) {
        sp1C = temp_v0;
        sp18 = temp_v1;
        func_800A8578_ovl1(*temp_v1 | 2, *temp_v1, -1);
        *temp_v1 = -1;
    }
    temp_v1_2 = (arg0 * 4) + &D_800DF850;
    if (-1 != *temp_v1_2) {
        sp18 = temp_v1_2;
        temp_ret = func_800A8578_ovl1(*temp_v1_2 | 2, *temp_v1_2, -1);
        *temp_v1_2 = -1;
        phi_return = temp_ret;
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9D64.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A9DE4(s32 arg0, f32 arg1) {
    f32 temp_f12;
    s32 temp_v0;
    s32 phi_return;

    temp_f12 = arg1;
    temp_v0 = *D_8004A7C4 * 4;
    phi_return = temp_v0;
    if (arg0 != (temp_v0 + 0x800E0000)->unk-B0) {
        phi_return = temp_v0;
        if (arg0 != (temp_v0 + 0x800E0000)->unk110) {
            arg1 = temp_f12;
            if (func_800A9B48_ovl1(temp_f12) != 0) {
                return func_800AEEB4_ovl1(arg1, *((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0, arg1);
            }
            phi_return = func_800AEE20_ovl1(arg1, *((*D_8004A7C4 * 4) + 0x800E0000)->unk-970, arg1);
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9DE4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A9EA4(void) {
    func_800A9DE4_ovl1(0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9EA4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800A9EC4(s32 arg0, f32 arg1, u16 arg2) {
    f32 temp_f12;
    s32 temp_v0;
    s32 phi_return;

    temp_f12 = arg1;
    temp_v0 = *D_8004A7C4 * 4;
    phi_return = temp_v0;
    if (arg0 != (temp_v0 + 0x800E0000)->unk-B0) {
        phi_return = temp_v0;
        if (arg0 != (temp_v0 + 0x800E0000)->unk110) {
            arg1 = temp_f12;
            if (func_800A9B48_ovl1(temp_f12) != 0) {
                func_800AEEB4_ovl1(arg1, *((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0, arg1);
                return func_800AF09C_ovl1(arg2);
            }
            func_800AEE20_ovl1(arg1, *((*D_8004A7C4 * 4) + 0x800E0000)->unk-970, arg1);
            phi_return = func_800AEFFC_ovl1(arg2);
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9EC4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800A9F98(s32 arg0, f32 arg1) {
    if (func_800A9B48_ovl1() != 0) {
        func_800AEEB4(*((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0, arg1);
        return;
    }
    func_800AEE20_ovl1(*((*D_8004A7C4 * 4) + 0x800E0000)->unk-970, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800A9F98.s")
#endif


extern void func_800A9F98(s32 arg0, f32 arg1);

void func_800AA018(s32 arg0) {
    func_800A9F98(arg0, 0.0f);
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA038(f32 arg1, s32 arg2) {
    s32 temp_v0;
    s32 temp_v0_2;

    if (func_800A9C78_ovl1(arg2) != 0) {
        temp_v0 = arg2 * 4;
        func_800AEFA4_ovl1(*(temp_v0 + 0x800E0000)->unk-7B0, arg1, (temp_v0 + 0x800E0000)->unk-1CB0, arg2);
        return;
    }
    temp_v0_2 = arg2 * 4;
    func_800AEF0C_ovl1(*(temp_v0_2 + 0x800E0000)->unk-970, arg1, (temp_v0_2 + 0x800E0000)->unk-1CB0, arg2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA038.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA0C4(f32 arg1) {
    if (func_800A9B48_ovl1() != 0) {
        func_800AEEB4_ovl1(*((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0, arg1);
        func_800AF09C_ovl1(1);
        return;
    }
    func_800AEE20_ovl1(*((*D_8004A7C4 * 4) + 0x800E0000)->unk-970, arg1);
    func_800AF27C_ovl1();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA0C4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA154(s32 arg0) {
    func_800AA0C4(arg0, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA154.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800AA174(void) {
    D_8004A7C4->unk3C->unk1C = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk25D0;
    D_8004A7C4->unk3C->unk20 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk2790;
    D_8004A7C4->unk3C->unk24 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk2950;
    D_8004A7C4->unk3C->unk30 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk4010;
    D_8004A7C4->unk3C->unk34 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk41D0;
    D_8004A7C4->unk3C->unk38 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk4390;
    D_8004A7C4->unk3C->unk40 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk4550;
    D_8004A7C4->unk3C->unk44 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk4710;
    D_8004A7C4->unk3C->unk48 = (f32) ((D_8004A7C4->unk0 * 4) + 0x800E0000)->unk48D0;
    return D_8004A7C4;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA174.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA2A0(void) {
    func_800A9760_ovl1();
    func_800AA174_ovl1();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA2A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA2C8(void) {
    func_800A9864_ovl1();
    func_800AA174_ovl1();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA2C8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA2F0(f32 arg1) {
    if (func_800A9B48_ovl1() != 0) {
        func_800B2288_ovl1(((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0, arg1);
        return;
    }
    func_800B21FC_ovl1(((*D_8004A7C4 * 4) + 0x800E0000)->unk-970, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA2F0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_800AA368(void *arg0) {
    s32 temp_a1;
    void *temp_t6;

    if (D_800D5DDC == arg0->unk74) {
        temp_a1 = *D_8004A7C4 * 4;
        temp_t6 = &D_800DFA10 + temp_a1;
        (temp_a1 + 0x800E0000)->unk-B30 = (void *) *temp_t6;
        *(&D_800DFA10 + (*D_8004A7C4 * 4)) = (s32) (*temp_t6)->unk0;
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-270 = (s32) (*temp_t6)->unk4;
        return 1;
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA368.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800AA3F0(void *arg0) {
    s32 temp_a0;
    void *temp_t6;

loop_1:
    if (D_800D5DE0 != arg0->unk74) {
        func_8000B6BC_ovl1(1);
        goto loop_1;
    }
    temp_a0 = *D_8004A7C4 * 4;
    temp_t6 = &D_800DFA10 + temp_a0;
    (temp_a0 + 0x800E0000)->unk-B30 = (void *) *temp_t6;
    *(&D_800DFA10 + (*D_8004A7C4 * 4)) = (s32) (*temp_t6)->unk0;
    ((*D_8004A7C4 * 4) + 0x800E0000)->unk-270 = (s32) (*temp_t6)->unk4;
    return *temp_t6;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA3F0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA49C(s32 arg0, s32 arg1, s32 arg2, u32 arg3, f32 arg4) {
    void *sp24;
    s32 temp_v0;
    s32 temp_v1_2;
    void *temp_v1;

    ((*D_8004A7C4 * 4) + 0x800E0000)->unk2D0 = arg3;
    ((*D_8004A7C4 * 4) + 0x800E0000)->unk-270 = arg0;
    temp_v1 = (((arg3 >> 0x10) * 4) + 0x800D0000)->unkC4 + ((arg3 & 0xFFFF) * 4);
    if (*temp_v1 != 0) {
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-5F0 = (s32) *temp_v1;
        func_800A8564_ovl1(*temp_v1, 1, *temp_v1);
    } else {
        sp24 = temp_v1;
        temp_v0 = func_800A9250_ovl1(arg3, 3, *temp_v1);
        *temp_v1 = temp_v0;
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-5F0 = temp_v0;
    }
    func_800A9B48_ovl1(arg1);
    temp_v1_2 = *D_8004A7C4 * 4;
    func_800B1FD0_ovl1(arg0, *(temp_v1_2 + 0x800E0000)->unk-970, arg2, *(temp_v1_2 + 0x800E0000)->unk-5F0, arg4);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA49C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA5C4(s32 arg0, ? arg1, f32 arg2) {
    func_800AA49C_ovl1(arg2, D_8004A7C4->unk3C->unk10, arg0, 0, arg1, arg2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA5C4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA608(void *arg0, s32 arg1, ? arg2, u32 arg3, f32 arg4) {
    void *sp34;
    void *sp30;
    s32 temp_v1;
    void *temp_a2;
    void *temp_v0;
    void *phi_a3;
    void *phi_v1;

    ((*D_8004A7C4 * 4) + 0x800E0000)->unk2D0 = arg3;
    temp_a2 = (((arg3 >> 0x10) * 4) + 0x800D0000)->unkC4 + ((arg3 & 0xFFFF) * 4);
    if (*temp_a2 != 0) {
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 = (void *) *temp_a2;
        sp34 = *temp_a2;
        func_800A8564_ovl1(*temp_a2, 1, temp_a2);
        phi_a3 = sp34;
        phi_v1 = D_8004A7C4;
    } else {
        sp30 = temp_a2;
        temp_v0 = func_800A9250_ovl1(arg3, 3, temp_a2);
        *temp_a2 = temp_v0;
        ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 = temp_v0;
        phi_a3 = temp_v0;
        phi_v1 = D_8004A7C4;
    }
    ((*phi_v1 * 4) + 0x800E0000)->unk-5F0 = (s32) phi_a3->unk0;
    ((*phi_v1 * 4) + 0x800E0000)->unk-270 = (s32) phi_a3->unk4;
    func_800A9B48_ovl1(arg1, phi_a3);
    temp_v1 = *D_8004A7C4 * 4;
    func_800B1FD0_ovl1(arg0, *(temp_v1 + 0x800E0000)->unk-970, arg2, (temp_v1 + 0x800E0000)->unk-5F0, arg4);
loop_4:
    if (D_800D5DE4 != arg0->unk74) {
        func_8000B6BC_ovl1(1);
        goto loop_4;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA608.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA78C(s32 arg0, ? arg1, f32 arg2) {
    func_800AA608_ovl1(arg2, D_8004A7C4->unk3C->unk10, arg0, 0, arg1, arg2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA78C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA7D0(f32 arg1, u16 arg2) {
    if (func_800A9B48_ovl1() != 0) {
        func_800AEEB4_ovl1(*((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0, arg1);
        func_800AF09C_ovl1(arg2);
        return;
    }
    func_800AEE20_ovl1(*((*D_8004A7C4 * 4) + 0x800E0000)->unk-970, arg1);
    func_800AEFFC_ovl1(arg2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA7D0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA864(? arg1) {
    func_800AA7D0_ovl1(0, arg1);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA864.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_800AA888(u32 arg0) {
    if (((*D_8004A7C4 * 4) + 0x800E0000)->unk-B30 == *((((arg0 >> 0x10) * 4) + 0x800D0000)->unkC4 + ((arg0 & 0xFFFF) * 4))) {
        return 1;
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA888.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_800AA8E4(s32 arg0, u32 arg1) {
    if (((arg0 * 4) + 0x800E0000)->unk-B30 == *((((arg1 >> 0x10) * 4) + 0x800D0000)->unkC4 + ((arg1 & 0xFFFF) * 4))) {
        return 1;
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA8E4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
? func_800AA934(s32 arg0) {
    if (arg0 == ((*D_8004A7C4 * 4) + 0x800E0000)->unk-B0) {
        return 1;
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA934.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AA96C(void *arg0, u32 arg1, ? arg2, ? arg3, f32 arg4) {
    s32 temp_s0_2;
    s32 temp_v0;
    s32 temp_v0_2;
    s32 temp_v1;
    void *temp_s0;
    s32 phi_s0;
    void *phi_s1;

    ((*D_8004A7C4 * 4) + 0x800E0000)->unk2D0 = arg1;
    temp_s0 = (((arg1 >> 0x10) * 4) + 0x800D0000)->unkC4 + ((arg1 & 0xFFFF) * 4);
    if (*temp_s0 != 0) {
        *(&D_800DFA10 + (*D_8004A7C4 * 4)) = (s32) *temp_s0;
        func_800A8564_ovl1(*temp_s0, 1, arg1);
    } else {
        temp_v0 = func_800A9250_ovl1(arg1, 3, arg1);
        *temp_s0 = temp_v0;
        *(&D_800DFA10 + (*D_8004A7C4 * 4)) = temp_v0;
    }
    func_800A9B48_ovl1(arg2);
    temp_v1 = *D_8004A7C4 * 4;
    if (*arg0 != -1) {
        phi_s0 = *arg0;
        phi_s1 = arg0;
loop_5:
        temp_v0_2 = phi_s0 * 4;
        func_8000EC98_ovl1(*(*(&D_800DFBD0 + (*D_8004A7C4 * 4)) + temp_v0_2), temp_v0_2 + *(temp_v1 + 0x800E0000)->unk-970, arg3, (phi_s0 * 0x2C) + **(&D_800DFA10 + temp_v1), 0, arg4, 0.0f, 0.0f, 0.0f);
        temp_s0_2 = phi_s1->unk4;
        phi_s0 = temp_s0_2;
        phi_s1 = phi_s1 + 4;
        if (temp_s0_2 != -1) {
            goto loop_5;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AA96C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AAB3C(void *arg0, ? arg3, f32 arg4) {
    func_800AA96C_ovl1(arg3, arg3, arg4);
loop_1:
    if (D_800D5DE8 != (*(((*D_8004A7C4 * 4) + 0x800E0000)->unk-430 + (*arg0 * 4)))->unk74) {
        func_8000B6BC_ovl1(1);
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AAB3C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800AABD4(void *arg0, f32 arg1, f32 arg2) {
    s32 temp_v1;
    void *temp_a0;
    void *temp_a1;
    void *temp_t1;
    void *temp_t3;
    s32 phi_v1;
    void *phi_a1;
    s32 phi_v1_2;
    void *phi_a0;
    void *phi_a1_2;
    void *phi_return;
    void *phi_return_2;

    phi_return_2 = (bitwise void *) D_800D5DEC;
    if (arg1 != D_800D5DEC) {
        phi_return_2 = (bitwise void *) D_800D5DEC;
        if (*arg0 != -1) {
            phi_v1 = *arg0;
            phi_a1 = arg0;
loop_3:
            temp_a1 = phi_a1 + 4;
            temp_t3 = *(&D_800DFBD0 + (*D_8004A7C4 * 4)) + (phi_v1 * 4);
            (*temp_t3)->unk78 = arg1;
            phi_v1 = *temp_a1;
            phi_a1 = temp_a1;
            phi_return_2 = *temp_t3;
            if (*temp_a1 != -1) {
                goto loop_3;
            }
        }
    }
    phi_return = phi_return_2;
    if (arg2 != D_800D5DEC) {
        phi_v1_2 = *arg0;
        phi_a1_2 = arg0;
        phi_return = phi_return_2;
        if (*arg0 != -1) {
loop_6:
            temp_t1 = *(&D_800DFBD0 + (*D_8004A7C4 * 4)) + (phi_v1_2 * 4);
            phi_a0 = (*temp_t1)->unk80;
            if ((*temp_t1)->unk80 != 0) {
loop_7:
                phi_a0->unk9C = arg2;
                temp_a0 = phi_a0->unk0;
                phi_a0 = temp_a0;
                if (temp_a0 != 0) {
                    goto loop_7;
                }
            }
            temp_v1 = phi_a1_2->unk4;
            phi_v1_2 = temp_v1;
            phi_a1_2 = phi_a1_2 + 4;
            phi_return = *temp_t1;
            if (temp_v1 != -1) {
                goto loop_6;
            }
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AABD4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800AACC8(void *arg0, ? arg1, s32 arg2, f32 arg3) {
    s32 temp_a1;
    s32 temp_v0_2;
    s32 temp_v0_3;
    s32 temp_v1_2;
    void *temp_s0;
    void *temp_s2;
    void *temp_t9;
    void *temp_v0;
    void *temp_v0_4;
    void *temp_v1;
    void *phi_s2;
    void *phi_s4;
    s32 phi_v0;
    s8 phi_s5;
    void *phi_s0;
    void *phi_s1;
    void *phi_s0_2;
    void *phi_s3;
    void *phi_return;
    s32 phi_v1;
    void *phi_return_2;

    phi_s2 = D_8004A7C4->unk3C;
    if (D_8004A7C4->unk3C != 0) {
loop_1:
        phi_s2->unk55 = (u8)0;
        temp_v0 = func_8000BE90_ovl1(phi_s2);
        phi_s2 = temp_v0;
        if (temp_v0 != 0) {
            goto loop_1;
        }
    }
    phi_s4 = NULL;
    if (arg2 != -1) {
        func_800A9B48_ovl1(arg2);
        phi_s4 = *((*D_8004A7C4 * 4) + 0x800E0000)->unk-7B0;
    }
    phi_return = func_800A9B48_ovl1(arg1);
    if (*arg0 != -1) {
        phi_s5 = (u8)1;
        phi_s3 = arg0;
        phi_v1 = *arg0;
loop_6:
        temp_v0_2 = phi_v1 * 4;
        phi_v0 = temp_v0_2;
        phi_s0 = temp_v0_2 + phi_s4;
        phi_return = (void *) temp_v0_2;
        if (phi_s4 == 0) {
            temp_v0_3 = phi_v1 * 4;
            phi_v0 = temp_v0_3;
            phi_s0 = phi_s4;
            phi_return = (void *) temp_v0_3;
        }
        temp_t9 = phi_v0 + *((*D_8004A7C4 * 4) + 0x800E0000)->unk-970;
        temp_s2 = *(*(&D_800DFBD0 + (*D_8004A7C4 * 4)) + phi_v0);
        if (*temp_t9 != 0) {
            func_8000C10C_ovl1(temp_s2, *temp_t9, arg3);
            temp_s2->unk55 = phi_s5;
            temp_s2->unk4->unk40 = arg3;
            *(&D_800DF310 + (*D_8004A7C4 * 4)) = 0;
            temp_v1 = (*D_8004A7C4 * 4) + &D_800DD8D0;
            *temp_v1 = (s32) (*temp_v1 & 0x3FFFFFFF);
            phi_s5 = (u8)0;
            phi_return = D_8004A7C4;
        } else {
            temp_s2->unk74 = (f32) D_800D5DF0;
            temp_s2->unk55 = (u8)0;
        }
        if (phi_s0 != 0) {
            temp_v0_4 = *phi_s0;
            phi_return = temp_v0_4;
            if (temp_v0_4 != 0) {
                phi_s1 = temp_v0_4;
                phi_s0_2 = temp_s2->unk80;
                phi_return = temp_v0_4;
                phi_return_2 = temp_v0_4;
                if (temp_s2->unk80 != 0) {
loop_14:
                    temp_a1 = *phi_s1;
                    if (temp_a1 != 0) {
                        phi_return_2 = func_8000C144_ovl1(phi_s0_2, temp_a1, arg3);
                    }
                    temp_s0 = *phi_s0_2;
                    phi_s1 = phi_s1 + 4;
                    phi_s0_2 = temp_s0;
                    phi_return = phi_return_2;
                    if (temp_s0 != 0) {
                        goto loop_14;
                    }
                }
            }
        }
        temp_v1_2 = phi_s3->unk4;
        phi_s3 = phi_s3 + 4;
        phi_v1 = temp_v1_2;
        if (temp_v1_2 != -1) {
            goto loop_6;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AACC8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AAF04(? arg3) {
    func_800AACC8_ovl1(arg3, arg3);
    func_800AF27C_ovl1();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AAF04.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AAF34(s32 arg0, s32 arg1, s32 arg2) {
    s32 sp20;
    void *sp1C;
    s32 temp_a3;
    s32 temp_a3_2;
    void *temp_v0;
    void *temp_v1;

    temp_a3 = (s32) (arg0 - 0xA) >> 1;
    temp_a3 = temp_a3 * 4;
    temp_v1 = temp_a3 + &D_800D7A00;
    if (*temp_v1 != 0) {
        sp1C = temp_v1;
        sp20 = temp_a3;
        func_800A8578_ovl1(*temp_v1 | 2, temp_a3);
        *temp_v1 = 0;
    }
    sp1C = temp_a3 + &D_800D7A00;
    sp20 = temp_a3 * 4;
    temp_v0 = func_800A94F4_ovl1(arg1, temp_a3 * 4);
    temp_a3_2 = temp_a3 * 4;
    *(temp_a3 + &D_800D7A00) = temp_v0;
    func_8000FE2C_ovl1((temp_a3_2 + 0x800D0000)->unk79D8, *temp_v0, arg2, temp_a3_2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AAF34.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AAFC4(s32 arg0, ? arg2) {
    func_800AAF34_ovl1(arg2, arg2);
loop_1:
    if (D_800D5DF4 != ((((s32) (arg0 - 0xA) >> 1) * 4) + 0x800D0000)->unk79D8->unk74) {
        func_8000B6BC_ovl1(1);
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AAFC4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB040(s32 arg0) {
loop_1:
    if (D_800D5DF8 != ((((s32) (arg0 - 0xA) >> 1) * 4) + 0x800D0000)->unk79D8->unk74) {
        func_8000B6BC_ovl1(1);
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB040.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800AB0A8(s32 arg0, f32 arg1) {
    void *temp_v0;

    temp_v0 = (((s32) (arg0 - 0xA) >> 1) * 4) + 0x800D0000;
    temp_v0->unk79D8->unk78 = arg1;
    return temp_v0->unk79D8;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB0A8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void *func_800AB0CC(s32 arg0) {
    void *temp_v0;

    temp_v0 = (((s32) (arg0 - 0xA) >> 1) * 4) + 0x800D0000;
    temp_v0->unk79D8->unk74 = (f32) D_800D5DFC;
    return temp_v0->unk79D8;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB0CC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
s32 func_800AB0F4(void *arg0) {
    return ((*arg0 * 4) + 0x800E0000)->unk-B30->unk8;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB0F4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB110(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB110.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB118(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB118.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB120(void *arg0) {
    void *temp_v1;

    temp_v1 = gDisplayListHeads;
    gDisplayListHeads = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) ((*arg0 * 4) + 0x800E0000)->unk-B30;
    func_800141D4_ovl1(&gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB120.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB174(void *arg0) {
    void *temp_a2;
    void *temp_v1;

    temp_v1 = gDisplayListHeads.unk0;
    gDisplayListHeads.unk0 = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    temp_a2 = gDisplayListHeads.unk4;
    gDisplayListHeads.unk4 = (void *) (temp_a2 + 8);
    temp_a2->unk0 = 0xDB060010;
    temp_a2->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    func_80014768_ovl1(temp_a2, &gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB174.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB1F0(void *arg0) {
    void *temp_v1;

    temp_v1 = gDisplayListHeads;
    gDisplayListHeads = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) ((*arg0 * 4) + 0x800E0000)->unk-B30;
    func_80014B4C_ovl1(&gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB1F0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB244(void *arg0) {
    void *temp_a2;
    void *temp_v1;

    temp_v1 = gDisplayListHeads.unk0;
    gDisplayListHeads.unk0 = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    temp_a2 = gDisplayListHeads.unk4;
    gDisplayListHeads.unk4 = (void *) (temp_a2 + 8);
    temp_a2->unk0 = 0xDB060010;
    temp_a2->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    func_80014FA4_ovl1(temp_a2, &gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB244.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB2C0(void *arg0) {
    void *temp_v1;

    temp_v1 = gDisplayListHeads;
    gDisplayListHeads = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) ((*arg0 * 4) + 0x800E0000)->unk-B30;
    func_800143A4_ovl1(&gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB2C0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB314(void *arg0) {
    void *temp_a2;
    void *temp_v1;

    temp_v1 = gDisplayListHeads.unk0;
    gDisplayListHeads.unk0 = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    temp_a2 = gDisplayListHeads.unk4;
    gDisplayListHeads.unk4 = (void *) (temp_a2 + 8);
    temp_a2->unk0 = 0xDB060010;
    temp_a2->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    func_80014AD4_ovl1(temp_a2, &gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB314.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB390(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB390.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB398(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB398.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB3A0(void *arg0) {
    void *temp_v1;

    temp_v1 = gDisplayListHeads;
    gDisplayListHeads = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) ((*arg0 * 4) + 0x800E0000)->unk-B30;
    func_8001585C_ovl1(&gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB3A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB3F4(void *arg0) {
    void *temp_a2;
    void *temp_v1;

    temp_v1 = gDisplayListHeads.unk0;
    gDisplayListHeads.unk0 = (void *) (temp_v1 + 8);
    temp_v1->unk0 = 0xDB060010;
    temp_v1->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    temp_a2 = gDisplayListHeads.unk4;
    gDisplayListHeads.unk4 = (void *) (temp_a2 + 8);
    temp_a2->unk0 = 0xDB060010;
    temp_a2->unk4 = (s32) *(&D_800DF4D0 + (*arg0 * 4));
    func_80015BCC_ovl1(temp_a2, &gDisplayListHeads);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB3F4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB470(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB470.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB478(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB478.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit e0e006e8858ba357d1dcb4dc64f038b7df278aa6
void func_800AB480(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_3/func_800AB480.s")
#endif
