#include <ultra64.h>
#include <macros.h>
#include "ovl1_6.h"
#include "D_8004A7C4.h"
#include "unk_structs/D_800DE350.h"

s32 func_800B3234(f32, f32, f32);
void func_800AFA88(struct GObj *);

void func_8000BEF4_ovl1(struct GObj *, f32);

void func_800AECC0(f32 arg0) {
    if (arg0 != D_800E09D0[D_8004A7C4->objId]) {
        D_800E09D0[D_8004A7C4->objId] = arg0;
        func_8000BEF4_ovl1(D_8004A7C4, D_800E09D0[D_8004A7C4->objId]);
    }
}

extern void func_8000BFA0_ovl1(struct GObj *, f32);

void func_800AED20(f32 arg0) {
    if (arg0 != D_800E0B90[D_8004A7C4->objId]) {
        D_800E0B90[D_8004A7C4->objId] = arg0;
        func_8000BFA0_ovl1(D_8004A7C4, D_800E0B90[D_8004A7C4->objId]);
    }
}

void func_800AED80(f32 arg0, s32 arg1) {
    if (arg0 != D_800E09D0[arg1]) {
        struct UnkStruct800DE350 *tmp = D_800DE350[arg1];

        D_800E09D0[arg1] = arg0;
        func_8000BEF4_ovl1(tmp, arg0);
    }
}

void func_800AEDD0(f32 arg0, s32 arg1) {
    if (arg0 != D_800E0B90[arg1]) {
        struct UnkStruct800DE350 *tmp = D_800DE350[arg1];

        D_800E0B90[arg1] = arg0;
        func_8000BFA0_ovl1(tmp, arg0);
    }
}

void func_8000C17C_ovl1(struct GObj *, s32, f32);

void func_800AEE20(s32 arg0, f32 arg1) {
    D_800DF310[D_8004A7C4->objId] = 0;
    D_800DD8D0[D_8004A7C4->objId] &= 0x3FFFFFFF;
    func_8000C17C_ovl1(D_8004A7C4, arg0, arg1);
    if (arg1 != 0.0f) {
        func_8000E324_ovl1(D_8004A7C4);
    }
}

void func_8000C218_ovl1(struct GObj *, s32, f32);

void func_800AEEB4(s32 arg0, f32 arg1) {
    func_8000C218_ovl1(D_8004A7C4, arg0, arg1);
    if (arg1 != 0.0f) {
        func_8000E324_ovl1(D_8004A7C4);
    }
}

void func_800AEF0C(s32 arg0, f32 arg1, struct GObj *arg2) {
    D_800DF310[arg2->objId] = 0;
    D_800DD8D0[arg2->objId] &= 0x3FFFFFFF;
    func_8000C17C_ovl1(arg2, arg0, arg1);
    if (arg1 != 0.0f) {
        func_8000E324_ovl1(arg2);
    }
}

void func_800AEFA4(s32 arg0, f32 arg1, struct GObj *arg2) {
    func_8000C218_ovl1(arg2, arg0, arg1);
    if (arg1 != 0.0f) {
        func_8000E324_ovl1(arg2);
    }
}

// control flow meme
#ifdef NON_MATCHING
void func_800AEFFC(u16 arg0) {
    while (1) {
        if (D_800DD8D0[D_8004A7C4->objId] & 0xC0000000 || --arg0 != 0) {
            D_800DD8D0[D_8004A7C4->objId] &= 0x3FFFFFFF;
            finish_current_thread(1);
        }
        else break;
    }
    // return D_800DD8D0[D_8004A7C4->objId];
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AEFFC.s")
#endif

u32 func_800AF0F4(void);

void func_800AF09C(u16 arg0) {
    while (1) {
        if (func_800AF0F4() != 0 || --arg0 != 0) {
            finish_current_thread(1);
            continue;
        }
        break;
    }
}

extern f32 D_800D6700, D_800D6704, D_800D6708;

// some meme in here
#ifdef NON_MATCHING
u32 func_800AF0F4(void) {
    struct UnkStruct8004A7C4_3C_80 *sp20;
    struct UnkStruct8004A7C4_3C *s0;

    s0 = D_8004A7C4->unk3C;
    while (s0 != 0) {
        if (s0->unk80 != 0) {
            sp20 = s0->unk80;
        } else {
            s0 = func_8000BE90(s0);
        }
    }
    if (D_800D6700 == sp20->unk98 || D_800D6704 == sp20->unk98) {
        return 0;
    }
    if (D_800D6708 == sp20->unk98) {
        D_800DD8D0[D_8004A7C4->objId] |= 0x20000000;
    } else {
        if (sp20->unkA0 < D_800E0B90[D_8004A7C4->objId]) {
            if (D_800DD8D0[D_8004A7C4->objId] * 4 >= 0) {
                return 0;
            }
            D_800DD8D0[D_8004A7C4->objId] &= 0xDFFFFFFF;
        }
    }
    return 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF0F4.s")
#endif

u32 func_800AF230(void) {
    if ((((u32)D_800DD8D0[D_8004A7C4->objId]) >> 0x1E) != 0) {
        D_800DD8D0[D_8004A7C4->objId] &= 0x3FFFFFFF;
        return 1;
    }
    return 0;
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 *func_800AF27C(void) {
    u32 *temp_v0;
    u32 *temp_v0_2;
    u32 temp_v1;
    u32 temp_v1_2;
    u32 phi_v1;
    u32 *phi_v0;
    u32 *phi_return;

    temp_v0 = &D_800DD8D0[D_8004A7C4->objId];
    temp_v1 = *temp_v0;
    phi_v1 = temp_v1;
    phi_v0 = temp_v0;
    phi_return = temp_v0;
    if ((temp_v1 >> 0x1E) == 0) {
loop_1:
        finish_current_thread(1);
        temp_v0_2 = &D_800DD8D0[D_8004A7C4->objId];
        temp_v1_2 = *temp_v0_2;
        phi_v1 = temp_v1_2;
        phi_v0 = temp_v0_2;
        phi_return = temp_v0_2;
        if ((temp_v1_2 & 0xC0000000) == 0) {
            goto loop_1;
        }
    }
    *phi_v0 = phi_v1 & 0x3FFFFFFF;
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF27C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 *func_800AF314(void) {
    struct GObj *temp_v1;
    struct UnkStruct8004A7C4_3C *temp_s0;
    struct UnkStruct8004A7C4_3C *temp_v0_2;
    u32 *temp_v0;
    struct UnkStruct8004A7C4_3C *phi_s0;
    struct GObj *phi_v1;

    temp_v1 = D_8004A7C4;
    temp_s0 = temp_v1->unk3C;
    phi_s0 = temp_s0;
    phi_v1 = temp_v1;
    if (temp_s0 != 0) {
loop_1:
        func_8000984C_ovl1(phi_s0);
        temp_v0_2 = func_8000BE90(phi_s0);
        phi_s0 = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_1;
        }
        phi_v1 = D_8004A7C4;
    }
    D_800DF310[phi_v1->objId] = 0;
    temp_v0 = &D_800DD8D0[phi_v1->objId];
    *temp_v0 = *temp_v0 & 0x3FFFFFFF;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF314.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AF3A0(void) {
    struct UnkStruct8004A7C4_3C *temp_s1;
    struct UnkStruct8004A7C4_3C *temp_v0;
    void *temp_s0;
    void *temp_s0_2;
    struct UnkStruct8004A7C4_3C *phi_s1;
    void *phi_s0;

    temp_s1 = D_8004A7C4->unk3C;
    phi_s1 = temp_s1;
    if (temp_s1 != 0) {
loop_1:
        temp_s0 = phi_s1->unk80;
        phi_s0 = temp_s0;
        if (temp_s0 != 0) {
loop_2:
            func_80009918_ovl1(phi_s0);
            temp_s0_2 = *phi_s0;
            phi_s0 = temp_s0_2;
            if (temp_s0_2 != 0) {
                goto loop_2;
            }
        }
        temp_v0 = func_8000BE90(phi_s1);
        phi_s1 = temp_v0;
        if (temp_v0 != 0) {
            goto loop_1;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF3A0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 *func_800AF408(void) {
    struct GObj *temp_v1;
    struct UnkStruct8004A7C4_3C *temp_s1;
    struct UnkStruct8004A7C4_3C *temp_v0_2;
    u32 *temp_v0;
    void *temp_s0;
    void *temp_s0_2;
    struct UnkStruct8004A7C4_3C *phi_s1;
    void *phi_s0;
    struct GObj *phi_v1;

    temp_v1 = D_8004A7C4;
    temp_s1 = temp_v1->unk3C;
    phi_s1 = temp_s1;
    phi_v1 = temp_v1;
    if (temp_s1 != 0) {
loop_1:
        func_8000984C_ovl1(phi_s1);
        temp_s0 = phi_s1->unk80;
        phi_s0 = temp_s0;
        if (temp_s0 != 0) {
loop_2:
            func_80009918_ovl1(phi_s0);
            temp_s0_2 = *phi_s0;
            phi_s0 = temp_s0_2;
            if (temp_s0_2 != 0) {
                goto loop_2;
            }
        }
        temp_v0_2 = func_8000BE90(phi_s1);
        phi_s1 = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_1;
        }
        phi_v1 = D_8004A7C4;
    }
    D_800DF310[phi_v1->objId] = 0;
    temp_v0 = &D_800DD8D0[phi_v1->objId];
    *temp_v0 = *temp_v0 & 0x3FFFFFFF;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF408.s")
#endif


// some meme
#ifdef NON_MATCHING
void func_800AF4BC(s32 arg0, s32 arg1, s32 arg2) {
    s32 sp30;
    f32 temp_f0;
    f32 temp_f0_2;

    sp30 = 0;
    if (D_8004A7C4->unkF == 1) {
        sp30 = 1;
        func_8000BBE0_ovl1(0);
    }
    if (arg1 == 0) {
        func_8000F980_ovl1(D_8004A7C4, arg0, arg2, 0x1C, 0, 0);
        temp_f0 = D_800E09D0[D_8004A7C4->objId];
        if (D_8004A7C4->unk3C->unk78 != temp_f0) {
            func_8000BEF4_ovl1(D_8004A7C4, temp_f0);
        }
    } else {
        func_8000FB10_ovl1(D_8004A7C4, arg0, arg1, arg2, 0x1C, 0, 0);
        temp_f0_2 = D_800E09D0[D_8004A7C4->objId];
        if (D_8004A7C4->unk3C->unk78 != temp_f0_2) {
            func_8000BEF4_ovl1(D_8004A7C4, temp_f0_2);
            func_8000BFA0_ovl1(D_8004A7C4, D_800E0B90[D_8004A7C4->objId]);
        }
    }
    if (sp30 != 0) {
        func_800AFA88(D_8004A7C4);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF4BC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
f32 func_800AF618(s32 arg0, void *arg1, void *arg2) {
    s32 sp30;
    s32 sp2C;
    f32 temp_f0;
    s32 temp_s1;
    s32 temp_s1_2;
    s32 temp_v0;
    struct GObj *temp_s0;
    struct GObj *temp_s0_2;
    struct GObj *temp_s0_3;
    struct UnkStruct8004A7C4_3C *temp_s2;
    struct UnkStruct8004A7C4_3C *temp_v0_3;
    void *temp_v0_2;
    struct GObj *phi_s0;
    void *phi_s3;
    struct UnkStruct8004A7C4_3C *phi_s2;
    s32 phi_s1;
    void *phi_s0_2;
    struct GObj *phi_s0_3;
    struct GObj *phi_s0_4;
    f32 phi_return;

    temp_s0 = D_8004A7C4;
    sp2C = 0;
    sp30 = 0;
    phi_s0 = temp_s0;
    if (temp_s0->unkF == 1) {
        sp2C = 1;
        func_8000BBE0_ovl1(0);
        phi_s0 = D_8004A7C4;
    }
    temp_v0 = func_80009C38_ovl1(phi_s0, arg0);
    *arg2 = temp_v0;
    func_8000F448_ovl1(temp_v0);
    temp_s0_2 = D_8004A7C4;
    temp_s2 = temp_s0_2->unk3C;
    if (arg1 != 0) {
        sp30 = 1;
    }
    phi_s3 = arg1;
    phi_s2 = temp_s2;
    phi_s0_3 = temp_s0_2;
    if (temp_s2 != 0) {
loop_5:
        if (phi_s3 != 0) {
            temp_v0_2 = *phi_s3;
            if (temp_v0_2 != 0) {
                temp_s1 = *temp_v0_2;
                phi_s1 = temp_s1;
                phi_s0_2 = temp_v0_2;
                if (temp_s1 != 0) {
loop_8:
                    func_80009A44_ovl1(phi_s2, phi_s1);
                    temp_s1_2 = phi_s0_2->unk4;
                    phi_s1 = temp_s1_2;
                    phi_s0_2 = phi_s0_2 + 4;
                    if (temp_s1_2 != 0) {
                        goto loop_8;
                    }
                }
            }
            phi_s3 = phi_s3 + 4;
        }
        temp_v0_3 = func_8000BE90(phi_s2);
        phi_s2 = temp_v0_3;
        if (temp_v0_3 != 0) {
            goto loop_5;
        }
        phi_s0_3 = D_8004A7C4;
    }
    phi_s0_4 = phi_s0_3;
    if (sp2C != 0) {
        func_800AFA88(phi_s0_3);
        phi_s0_4 = D_8004A7C4;
    }
    temp_f0 = (&gEntitiesNextPosXArray[phi_s0_4->objId])[0x274];
    phi_return = temp_f0;
    if (phi_s0_4->unk3C->unk78 != temp_f0) {
        phi_return = func_8000BEF4_ovl1(phi_s0_4, temp_f0);
        if (sp30 != 0) {
            temp_s0_3 = D_8004A7C4;
            phi_return = func_8000BFA0_ovl1(temp_s0_3, (&D_800E4F10 + (temp_s0_3->objId * 4))->unkB90);
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF618.s")
#endif


extern void (*D_800D4F10[])(struct GObj *);

void func_800AF7A0(s32 arg0) {
    u32 *tmp;

    if (arg0 == 0x0001869F) {
        tmp = gSegment4StartArray[D_8004A7C4->objId];
        arg0 = tmp[2];
    }
    D_8004A7C4->unk2C = D_800D4F10[arg0];
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 func_800AF7EC(u32 arg0, u8 arg1, u8 arg2, u8 arg3) {
    void *temp_v0;

    temp_v0 = func_800AC954(D_8004A7C4, arg3, func_800A8C40());
    if (temp_v0 == NULL) {
        return 0;
    }
    D_800E02D0[D_8004A7C4->objId] = arg0;
    temp_v0->unk13 |= arg2;
    func_8000A5FC_ovl1(D_8004A7C4, &D_800AD1A0, arg1, 0x80000000, arg1);
    return 1;
}

#else
u32 func_800AF7EC(s32, u8, u8, u8);
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF7EC.s")
#endif

u32 func_800AF890(s32 arg0, u8 arg1, u8 arg2) {
    return func_800AF7EC(arg0, arg1, arg2, 0);
}

u32 func_800AF8C0(s32 arg0, u8 arg1, u8 arg2) {
    return func_800AF7EC(arg0, arg1, arg2, 1);
}

u32 func_800AF8F0(s32 arg0, u8 arg1, u8 arg2) {
    return func_800AF7EC(arg0, arg1, arg2, 4);
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 func_800AF920(s32 arg0) {
    u32 temp_v0;

    temp_v0 = D_8004A7C4->unk4C;
    if (arg0 < 0) {
        temp_v0->unk13 = temp_v0->unk13 ^ 8;
        return temp_v0;
    }
    if (arg0 != 0) {
        temp_v0->unk13 = temp_v0->unk13 & 0xFFF7;
        return temp_v0;
    }
    temp_v0->unk13 = temp_v0->unk13 | 8;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF920.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 func_800AF96C(s8 arg0) {
    u32 temp_v0;

    temp_v0 = D_8004A7C4->unk4C;
    temp_v0->unk11 = arg0;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF96C.s")
#endif

struct GObj *func_800AF980(s32 arg0) {
    D_800E0810[D_8004A7C4->objId] = arg0;
    D_8004A7C4->unk28 = D_800E0810[D_8004A7C4->objId];
}
 
#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AF9B8(u16 arg0, u8 arg1) {
    s32 temp_a2;
    struct GObj *temp_a0;

    temp_a0 = D_8004A7C4;
    temp_a2 = arg1 & 0xFF;
    func_8000A5FC_ovl1(D_8004A7C4, D_800D4F10[arg0], arg1, D_800E0810[D_8004A7C4->objId], temp_a2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AF9B8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AFA14(void) {
loop_1:
    finish_current_thread(0x7FFFFFFF);
    goto loop_1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AFA14.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AFA54(s32 arg0) {
    func_8000FD78_ovl1(D_8004A7C4, arg0);
    func_800AFA88(D_8004A7C4);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AFA54.s")
#endif

void func_800AFA88(struct GObj *arg0) {
    arg0->unk3C->unk1C.x = gEntitiesNextPosXArray[D_8004A7C4->objId];
    arg0->unk3C->unk1C.y = gEntitiesNextPosYArray[D_8004A7C4->objId];
    arg0->unk3C->unk1C.z = gEntitiesNextPosZArray[D_8004A7C4->objId];
    arg0->unk3C->unk30.x = gEntitiesAngleXArray[D_8004A7C4->objId];
    arg0->unk3C->unk30.y = gEntitiesAngleYArray[D_8004A7C4->objId];
    arg0->unk3C->unk30.z = gEntitiesAngleZArray[D_8004A7C4->objId];
    arg0->unk3C->unk40.x = gEntitiesScaleXArray[D_8004A7C4->objId];
    arg0->unk3C->unk40.y = gEntitiesScaleYArray[D_8004A7C4->objId];
    arg0->unk3C->unk40.z = gEntitiesScaleZArray[D_8004A7C4->objId];
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AFBB4(s32 arg0, struct GObj *arg1) {
    if (arg0 == 0) {
        arg1->unk44 = arg1->unk44 | 1;
    } else {
        arg1->unk44 = arg1->unk44 & ~1;
    }
    arg1->unkE = D_8003DCA8 - 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AFBB4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AFBEC(s32 arg2) {
    play_music();
    if (arg2 != 0) {
        finish_current_thread(arg2);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AFBEC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AFC20(s32 arg0, s32 arg1) {
    play_sound(arg0);
    if (arg1 != 0) {
        finish_current_thread(arg1);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AFC20.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800AFC54(s32 arg1) {
    func_800FB914();
    if (arg1 != 0) {
        finish_current_thread(arg1);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800AFC54.s")
#endif

extern f32 D_800D670C;
void func_800AFC88(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    if (arg0 != D_800D670C) {
        D_800E2090[D_8004A7C4->objId] = arg0;
        gEntitiesNextPosXArray[D_8004A7C4->objId] = D_800E2090[D_8004A7C4->objId];
    }
    if (arg1 != D_800D670C) {
        D_800E2250[D_8004A7C4->objId] = arg1;
        gEntitiesNextPosYArray[D_8004A7C4->objId] = D_800E2250[D_8004A7C4->objId];
    }
    if (arg2 != D_800D670C) {
        D_800E2410[D_8004A7C4->objId] = arg2;
        gEntitiesNextPosZArray[D_8004A7C4->objId] = D_800E2410[D_8004A7C4->objId];
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}

extern f32 D_800D6710;
void func_800AFDA0(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    if (arg0 != D_800D6710) {
        D_800E4A90[D_8004A7C4->objId] = arg0;
        gEntitiesAngleXArray[D_8004A7C4->objId] = D_800E4A90[D_8004A7C4->objId];
    }
    if (arg1 != D_800D6710) {
        D_800E4C50[D_8004A7C4->objId] = arg1;
        gEntitiesAngleYArray[D_8004A7C4->objId] = D_800E4C50[D_8004A7C4->objId];
    }
    if (arg2 != D_800D6710) {
        D_800E4E10[D_8004A7C4->objId] = arg2;
        gEntitiesAngleZArray[D_8004A7C4->objId] = D_800E4E10[D_8004A7C4->objId];
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}

extern f32 D_800D6714;
void func_800AFEB8(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    if (arg0 != D_800D6714) {
        D_800E4FD0[D_8004A7C4->objId] = arg0;
        gEntitiesScaleXArray[D_8004A7C4->objId] = D_800E4FD0[D_8004A7C4->objId];
    }
    if (arg1 != D_800D6714) {
        D_800E5190[D_8004A7C4->objId] = arg1;
        gEntitiesScaleYArray[D_8004A7C4->objId] = D_800E5190[D_8004A7C4->objId];
    }
    if (arg2 != D_800D6714) {
        D_800E5350[D_8004A7C4->objId] = arg2;
        gEntitiesScaleZArray[D_8004A7C4->objId] = D_800E5350[D_8004A7C4->objId];
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}

extern f32 D_800D6718;
void func_800AFFD0(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    if (arg0 != D_800D6718) {
        D_800E2090[D_8004A7C4->objId] += arg0;
        gEntitiesNextPosXArray[D_8004A7C4->objId] = D_800E2090[D_8004A7C4->objId];
    }
    if (arg1 != D_800D6718) {
        D_800E2250[D_8004A7C4->objId] += arg1;
        gEntitiesNextPosYArray[D_8004A7C4->objId] = D_800E2250[D_8004A7C4->objId];
    }
    if (arg2 != D_800D6718) {
        D_800E2410[D_8004A7C4->objId] += arg2;
        gEntitiesNextPosZArray[D_8004A7C4->objId] = D_800E2410[D_8004A7C4->objId];
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}


extern f32 D_800D671C;
void func_800B0100(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    if (arg0 != D_800D671C) {
        gEntitiesAngleXArray[D_8004A7C4->objId] += arg0;
    }
    if (arg1 != D_800D671C) {
        gEntitiesAngleYArray[D_8004A7C4->objId] += arg1;
    }
    if (arg2 != D_800D671C) {
        gEntitiesAngleZArray[D_8004A7C4->objId] += arg2;
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}

extern f32 D_800D6720;
void func_800B01DC(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    if (arg0 != D_800D6720) {
        D_800E4FD0[D_8004A7C4->objId] += arg0;
        gEntitiesScaleXArray[D_8004A7C4->objId] = D_800E4FD0[D_8004A7C4->objId];
    }
    if (arg1 != D_800D6720) {
        D_800E5190[D_8004A7C4->objId] += arg1;
        gEntitiesScaleYArray[D_8004A7C4->objId] = D_800E5190[D_8004A7C4->objId];
    }
    if (arg2 != D_800D6720) {
        D_800E5350[D_8004A7C4->objId] += arg2;
        gEntitiesScaleZArray[D_8004A7C4->objId] = D_800E5350[D_8004A7C4->objId];
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}

extern f32 D_800D6724;
void func_800B030C(f32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, f32 arg8, s32 arg9) {
    f32 temp_f0;

    temp_f0 = D_800D6724;
    if (arg0 != temp_f0) {
        D_800E2090[D_8004A7C4->objId] = arg0;
    }
    if (arg3 != temp_f0) {
        D_800E2250[D_8004A7C4->objId] = arg3;
    }
    if (arg6 != temp_f0) {
        D_800E2410[D_8004A7C4->objId] = arg6;
    }
    if (arg1 != temp_f0) {
        D_800E4A90[D_8004A7C4->objId] = arg1;
    }
    if (arg4 != temp_f0) {
        D_800E4C50[D_8004A7C4->objId] = arg4;
    }
    if (arg7 != temp_f0) {
        D_800E4E10[D_8004A7C4->objId] = arg7;
    }
    if (arg2 != temp_f0) {
        D_800E4FD0[D_8004A7C4->objId] = arg2;
    }
    if (arg5 != temp_f0) {
        D_800E5190[D_8004A7C4->objId] = arg5;
    }
    if (arg8 != temp_f0) {
        D_800E5350[D_8004A7C4->objId] = arg8;
    }
    if (arg9 != 0) {
        finish_current_thread(arg9);
    }
}

extern f32 D_800D6728;
void func_800B04D4(f32 arg0, f32 arg1, f32 arg2, f32 arg3, f32 arg4, f32 arg5, f32 arg6, f32 arg7, f32 arg8, s32 arg9) {
    if (arg0 != D_800D6728) {
        D_800E3050[D_8004A7C4->objId] = arg0;
    }
    if (arg1 != D_800D6728) {
        D_800E3590[D_8004A7C4->objId] = arg1;
    }
    if (arg2 == 65536.0f) {
        D_800E3AD0[D_8004A7C4->objId] = D_800D6728;
    } else if (arg2 != D_800D6728) {
        D_800E3AD0[D_8004A7C4->objId] = ABSF(arg2);
    }
    if (arg3 != D_800D6728) {
        D_800E3210[D_8004A7C4->objId] = arg3;
    }
    if (arg4 != D_800D6728) {
        D_800E3750[D_8004A7C4->objId] = arg4;
    }
    if (arg5 == 65536.0f) {
        D_800E3C90[D_8004A7C4->objId] = D_800D6728;
    } else if (arg5 != D_800D6728) {
        D_800E3C90[D_8004A7C4->objId] = ABSF(arg5);
    }
    if (arg6 != D_800D6728) {
        D_800E33D0[D_8004A7C4->objId] = arg6;
    }
    if (arg7 != D_800D6728) {
        D_800E3910[D_8004A7C4->objId] = arg7;
    }
    if (arg8 == 65536.0f) {
        D_800E3E50[D_8004A7C4->objId] = D_800D6728;
    } else if (arg8 != D_800D6728) {
        D_800E3E50[D_8004A7C4->objId] = ABSF(arg8);
    }
    if (arg9 != 0) {
        finish_current_thread(arg9);
    }
}

// regalloc and reordering around the third leg
#ifdef NON_MATCHING
extern f32 D_800D672C, D_800D6730;
void func_800B07B4(u8 arg0, u8 arg1, u8 arg2, s32 arg3) {
    if (((arg0 & 1) | (2 | 4)) != 0) {
        if (arg0 & 1) {
            D_800E3050[D_8004A7C4->objId] = 0.0f;
        }
        if ((arg0 & 2) != 0) {
            D_800E3210[D_8004A7C4->objId] = 0.0f;
        }
        if ((arg0 & 4) != 0) {
            D_800E33D0[D_8004A7C4->objId] = 0.0f;
        }
    }
    if (((arg1 & 1) | (2 | 4)) != 0) {
        if ((arg1 & 1) != 0) {
            D_800E3590[D_8004A7C4->objId] = 0.0f;
        }
        if ((arg1 & 2) != 0) {
            D_800E3750[D_8004A7C4->objId] = 0.0f;
        }
        if ((arg1 & 4) != 0) {
            D_800E3910[D_8004A7C4->objId] = 0.0f;
        }
    }
    if (((arg2 & 1) | (2 | 4)) != 0) {
        if ((arg2 & 1) != 0) {
            D_800E3AD0[D_8004A7C4->objId] = D_800D672C;
        }
        if ((arg2 & 2) != 0) {
            D_800E3C90[D_8004A7C4->objId] = D_800D6730;
        }
        if ((arg2 & 4) != 0) {
            D_800E3E50[D_8004A7C4->objId] = D_800D6730;
        }
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B07B4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B0974(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    f32 temp_f0;
    u32 temp_v0;
    u32 temp_v0_2;

    temp_f0 = D_800D6734;
    if (arg0 != temp_f0) {
        temp_v0 = D_8004A7C4->objId;
        if (D_800E10D0[temp_v0] == 1.0f) {
            D_800E3050[temp_v0] = arg0;
        } else {
            (&D_800E3050[temp_v0])[0xC14] = -arg0;
        }
    }
    if (arg1 != temp_f0) {
        temp_v0_2 = D_8004A7C4->objId;
        if (D_800E10D0[temp_v0_2] == 1.0f) {
            D_800E3590[temp_v0_2] = arg1;
        } else {
            (&D_800E3590[temp_v0_2])[0xD64] = -arg1;
        }
    }
    if (arg2 == 65536.0f) {
        D_800E3AD0[D_8004A7C4->objId] = temp_f0;
    } else if (arg2 != temp_f0) {
        D_800E3AD0[D_8004A7C4->objId] = arg2;
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B0974.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B0AD4(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    f32 temp_f0;

    temp_f0 = D_800D6738;
    if (arg0 != temp_f0) {
        D_800E64D0[D_8004A7C4->objId] = arg0;
    }
    if (arg1 != temp_f0) {
        D_800E6690[D_8004A7C4->objId] = arg1;
    }
    if (arg2 == 65536.0f) {
        D_800E6850[D_8004A7C4->objId] = temp_f0;
    } else if (arg2 != temp_f0) {
        D_800E6850[D_8004A7C4->objId] = arg2;
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B0AD4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B0BC4(f32 arg0, f32 arg1, f32 arg2, s32 arg3) {
    f32 temp_f0;
    u32 temp_v0;
    u32 temp_v0_2;

    temp_f0 = D_800D673C;
    if (arg0 != temp_f0) {
        temp_v0 = D_8004A7C4->objId;
        if (D_800E6A10[temp_v0] == 1.0f) {
            D_800E64D0[temp_v0] = arg0;
        } else {
            (&D_800E64D0[temp_v0])[0x1934] = -arg0;
        }
    }
    if (arg1 != temp_f0) {
        temp_v0_2 = D_8004A7C4->objId;
        if (D_800E6A10[temp_v0_2] == 1.0f) {
            D_800E6690[temp_v0_2] = arg1;
        } else {
            (&D_800E6690[temp_v0_2])[0x19A4] = -arg1;
        }
    }
    if (arg2 == 65536.0f) {
        D_800E6850[D_8004A7C4->objId] = temp_f0;
    } else if (arg2 != temp_f0) {
        D_800E6850[D_8004A7C4->objId] = arg2;
    }
    if (arg3 != 0) {
        finish_current_thread(arg3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B0BC4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B0D24(s32 arg0) {
    void (*temp_v1)(s32);
    s32 temp_v0_2;
    u32 temp_a0;
    u32 temp_v0;
    s32 phi_return;

    func_800B1C7C();
    temp_v0 = D_8004A7C4->objId;
    temp_v0_2 = temp_v0 * 4;
    temp_v1 = D_800DEDD0[D_8004A7C4->objId];
    if (temp_v1 != NULL) {
        temp_a0 = D_800DD8D0[D_8004A7C4->objId];
        if ((temp_a0 & 1) == 0) {
            if ((temp_a0 & 0x80) == 0) {
                temp_v1(arg0);
            }
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B0D24.s")
#endif

// this function calls D_800DF150 and D_800DEF90
s32 func_800B0D90(struct GObj *arg0) {
    if (D_800DD710[D_8004A7C4->objId] != -1 && !(D_800DD8D0[D_8004A7C4->objId] & 0x80)) {
        if (!(D_800DD8D0[D_8004A7C4->objId] & 2)) {
            if (arg0->unk3C != NULL) {
                if (D_800DEF90[D_8004A7C4->objId] != NULL) {
                    D_800DD8D0[D_8004A7C4->objId] &= 0x3FFFFFFF;
                    func_8000E324_ovl1(arg0);
                }
            }
        }
        if ((D_800DD8D0[D_8004A7C4->objId] & 4) == 0) {
            if (D_800DEF90[D_8004A7C4->objId] != 0) {
                D_800DEF90[D_8004A7C4->objId](arg0);
            }
        }
        D_800E56D0[D_8004A7C4->objId] = 0.0f;
        D_800E5510[D_8004A7C4->objId] = D_800E56D0[D_8004A7C4->objId];
        D_800E5DD0[D_8004A7C4->objId] = 0.0f;
        D_800E5A50[D_8004A7C4->objId] =
        D_800E5C10[D_8004A7C4->objId] = D_800E5DD0[D_8004A7C4->objId];
        if (D_800DF150[D_8004A7C4->objId] != NULL) {
            if (!(D_800DD8D0[D_8004A7C4->objId] & 8)) {
                D_800DF150[D_8004A7C4->objId](arg0);
            }
        }
    }
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
Failed to decompile function func_800B0F28:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl"/"jpt_".
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B0F28.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
Failed to decompile function func_800B113C:

Unable to determine jump table for jr instruction.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl"/"jpt_".
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B113C.s")
#endif

#ifdef NON_MATCHING
void func_800B1378(s32 arg1, s32 arg2, f32 arg3) {
    if (arg2 != -2) {
        D_800DD8D0[D_8004A7C4->objId] |= 0x80000000;
    }
    else if (arg2 == -1) { // move this comparison to right after the first one somehow
        D_800DD8D0[D_8004A7C4->objId] |= 0x40000000;
    }
    else if (D_800DF310[D_8004A7C4->objId] != 0) {
        D_800DF310[D_8004A7C4->objId](arg1, arg2, arg3);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1378.s")
#endif

void func_800B1434(s32 arg0) {

}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B143C(void) {
    u32 temp_v0;
    void *temp_v1;

    temp_v0 = D_8004A7C4->objId;
    if ((D_800DD8D0[temp_v0] & 0x40) == 0) {
        temp_v1 = ERROR(Read from unset register $a0)->unk3C;
        if (temp_v1 != 0) {
            temp_v1->unk1C = gEntitiesNextPosXArray[temp_v0];
            ERROR(Read from unset register $a0)->unk3C->unk20 = gEntitiesNextPosYArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk24 = gEntitiesNextPosZArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk30 = gEntitiesAngleXArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk34 = gEntitiesAngleYArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk38 = gEntitiesAngleZArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk40 = gEntitiesScaleXArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk44 = gEntitiesScaleYArray[D_8004A7C4->objId];
            ERROR(Read from unset register $a0)->unk3C->unk48 = gEntitiesScaleZArray[D_8004A7C4->objId];
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B143C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
its a switch case lol 
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B158C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B175C(void *arg0) {
    if (((D_800DD8D0[D_8004A7C4->objId] & 0x40) == 0) && (arg0->unk3C != 0)) {
        func_8019BBEC_ovl1();
        D_800B143C_ovl1(arg0);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B175C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B17B8(void *arg0) {
    if (((D_800DD8D0[D_8004A7C4->objId] & 0x40) == 0) && (arg0->unk3C != 0)) {
        D_800B143C_ovl1();
        func_801D1CAC_ovl1();
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B17B8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B1814(void *arg0) {
    if (((D_800DD8D0[D_8004A7C4->objId] & 0x40) == 0) && (arg0->unk3C != 0)) {
        D_800B143C_ovl1();
        func_801D1E98_ovl1();
    } 
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1814.s")
#endif

void func_800B1870(s32 arg0) {

}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B1878(s32 arg0) {
loop_1:
    finish_current_thread(0x7FFFFFFF);
    goto loop_1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1878.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
struct GObj *func_800B18B4(s32 arg0) {
    struct GObj *temp_v0;
    u32 *temp_v1;
    u32 temp_a0;

    temp_v0 = D_8004A7C4;
    temp_v1 = &D_800E7CE0[temp_v0->objId];
    temp_a0 = *temp_v1;
    if (temp_a0 != 0) {
        *temp_v1 = temp_a0 - 1;
        if (temp_a0 <= 0) {
            D_800E7CE0[temp_v0->objId] = 0;
        }
    }
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B18B4.s")
#endif

extern struct GObjProcess *D_8004A7D0;
void func_800A9D64(u16);
void func_800A99E4(u32);

// some sort of destructor?
void func_800B1900(u16 arg0) {
    struct GObj *temp_t7 = D_800DE350[arg0];

    func_800A9D64(arg0);
    func_800A99E4(arg0);
    if (temp_t7 == D_8004A7C4) {
        func_800AE138(D_8004A7C4->objId);
        if (D_8004A7D0->kind == 0) {
            func_8000A29C_ovl1(D_8004A7C4);
            finish_current_thread(1);
            return;
        }
        func_8000A29C_ovl1(D_8004A7C4);
        return;
    }
    func_800AE138(temp_t7->objId);
    func_8000A29C_ovl1(temp_t7);
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_800B19B8(s32 arg0, s32 arg1) {
    void *sp18;
    s32 temp_t6;
    struct GObjThreadStack temp_a2;
    void *temp_v0;

    temp_t6 = arg1 * 4;
    temp_v0 = arg0 + temp_t6;
    temp_a2 = *temp_v0;
    if (temp_a2 != 0) {
        sp18 = temp_v0;
        func_80008DA8(temp_a2);
        *temp_v0 = 0;
    }
    return arg0 + temp_t6;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B19B8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B19F4(s32 arg0, s32 arg1) {
    u32 *temp_v1;
    u32 temp_a2;

    temp_v1 = &D_800DD8D0[arg1];
    temp_a2 = *temp_v1;
    if ((temp_a2 & 0x80) == 0) {
        *temp_v1 = (temp_a2 & ~0xFF) | (arg0 & 0xFF);
        func_800B1C7C(D_800DE350[arg1], temp_a2);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B19F4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B1A4C(s32 arg0, s32 arg1) {
    s32 temp_s0;
    s32 temp_v1;
    void *temp_v0;
    s32 *phi_s2;
    s32 phi_s0;
    s32 phi_s1;

    phi_s2 = D_800DD710;
    phi_s0 = 0;
    phi_s1 = 0;
loop_1:
    if (*phi_s2 != -1) {
        temp_v0 = D_800DD8D0 + phi_s1;
        if (phi_s0 != arg1) {
            temp_v1 = *temp_v0;
            if ((temp_v1 & 0x80) == 0) {
                *temp_v0 = (temp_v1 & ~0xFF) | (arg0 & 0xFF);
                func_800B1C7C(*(D_800DE350 + phi_s1));
            }
        }
    }
    temp_s0 = phi_s0 + 1;
    phi_s2 = phi_s2 + 4;
    phi_s0 = temp_s0;
    phi_s1 = phi_s1 + 4;
    if (temp_s0 != 0x70) {
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1A4C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_800B1B28(s32 arg0) {
    s32 *temp_s1;
    s32 temp_v1;
    void *temp_v0;
    s32 *phi_s1;
    s32 phi_s0;
    void *phi_return;

    phi_s1 = D_800DD710;
    phi_s0 = 0;
loop_1:
    temp_v0 = D_800DD8D0 + phi_s0;
    phi_return = temp_v0;
    if (*phi_s1 != -1) {
        temp_v1 = *temp_v0;
        phi_return = temp_v0;
        if ((temp_v1 & 0x80) == 0) {
            *temp_v0 = (temp_v1 & ~0xFF) | (arg0 & 0xFF);
            phi_return = func_800B1C7C(*(D_800DE350 + phi_s0));
        }
    }
    temp_s1 = phi_s1 + 4;
    phi_s1 = temp_s1;
    phi_s0 = phi_s0 + 4;
    if (temp_s1 != D_800DD8D0) {
        goto loop_1;
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1B28.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B1BF0(s32 arg0, s32 arg1) {
    u32 *temp_v1;
    u32 *temp_v1_2;

    if (arg0 == 0x80) {
        temp_v1 = &D_800DD8D0[arg1];
        *temp_v1 = (*temp_v1 & ~0xFF) + 0x80;
        func_800B1C7C(D_800DE350[arg1]);
        return;
    }
    temp_v1_2 = &D_800DD8D0[arg1];
    *temp_v1_2 = *temp_v1_2 & ~0xFF;
    func_800B1C7C(D_800DE350[arg1]);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1BF0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
u32 *func_800B1C7C(void *arg0) {
    u32 *sp2C;
    s32 temp_a1;
    s32 temp_s0;
    u32 *temp_ret;
    u32 *temp_v0;
    u32 *temp_v0_2;
    u32 temp_v1;

    temp_s0 = arg0->unk0;
    temp_v0 = &D_800DD8D0[temp_s0];
    temp_v1 = *temp_v0;
    temp_a1 = temp_v1 & 0x80;
    if ((temp_a1 != 0) && ((temp_v1 & 0x8000) == 0)) {
        sp2C = temp_v0;
        func_8000B758_ovl1(temp_a1);
        arg0->unk44 = arg0->unk44 | 1;
        *temp_v0 = *temp_v0 | 0x8000;
        return temp_v0;
    }
    if ((temp_a1 == 0) && ((temp_v1 & 0x8000) != 0)) {
        sp2C = temp_v0;
        func_8000B78C_ovl1(arg0, temp_a1);
        arg0->unk44 = arg0->unk44 & ~1;
        *temp_v0 = *temp_v0 ^ 0x8000;
        return temp_v0;
    }
    func_800B1E08(1, 0, temp_s0);
    func_800B1E08(2, gEntityGObjProcessArray[temp_s0], temp_s0);
    func_800B1E08(4, 0, temp_s0);
    func_800B1E08(8, 0, temp_s0);
    func_800B1E08(0x10, D_800DE890[temp_s0], temp_s0);
    func_800B1E08(0x20, D_800DEA50[temp_s0], temp_s0);
    temp_ret = func_800B1E08(0x40, D_800DEC10[temp_s0], temp_s0);
    temp_v0_2 = temp_ret;
    if (temp_v0_2 == 1) {
        arg0->unk44 = arg0->unk44 | 1;
        return temp_ret;
    }
    if (temp_v0_2 != 2) {
        return temp_ret;
    }
    arg0->unk44 = arg0->unk44 & ~1;
    return temp_ret;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1C7C.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
? func_800B1E08(s32 arg0, s32 arg1, s32 arg2) {
    u32 *sp28;
    s32 sp1C;
    s32 temp_a1;
    s32 temp_a1_2;
    s32 temp_a3;
    u32 *temp_v1;
    u32 temp_v0;
    u32 phi_v0;
    u32 phi_v0_2;
    ? phi_t0;

    temp_v1 = &D_800DD8D0[arg2];
    temp_v0 = *temp_v1;
    temp_a3 = temp_v0 & arg0;
    if ((temp_a3 != 0) && (temp_a1 = arg0 << 8, ((temp_v0 & temp_a1) == 0))) {
        phi_v0 = temp_v0;
        if (arg1 != 0) {
            sp28 = temp_v1;
            sp1C = temp_a1;
            func_8000B7C0_ovl1(arg1, temp_a1, temp_a3);
            phi_v0 = *temp_v1;
        }
        D_800DD8D0[arg2] = phi_v0 | (arg0 << 8);
        phi_t0 = 1;
    } else {
        temp_a1_2 = arg0 << 8;
        phi_t0 = 0;
        if (temp_a3 == 0) {
            phi_t0 = 0;
            if ((temp_v0 & temp_a1_2) != 0) {
                phi_v0_2 = temp_v0;
                if (arg1 != 0) {
                    sp28 = temp_v1;
                    sp1C = temp_a1_2;
                    func_8000B7D8_ovl1(arg1, temp_a1_2, temp_a3);
                    phi_v0_2 = *temp_v1;
                }
                D_800DD8D0[arg2] = phi_v0_2 ^ (arg0 << 8);
                phi_t0 = 2;
            }
        }
    }
    return phi_t0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1E08.s")
#endif


// current entity stack size?
extern u32 gNewEntityStackSize;

void assign_new_process_entry(struct GObjProcess *ts, void (*func)(struct GObj *)) {
    struct GObjThread *temp_v0;
    s32 id;

    temp_v0 = ts->thread;
    id = temp_v0->thread.id;
    ts->entryPoint = func;
    osDestroyThread(&temp_v0->thread);
    osCreateThread(&temp_v0->thread,
                   id,
                   func,
                   ts->gobj,
                   &temp_v0->objStack->stack[gNewEntityStackSize / 8],
                   0x33);
    temp_v0->objStack->stack[7] = STACK_TOP_MAGIC;
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B1F68(void *arg0, ?32 arg1) {
    arg0->unk1C = arg1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1F68.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_800B1F70(void *arg0, s32 arg1) {
    s32 temp_v0;
    s32 temp_v0_2;
    s32 temp_v1;
    void *temp_v0_3;
    void *phi_a0;

    temp_v0 = arg0->unk10;
    if (temp_v0 != 0) {
        return temp_v0;
    }
    temp_v0_2 = arg0->unk8;
    phi_a0 = arg0;
    if (temp_v0_2 != 0) {
        return temp_v0_2;
    }
loop_4:
    temp_v0_3 = phi_a0->unk14;
    if (arg1 == temp_v0_3) {
        return 0;
    }
    temp_v1 = temp_v0_3->unk8;
    if (temp_v1 == 0) {
        phi_a0 = temp_v0_3;
        goto loop_4;
    }
    return temp_v1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1F70.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B1FD0(s32 arg0, s32 arg1, ? arg2, s32 arg3, f32 arg4) {
    struct UnkStruct8004A7C4_3C *temp_s5;
    struct UnkStruct8004A7C4_3C *temp_v0;
    struct UnkStruct8004A7C4_3C *temp_v0_2;
    s32 phi_s3;
    s32 phi_s4;
    struct UnkStruct8004A7C4_3C *phi_s5;
    struct UnkStruct8004A7C4_3C *phi_s5_2;
    struct UnkStruct8004A7C4_3C *phi_s0;
    s32 phi_s2;
    s32 phi_s1;
    s32 phi_s3_2;
    s32 phi_s4_2;
    s32 phi_s3_3;
    s32 phi_s4_3;

    temp_s5 = D_8004A7C4->unk3C;
    phi_s3 = arg1;
    phi_s4 = arg3;
    phi_s5 = temp_s5;
    phi_s5_2 = temp_s5;
    phi_s3_3 = arg1;
    phi_s4_3 = arg3;
    if (arg0 != temp_s5) {
loop_1:
        phi_s3_2 = phi_s3;
        if (phi_s3 != 0) {
            phi_s3_2 = phi_s3 + 4;
        }
        phi_s4_2 = phi_s4;
        if (phi_s4 != 0) {
            phi_s4_2 = phi_s4 + 0x2C;
        }
        temp_v0 = func_8000BE90(phi_s5);
        phi_s3 = phi_s3_2;
        phi_s4 = phi_s4_2;
        phi_s5 = temp_v0;
        phi_s5_2 = temp_v0;
        phi_s3_3 = phi_s3_2;
        phi_s4_3 = phi_s4_2;
        if (arg0 != temp_v0) {
            goto loop_1;
        }
    }
    if (phi_s5_2 != 0) {
        phi_s0 = phi_s5_2;
        phi_s2 = phi_s3_3;
        phi_s1 = phi_s4_3;
loop_8:
        func_8000EC98_ovl1(phi_s0, phi_s2, arg2, phi_s1, 0, arg4, 0.0f, 0.0f, 0.0f);
        temp_v0_2 = func_800B1F70(phi_s0, phi_s5_2);
        if (phi_s2 != 0) {
            phi_s2 = phi_s2 + 4;
        }
        if (phi_s1 != 0) {
            phi_s1 = phi_s1 + 0x2C;
        }
        phi_s0 = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_8;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B1FD0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B20E0(void *arg0, void *arg1) {
    struct UnkStruct8004A7C4_3C *temp_s0;
    struct UnkStruct8004A7C4_3C *temp_v0_2;
    void *temp_a0;
    void *temp_s1;
    void *temp_v0;
    void *phi_s1;
    struct UnkStruct8004A7C4_3C *phi_s0;

    temp_s0 = arg0->unk3C;
    phi_s1 = arg1;
    phi_s0 = temp_s0;
    if (temp_s0 != 0) {
loop_1:
        if (phi_s1 != 0) {
            temp_a0 = *phi_s1;
            temp_s1 = phi_s1 + 4;
            phi_s1 = temp_s1;
            if (temp_a0 != 0) {
                temp_v0 = *temp_a0;
                phi_s0->unk80->unk8 = temp_v0->unk0;
                phi_s0->unk80->unkA = temp_v0->unk2;
                phi_s0->unk80->unkB = temp_v0->unk3;
                phi_s0->unk80->unkC = temp_v0->unk4;
                phi_s0->unk80->unk10 = temp_v0->unk8;
                phi_s0->unk80->unk12 = temp_v0->unkA;
                phi_s0->unk80->unk14 = temp_v0->unkC;
                phi_s0->unk80->unk16 = temp_v0->unkE;
                phi_s0->unk80->unk18 = temp_v0->unk10;
                phi_s0->unk80->unk1C = temp_v0->unk14;
                phi_s0->unk80->unk20 = temp_v0->unk18;
                phi_s0->unk80->unk24 = temp_v0->unk1C;
                phi_s0->unk80->unk28 = temp_v0->unk20;
                phi_s0->unk80->unk2C = temp_v0->unk14;
                phi_s0->unk80->unk30 = temp_v0->unk1C;
                phi_s0->unk80->unk80 = 0;
                phi_s1 = temp_s1;
            }
        }
        temp_v0_2 = func_8000BE90(phi_s0);
        phi_s0 = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_1;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B20E0.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B21FC(void *arg0, f32 arg1) {
    s32 temp_a1;
    struct UnkStruct8004A7C4_3C *temp_s0;
    struct UnkStruct8004A7C4_3C *temp_v0;
    void *phi_s1;
    struct UnkStruct8004A7C4_3C *phi_s0;
    s8 phi_s2;

    temp_s0 = D_8004A7C4->unk3C;
    (bitwise void *) temp_s0->unk0.y->unk40 = arg1;
    phi_s1 = *arg0;
    phi_s0 = temp_s0;
    phi_s2 = 1;
    if (temp_s0 != 0) {
loop_1:
        temp_a1 = *phi_s1;
        if (temp_a1 != 0) {
            func_8000C10C_ovl1(phi_s0, temp_a1, arg1);
            phi_s0->unk55 = phi_s2;
            phi_s2 = 0;
        }
        temp_v0 = func_8000BE90(phi_s0);
        phi_s1 = phi_s1 + 4;
        phi_s0 = temp_v0;
        if (temp_v0 != 0) {
            goto loop_1;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B21FC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B2288(void *arg0, ? arg1) {
    s32 temp_a1;
    struct UnkStruct8004A7C4_3C *temp_s3;
    struct UnkStruct8004A7C4_3C *temp_v0_2;
    void *temp_s0;
    void *temp_s0_2;
    void *temp_v0;
    void *phi_s2;
    struct UnkStruct8004A7C4_3C *phi_s3;
    void *phi_s1;
    void *phi_s0;

    temp_s3 = D_8004A7C4->unk3C;
    phi_s2 = arg0;
    phi_s3 = temp_s3;
    if (temp_s3 != 0) {
loop_1:
        if (phi_s2 != 0) {
            temp_v0 = *phi_s2;
            if (temp_v0 != 0) {
                temp_s0 = phi_s3->unk80;
                phi_s1 = temp_v0;
                phi_s0 = temp_s0;
                if (temp_s0 != 0) {
loop_4:
                    temp_a1 = *phi_s1;
                    if (temp_a1 != 0) {
                        func_8000C144_ovl1(phi_s0, temp_a1, arg1);
                    }
                    temp_s0_2 = *phi_s0;
                    phi_s1 = phi_s1 + 4;
                    phi_s0 = temp_s0_2;
                    if (temp_s0_2 != 0) {
                        goto loop_4;
                    }
                }
            }
            phi_s2 = phi_s2 + 4;
        }
        temp_v0_2 = func_8000BE90(phi_s3);
        phi_s3 = temp_v0_2;
        if (temp_v0_2 != 0) {
            goto loop_1;
        }
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B2288.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_800B2340(void *arg0, struct UnkStruct8004A7C4_3C *arg1, u32 arg2) {
    ? spB8;
    ? sp78;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f0_3;
    f32 temp_f0_4;
    f32 temp_f0_5;
    f32 temp_f0_6;
    f32 temp_f12;
    f32 temp_f12_2;
    f32 temp_f12_3;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    struct UnkStruct8004A7C4_3C *temp_s0;
    u32 phi_a2;
    struct UnkStruct8004A7C4_3C *phi_s0;

    phi_a2 = arg2;
    if (arg2 == 0xFFFF) {
        phi_a2 = D_8004A7C4->objId;
    }
    phi_s0 = arg1;
    if (arg1 == 0) {
        phi_s0 = D_8004A7C4->unk3C;
    }
    arg2 = phi_a2;
    guMtxIdentF_ovl1(&spB8, phi_a2);
loop_5:
    if (phi_s0->unk14 != 1) {
        temp_f0 = phi_s0->unk40.x;
        if ((temp_f0 != 1.0f) || (phi_s0->unk40.y != 1.0f) || (phi_s0->unk40.z != 1.0f)) {
            func_8001B4AC_ovl1(&sp78, temp_f0, (bitwise s32) phi_s0->unk40.y, (bitwise s32) phi_s0->unk40.z);
            guMtxCatF(&spB8, &sp78, &spB8);
        }
        temp_f0_2 = phi_s0->unk30.x;
        if ((temp_f0_2 != 0.0f) || (phi_s0->unk30.y != 0.0f) || (phi_s0->unk30.z != 0.0f)) {
            _guRotateRPYF(&sp78, temp_f0_2, (bitwise f32) (bitwise s32) phi_s0->unk30.y, (bitwise f32) (bitwise s32) phi_s0->unk30.z);
            guMtxCatF(&spB8, &sp78, &spB8);
        }
        temp_f0_3 = phi_s0->unk1C.x;
        if ((temp_f0_3 != 0.0f) || (phi_s0->unk1C.y != 0.0f) || (phi_s0->unk1C.z != 0.0f)) {
            func_8001B6E4_ovl1(&sp78, temp_f0_3, (bitwise s32) phi_s0->unk1C.y, (bitwise s32) phi_s0->unk1C.z);
            guMtxCatF(&spB8, &sp78, &spB8);
        }
    } else {
        temp_f0_4 = gEntitiesScaleXArray[arg2];
        temp_f2 = gEntitiesScaleYArray[arg2];
        temp_f12 = gEntitiesScaleZArray[arg2];
        if ((temp_f0_4 != 1.0f) || (temp_f2 != 1.0f) || (temp_f12 != 1.0f)) {
            func_8001B4AC_ovl1(temp_f12, &sp78, temp_f0_4, temp_f2, temp_f12);
            guMtxCatF(&spB8, &sp78, &spB8);
        }
        temp_f0_5 = gEntitiesAngleXArray[arg2];
        temp_f2_2 = gEntitiesAngleYArray[arg2];
        temp_f12_2 = gEntitiesAngleZArray[arg2];
        if ((temp_f0_5 != 0.0f) || (temp_f2_2 != 0.0f) || (temp_f12_2 != 0.0f)) {
            _guRotateRPYF(&sp78, temp_f0_5, temp_f2_2, temp_f12_2);
            guMtxCatF(&spB8, &sp78, &spB8);
        }
        temp_f0_6 = gEntitiesNextPosXArray[arg2];
        temp_f2_3 = gEntitiesNextPosYArray[arg2];
        temp_f12_3 = gEntitiesNextPosZArray[arg2];
        if ((temp_f0_6 != 0.0f) || (temp_f2_3 != 0.0f) || (temp_f12_3 != 0.0f)) {
            func_8001B6E4_ovl1(temp_f12_3, &sp78, temp_f0_6, temp_f2_3, temp_f12_3);
            guMtxCatF(&spB8, &sp78, &spB8);
        }
    }
    temp_s0 = phi_s0->unk14;
    phi_s0 = temp_s0;
    if (temp_s0 != 1) {
        goto loop_5;
    }
    arg0->unk0 = spE8;
    arg0->unk4 = spEC;
    arg0->unk8 = spF0;
    return arg0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B2340.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B26D8(void *arg0, struct UnkStruct8004A7C4_3C *arg1, u32 arg2) {
    f32 sp90;
    ? sp50;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f0_3;
    f32 temp_f12;
    f32 temp_f2;
    f32 temp_f2_2;
    s32 temp_cond;
    struct UnkStruct8004A7C4_3C *phi_s0;
    u32 phi_s5;

    phi_s5 = arg2;
    if (arg2 == 0xFFFF) {
        phi_s5 = D_8004A7C4->objId;
    }
    phi_s0 = arg1;
    if (arg1 == 0) {
        phi_s0 = D_8004A7C4->unk3C;
    }
    guMtxIdentF_ovl1(&sp90);
loop_5:
    if (phi_s0->unk14 != 1) {
        temp_f0 = phi_s0->unk30.x;
        if ((temp_f0 != 0.0f) || (phi_s0->unk30.y != 0.0f) || (phi_s0->unk30.z != 0.0f)) {
            _guRotateRPYF(&sp50, temp_f0, (bitwise f32) (bitwise s32) phi_s0->unk30.y, (bitwise f32) (bitwise s32) phi_s0->unk30.z);
            guMtxCatF(&sp90, &sp50, &sp90);
block_14:
        }
    } else {
        temp_f0_2 = gEntitiesAngleXArray[phi_s5];
        temp_f2 = gEntitiesAngleYArray[phi_s5];
        temp_f12 = gEntitiesAngleZArray[phi_s5];
        if ((temp_f0_2 != 0.0f) || (temp_f2 != 0.0f) || (temp_f12 != 0.0f)) {
            _guRotateRPYF(&sp50, temp_f0_2, temp_f2, temp_f12);
            guMtxCatF(&sp90, &sp50, &sp90);
            goto block_14;
        }
    }
    phi_s0 = phi_s0->unk14;
    if (phi_s0->unk14 != 1) {
        goto loop_5;
    }
    temp_f0_3 = asinf(-sp98);
    temp_f2_2 = D_800D67D4;
    temp_cond = temp_f0_3 == temp_f2_2;
    arg0->unk4 = temp_f0_3;
    if (temp_cond || (D_800D67D8 == arg0->unk4)) {
        if (temp_f2_2 == arg0->unk4) {
            arg0->unk0 = atan2f(spA0, spA4);
        } else {
            arg0->unk0 = atan2f(-spA0, spA4);
        }
        arg0->unk8 = 0.0f;
    } else {
        arg0->unk0 = atan2f(spA8, spB8);
        arg0->unk8 = atan2f(sp94, sp90);
    }
    func_800A4598(arg0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B26D8.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_800B2928(void *arg0, struct UnkStruct8004A7C4_3C *arg1, u32 arg2) {
    f32 sp90;
    ? sp50;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f12;
    f32 temp_f2;
    struct UnkStruct8004A7C4_3C *phi_s0;
    u32 phi_s5;

    phi_s5 = arg2;
    if (arg2 == 0xFFFF) {
        phi_s5 = D_8004A7C4->objId;
    }
    phi_s0 = arg1;
    if (arg1 == 0) {
        phi_s0 = D_8004A7C4->unk3C;
    }
    guMtxIdentF_ovl1(&sp90);
loop_5:
    if (phi_s0->unk14 != 1) {
        temp_f0 = phi_s0->unk40.x;
        if ((temp_f0 != 1.0f) || (phi_s0->unk40.y != 1.0f) || (phi_s0->unk40.z != 1.0f)) {
            func_8001B4AC_ovl1(&sp50, temp_f0, (bitwise s32) phi_s0->unk40.y, (bitwise s32) phi_s0->unk40.z);
            guMtxCatF(&sp90, &sp50, &sp90);
block_14:
        }
    } else {
        temp_f0_2 = gEntitiesScaleXArray[phi_s5];
        temp_f2 = gEntitiesScaleYArray[phi_s5];
        temp_f12 = gEntitiesScaleZArray[phi_s5];
        if ((temp_f0_2 != 1.0f) || (temp_f2 != 1.0f) || (temp_f12 != 1.0f)) {
            func_8001B4AC_ovl1(temp_f12, &sp50, temp_f0_2, temp_f2, temp_f12);
            guMtxCatF(&sp90, &sp50, &sp90);
            goto block_14;
        }
    }
    phi_s0 = phi_s0->unk14;
    if (phi_s0->unk14 != 1) {
        goto loop_5;
    }
    arg0->unk0 = sp90;
    arg0->unk4 = spA4;
    arg0->unk8 = spB8;
    return arg0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B2928.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
f32 func_800B2AD4(void *arg0, struct UnkStruct8004A7C4_3C *arg1, u32 arg2) {
    f32 spBC;
    ? sp7C;
    f32 temp_f0;
    f32 temp_f0_2;
    f32 temp_f0_3;
    f32 temp_f0_4;
    f32 temp_f0_5;
    f32 temp_f0_6;
    f32 temp_f0_7;
    f32 temp_f12;
    f32 temp_f12_2;
    f32 temp_f12_3;
    f32 temp_f12_4;
    f32 temp_f2;
    f32 temp_f2_2;
    f32 temp_f2_3;
    f32 temp_f2_4;
    struct UnkStruct8004A7C4_3C *temp_s0;
    u32 phi_a2;
    struct UnkStruct8004A7C4_3C *phi_s0;

    phi_a2 = arg2;
    if (arg2 == 0xFFFF) {
        phi_a2 = D_8004A7C4->objId;
    }
    phi_s0 = arg1;
    if (arg1 == 0) {
        phi_s0 = D_8004A7C4->unk3C;
    }
    arg2 = phi_a2;
    guMtxIdentF_ovl1(&spBC, phi_a2);
loop_5:
    if (phi_s0->unk14 != 1) {
        temp_f0_2 = phi_s0->unk40.x;
        if ((temp_f0_2 != 1.0f) || (phi_s0->unk40.y != 1.0f) || (phi_s0->unk40.z != 1.0f)) {
            func_8001B4AC_ovl1(&sp7C, 1.0f / temp_f0_2, 1.0f / phi_s0->unk40.y, 1.0f / phi_s0->unk40.z);
            guMtxCatF(&sp7C, &spBC, &spBC);
        }
        temp_f0_3 = phi_s0->unk30.x;
        if ((temp_f0_3 != 0.0f) || (phi_s0->unk30.y != 0.0f) || (phi_s0->unk30.z != 0.0f)) {
            func_800A465C(&sp7C, -temp_f0_3, -phi_s0->unk30.y, -phi_s0->unk30.z);
            guMtxCatF(&sp7C, &spBC, &spBC);
        }
        temp_f0_4 = phi_s0->unk1C.x;
        if ((temp_f0_4 != 0.0f) || (phi_s0->unk1C.y != 0.0f) || (phi_s0->unk1C.z != 0.0f)) {
            func_8001B6E4_ovl1(&sp7C, -temp_f0_4, -phi_s0->unk1C.y, -phi_s0->unk1C.z);
            guMtxCatF(&sp7C, &spBC, &spBC);
        }
    } else {
        temp_f0_5 = gEntitiesScaleXArray[arg2];
        temp_f2 = gEntitiesScaleYArray[arg2];
        temp_f12 = gEntitiesScaleZArray[arg2];
        if ((temp_f0_5 != 1.0f) || (temp_f2 != 1.0f) || (temp_f12 != 1.0f)) {
            func_8001B4AC_ovl1(temp_f12, &sp7C, 1.0f / temp_f0_5, 1.0f / temp_f2, 1.0f / temp_f12);
            guMtxCatF(&sp7C, &spBC, &spBC);
        }
        temp_f0_6 = gEntitiesAngleXArray[arg2];
        temp_f2_2 = gEntitiesAngleYArray[arg2];
        temp_f12_2 = gEntitiesAngleZArray[arg2];
        if ((temp_f0_6 != 0.0f) || (temp_f2_2 != 0.0f) || (temp_f12_2 != 0.0f)) {
            func_800A465C(temp_f12_2, &sp7C, -temp_f0_6, -temp_f2_2, -temp_f12_2);
            guMtxCatF(&sp7C, &spBC, &spBC);
        }
        temp_f0_7 = gEntitiesNextPosXArray[arg2];
        temp_f2_3 = gEntitiesNextPosYArray[arg2];
        temp_f12_3 = gEntitiesNextPosZArray[arg2];
        if ((temp_f0_7 != 0.0f) || (temp_f2_3 != 0.0f) || (temp_f12_3 != 0.0f)) {
            func_8001B6E4_ovl1(temp_f12_3, &sp7C, -temp_f0_7, -temp_f2_3, -temp_f12_3);
            guMtxCatF(&sp7C, &spBC, &spBC);
        }
    }
    temp_s0 = phi_s0->unk14;
    phi_s0 = temp_s0;
    if (temp_s0 != 1) {
        goto loop_5;
    }
    temp_f0 = arg0->unk0;
    temp_f2_4 = arg0->unk4;
    temp_f12_4 = arg0->unk8;
    arg0->unk0 = spEC + ((spBC * temp_f0) + (spCC * temp_f2_4) + (spDC * temp_f12_4));
    arg0->unk4 = spF0 + ((spC0 * temp_f0) + (spD0 * temp_f2_4) + (spE0 * temp_f12_4));
    arg0->unk8 = spF4 + ((spC4 * temp_f0) + (spD4 * temp_f2_4) + (spE4 * temp_f12_4));
    return temp_f0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B2AD4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B2F54(s32 arg0, ? arg2) {
    func_8000FE2C_ovl1(arg2, *(&D_800D79D8 + (((arg0 - 0xA) >> 1) * 4)), arg2);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B2F54.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B2F90(s32 arg0, ? arg2) {
    void *temp_s0;

    temp_s0 = *(&D_800D79D8 + (((arg0 - 0xA) >> 1) * 4));
    func_8000FE2C_ovl1(arg2, temp_s0, arg2);
loop_1:
    if (D_800D67DC != temp_s0->unk74) {
        finish_current_thread(1);
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B2F90.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B3008(s32 arg0) {
loop_1:
    if (D_800D67E0 != (*(&D_800D79D8 + (((arg0 - 0xA) >> 1) * 4)))->unk74) {
        finish_current_thread(1);
        goto loop_1;
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B3008.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_800B3070(s32 arg0, f32 arg1) {
    void *temp_v0;

    temp_v0 = *(&D_800D79D8 + (((arg0 - 0xA) >> 1) * 4));
    temp_v0->unk78 = arg1;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B3070.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void *func_800B3094(s32 arg0) {
    void *temp_v0;

    temp_v0 = *(&D_800D79D8 + (((arg0 - 0xA) >> 1) * 4));
    temp_v0->unk74 = D_800D67E4;
    return temp_v0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B3094.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_800B30BC(f32 arg0, f32 arg1, ? arg2) {
    f32 temp_f0;
    f32 temp_f0_2;
    struct Normal *temp_v1;
    f32 phi_f2;
    s32 phi_v0;
    f32 phi_f2_2;
    s32 phi_return;

    temp_v1 = &D_800E6F50[D_8004A7C4->objId];
    temp_f0 = temp_v1->x;
    if (temp_f0 < 0.0f) {
        phi_f2 = -temp_f0;
    } else {
        phi_f2 = temp_f0;
    }
    phi_v0 = 0;
    phi_return = 0;
    if (phi_f2 < arg0) {
        phi_v0 = 1;
        phi_return = 1;
    }
    if (phi_v0 != 0) {
        temp_f0_2 = temp_v1->y;
        if (temp_f0_2 < 0.0f) {
            phi_f2_2 = -temp_f0_2;
        } else {
            phi_f2_2 = temp_f0_2;
        }
        phi_return = 0;
        if (phi_f2_2 < arg1) {
            phi_return = 1;
        }
    }
    return phi_return;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B30BC.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
? func_800B3158(void) {
    u32 temp_v0;

    temp_v0 = D_8004A7C4->objId;
    if (func_800B3234(gEntitiesNextPosXArray[temp_v0], gEntitiesNextPosYArray[temp_v0], gEntitiesNextPosZArray[temp_v0]) != 0) {
        return 0;
    }
    return 1;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B3158.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_800B31B4(void) {
    s32 sp18;
    s32 temp_a0;
    u32 temp_v0;

    temp_v0 = D_8004A7C4->objId;
    temp_a0 = D_800DE350[temp_v0];
    sp18 = temp_a0;
    if (func_800B3234(gEntitiesNextPosXArray[temp_v0], gEntitiesNextPosYArray[temp_v0], temp_a0, (bitwise s32) gEntitiesNextPosZArray[temp_v0]) != 0) {
        temp_a0->unk48 = 0;
        func_8019B7D8_ovl1(temp_a0);
        func_8019D8A0_ovl1(D_8004A7C4->unk2);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B31B4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
? func_800B3234(f32 arg0, f32 arg1, f32 arg2) {
    f32 sp38;
    f32 sp34;
    f32 sp30;
    s32 sp2C;
    f32 *temp_a1;
    f32 temp_f0;
    f32 temp_f14;
    f32 temp_f2;
    struct Normal *temp_a0_2;
    struct GObj *temp_v1;
    struct GObj *temp_v1_2;
    struct GObj *temp_v1_3;
    u32 temp_a0;

    temp_v1 = D_8004A7C4;
    D_800E6F50[temp_v1->objId].z = 0.0f;
    temp_a0 = temp_v1->objId;
    temp_a1 = &sp30;
    if (gEntitiesNextPosYArray[temp_a0] < D_800D67E8) {
        D_800E6F50[temp_a0].z = 1.0f;
        return 1;
    }
    sp30 = arg0;
    sp34 = arg1;
    sp38 = arg2;
    temp_v1_2 = D_8004A7C4;
    sp2C = func_800A4F48(D_800D799C->unk3C, temp_a1, 0x3FD9999A, 0x4019999A);
    D_800E6F50[temp_v1_2->objId].x = sp30;
    D_800E6F50[temp_v1_2->objId].y = sp34;
    temp_f0 = arg0 - *gEntitiesNextPosXArray;
    temp_f2 = arg1 - (*gEntitiesNextPosYArray + 20.0f);
    temp_f14 = arg2 - *gEntitiesNextPosZArray;
    temp_v1_3 = D_8004A7C4;
    D_800E6F50[temp_v1_3->objId].originOffset = sqrtf((temp_f0 * temp_f0) + (temp_f2 * temp_f2) + (temp_f14 * temp_f14));
    if (sp2C == 0) {
        temp_a0_2 = &D_800E6F50[temp_v1_3->objId];
        if (temp_a0_2->originOffset > 500.0f) {
            temp_a0_2->z = 1.0f;
            return 1;
        }
    }
    return 0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl1/ovl1_7/func_800B3234.s")
#endif


extern f32 D_800D67EC;
void func_800B33F4(void) {
    D_800E64D0[D_8004A7C4->objId] = 0.0f;

    D_800E3050[D_8004A7C4->objId] =
    D_800E3210[D_8004A7C4->objId] =
    D_800E33D0[D_8004A7C4->objId] = D_800E64D0[D_8004A7C4->objId];

    D_800E6690[D_8004A7C4->objId] = 0.0f;

    D_800E3590[D_8004A7C4->objId] =
    D_800E3750[D_8004A7C4->objId] =
    D_800E3910[D_8004A7C4->objId] = D_800E6690[D_8004A7C4->objId];

    D_800E6850[D_8004A7C4->objId] = D_800D67EC;

    D_800E3AD0[D_8004A7C4->objId] =
    D_800E3C90[D_8004A7C4->objId] =
    D_800E3E50[D_8004A7C4->objId] = D_800E6850[D_8004A7C4->objId];
}

extern f32 D_800D67F0;
void func_800B3520(void) {
    f32 temp_f0;

    D_800E6690[D_8004A7C4->objId] = 0.0f;
    temp_f0 = D_800E6690[D_8004A7C4->objId];
    D_800E3750[D_8004A7C4->objId] = temp_f0;
    D_800E64D0[D_8004A7C4->objId] = temp_f0;
    D_800E3210[D_8004A7C4->objId] = temp_f0;
    D_800E6850[D_8004A7C4->objId] = D_800D67F0;
    D_800E3C90[D_8004A7C4->objId] = D_800E6850[D_8004A7C4->objId];
}
