#include <ultra64.h>
#include <macros.h>

#include "ovl1/ovl1_6.h"
#include "D_8004A7C4.h"
#include "buffers.h"
#include "ovl0/ovl0_2.h"

extern void func_800B4924(void);
extern void func_800B143C(void);
extern u32 D_800D6B98;
extern s32 D_8015C668;
extern s32 D_8015C710, D_8015C714, D_8015C718, D_8015C71C;


void func_80158188_ovl4(void) {

}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
Failed to decompile function func_80158190_ovl4:

Unable to determine jump table for jr instruction at /home/faris/kirby_decomp/asm/non_matchings/ovl4/ovl4_3/func_80158190_ovl4.s line 17.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl"/"jpt_".
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80158190_ovl4.s")
#endif

void func_80158428_ovl4(s32);

extern s32 D_8015C360[];
extern s32 D_800D6B7C;
extern s32 D_800D6B9C;

void func_80158224_ovl4(s32 arg0) {
    D_800DF150[D_8004A7C4->objId] = NULL;
    D_8015C718 = D_8004A7C4->objId;
    D_800E98E0[D_8004A7C4->objId] = 0;
    D_800E9AA0[D_8004A7C4->objId] = 5;
    D_800E9C60[D_8004A7C4->objId] = 0;
    D_800E9E20[D_8004A7C4->objId] = D_800D6B98;
    func_800B2F54(0x10, D_8015C360[D_8015C71C], func_80159124_ovl4(D_800D6B98));
    func_800A71A0(0x10);
    if (D_800D6B7C != 0) {
        func_800A7678(0x115);
        D_800E9E20[D_8004A7C4->objId] = D_800D6B98 + 1;
        func_8000B6BC(5);
        D_800D6B7C = 0;
        D_800E9C60[D_8004A7C4->objId] = 2;
        D_800D6B9C = 0;
        while (D_800E9C60[D_8004A7C4->objId] != 0) {
            func_8000B6BC(1);
        }
        func_8000B6BC(5);
    }
    D_800DF150[D_8004A7C4->objId] = func_80158428_ovl4;
    while (D_8015C710 == 0) {
        func_8000B6BC(1);
    }
    D_800DF150[D_8004A7C4->objId] = NULL;
    D_8015C710 = 2;
    func_800AFA14();
}

void func_80158428_ovl4(s32 arg0) {
    s32 tmp_func_return;

    if (D_800E9AA0[D_8004A7C4->objId] != 0) {
        D_800E9AA0[D_8004A7C4->objId]--;
        return;
    }
    if (D_800E9C60[D_8004A7C4->objId] != 0) {
        D_800E98E0[D_8015C718] = 0;
        return;
    }
    if ((D_80048F20[0].buttonPressed & 0x9000) != 0) {
        D_8015C710 = 1;
        func_800A7678(0xF0);
        return;
    }
    tmp_func_return = func_80158120_ovl4(0xF0);
    if (tmp_func_return == 1) {
        if (D_800D6B98 < func_8015874C_ovl4()) {
            D_800E9E20[D_8004A7C4->objId] = D_800D6B98 + 1;
            D_800E9C60[D_8004A7C4->objId] = 2;
            func_800A7678(0x115);
            D_800D6B9C = 0;
            D_800E98E0[D_8004A7C4->objId] = 0x25;
        } else {
            if (D_8015C71C == 0) {
                if (func_8015874C_ovl4() != 5) {
            block_12:
                    if ((D_8015C71C == 1) && (func_8015874C_ovl4() == 6)) {
            block_14:
                        D_800E9E20[D_8004A7C4->objId] = 0;
                        D_800E9C60[D_8004A7C4->objId] = 2;
                        func_800A7678(0x115);
                        D_800D6B9C = 0;
                        D_800E98E0[D_8004A7C4->objId] = 0x25;
                    }
                } else {
                    goto block_14;
                }
            } else {
                goto block_12;
            }
        }
    }
    if (tmp_func_return == -1) {
        if (D_800D6B98 > 0) {
            D_800E9E20[D_8004A7C4->objId] = D_800D6B98 - 1;
            D_800E9C60[D_8004A7C4->objId] = 1;
            func_800A7678(0x115);
            D_800D6B9C = 0;
            D_800E98E0[D_8004A7C4->objId] = 0x25;
            return;
        }
        if (D_8015C71C == 0) {
            if (func_8015874C_ovl4() != 5) {
block_21:
                if ((D_8015C71C == 1) && (func_8015874C_ovl4() == 6)) {
block_23:
                    D_800E9E20[D_8004A7C4->objId] = func_8015874C_ovl4();
                    D_800E9C60[D_8004A7C4->objId] = 1;
                    func_800A7678(0x115);
                    D_800D6B9C = 0;
                    D_800E98E0[D_8004A7C4->objId] = 0x25;
                }
            } else {
                goto block_23;
            }
        } else {
            goto block_21;
        }
    }
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_8015874C_ovl4(void) {
    s32 temp_v1;

    temp_v1 = gCurrentWorld;
    if (temp_v1 < 6) {
        return temp_v1 - 1;
    }
    if (D_800D6BC5 == 0) {
        return 5;
    }
    if (D_800D6BA8 != 0x64) {
        return 5;
    }
    if (func_800B9F50(0xD) == 0) {
        return 5;
    }
    return 6;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_8015874C_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
Failed to decompile function func_801587CC_ovl4:

Unable to determine jump table for jr instruction at /home/faris/kirby_decomp/asm/non_matchings/ovl4/ovl4_3/func_801587CC_ovl4.s line 9.

There must be a read of a variable in the same block as
the instruction, which has a name starting with "jtbl"/"jpt_".
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_801587CC_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80158E98_ovl4(s32 arg0, ? arg1, s32 arg2) {
    f32 sp24;
    f32 temp_f0;
    f32 temp_f0_2;
    s32 temp_s0;
    s32 temp_s0_2;
    s32 temp_s0_3;
    s32 temp_s0_4;
    s32 temp_s0_5;
    s32 temp_s0_6;
    s32 temp_v0;
    s32 temp_v1;
    s32 phi_v0;
    s32 phi_s0;
    s32 phi_s0_2;
    s32 phi_s0_3;

    temp_v1 = D_8015C71C;
    if (temp_v1 == 1) {
        temp_s0 = arg0 * 4;
        if (arg2 == 2) {
            temp_s0_2 = arg0 * 4;
            phi_v0 = *(&D_8015C3A0 + temp_s0_2);
            phi_s0 = temp_s0_2;
        } else {
            phi_v0 = *(&D_8015C3BC + temp_s0);
            phi_s0 = temp_s0;
        }
    } else {
        temp_s0_3 = arg0 * 4;
        if (arg2 == 2) {
            temp_s0_4 = arg0 * 4;
            phi_v0 = *(&D_8015C368 + temp_s0_4);
            phi_s0 = temp_s0_4;
        } else {
            phi_v0 = *(&D_8015C384 + temp_s0_3);
            phi_s0 = temp_s0_3;
        }
    }
    if (temp_v1 == 1) {
        temp_f0 = phi_v0;
        sp24 = temp_f0;
        func_800A9F98(0x30012, temp_f0, 1);
    } else {
        temp_f0_2 = phi_v0;
        sp24 = temp_f0_2;
        func_800A9F98(0x30014, temp_f0_2, 1);
    }
    if (sp24 == 0.0f) {
        func_8000E324_ovl4(*(&D_800DE350 + (*D_8004A7C4 * 4)));
    }
    func_800AECC0(0x40000000);
    func_800AED20(0x40000000);
    func_800B3070(0x10, 0x40000000);
    func_800B2F54(0x10, *(&D_8015C360 + (D_8015C71C * 4)), (bitwise s32) sp24);
    func_800A71A0(0x10);
    if (D_8015C71C == 1) {
        if ((phi_s0 == 0x14) || (phi_s0 == 0x18)) {
            if (arg2 != 2) {
block_16:
                if ((phi_s0 == 0) || (phi_s0 == 0x18)) {
                    if (arg2 == 1) {
block_19:
                        phi_s0_2 = 0;
loop_20:
                        func_800A71A0(0x10);
                        func_8000B6BC(1);
                        temp_s0_5 = phi_s0_2 + 1;
                        phi_s0_2 = temp_s0_5;
                        if (temp_s0_5 != 0x23) {
                            goto loop_20;
                        }
                    } else {
block_22:
                        phi_s0_3 = 0;
loop_23:
                        func_800A71A0(0x10);
                        func_8000B6BC(1);
                        temp_s0_6 = phi_s0_3 + 1;
                        phi_s0_3 = temp_s0_6;
                        if (temp_s0_6 != 0x19) {
                            goto loop_23;
                        }
                    }
                } else {
                    goto block_22;
                }
            } else {
                goto block_19;
            }
        } else {
            goto block_16;
        }
    } else {
        goto block_22;
    }
    temp_v0 = D_8015C718 * 4;
    *(&D_800E9C60 + temp_v0) = 0;
    D_800D6B98 = *(&D_800E9E20 + temp_v0);
    func_800AECC0(0);
    func_800AED20(0);
    func_800B9C50(D_800D6B88);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80158E98_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
f32 func_80159124_ovl4(s32 arg0) {
    if (D_8015C71C == 1) {
        return D_8015C3A0[arg0];
    }
    return D_8015C368[arg0];
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159124_ovl4.s")
#endif


void func_80159160_ovl4(s32 arg0) {
    func_800B1F68(D_800DEC10[D_8004A7C4->objId], func_800B143C);
    D_800DEF90[D_8004A7C4->objId] = &func_800B4924;
    D_800DF150[D_8004A7C4->objId] = 0;
    D_800E3750[D_8004A7C4->objId] = 0.0f;
    D_800E3210[D_8004A7C4->objId] = D_800E3750[D_8004A7C4->objId];
    D_800E3C90[D_8004A7C4->objId] = D_8015C668;
    gEntitiesPosXArray[D_8004A7C4->objId] = 0.0f;
    gEntitiesPosYArray[D_8004A7C4->objId] = 0.0f;
    gEntitiesPosZArray[D_8004A7C4->objId] = 0.0f;
    D_8015C714 = D_8004A7C4->objId;
    D_800E98E0[D_8004A7C4->objId] = D_800D6B98;
    func_800A9864(0x3000A, 0x1869F, 0x10, &D_800E3750);
    if (D_8015C71C == 1) {
        func_800A9F98(0x30012, func_80159124_ovl4(D_800D6B98));
    } else {
        func_800A9F98(0x30014, func_80159124_ovl4(D_800D6B98));
    }
    func_800AECC0(0);
    func_800AED20(0);
    while (D_8015C710 == 0) {
        if (D_800E9C60[D_8015C718] != 0) {
            func_80158E98_ovl4(D_800D6B98, D_800E9E20[D_8015C718], D_800E9C60[D_8015C718]);
        }
        func_8000B6BC(1);
    }
    func_800AFA14();
}

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_8015986C_ovl4(s32 arg0) {
    if ((D_800D6B24 == 0) && (D_8015C710 == 2)) {
        func_800A5744(0, 0, 0);
        func_800A5A14(0, 0x10, 2);
    }
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_8015986C_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_801598C4_ovl4(void) {
    s32 temp_s0;
    s32 phi_s0;

    func_800A41B0(0x40000000);
    func_8000BDF0(0x19, 0x80000000, 0x63, 3, 0xA0A32FF);
    func_800AE048(0x80);
    func_800AE0F0();
    func_800A6E64();
    func_800A78D0(0);
    func_800A8724(0);
    func_800A7A40();
    func_80159828_ovl4();
    func_800A75B0(0, 0x25);
    func_800A6BC0(0xB);
    *(&D_800E98E0 + (func_800AEA64(2, 0, 0x70) * 4)) = 0;
    *(&D_800E98E0 + (func_800AEC08(2, 0, 0x70) * 4)) = 1;
    for (phi_s0 = 2; phi_s0 < 9; phi_s0++) {
        *(&D_800E98E0 + (func_800AEC08(2, 0, 0x70) * 4)) = phi_s0;
    }
    *(&D_800E98E0 + (func_800AEC70(2, 0, 0x70) * 4)) = 9;
    func_8000A180(0, &D_8015986C, 0x1A, 0x80000000);
    func_800A5744(0, 0, 0);
    func_800A5A14(0xFF, -0x10, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_801598C4_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
s32 func_80159B00_ovl4(void) {
    s32 temp_v0;

    temp_v0 = *(&D_800DDC50 + (*D_8004A7C4 * 4));
    if (temp_v0 == 0) {
        return func_80159B68_ovl4();
    }
    if (temp_v0 != 1) {
        return temp_v0;
    }
    return func_80159CB8_ovl4();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159B00_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80159B68_ovl4(s32 arg0) {
    void *temp_v0;

    *(&D_800DF150 + (*D_8004A7C4 * 4)) = &D_80159C40;
    func_800AAF34(0x10, 0x300AF, 0);
    func_800A71A0(0x10);
    temp_v0 = D_8004A7C4;
    *(&gEntitiesAngleYArray + (*temp_v0 * 4)) = 0.0f;
    *(&D_800EA6E0 + (*temp_v0 * 4)) = D_8015C670;
    func_800A9864(0x300B7, 0x1869F, 0x10);
    D_8015C720 = 2;
    func_8000B6BC(0x1E);
    func_800A75B0(0, 0x17);
    func_800AFA14();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159B68_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
f32 func_80159C40_ovl4(s32 arg0) {
    f32 temp_f0;
    f32 temp_f2;
    s32 temp_v1;
    void *temp_a0;
    void *temp_a1;
    void *temp_v0;

    temp_v0 = D_8004A7C4;
    temp_f2 = D_8015C674;
    temp_v1 = *temp_v0 * 4;
    temp_a0 = temp_v1 + &gEntitiesAngleYArray;
    *temp_a0 = *temp_a0 + *(&D_800EA6E0 + temp_v1);
    temp_a1 = (*temp_v0 * 4) + &D_800E4C50;
    temp_f0 = *temp_a1;
    if (temp_f2 <= temp_f0) {
        *temp_a1 = temp_f0 - temp_f2;
    }
    return temp_f0;
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159C40_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80159CB8_ovl4(s32 arg0) {
    void *temp_v0;

    temp_v0 = D_8004A7C4;
    *(&D_800DEF90 + (*temp_v0 * 4)) = &D_800B4924;
    *(&D_800DF150 + (*temp_v0 * 4)) = &D_80159D70;
    func_800AECC0(D_800D6B10);
    func_800AED20(D_800D6B10);
    func_800A9864(0x300B6, 0x1869F, 0x10);
    func_800AA154(0x300AE);
    D_8015C720 = 1;
    func_800AA018(0x300AD);
    func_800AFA14();
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159CB8_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80159D70_ovl4(s32 arg0) {

}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159D70_ovl4.s")
#endif

#ifdef MIPS_TO_C
//generated by mips_to_c commit 3ec45aadfc2cb619035fb802d88c52eacfab0326
void func_80159DE8_ovl4(void) {
    s32 temp_t1;
    s32 temp_t8;
    s32 temp_v0;
    s32 temp_v0_2;

    func_8000BDF0(0x19, 0x80000000, 0x63, 3, 0xFF);
    func_800AE0F0();
    func_800A6E64();
    func_800A8724(0);
    func_800A6BC0(4);
    D_8015C720 = 0;
    temp_v0 = func_800AEC08(5, 0, 0x70);
    temp_t8 = temp_v0 * 4;
    D_800D71F8 = temp_v0;
    *(&D_800DDC50 + temp_t8) = 0;
    temp_v0_2 = func_800AEC08(5, 0, 0x70);
    temp_t1 = temp_v0_2 * 4;
    D_800D71FC = temp_v0_2;
    *(&D_800DDC50 + temp_t1) = 1;
    func_8000A180(0, &D_80159D78, 0x1A, 0x80000000);
    func_800A5744(0, 0, 0);
    func_800A5A14(0xFF, -0x10, 0);
}
#else
GLOBAL_ASM("asm/non_matchings/ovl4/ovl4_3/func_80159DE8_ovl4.s")
#endif

extern Gfx D_8015C3E0[];

void func_80159ED8_ovl4(Gfx **arg0) {
    gSPDisplayList((*arg0)++, &D_8015C3E0);
}
